### ISSUE TITLE
Wheels ORM where clauses wrap integer values in quotes

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#1000]
When passing a where clause to a wheels ORM function, it wraps all numeric values in single quotes. This can't be optimal for database engines.

Could the sql generator function check the column's datatype and conditionally quote the values only for "string" columns?

Input:
`where = "numericColumn = 1 AND anotherNumericColumn IN (1,2)" AND stringColumn = 'foo'`

Wheels:
`where = "numericColumn = '1' AND anotherNumericColumn IN ('1','2') AND stringColumn = 'foo'"`

Desired (exactly as per input):
`where = "numericColumn = 1 AND anotherNumericColumn IN (1,2) AND stringColumn = 'foo'"`

**Comment by perdjurner** [comment]
Is this when not using cfqueryparam? (i.e. parameterize=false)

**Comment by chapmandu** [comment]
No, this is when using defaults.. Which parameterize=true. Not sure if db engine plays a role but I'm using mysql 5.6.

**Comment by perdjurner** [comment]
Yes, seems fine on SQL Server.

**Comment by chapmandu** [comment]
This is due to not using the `dataType` argument on the calculated `property()` function in the model.. Wheels doesn't know the data type of calculated properties and defaults to `char`
