### ISSUE TITLE
Core Tests: MySQL 5.6 Errors

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#1005]
Using the test docker test suite, starting to stumble across multiple issues:

(Lucee 5 passing)

---------------------------------
Adobe 2016 and Adobe 2018 MySQL
---------------------------------
Path: wheels.tests
Cases: 304
Tests: 1470
Passes: 1468
Failures: 2
Errors:  0
Started: April, 22 2020 13:33:57
Ended: April, 22 2020 13:33:57

- Failure: Add a boolean column -> migrator.migration.addboolean
assert failed: actual eq expected
actual = 'TINYINT'
expected = 'BIT'

- Failure: Add multiple boolean columns -> migrator.migration.addboolean
assert failed: actual[2] eq expected
actual[2] = 'TINYINT'
expected = 'BIT'
actual = Array containing 3 items

**Comment by dbelanger** [comment]
This was a minor fix but MySQL used to use TINYINT and now uses BIT.
