### ISSUE TITLE
Tests Packages

### ISSUE THREAD

**Issue by michaeldiederich** [cfwheels/cfwheels#1008]
### Feature Request:

I would like to use the Packages at the Tests (right now App and Core) for my own name schema and I would like to have an "All" Tab, e.g.:

[All] [API] [Core] [Helpers] [Wheels]

### Bug:

If possible, show only Wheels if any wheels tests are defined. Right now, as not all tests are working for me (#993), i have deleted the wheels test in my local application. So, if I click on "Core" i get an exception:

```
Wheels.Testing
Cannot find test package or single test

Tag context
Error thrown on line 629 in wheels/test/functions.cfm
- called from line 1 in root.cfm
- called from line 563 in wheels/global/internal.cfm
- called from line 6 in wheels/public/views/packages.cfm
- called from line 30 in wheels/public/includes.cfm
- called from line 199 in wheels/dispatch/functions.cfm
- called from line 5 in wheels/index.cfm
- called from line 2 in index.cfm
- called from line 5 in wheels/events/onrequest.cfm
```

### Files to modify
I guess `wheels\tests\functions.cfm` the function `$listTestPackages()`?

(It is wheels 2.1.0)

**Comment by neokoenig** [comment]
We can definitely hide the Core tab if no core tests exist; the rest seems quite specific to your application; Whilst we could hypothetically create tabs dependent on the packages/folders within `/tests/` it might be that someone else has a different test folder layout which results something unusable..

**Comment by neokoenig** [comment]
Core tests are now hidden if they don't exist
(https://github.com/cfwheels/cfwheels/commit/5514a32ea6659f891615ef827dde77885292c9c8#diff-fa8dd3ff8328bcba6d817d559c15f1c7) - thanks @chapmandu
