### ISSUE TITLE
WHERE clause doesn't support spaces around operator

### ISSUE THREAD

**Issue by bawelter** [cfwheels/cfwheels#1020]
where="thing1 = 'this' and thing2 = 'that'" fails
where="thing1='this' and thing2='that'" works fine.

**Comment by neokoenig** [comment]
Which version of wheels?
I assume you mean:
`where="thing1 = 'this' AND thing2 = 'that'"` as it's case sensitive?

**Comment by bawelter** [comment]
I'll try it with upper case and see if this resolves the issue.  Thank you!

**Comment by bawelter** [comment]
Yeah that fixes the problem and I'm using v2.1.0

**Comment by bawelter** [comment]
Is there a reason for it being case sensitive?

**Comment by neokoenig** [comment]
Yeah, it makes the regex a lot easier I think
