### ISSUE TITLE
Return true if ALL associations are valid.

### ISSUE THREAD

**Issue by mmaranao** [cfwheels/cfwheels#103]
When saving nested properties, make sure that the model and the associated model(s) are valid before saving.

**Comment by perdjurner** [comment]
@chrisdpeters Any thoughts on this issue?

**Comment by chrisdpeters** [comment]
I thought nested properties were already doing this. @mmaranao can you explain further why you reported this?

If you can give us a reproduceable scenario, we'll reopen this issue.
