### ISSUE TITLE
Test mySQL8

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#1033]
Er, probably about time.
Should be easy-ish to add to the docker test suite, so shouldn't be completely painful to test against.

**Comment by neokoenig** [comment]
Hmm... looks like lucee is the only real contender for this?

---------------------------------
Adobe 2016 MySQL 8
---------------------------------

- Not supported (well, not officially) - see top answer on https://stackoverflow.com/questions/50106525/could-not-create-connection-to-database-coldfusion

---------------------------------
Adobe 2018 MySQL 8
---------------------------------

 - Also not supported(!) officially - see https://helpx.adobe.com/pdf/coldfusion2018-support-matrix.pdf

---------------------------------
Lucee 5 MySQL 8
---------------------------------
Path: wheels.tests
Cases: 304
Tests: 1477
Passes: 1474
Failures: 2
Errors:  1
Started: June, 21 2020 12:00:27 +0000
Ended: June, 21 2020 12:00:27 +0000

- Failure: Sum with group on calculated property -> model.calculations.sum
assert failed: result['galleryIdSum'][2] IS 10
result['galleryIdSum'][2] = 1
result = Query with 250 rows


- Failure: Sum with group on calculated property on associated model -> model.calculations.sum
assert failed: result['userIdSum'][3] IS 3
result['userIdSum'][3] = 1
result = Query with 250 rows


- Error: Order clause with paginated include and ambiguous columns -> model.crud.order
Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'wheelstestdb.trucks.registration' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

cfquery.cfm:17


SELECT shops.shopid
FROM shops LEFT OUTER JOIN trucks ON shops.shopid = trucks.shopid
GROUP BY shops.shopid
ORDER BY CASE WHEN registration IN ('foo') THEN 0 ELSE 1 END DESC,shops.shopid
LIMIT 3


/cfwheels-test-suite/wheels/model/adapters/cfquery.cfm:17
/cfwheels-test-suite/wheels/model/adapters/Base.cfc:468
/cfwheels-test-suite/wheels/model/adapters/MySQL.cfc:108
/cfwheels-test-suite/wheels/model/read.cfm:346
/cfwheels-test-suite/wheels/model/read.cfm:160
/cfwheels-test-suite/wheels/tests/model/crud/order.cfc:41
/cfwheels-test-suite/wheels/test/functions.cfm:326
/cfwheels-test-suite/wheels/test/functions.cfm:518
/cfwheels-test-suite/root.cfm:5
/cfwheels-test-suite/wheels/global/internal.cfm:605
/cfwheels-test-suite/wheels/public/views/tests.cfm:11
/cfwheels-test-suite/wheels/public/includes.cfm:34
/cfwheels-test-suite/wheels/dispatch/functions.cfm:194
/cfwheels-test-suite/wheels/index.cfm:6
/cfwheels-test-suite/rewrite.cfm:2
/cfwheels-test-suite/wheels/events/onrequest.cfm:4

**Comment by neokoenig** [comment]
Added a branch with the changes necessary to run the local docker setup
https://github.com/cfwheels/cfwheels/tree/mysql8-support

**Comment by bpamiri** [comment]
I believe this is handled now that the test suite is using MySQL-latest for testing.
