### ISSUE TITLE
Migration files should be created with 664 mode

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#1034]
Eg: https://github.com/cfwheels/cfwheels/blob/master/wheels/migrator/functions.cfm#L331

```
local.migrationFile = $getNextMigrationNumber(arguments.migrationPrefix) & "_#local.migrationFile#.cfc";
local.migrationFilePath = "#this.paths.migrate#/#local.migrationFile#";
FileWrite(local.migrationFilePath, local.templateContent);
FileSetAccessMode(local.migrationFilePath, "664"); 
```

I'm not sure if this will throw an exception on Windeauxs?

**Comment by chapmandu** [comment]
Closed via f50dd7af4c7c410e01b382a2a73f8c9c23d4650f

@neokoenig Could you please test this on Windoze? All is good if the test suite passes.

**Comment by neokoenig** [comment]
@chapmandu Passes on my local *d0ze via commandbox / lucee5 / mysql.

**Comment by chapmandu** [comment]
@neokoenig Could you please re-test on Windeauxz without the try/catch

https://github.com/cfwheels/cfwheels/blob/master/wheels/migrator/functions.cfm#L377

**Comment by neokoenig** [comment]
@chapmandu Yep passes without try/catch on lucee5
