### ISSUE TITLE
Cache wheels/docs

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#1036]
In large applications, this page is quite slow to load. 

It should be stored in application scope when `get("environment") == "development"` onapplicationstart

**Comment by neokoenig** [comment]
I think this only needs to be cached when you hit the page the first time; the docs shouldn't really be accessible outside development, but you could hypothetically have the GUI on in other modes.

**Comment by chapmandu** [comment]
Ripper!
