### ISSUE TITLE
Flag wheels functions in docs as distinct from application functions

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#1050]
In the docs data structure (`$returnInternalDocumentation`), wheels framework functions should be distinguishable from user defined application function.

Eg: `isWheelsFunction = true|false`

**Comment by chapmandu** [comment]
Redundant if run using just the core

**Comment by neokoenig** [comment]
Also if you ever need the core functions alone, there's:
https://api.cfwheels.org/files/json/v2.2.json
https://api.cfwheels.org/files/json/v2.1.json
https://api.cfwheels.org/files/json/v2.0.json
https://api.cfwheels.org/files/json/v1.4.5.json
