### ISSUE TITLE
Tests section throws an error after install

### ISSUE THREAD

**Issue by mikegrogan** [cfwheels/cfwheels#1052]
https://github.com/cfwheels/cfwheels/blob/517fd130e6534b63bf91c9c34fbea581d361c1d2/wheels/public/tests/_navigation.cfm#L98

Does anyone else have an issue with <cfif _format == "html">? On a fresh install of 2.2.0 running CF Server 2016 in Commandbox I get an error when I go to the tests link. As soon as I change this to <cfif _format eq "html"> active</cfif> the tests sections loads up fine.

**Comment by neokoenig** [comment]
Ah, that's quite possible that snuck in. (ironically, the test pages themselves don't have unit tests!). According to cfdocs, `The operators == != < <= > >= do not work in tags such as cfif or cfset in Adobe ColdFusion (as of Version 2016)`

*sigh* :)

Easy fix though!

**Comment by mikegrogan** [comment]
Thanks!
