### ISSUE TITLE
error: null can not be casted to a Struct

### ISSUE THREAD

**Issue by michaeldiederich** [cfwheels/cfwheels#1054]
I get this error and I have no clue why and what...

Lucee 5.2.8.50 Error (expression)
--
Message | null can not be casted to a Struct
Stacktrace | The Error Occurred in/home/[...]/wheels/events/onerror/cfmlerror.cfm: line 1311: </cfif>12: </p>13: <cfif StructKeyExists(arguments.exception, "cause") && StructKeyExists(arguments.exception.cause, "tagContext") && ArrayLen(arguments.exception.cause.tagContext)>14: <cfset local.tagContext = arguments.exception.cause.tagContext>15: <cfelseif StructKeyExists(arguments.exception, "rootCause") && StructKeyExists(arguments.exception.rootCause, "tagContext") && ArrayLen(arguments.exception.rootCause.tagContext)>called from /home/[...]/wheels/global/cfml.cfm: line 117called from /home/[...]/wheels/events/onerror.cfm: line 47called from /home/[...]/wheels/global/cfml.cfm: line 157called from /home/[...]/wheels/global/cfml.cfm: line 33called from /home/[...]/wheels/events/onerror.cfm: line 15

Lucee 5.2.8.50
Wheels 2.1

Obviously, "full null support" is active.

**Comment by neokoenig** [comment]
Can you recreate this ? If so, would be useful to see what `arguments` looks like dumped out (I'm wondering whether null support changes anything in the data coming into the error handler)

**Comment by michaeldiederich** [comment]
After a lucee restart i cannot reproduce it. I am sorry. But i think, it would make sense to check for `arguments.exception`, too.

**Comment by michaeldiederich** [comment]
As I cannot reproduce it, i close the issue.
