### ISSUE TITLE
Bottleneck in $serializeQueryToStructs()

### ISSUE THREAD

**Issue by bshea5** [cfwheels/cfwheels#1055]
I have a call in my app for invoices and their costs, which takes about 15s to run on my server. Ran fusionreactor to get a better idea of what is happening, and its seems like its hitting a bottleneck in $serializeQueryToStructs() at /wheels/model/serialize.cfm . I reviewed the code, and it seems to be due to the instantiation of objects for hasMany relationships. In my case, the invoice costs associated with each invoice. There is a comment in the code indicating its a known issue, but I'm wondering if there has been any attempt to resolve this or anything is in the pipeline.

Thanks.

**Comment by neokoenig** [comment]
I'd recommend against doing full objects wherever possible - it's a coldfusion thing - init'ing object is expensive.
Can you do 
```
orders = model("order").findAll(include="lineitems")
```
and group instead? Do you really need each child's object level functions?

**Comment by bshea5** [comment]
I don't need each child's object level functions, only the data. I return as a struct in my findAll(), but I guess the children are still initialized when converting? What do you mean group instead?

**Comment by neokoenig** [comment]
If you're using findAll() it should return a query (unless you've got returnAs="structs" or something).
So you with ` = model("order").findAll(include="lineitems", group="orders.id, lineitems.id" )`you   might have
```
orderid | lineitemid | lineitemname | description
123 | 1789 | name | somethingelse
123 | 1790 | name | somethingelse
123 | 1791 | name | somethingelse
```

Basically you want to get SQL to do the hard work and skip CF doing the object creation

**Comment by bshea5** [comment]
I am using "structs" as my returnAs. Do I have to avoid that as well than? If that is the case, I have some fun refactoring in my future. Was really relying on the output that returning as a struct provided.

**Comment by neokoenig** [comment]
`returnAs = "structs"` is basically a fancy way of doing `returnAs = "objects"` just without the functions. I'm pretty sure it's not a performant solution. *if* all CF engines directly supported `cfquery` returning structs, then life would be different.

So if you're on Lucee, there are interesting ways around it, but they're not in the wheels core due to cfengine cross compatibility.

**Comment by bshea5** [comment]
Understood. I'm on ACF atm. I'll have to see what I can do. 

What are the ways around with Lucee? I'm considering moving to it sometime in the future.

**Comment by neokoenig** [comment]
It's a relatively new thing (https://www.bennadel.com/blog/3849-returning-cfquery-query-results-as-structs-in-lucee-5-3-6-61.htm ) and I've not yet had the opportunity to properly benchmark it, so YMMV. But anything native is going to be better than in-framework...

**Comment by bshea5** [comment]
Thanks for your quick responses. Gonna chew on this and close the ticket.

**Comment by chapmandu** [comment]
This may help..

```
public array function queryToArrayOfStructs(required query query) {
	local.returnValue = [];
	loop query=arguments.query {
		ArrayAppend(local.returnValue, QueryRowData(arguments.query, arguments.query.currentRow));
	}
	return local.returnValue;
}
```

**Comment by bshea5** [comment]
Thanks chapmandu. That is something I do with query results, but the problem is that returning as a struct neatly organized to-many relationships into  arrays per model item. Whereas returning as a query means that data will be essentially "flattened", having a record per relationship. So an invoice with multiple costs, would have a record per cost, whereas with "struct", it was invoice: ... costs: [...] .

**Comment by andybellenie** [comment]
SerializeQueryToStructs() isn't super performant, but 15s is extreme. How many rows are you returning? And how many includes? As others have recommend, when dealing with a large recordset it's best to use a query and refactor your code accordingly. This isn't a Wheels specific thing, it's a 'feature' of Coldfusion itself.
