### ISSUE TITLE
onerror requestTimeout should increase user defined value

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#1056]
In the wheels/events/onerror.cfm file, there is a hard-coded requestTimeout value of 70 seconds.

If there is an exception thrown in a request that runs for longer than 70 seconds, the actual exception message is not reported, but rather:
```
request /rewrite.cfm (/var/lib/tomcat8/webapps/ROOT/rewrite.cfm) has run into a timeout (timeout: 70 seconds) and has been stopped. The thread did start 83690ms ago. Open locks at this time (reloadlock403bb92cac7fd71409997ddaf89a50ae).
```

Suggested fix is to get increment the page's requestTimeout
```
// Lucee (ms)
local.requestTimeout = (getPageContext().getRequestTimeout() / 1000) + 30;

// ACF (Seconds)
local.requestTimeout = CreateObject("java", "coldfusion.runtime.RequestMonitor").GetRequestTimeout() + 30;
```

https://github.com/cfwheels/cfwheels/blob/d58db3f9a3c22f5940b53e9abea7b27be6799d3e/wheels/events/onerror.cfm#L5

How to reproduce:

// Your controller/action:
```
setting requestTimeout = 5;
sleep(4000);
Throw("someError");
set(environment = "production");
```

// wheels/events/onerror.cfm
`local.requestTimeout = 3;`

**Comment by dbelanger** [comment]
I just found a problem with this fix on ACF: If the server was setup using the Application Lockdown guide, access to the internal ColdFusion Java components should be disabled.  
I think you may have seen this idea from a blog post from Ben Nadel but further down in the comments, Ben mentioned that they simply used a high number (like 10 minutes) for ACF.
