### ISSUE TITLE
No output from Debug() usage in plugin test cases 

### ISSUE THREAD

**Issue by bshea5** [cfwheels/cfwheels#1061]
No output from Debug() usage in plugin test cases. 

message = "testing...";
debug("message", true);

I'd expect it to print the message with the rest of the TC view, but nothing is printed.  Bufferoutput is set to true. Not aware of any other setting that should influence this. After talking to @neokoenig , he agreed that this is weird. Opening a ticket so maybe it can be investigated. Writedump still works, so not urgent, but something that should be working.

Wheels 2.1

**Comment by chapmandu** [comment]
Is the behaviour the same in non-plugin test cases?

**Comment by bshea5** [comment]
Non-plugin tests cases behave as expected, with debug() producing output.
