### ISSUE TITLE
Timestamp settings (UTC) ignored for deletedAt

### ISSUE THREAD

**Issue by dbelanger** [cfwheels/cfwheels#1063]
This went unnoticed for us for quite some time because honestly, we rarely check the timestamp of a soft deleted record.

However, I recently needed to compare records when I noticed that my **deletedAt** timestamp was before my **createdAt**.  Obviously, that should never be the case.

We added timestamp modes and UTC support was requested as an enhancement in #293 and implemented in #695 / #696 however we only did it for **deletedAt**.

There is only one small change necessary to make this happen however we should warn users that the **deletedAt** will now also default to the timestamp mode selected (just like **createdAt** and **updatedAt** do).  

NOTE: We also use the timestamps in the migrator however the "removeRecord" always hard deletes the records which I believe to be correct only because it's in the migrator

**Comment by neokoenig** [comment]
Pls add to changelog for 2.3 release!
