### ISSUE TITLE
resources() should allow an empty "only" value

### ISSUE THREAD

**Issue by absentbri** [cfwheels/cfwheels#1083]
```coldfusion
resources(name = "Foo", nested = true, only = "")
  .resources(name = "Bar")
.end()
```
This does not work as (I'd) expected where I'd like the relationship/nesting but I do not need/cannot use restful routes for the parent, but want to keep the structure (in this case, a legacy app with legacy pre-restful routes).

While not shown explicitly in the docs in rails https://guides.rubyonrails.org/routing.html#restricting-the-routes-created you can use an empty array `only: []` to not have any routes at all, this shows up in testing and also mentioned in this SO answer: https://stackoverflow.com/a/27425638

Can we allow only to be passed as an empty list/string and be accepted?

**Comment by neokoenig** [comment]
I don't see a problem with this; should be do-able.
Temp workarounds could be achieved via:

```
.resources(name = "Foo", nested = true, except = "index,show,edit,create,new,delete,update")
	.resources(name = "Bar")
.end()
```
But I appreciate that's a bit ugly

**Comment by absentbri** [comment]
@neokoenig yep, that's exactly how I did it :)
I'll try for a PR to change it soon maybe, its quite minor
