### ISSUE TITLE
Migrator log overflows parent modal

### ISSUE THREAD

**Issue by absentbri** [cfwheels/cfwheels#1085]
Migration modal dialog overflow, minor/bugbear.

issue (excuse ugly/redactions)
![overflow-issue](https://user-images.githubusercontent.com/16235510/128131088-a662adad-a0d3-468a-bad9-a9b4d9a995ff.png)

Can fix with semantic-ui scroll content class, will raise PR:
![overflow-fix](https://user-images.githubusercontent.com/16235510/128131150-ad67a121-7828-468f-9b72-f12ffb9d2223.png)

**Comment by chapmandu** [comment]
closed via 06cf285
