### ISSUE TITLE
/wheels/events/onerror/cfmlerror.cfm inappropriately stripping error info 

### ISSUE THREAD

**Issue by adamcameron** [cfwheels/cfwheels#1091]
Copy/paste from CFWheels google group:

Anyone know why this logic (in /wheels/events/onerror/cfmlerror.cfm) is there:

<cfif local.template Does Not Contain "wheels" AND FindOneOf("/\", local.template) IS NOT 0>
    Line #local.tagContext[local.pos].line# in #local.template#<br>
</cfif>

Why would CFWheels actively remove lines from the error context? It's not like errors don't occur in Wheels's code, or Wheels's code doesn't contribute to an erroring situation. What is being gained by taking that information out?

A real world case in point here. I just got this alert:

Error: key [COLUMN] doesn't exist
Location: Line 123 in /path/to/file/in/our/app

That error came from CFWheels's `wheels/model/adapters/Base.cfc` file, a fact Wheels has unhelpfully stripped from the error reporting.

However for someone who doesn't know the mungling being done, they're gonna be looking for a stray reference to COLUMN in their code @ line 123.

Also... what if my filename / path actually has "wheels" in it?

This feature seems "unhelpful" to me on first blush, but I might be missing something?

I'm using 1.4.x but do not expect any bugfixes to that; it's the same issue with 2.x though.

**Comment by bpamiri** [comment]
@adamcameron This should be fixed and is in the bleeding edge release for now. You can check it out by doing a `box install cfwheels` and drop the wheels folder into an active project.
