### ISSUE TITLE
"before"-Filter not running in production-mode

### ISSUE THREAD

**Issue by michaeldiederich** [cfwheels/cfwheels#1093]
I haven't found the root cause, so I want to explain it with an example:

"development"-mode:

I request a page like `/index.cfm/detail?foo=bar`. The `controller.cfc` is called and there is a `before` filter to check my permissions. It is my first request, I am not authentificated so there is a redirect to the `/index.cfm/login` page. Works fine.

"production"-mode:

I request a page like `/index.cfm/detail?foo=bar`. The page is empty, the return code is 500 and the view throws and error about an half initialized session (e.g. no authentification, no choosen language,...).

Is there anything more I can provide for this bug report?

**Comment by neokoenig** [comment]
It sounds like the most likely explanation is that the code block in `config()` is cached in production.
So if you set `session.foo = 1` within the `config()` call or anything like that, it will be cached on the first hit/application start.

Might be worth looking at the example app which has authentication checks via filters:
https://github.com/cfwheels/cfwheels-example-app/blob/master/controllers/Controller.cfc#L34
https://github.com/cfwheels/cfwheels-example-app/blob/master/controllers/functions/auth.cfm#L13

**Comment by michaeldiederich** [comment]
And then, 3 hours later after comparing all the files, he found the `super.config(usePermissions=false);` in a controller-file and he removed it and it works.

Thank you very much, this bugged me some weeks already.
