### ISSUE TITLE
Customize Error Email Template

### ISSUE THREAD

**Issue by timsayshey** [cfwheels/cfwheels#1097]
Would be nice to be able to override the error email template. For instance, I would include `errorEmail.cfm` in the `/config` directory. I like to include additional information in the error email for debugging purposes and currently I have to modify the framework code which breaks every time I upgrade.

**Comment by andybellenie** [comment]
I think you should be able to override $runOnError() found here
https://github.com/cfwheels/cfwheels/blob/master/wheels/events/onerror.cfm

Then you can do whatever you like during error handling and it is unlikely to change with framework updates.

**Comment by timsayshey** [comment]
Ah yes, that will also work - Thanks Andy!
