### ISSUE TITLE
Automatically set labels on association keys

### ISSUE THREAD

**Issue by andybellenie** [cfwheels/cfwheels#110]
Currently, you need to do the following to define labels on an association key:

```
<cfset belongsTo(name="Client")>
<cfset property(name="clientId", label="Client")>
```

This should be automatic.

**Comment by perdjurner** [comment]
Running out of time for this to be in 1.4, postponing.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
