### ISSUE TITLE
Typos in CFWheels guides - command line tools

### ISSUE THREAD

**Issue by tamdang501** [cfwheels/cfwheels#1164]
I was reading the guides and found some typo.  Hope I can contribute.

![wheels dbmigrate info](https://user-images.githubusercontent.com/12297413/180269466-f216116c-67c1-4f41-9893-087092ea0526.PNG)
![wheels generate app-wizard step 3](https://user-images.githubusercontent.com/12297413/180269472-60bbf712-1738-498d-9686-c62740afbe25.PNG)
![wheels generate app-wizard step 4](https://user-images.githubusercontent.com/12297413/180269477-2b9e9f6f-53b0-4835-b3d0-354b5605e8e9.PNG)
![wheels generate app-wizard step 7](https://user-images.githubusercontent.com/12297413/180269484-139b04b8-a773-41a0-bd38-61b285ca0930.PNG)
![wheels generate app-wizard](https://user-images.githubusercontent.com/12297413/180269485-8877ad11-5d8e-4d43-8552-667dca5adae3.PNG)
![wheels generate](https://user-images.githubusercontent.com/12297413/180269488-ab8283aa-66bb-4475-a2c5-b4cf1b98e194.PNG)
![wheels info](https://user-images.githubusercontent.com/12297413/180269491-34c6d93e-f4ea-46b1-a430-9ea23379ccfb.PNG)
![wheels plugins - commands](https://user-images.githubusercontent.com/12297413/180269499-a363f162-904c-4b4c-9527-4d0c53800093.PNG)
![wheels test](https://user-images.githubusercontent.com/12297413/180269504-79bd16c1-1029-4810-a330-8a451be24363.PNG)
![continuous or continual](https://user-images.githubusercontent.com/12297413/180269577-38676566-88ad-4eaa-912b-5f1c09abf241.PNG)

**Comment by MvdO79** [comment]
Thanks @tamdang501, by now much was already fixed, did some last missing fixes for this issue. Can be closed after PR's approved.
