### ISSUE TITLE
Add instruction to install cfwheels client when using command box

### ISSUE THREAD

**Issue by tamdang501** [cfwheels/cfwheels#1165]
**Is your feature request related to a problem? Please describe.**
I am in Visual Studio Code and am using command box.  I did not know the box has the cfwheels client installed.  When I run the command line wheels info, I got an error.
![commandbox wheels info modified](https://user-images.githubusercontent.com/12297413/180271065-9e8f8067-3673-4241-8dfb-3032b0b19c1b.png)

**Describe the solution you'd like**
It would be nice to have an instruction or a reminder in the guides.
![CLI commands](https://user-images.githubusercontent.com/12297413/180271213-f83239bc-ed13-4aa1-ab5e-c739c3930b9b.PNG)

**Comment by MvdO79** [comment]
Thanks @tamdang501, the documentation seems to be updated right now with additional info about installing the cfwheels-cli module. So this issue can be closed! https://github.com/MvdO79/cfwheels/blob/develop/guides/command-line-tools/cli-commands.md
