### ISSUE TITLE
CFWheels guides - do we need the prefix crud/

### ISSUE THREAD

**Issue by tamdang501** [cfwheels/cfwheels#1167]
![generate view](https://user-images.githubusercontent.com/12297413/180272404-62537f9c-2149-46a6-8a4e-dc2400db058a.PNG)

FYI, as I tested, the command line worked without the "crud/Show".

**Comment by zainforbjs** [comment]
@tamdang501 The "crud/show" is the template used to create the view. It is not required and if we do not specify it in the command "wheels generate view show", then that will create a default empty view and if you pass in "crud/show" as well like "wheels generate view show crud/show", it will create a view file using the "show" template that is inside templates folder in your app.

The prefix "crud" is required as there is a templates folder in the app and it has a "crud" folder in which the templates are placed. The "crud/show" template command fetches the .txt file in the folder and uses that in the template.

![image](https://user-images.githubusercontent.com/115699497/222650494-da2c1b95-f817-40c3-a38e-b9f9db555ae8.png)


Hope that clarifies things.

**Comment by MvdO79** [comment]
Checking the guides for this issue here: https://guides.cfwheels.org/cfwheels-guides/command-line-tools/wheels-generate-commands#wheels-generate-view 

So is what's explained there understandable enough or should I add your explanation there @zainforbjs ?

**Comment by zainforbjs** [comment]
@MvdO79 Yeah that is understandable enough and is a summary of what I commented here.

But I think we should probably add this explanation there as well in case someone wants to go inside the default templates and make changes for their own specific site for the view templates.

**Comment by zainforbjs** [comment]
@bpamiri Once we update the Guides, we can mark this ticket as closed. Thanks

**Comment by MvdO79** [comment]
@zainforbjs I tried to clarify the text some more, can you confirm this is correct?

"The "crud/show" parameter of this command is referring to an existing template to be used to generate the "user/show" view. The prefix "crud" points to a templates directory in the app that holds a "crud" directory in which templates like "show" are placed. In this way the "crud/show" parameter fetches the show.txt template in the "templates/crud" directory and uses that for generating the "user/show" view."

I will add the image also.

**Comment by zainforbjs** [comment]
@MvdO79 Yeah that's perfect.

**Comment by bpamiri** [comment]
I also wanted to add some color around the template folder. I created that folder a couple of years ago, when I was working the CLI. At the time the CLI had its own internal template folder where it kept the CRUD files in and used them to generate the individual pages when the CLI commands were used.
