### ISSUE TITLE
wheels generate controller

### ISSUE THREAD

**Issue by tamdang501** [cfwheels/cfwheels#1168]
**Describe the bug**
2 command lines give a same result of creating a controller Users.cfc (with plural)
1. wheels generate controller user
2. wheels generate controller users

**Expected behavior**
I don't know if this is a bug, but because by the conventions, the name controllers is in plural form while model is singular, I want to report this.

**Comment by zainforbjs** [comment]
@tamdang501 I am not understanding what this issue is for. 
It is working as expected and creates controller with plural name in both commands.

Wheels automatically pluralize the controller name every time even if we pass in a singular name.

What is the bug here? Please clarify

**Comment by MvdO79** [comment]
> **Describe the bug** 2 command lines give a same result of creating a controller Users.cfc (with plural)
> 
> 1. wheels generate controller user
> 2. wheels generate controller users
> 
> **Expected behavior** I don't know if this is a bug, but because by the conventions, the name controllers is in plural form while model is singular, I want to report this.

Hi @tamdang501, as @zainforbjs reported this is indeed default behaviour so no bug. It forces the naming convention. I think the issue can be closed? Thanks for reporting though!

**Comment by neokoenig** [comment]
IIRC when I wrote it, the aim was to follow wheels conventions of singular models and plural controllers.
It actually uses the inbuilt wheels functions to do this:

```
 loc.objectName          = lcase(trim(arguments.name));
  loc.objectNameSingular  = singularize(loc.objectName);
  loc.objectNamePlural    = pluralize(loc.objectName);
  loc.objectNameSingularC = capitalize(loc.objectNameSingular);
  loc.objectNamePluralC   = capitalize(loc.objectNamePlural);
 ```
 
 So yeah,  as intended :P

**Comment by MvdO79** [comment]
Nice, and great, another problem solved 👍
