### ISSUE TITLE
Don't reload js/css from the internet

### ISSUE THREAD

**Issue by michaeldiederich** [cfwheels/cfwheels#1179]
**Describe the bug**
The testpage is loading CSS and JS-Files over the public internet, e.g.

https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css
https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js

As not all servers have full access to the internet, the test pages is not loaded completly. In addition, I don't want to share my IP-address with cloudflare or other CDNs.

I kindly request to store all needed files locally.

**To Reproduce**
Open the testpage: /index.cfm/wheels/packages/app
Check the network tab in your browser for the requests above

**Expected behavior**
Do not load any additional files over the public internet.

**Additional context**
cfwheels 2.4

**Comment by zainforbjs** [comment]
@michaeldiederich I stored the files in wheels directory and changed the links to refer to those files.
They should work offline now.

Here is a PR. https://github.com/cfwheels/cfwheels/pull/1255
