### ISSUE TITLE
Docker volume (adobe) causing exception in development/testing

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#1210]
**Describe the bug**

After uncommenting the ` # - ./:/cfwheels-test-suite` volume line in abobe2016 and abobe2018 services in docker-compose.yml, and booting the containers, an exception is thrown when loading any page in a browser.

Could not find the ColdFusion component or interface /cfwheels-test-suite/Application.cfc.

The file appears to have been copied into the docker container.

This is not the case with Lucee service

**To Reproduce**
1. Uncomment - ./:/cfwheels-test-suite in either abobe2016 or abobe2018 service in docker-compose.yml
2. run `docker compose up --build adobe2016 mysql`
3. Visit http://localhost:62016
4. See exception

**Expected behavior**

- No exception thrown
- Allow changes to files to be seen in docker container without rebuilding

**Screenshots**
![image](https://user-images.githubusercontent.com/1092563/198154583-2fb6eb96-594e-4c78-928c-df42244a933b.png)

![image](https://user-images.githubusercontent.com/1092563/198154495-c119c240-1f72-4c7a-9e7b-d8acc3bcb1be.png)

**Desktop **
 - OS: Ubuntu Linux

**Comment by bpamiri** [comment]
@chapmandu Adam am going to close this issue since the 2.5.0 branch now has a reworked testing suite and there is no need to comment or uncomment lines any longer.
