### ISSUE TITLE
Attribute to define whether a calculated property is used by default in a select statement with findAll() 

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#122]
Some calculated properties should not be used in a select statement by default if the select attribute is not specified, particularly aggregate functions and complex statements. They can significantly affect existing application code if added part-way through development.

An attribute to determine whether a column is used in a select statement (only when a select attribute has not been defined) would be useful. It would default to "true". One would need to specify these columns in the select statement to use them.

Eg:
&lt;cfset property(name="yearcreated", sql="YEAR(createdat)", includeInSelect=false) />
&lt;cfset property(name="thecount", sql="COUNT(1)", includeInSelect=false) />
&lt;cfset property(name="complex", sql="[a really complex bit of SQL]", includeInSelect=false) />

Comment 1 by project member tpetru...@gmail.com, Jun 30, 2012 look at $createSQLFieldList()

Copied from
http://code.google.com/p/cfwheels/issues/detail?id=843

**Comment by perdjurner** [comment]
Running out of time for this to be in 1.4, postponing.

**Comment by perdjurner** [comment]
Aggregate functions should never be in the select statement unless group by is used.
Ideally we should just not include them in those cases.

**Comment by perdjurner** [comment]
Needs a test written before release.
