### ISSUE TITLE
Error generating a new app

### ISSUE THREAD

**Issue by edthetechie** [cfwheels/cfwheels#1235]
**Describe the bug**
I need to start a new project so I opened an administrator command prompt in windows , ran up the commandbox cli, navigated to the parent projects folder and issued the usual "wheels generate app [client_name]" command. I then ran the cli command to install wheels and thereby update it, after which I re-ran the generate command, but no joy. The cli returned an error as follows:
```
CommandBox:Work Projects> wheels generate app rorc
Currently working in C:\Users\ed\Work Projects\
Installing the application template...
 × | Installing package [forgebox:cfwheels-template-base]
   | > Error getting ForgeBox entry [cfwheels-template-base]
   |-------------------------------------------------------------------
   | Verifying package 'cfwheels-template-base' in forgebox, please wait...
   | Error getting ForgeBox entry [cfwheels-template-base]  The entry slug sent is invalid or does not exist
   |-------------------------------------------------------------------

ERROR (5.4.2+00453)

Error getting ForgeBox entry [cfwheels-template-base]

The entry slug sent is invalid or does not exist
\system\endpoints\ForgeBox.cfc: line 578
576:                    if( e.detail contains 'The entry slug sent is invalid or does not exist' ) {
577:                            job.addErrorLog( "#e.message#  #e.detail#" );
578:                            throw( e.message, 'endpointException', e.detail );
579:                    }
580:
called from \system\endpoints\ForgeBox.cfc: line 58
called from \system\services\PackageService.cfc: line 109
called from \modules\cfwheels-cli\commands\wheels\generate\app.cfc: line 113
called from \system\services\CommandService.cfc: line 345
called from \system\services\CommandService.cfc: line 139
called from \system\Shell.cfc: line 787
called from \system\Shell.cfc: line 607
called from \system\Bootstrap.cfm: line 160
```

**To Reproduce**
1. Go to commandbox
2. Enter: wheels generate app rorc
3. Wait

**Expected behavior**
The cli should do its thing and generate me a shiny new app to start working on

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Commandbox Version: 5.4.2+00453

**Comment by neokoenig** [comment]
Looks like it should be "cfwheels-base-template" - https://forgebox.io/view/cfwheels-base-template rather than cfwheels-template-base in the cli.

Looks correct here though - https://github.com/cfwheels/cfwheels-cli/blob/develop/commands/wheels/generate/app.cfc

Is your version of the CLI up to date? Run `update --system` from commandbox and it should update

**Comment by neokoenig** [comment]
https://github.com/cfwheels/cfwheels-cli/commit/26a3ab6429699bd295b83b510907d131bc10e0a4 <-- yeah  you're definitely on an older version of the cfwheels-cli package

**Comment by edthetechie** [comment]
I updated Commandbox as instructed and then tried the wheels generate command again but got the same error. So I exited out of Commandbox and restarted the cli, it has worked now. It was definitely an update issue. My bad, I thought reinstalling the wheels cli would update it, I know differently now. Thanks again for the quick response, Tom. Most appreciated. Have a great weekend!

**Comment by bpamiri** [comment]
CommandBox downloads and caches the artifacts so reinstalling will reinstall the same version. The update command or clear artifacts commands force CommandBox to download fresh copies.

--Peter Amiri
  ***@***.***
