### ISSUE TITLE
In the API documentation inform that subqueries are not allowed in the WHERE clause

### ISSUE THREAD

**Issue by MvdO79** [cfwheels/cfwheels#1272]
Might be useful to add some information in the API documentation that subqueries are not allowed in the WHERE clause?
If so, assign me if possible. 

### Discussed in https://github.com/cfwheels/cfwheels/discussions/1271

<div type='discussions-op-text'>

<sup>Originally posted by **MvdO79** July 17, 2023</sup>
Hi all!

Using this:

`listings=model("listing").findAll(where="#whereQuery#", page=params.page, perPage=6, order="pk_listings DESC", handle="listingsData");`

and this query in #whereQuery#:

`status='1' AND headcategory='2' AND (country='Nederland' OR fk_listings_users IN(SELECT pk_users FROM users WHERE country='Nederland'))`

i get an error:

`<html>
<body>

Array index [4] out of range, array size is [3]
--
Stacktrace | The Error Occurred inD:\odrive\OneDrive\Websites\advertenties\wheels\model\sql.cfm: line 489487: }488: if (local.i < ListLen(local.where, "?")) {489: local.column = local.params[local.i].column;490: ArrayAppend(local.rv, local.column & " " & local.params[local.i].operator);491: local.param = {type=local.params[local.i].type, dataType=local.params[local.i].dataType, scale=local.params[local.i].scale, list=local.params[local.i].list};

</body>
</html>`

Any ideas?</div>

**Comment by MvdO79** [comment]
Added extra info for where clause and created PR.

**Comment by bpamiri** [comment]
@MvdO79 I've added some quick guides on how to modify the CFWheels Guides which you have already figured out as well as how to modify the API Docs. The API docs is a little more involved but at the end of the day its just submitting a PR to the main repository, getting it published is a manual process at the but I hope to be able to automated that in the future.

**Comment by MvdO79** [comment]
Great, thanks, will check it.
