### ISSUE TITLE
AJAX tutorial documentation improvement

### ISSUE THREAD

**Issue by MvdO79** [cfwheels/cfwheels#1306]
I'm on the 3rd tutorial for AJAX.  As feedback from fresh eyes, I think it would be helpful to explain what the route "to" attribute "say##hello" means to CFW.  I see from debugger mode that it creates an action "say-hello" with the query params. How does CFW interpret that? No explanation about it. I didn't have the functions added in the Say.cfc yet and nothing was working. I tried adding a "pattern='say/hello'" but that didn't do anything. I then added the Say.cfc additions and still didn't work till I removed that pattern. Then it worked. But how is it working with say-hello action?

_Originally posted by @cfcoder in https://github.com/cfwheels/cfwheels/discussions/1298#discussioncomment-7459182_

**Comment by bpamiri** [comment]
Added more description to point out that the `to` parameter is a shorthand for the `controller` and `action` parameters.
