### ISSUE TITLE
Rewrite the Vue based TestUI app as a stand alone CFML app with some HTMX/Alpine thrown in

### ISSUE THREAD

**Issue by bpamiri** [cfwheels/cfwheels#1317]
**Is your feature request related to a problem? Please describe.**
The Vue.js TestUI app is only used to queue up jobs for the test runner. Realistically it doesn't even need to exist since each of the CFEngine containers can be launched manually and the tests run manually. The TestUI app is just a convenient way to run multiple server/database combinations or queue up tests to run in sequence.

The Vue.js app causes issues when libraries are update and vulnerabilities are discovered.

**Describe the solution you'd like**
Rewrite the Vue.js app in pure CFML perhaps with HTMX and Alpine.js to achieve the same interactivity.

**Comment by neokoenig** [comment]
TBH I wrote that vue app as purely a convenience... 
You could actually refactor using a single script tag with no dependencies (as you could replace axios with fetch) or use Petit Vue ( https://github.com/vuejs/petite-vue ) maybe.

**Comment by zainforbjs** [comment]
@bpamiri I've started to dig more details, will keep you posted here.

**Comment by bpamiri** [comment]
@zainforbjs The rewrite looks good. Just ran some quick tests against it for testing multiple paths. Great job.
