### ISSUE TITLE
Problem with using a different datasource in a model cfc in v2.5

### ISSUE THREAD

**Issue by edthetechie** [cfwheels/cfwheels#1319]
**Describe the bug**
I updated one of my client sites today from 2.4 to 2.5 and it all seems to work except that I'm getting an error on pages where I need to connect to a different database than the default one in settings.cfm 
My model config looks like this:
```
component extends="Model" {
  function config() {
    dataSource("other_database_name");
  }
}
```

In 2.4 it works fine but in 2.5 I get an error saying:
[Macromedia][SQLServer JDBC Driver][SQLServer]Invalid object name 
Which leads me to believe that the correct datasource isn't being accessed

**To Reproduce**
1. In the model's CF add a different datasource to the default one
2. Write a test findAll() function to request rows from a table in the database added in step 1

**Comment by bpamiri** [comment]
Ed,

Can you try `findAll(datasource="other_database_name")` to see if that works. I just did some tests and it appears that the datasource setting in the model is being ignored but if I add it to the findAll() it work. Just wanted to make sure you can confirm this behavior on your end.

-Peter

**Comment by edthetechie** [comment]
Hi Peter,

Yes that works. Will I need to change my code or is this something that can be fixed in a future version? I don't mind waiting to upgrade this client if necessary.

-= Ed

**Comment by zainforbjs** [comment]
@edthetechie Great to hear that works for you. For sure, we can have that fix in future version. Thank you

**Comment by edthetechie** [comment]
No problem at all, I'm currently testing my client sites on the new version so you might see more issues from me but hopefully not. So far everything seems really smooth.

**Comment by zainforbjs** [comment]
@edthetechie Looking forward. Appreciated.

**Comment by edthetechie** [comment]
Thanks for all your hard work, Zain!

**Comment by chapmandu** [comment]
It's possible I broke this when adding the datasource argument to finder functions.

**Comment by chapmandu** [comment]
https://github.com/cfwheels/cfwheels/pull/1324
