### ISSUE TITLE
Problem with pagination in v2.5

### ISSUE THREAD

**Issue by edthetechie** [cfwheels/cfwheels#1320]
**Describe the bug**
I have a site with some complex pagination on it and that has broken with the update to version 2.5. In essence, I'm adding "previous" and "next" links to the pagination using a custom _pagination.cfm partial that I created. The code in that partial looks like this:
```
<cfoutput>
    <cfset paginationData = pagination()>
    <cfif paginationData.currentPage GT 1>
      <cfif IsDefined("paginationArgs.params")>
        <cfset prev = '<li>' & linkTo(argumentCollection=paginationArgs, params="#paginationArgs.params#&page=#paginationData.currentPage-1#", text="<i class='fas fa-arrow-left'></i>", encode=false, class="pagination-previous") & '</li>'>
      <cfelse>
        <cfset prev = '<li>' & linkTo(argumentCollection=paginationArgs, params="page=#paginationData.currentPage-1#", text="<i class='fas fa-arrow-left'></i>", encode=false, class="pagination-previous") & '</li>'>
      </cfif>
    <cfelse>
      <cfset prev = ''>
    </cfif>
    <cfif paginationData.currentPage LT paginationData.totalPages>
      <cfif IsDefined("paginationArgs.params")>
        <cfset next = '<li>' & linkTo(argumentCollection=paginationArgs, params="#paginationArgs.params#&page=#paginationData.currentPage+1#", text="<i class='fas fa-arrow-right'></i>", encode=false, class="pagination-next") & '</li>'>
      <cfelse>
        <cfset next = '<li>' & linkTo(argumentCollection=paginationArgs, params="page=#paginationData.currentPage+1#", text="<i class='fas fa-arrow-right'></i>", encode=false, class="pagination-next") & '</li>'>
      </cfif>
    <cfelse>
      <cfset next = ''>
    </cfif>
    <cfset paginationArgs.prepend = "<ul class='pagination is-small is-rounded' role='navigation' aria-label='pagination'>#prev#">
    <cfset paginationArgs.append = "#next#</ul>">
    <cfset paginationArgs.encode = false>
    <cfset paginationArgs.class = "pagination-link">
    <cfset paginationArgs.windowSize = 6>
      #paginationLinks(argumentCollection=paginationArgs)#
      <cfset paginationArgs.prepend = "">
    <cfset paginationArgs.append = "">  
  </cfoutput>
```

The error I'm getting in Coldfusion is here
<html>
<body>

Element addActiveClassToPrependedParent is undefined in ARGUMENTS.
--
 
 
The error occurred in E:/Domains/demo/demo.glf-group.com/wwwroot/wheels/view/links.cfm: line 342Called from E:/Domains/demo/demo.glf-group.com/wwwroot/views/admin/registrants/_pagination.cfm: line 29Called from E:/Domains/demo/demo.glf-group.com/wwwroot/wheels/global/cfml.cfm: line 118Called from E:/Domains/demo/demo.glf-group.com/wwwroot/wheels/controller/rendering.cfm: line 625Called from E:/Domains/demo/demo.glf-group.com/wwwroot/wheels/controller/rendering.cfm: line 447Called from E:/Domains/demo/demo.glf-group.com/wwwroot/wheels/controller/rendering.cfm: line 475Called from E:/Domains/demo/demo.glf-group.com/wwwroot/wheels/view/miscellaneous.cfm: line 290Called from E:/Domains/demo/demo.glf-group.com/wwwroot/views/admin/registrants/index.cfm: line 144Called from E:/Domains/demo/demo.glf-group.com/wwwroot/wheels/global/cfml.cfm: line 118Called from E:/Domains/demo/demo.glf-group.com/wwwroot/wheels/controller/rendering.cfm: line 625Called from E:/Domains/demo/demo.glf-group.com/wwwroot/wheels/controller/rendering.cfm: line 380Called from E:/Domains/demo/demo.glf-group.com/wwwroot/wheels/controller/rendering.cfm: line 69Called from E:/Domains/demo/demo.glf-group.com/wwwroot/wheels/controller/processing.cfm: line 134Called from E:/Domains/demo/demo.glf-group.com/wwwroot/wheels/controller/processing.cfm: line 92Called from E:/Domains/demo/demo.glf-group.com/wwwroot/wheels/dispatch/functions.cfm: line 199Called from E:/Domains/demo/demo.glf-group.com/wwwroot/wheels/index.cfm: line 6Called from e:/domains/demo/demo.glf-group.com/wwwroot/rewrite.cfm: line 2Called from E:/Domains/demo/demo.glf-group.com/wwwroot/wheels/events/onrequest.cfm: line 4
340 : 						The changes made here set the active class to the immediate parent of the current page element in case nested elements are passed in. 341 : 					 */ 342 : 					if(local.currentPage == local.i  && arguments.addActiveClassToPrependedParent && findNoCase('class', arguments.prependToPage)) { 343 : 						local.prependToPageElementArr = listToArray(arguments.prependToPage, '<'); 344 : 						local.lastElementArrIndex = arrayLen(local.prependToPageElementArr);

</body>
</html>

The code on line 29 of _pagination.cfm is:
```
#paginationLinks(argumentCollection=paginationArgs)#
```

**Comment by zainforbjs** [comment]
@edthetechie Did you try by restarting the application server?

Because the error you are getting is saying that this variable is not defined in the arguments scope even though I added that in the defaults in the onapplicationstart.cfm file for the function paginationLinks().

![image](https://github.com/cfwheels/cfwheels/assets/115699497/11d1c884-84b7-4240-a12f-d7215b90b2b5)

Can you try by restarting the application server and see if that fixes it for you?

**Comment by edthetechie** [comment]
@zainforbjs I thought I had when I switched the wheels folders over with the upgrade but maybe I forgot because when I tried it this morning the problem has gone. Looks like a user (me) error. Apologies for the time-wasting!

**Comment by zainforbjs** [comment]
@edthetechie Sounds Good. No worries.
