### ISSUE TITLE
Wildcard route in v2.5 throws an error with no controller in the linkTo() or urlFor()

### ISSUE THREAD

**Issue by edthetechie** [cfwheels/cfwheels#1321]
**Describe the bug**
When using the wildcard() route in version 2.5 I'm getting errors when the linkTo() and urlFor() methods have an action but no controller. I know using the wildcard is not best practise but I have a legacy site that has hundreds of them.

**To Reproduce**
1. Activate the wildcard route in routes.cfm
2. Create a test controller called "Testing.cfc" with action called "wildcard"
3. In a test view add: #linkTo(action="wildcard")#

**Expected behavior**
The wildcard should default to using the name of the current controller

**Comment by zainforbjs** [comment]
@edthetechie Thanks for posting, Sure. We will keep you posted with fix in future versions.

**Comment by zainforbjs** [comment]
@edthetechie I've gone through and followed as mentioned and able to reproduce the error on both versions of cfwheels 2.4 and 2.5. Could you please add some screenshots or video recordings that might more helpful?

**Comment by edthetechie** [comment]
@zainforbjs Did you mean "unable to reproduce"? It definitely wasn't a problem in 2.4 but my first install of 2.5 caused the problem. I put 2.5.1 on there and restarted the server and the problem has gone away. I suggest we close this one and if it crops up again I'll raise another issue.

**Comment by zainforbjs** [comment]
@edthetechie Sure, Sounds good.
