### ISSUE TITLE
Test framework documentation enhancements

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#133]
## Troubleshooting guide
- What to do when you are redirected to a page in your application whilst running tests (check for &lt;cfset redirectTo(...)> rather than cfreturn or missing delay=true attribute)
- What do do when browser message "The page isn't redirecting properly
    Firefox has detected that the server is redirecting the request for this address in a way that will never complete.
  This problem can sometimes be caused by disabling or refusing to accept
    cookies." (sometimes due to filters handlers and redirects?.. TBA)
- Tests being skipped.. (component doesn't extend wheelsMapping.Test.. or test case isn't named "test*")
## More practical examples. 

Perhaps step through testing of: 
- a Scaffold generated controller
- a helper function (events/functions.cfm)
- a plugin. (table-less models should help here BIG time)
- WHAT to test.. eg: one test case for every validation, one test case for every method in your model
- Switching transactionMode to "rollback" for testing
- Replicating a user session
- Mock data
- Plugin testing.. using a plugin-centric assets/test environment
- Using additional arguments in assert() for debugging
- Practical example of raised()
- a line-by-line description of some test cases
- testing an ajax request
## Recommended conventions / best practice
- tests/model <-- named UserModelTest.cfc
- tests/controllers <-- named UsersControllerTest.cfc
- tests/views <-- UsersViewsTest.cfc
- tests/helpers <-- HelpersTest.cfc
- test cases must begin with "test" 
- using a global helper (tests/helper.cfm)
- controllers/models should be modified to pass tests.. not vice-versa 

http://guides.rubyonrails.org/testing.html

**Comment by chapmandu** [comment]
Can we close this?

**Comment by perdjurner** [comment]
Yes.
