### ISSUE TITLE
v2.5.1 Error after install and reload

### ISSUE THREAD

**Issue by edthetechie** [cfwheels/cfwheels#1330]
**Describe the bug**
I just installed the 2.5.1 update to check the datasource fix and the website is throwing the error below. I updated it the same way I normally do; by downloading the zip and extracting the wheels folder. I did it twice to make sure I wasn't doing something dumb.
<html>
<body>

Could not find the included template wheels/functions.cfm.
--
Note: If you wish to use an absolute template path (for example, template="/mypath/index.cfm") with include, you must create a mapping for the path using the ColdFusion Administrator. Or, you can use per-application settings to specify mappings specific to this application by specifying a mappings struct to THIS.mappings in Application.cfc.Using relative paths (for example, template="index.cfm" or template="../index.cfm") does not require the creation of any special mappings. It is therefore recommended that you use relative paths with include whenever possible.
 
The error occurred in E:/website_path/wwwroot/Application.cfc: line 2
1 : component output="false" { 2 : 	include "wheels/functions.cfm"; 3 : }

</body>
</html>

**To Reproduce**
1. Rename old wheels folder
2. Extract wheels folder from zip
3. Reload the application

**Expected behavior**
The application should reload normally without any errors

**Comment by edthetechie** [comment]
I tried copying the Application.cfc in the web root of the 2.5.1 bundle into my application route but now I'm getting an error with a plugin method not being found.

**Comment by bpamiri** [comment]
@edthetechie Did you restart the server? Not just reload the application?

**Comment by neokoenig** [comment]
@bpamiri 
I think the 2.5.1 release (as on https://github.com/cfwheels/cfwheels/tags) is actually 3.0.0-SNAPSHOT ?

I was a little surprised when I downloaded it to see a bunch of "stuff I tried once" in /wheels/; certainly the download supplied doesn't have `./wheels/functions.cfm`, and I got the error above.

When I updated my application.cfc (which used to reference /wheels/functions) to match the current master it then worked and was reporting its version as 3.0.0-SNAPSHOT - might be worth investgating....?

**Comment by edthetechie** [comment]
@bpamiri Restarting the CF server seems to have done the trick and my development site is working

**Comment by bpamiri** [comment]
@neokoenig you were absolutely correct. The release to ForgeBox is an automated process but tagging and packaging the release on GitHub is still a manual process which I botched up pretty badly. When I tagged v2.5.1, I actually tagged develop and not master. Secondly I missed the manual step of downloading the variant zip file from the release GitHub action and uploading it to the actual release so the only thing in the release was the source which I had pointed to the wrong branch.

I believe all is fixed now. 

@edthetechie if you were downloading the artifacts from the release please download the new artifacts. If you did a download from the main branch then you should have gotten the correct code.

**Comment by zainforbjs** [comment]
Seems like we are good to go, @bpamiri we can close this issue, if there is no further issue.
