### ISSUE TITLE
Cannot test controller actions that use verifies() & a handler with redirectTo()

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#136]
If I write a test case called test_edit_action_redirects_to_someAction_when_userid_is_missing.. I will actually be redirected out of the test framework and to someAction because the redirectTo() is being called 'by proxy' (for want of a better term)

The only workaround I have found is to code the condition and redirect into the edit action.. which makes my controller testable, but less DRY.

<pre>
&lt;cfcomponent extends="Controller" output="false">
        
    &lt;cffunction name="init">
        &lt;cfset verifies(only="edit", params="userId", handler="someHandler")>
    &lt;/cffunction>

    &lt;cffunction name="someHandler">
        &lt;cfreturn redirectTo(action="someAction", delay=true)>
    &lt;/cffunction>

    &lt;cffunction name="edit">
        &lt;cfset ... />
    &lt;/cffunction>

&lt;/cfcomponent>
</pre>

**Comment by perdjurner** [comment]
Fixed in e06f588aadbbe7acfc987d03f1985eb607a26855, please confirm.

**Comment by perdjurner** [comment]
Closing, assumed fixed.
