### ISSUE TITLE
Using the same function names in different test packages causes debug() output duplication

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#176]
Edge case!
- create 2 tests in different packages with the same name. eg: name="test_something"
- in those 2 tests, create a variable with the same names. eg: loc.response
- use the debug function in one of the tests to display loc.response

The "loc.response" debug will be displayed in both tests.

Workaround: Ensure test names are unique across all packages

UPDATE:
running this package via URL "package=controllers.AdministratorsTest"

Will run any nested package called "AdministratorsTest" underneath "controllers" folder.

Eg:

controllers.AdministratorsTest
controllers.security.AdministratorsTest
controllers.subdomains.AdministratorsTest

**Comment by neokoenig** [comment]
Is this still an issue in 2.x? I've not hit it myself.
