### ISSUE TITLE
Cannot use test framework to test for  ajax responses

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#214]
Using params.format="json" in any test in the RocketUnit test framework results in the entire test result response (HTML) being displayed as plain text

**Comment by chapmandu** [comment]
This is still an issue

https://groups.google.com/forum/?fromgroups=#!topic/cfwheels/snVT8rLAUW4

**Comment by jkeczan** [comment]
I have made some progress on this. In my tests on CF11, I am successfully able to to receive json requests inthe test framework without the page dumping. What we do is put a <cfcontent type="text/html" /> right after the process action call. This will reset the content of the page back to html and allow the action to return the proper data.

**Comment by perdjurner** [comment]
Any changes required to CFWheels code?

**Comment by jkeczan** [comment]
No, sorry I typed that comment with my iPad and it didn't appear to show the code snippet

```
<cfcontent type="text/html" />
```

This required no additional code in the production codebase, only the above line in the test

**Comment by perdjurner** [comment]
Closing this since it can be fixed outside of Wheels code.

However, if it would simplify things to have that line of code inside Wheels somehow, please submit a pull request.

Thanks.

**Comment by perdjurner** [comment]
Fixed.

When using the new processRequest() function it will set the content-type header back to text/html.
