### ISSUE TITLE
Rename renderPage()

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#288]
Rename it to renderView() to make the name less confusing.

**Comment by perdjurner** [comment]
Closing this in favor of better debugging:
https://github.com/cfwheels/cfwheels/issues/463

**Comment by chapmandu** [comment]
@perdjurner Would an alias be considered for 2.0? `renderView` is a more intuitive name than `renderPage`

**Comment by perdjurner** [comment]
Sure, I think we should just rename it though.

We already did it once for 1.2:
https://github.com/cfwheels/cfwheels/commit/f4718f0d841ff54aa0677bc9ce937e3a34e1184e

@neokoenig @chrisdpeters any thoughts on this?

**Comment by neokoenig** [comment]
If we're going to do it, now is the correct time to do it. I've never had an issue with renderPage() myself, but I suppose renderView() is more "correct".

**Comment by perdjurner** [comment]
Adding to Beta milestone so we at least consider this before releasing.

**Comment by chrisdpeters** [comment]
I think the clearer name is win.

**Comment by andybellenie** [comment]
Nice to see this one raised from the dead. I support, obviously :)

**Comment by perdjurner** [comment]
Done in https://github.com/cfwheels/cfwheels/commit/9745a6d4e9baf28cda86da37c57c171f2327b7cb.

Leaving open to document before release.

**Comment by perdjurner** [comment]
Everything under "Documentation" in Readme has been updated now.
