### ISSUE TITLE
Models in sub-folders

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#295]
Allow placement of models in sub-folders for better organization.
Any other code needed than simple the ability to place them there?

**Comment by perdjurner** [comment]
@chrisdpeters Is this redundant now that we plan on integrating ColdRoute?

Please close this one if that is the case.

**Comment by chrisdpeters** [comment]
@perdjurner This would be redundant for controllers with ColdRoute integration, but not models.

I'd love to see this for models if you want to change the title of this issue and schedule it for v2.0.

**Comment by neokoenig** [comment]
With the new `app` mapping in 2.x, this is actually now more do-able. 

i.e, if you do `models/foo/bar` and the model extends `app.model`, then you can call that model by it's dot notation path, i.e, `mystuff=model("foo.bar").new()` - I've only tested this on tableless models though. I assume if you've got `models/admin/User.cfc`, it's going to get very confused about what the table name is: I need to check whether it's as simple as just defining `table()` in the `config()` section of the model, or whether it's more involved

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
