### ISSUE TITLE
Improvements to sendEmail()

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#296]
Make it accept external link and full paths attachments.
Allow custom "mailparams" to by passed in.

**Comment by perdjurner** [comment]
@neokoenig I think you worked on this or something similar, can this issue be closed?

**Comment by neokoenig** [comment]
I don't think this was ever resolved (but also can't remember what the original issue was really)

**Comment by perdjurner** [comment]
Yeah, can't remember either, closing.
