### ISSUE TITLE
More documentation on contributing to the framework

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#308]
One of the (perceived) barriers in contributing to the cfwheels codebase is a lack of documentation on how the framework is 'architected'. Numerous cfwheels users (myself included) have been somewhat reluctant to contribute due to the learning curve of jumping into the core code. If we could lessen that learning curve it may encourage more contributions? 

Perhaps some thought could be given to mapping/diagramming/explaining:
- How a request is processed
- Where to find particular core code (eg: model, caching, plugin mixins etc)
- How to write tests for the code contributed (see my previous whinge here #133)

The late Kym Kovan started a diagram.. 
https://www.lucidchart.com/documents/view/4177-5540-50845070-af16-12310ace1e50

**Comment by perdjurner** [comment]
Closing this.

I plan on improving the code comments though so please open new issues if there is anything that can be improved in terms of that (much easier if we break it down like that to find the real barriers for contribution).
