### ISSUE TITLE
Select all columns on self joins

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#309]
When doing a self join (i.e. include="tosamemodelascurrent") the select should automatically include all columns.

Example for a User model with a manager belongsTo.

model("user").findAll(include="manager").

users.id, users.name, managers.id AS managerId, managers.name AS managerName

(the WHERE sets the alias on the table to the pluralized version of the association name already).

**Comment by andybellenie** [comment]
I think this should be marked as a bug - without the ability to return the associated columns the self join is useless when returning recordsets

**Comment by perdjurner** [comment]
I think you can return them, it's just not automatic.

Example from above:
select="users.id, users.name, managers.id AS managerId, managers.name AS managerName"

I agree with you though, this should be marked as a bug because if we get it done for 2.0 it makes sense to back-port.

**Comment by andybellenie** [comment]
Hmm, frustrating thing about that is you can't use the select argument to add additional columns to the default, so you end up having to specify them all. That would make a useful additional argument actually - e.g. additionalColumns

**Comment by perdjurner** [comment]
@andybellenie I've started on a plugin to deal with that frustrating issue you mentioned: https://github.com/perdjurner/selectstring

Very simple for now but I hope to build on it (and perhaps add to core at some point).

Let me know if you have any ideas.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
