### ISSUE TITLE
Get rid of "design" mode

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#312]
This makes "development" the default mode which is a good thing since it will force developers to do a reload when they want changes to their "init" methods to be picked up.

That way they will quickly realize that the "init" method does not run on every request and they do not make the mistake of trying to put request specific code in there.

**Comment by perdjurner** [comment]
I made "development" the default instead.
Should be almost as effective.

**Comment by neokoenig** [comment]
Ugh. My only bug bear with this is development is longer to type :P
