### ISSUE TITLE
Prefix associated columns with association name

### ISSUE THREAD

**Issue by jkeczan** [cfwheels/cfwheels#328]
Without the ability to join to the same model twice, it limits what queries you can do in CFWheels syntax rather than dropping down into the model to write a custom query. It appears there are two things that must happen for this to be viable. 

One, a model would need the option to supply an alias name that is used instead of the normal table name. The default alias could be "cfwa" + tableName. for example a model with the table "User" would have a default alias of cfwaUser. The alias could also be set in the model with setTableAlias("")

The second part would require making model joins append a numeric value from a sequence everytime they are joined. For example,

cfwaUser
cfwaUser2

I have probably wrote 2 dozen custom queries due to have userCreated and userModified as foreign keys on the same model. Any thoughts?

**Comment by perdjurner** [comment]
"I'm saying that it should always use the association name for all included associations in queries"

I know I've +1'ed that but I'm not 100% sold on it.

It would mean adding " AS something" on every single column in the SELECT statement. That just doesn't seem right to me and just makes you think that we should rename the actual database columns instead (which I don't like because it's redundant).

**Comment by perdjurner** [comment]
Wait, I take that back, sine we're just talking about the associated data.

So, this makes me look like an idiot but I'm going to leave this here to remind me of my (stupid) thought process when I come back to thinking about an implementation in the future :)

**Comment by perdjurner** [comment]
FYI, I changed the issue title since you can now actually join a model to itself and this issue is more about how the naming of those columns should be done.

**Comment by perdjurner** [comment]
Also, here's a related issue:
https://github.com/cfwheels/cfwheels/issues/309

**Comment by chrisdpeters** [comment]
@perdjurner See [this comment](https://github.com/cfwheels/cfwheels/issues/328#issuecomment-51056414). :)

**Comment by perdjurner** [comment]
:+1:

**Comment by chrisdpeters** [comment]
Just a note that today someone in the CFWheels Slack channel expressed some desire for this enhancement so they could join the same table twice in a query.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
