### ISSUE TITLE
afterFind doesn't seem to register with findAll on included models

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#329]
The callback doesn't register in the "bar" model

&lt;cfset foobars = model("Foo").findAll(include="Bars") >

But registers when the models are swapped..

&lt;cfset foobars = model("Bar").findAll(include="Foo") >

**Comment by chapmandu** [comment]
Could this be flagged as an enhancement. I am having more and more need for this and the workarounds are getting rather ugly. It doesn't really make sense for the feature NOT to be run in included models..

**Comment by perdjurner** [comment]
Sure, would be great if this can be improved. Setting it to enhancement doesn't magically mean it gets  done though ;)

**Comment by perdjurner** [comment]
Documented.

**Comment by chapmandu** [comment]
Since you guys are up to your nuts in callbacks.. I don't suppose this could be looked at? I am regularly doing battle with workarounds for this.. quite often having to add static methods or helpers to compensate for columns that should be generated with afterFind..

**Comment by perdjurner** [comment]
Can you create a failing test for this (or multiple ones if you think it's needed)?

That always makes it easier to implement a fix.

Thanks.

**Comment by chapmandu** [comment]
Sure..and thanks for reconsidering.. :)

**Comment by chapmandu** [comment]
bump!

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
