### ISSUE TITLE
Implement a version of cfflush

### ISSUE THREAD

**Issue by jkeczan** [cfwheels/cfwheels#330]
One of the main issues we experience with CFWHeels is displaying tables with 100's of rows. Since the framework has to completely finish generating the page, the initial page load times are delayed by the amount of rows it has to render. Coldfusion handles this with cfflush. Is there anyway to port this into CFWheels. I know we can paginate data but we have customers who simply do not want paged data. They want a long list. 

Would implementing something like flush() be an option?

**Comment by perdjurner** [comment]
Closing, not really feasible given the current Wheels architecture.
