### ISSUE TITLE
MongoDB Support

### ISSUE THREAD

**Issue by jkeczan** [cfwheels/cfwheels#346]
I was reading some old google forums and noticed you guys were investigating a MongoDB wrapper. Did you have any success or do any work that? I may have a project coming up that MongoDB would be perfect for.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
