### ISSUE TITLE
CGI.HTTP_Host is undefined during websocket call

### ISSUE THREAD

**Issue by jkeczan** [cfwheels/cfwheels#350]
I am using websockets for a particular piece of functionality on my site and I was wanting to query a count of objects during the request. The query was 

```
<cfset c = model("ModelName").count(where="isComplete = 1") />

```

This query works just fine in normal requests, but in web socket requests, I get the following error:

**coldfusion.runtime.UndefinedElementException: Element CGI.HTTP_HOST is undefined in REQUEST.**

I unfortunately do not get any stack traces or line numbers in the error in any log nor during a try/catch. My thought is wheels uses HTTP_Host down in its framework but first doesn't check to see if it exists.

According to this blog post from Ben Nadel:
http://www.bennadel.com/blog/2545-dumping-out-the-cgi-scope-does-not-list-all-available-cgi-values-in-coldfusion.htm

websocket requests do not follow traditional http structures and may have missing information.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
