### ISSUE TITLE
Event Callback Enhancement

### ISSUE THREAD

**Issue by jkeczan** [cfwheels/cfwheels#353]
I was wondering what your guys thoughts would be on additional callbacks in the model for "onFailedValidate", "onFailedSave", "onFailedCreate", "onFailedUpdate". The reason I believe these would be good is due to times when data needs converted going in/out of the database, such as encryption routines.

What do you guys think?

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
