### ISSUE TITLE
Ability to verify variable values in Test Cases

### ISSUE THREAD

**Issue by jkeczan** [cfwheels/cfwheels#358]
It would be very helpful if we had the ability to test a value within a action call specifically. For example, we have the following before filter function that runs on every action:

```
<cffunction name="$setEmployee">
    <cfset var loc = {} />

    <cflock type="readonly" scope="session" timeout="3000">
        <cfset employeeNumber = SESSION.employee.empNum />
    </cflock>

    <cfif checkParam("empNum")>
        <cfset employeeNumber = PARAMS.empNum />
    </cfif>
</cffunction>

<cffunction name="checkParam" returnType="boolean">
    <cfreturn StructKeyExists(PARAMS, "empNum") AND PARAMS.empNum neq "" />
</cffunction>
```

it would be nice if we could verify the value of employeeNumber in a test case. Maybe this is possible and I am unaware, but if not, it would really be helpful in this case. I know there are other ways to verify the information such as what the page renders, but that may not be as easy for all cases.

**Comment by perdjurner** [comment]
To make it testable you need to add it to the this scope instead so it's available from the outside:
`<cfset this.employeeNumber = PARAMS.empNum />`

Then from your test:
```
local.controller = controller(...);
local.controller.processAction();
theValue = local.controller.employeeNumber;
```

Or if you think that's too ugly, make a public function on the controller that just returns the value and then call that from your tests instead.

**Comment by perdjurner** [comment]
Actually, this might be useful to document so opening it back up for that.

**Comment by perdjurner** [comment]
Removing milestone, not needed for 2.0.

**Comment by perdjurner** [comment]
Documented here:
https://guides.cfwheels.org/v2/docs/testing-your-application#section-testing-controller-variables
