### ISSUE TITLE
Add checkboxes to List of App Test Packages to let user select test packages to run

### ISSUE THREAD

**Issue by tapirus** [cfwheels/cfwheels#374]
I would like to suggest the enhancement to let the user select individually which tests to run.

There could be added selectboxes to each test package on the overview list.

To run run each test package indiviudally is a bit tedious.
To run all packages takes a long time in some apps.

What do you think?

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
