### ISSUE TITLE
Markdown Conversion: Responding with Multiple Formats

### ISSUE THREAD

**Issue by chrisdpeters** [cfwheels/cfwheels#392]
This content:
http://cfwheels.org/docs/1-3/chapter/responding-with-multiple-formats

Needs to be converted to [Markdown format](http://daringfireball.net/projects/markdown/syntax) here:
https://github.com/cfwheels/cfwheels/blob/markdown_docs/docs/03-Handling-Requests-with-Controllers/06-Responding-with-Multiple-Formats.md

**Comment by neokoenig** [comment]
On it.
