### ISSUE TITLE
Markdown Conversion: Using the Flash

### ISSUE THREAD

**Issue by chrisdpeters** [cfwheels/cfwheels#393]
This content:
http://cfwheels.org/docs/1-3/chapter/using-the-flash

Needs to be converted to [Markdown format](http://daringfireball.net/projects/markdown/syntax) here:
https://github.com/cfwheels/cfwheels/blob/markdown_docs/docs/03-Handling-Requests-with-Controllers/07-Using-the-Flash.md

**Comment by neokoenig** [comment]
On it.
