### ISSUE TITLE
Enhancement - Ability have hasChanged or changeProperties to respect "afterFind" handlers

### ISSUE THREAD

**Issue by jkeczan** [cfwheels/cfwheels#433]
Currently, we store all times in our system in UTC format. We have created an afterFind that converts all "time based columns" based on a employees custom timezone request. In the event we want to detect whether or not the time has been change by the user, the hasChanged and changedProperties are not effective since they do not respect the afterFind handlers.

Example

IN DATABASE
```
ID               name                startTime
1                 Bob                  12-02-2014 14:06:1000
```

From the form
```
ID              name                 startTime
2                Bob Barker        12-02-2014 9:06:1000
```

The Processor
```
<cfset loc.record = model("Model").findByKey(1) />
<cfset loc.modifiedColumnList = record.changedProperties()  />
```
Output for loc.modifiedColumnList is: name,startTime

Technically, the start time didn't change, it just went through the afterFind filter. I think, if we would provide an argument for the hasChanged and changedProperties functions, say "callbacks (true|false)", it would give us greater flexibility.

**Comment by perdjurner** [comment]
After you change the time in the after find callback you can now do this:
clearChangeInformation(property="startTime");

Now Wheels doesn't "know" it's been changed and won't try to save it to the database or report it as being changed etc.
