### ISSUE TITLE
Bug with usesLayout

### ISSUE THREAD

**Issue by jkeczan** [cfwheels/cfwheels#443]
The usesLayout does not appear to be respecting the "only" argument passed through.

Here is my code
```
<!--- Account.cfc  extends Base.cfc--->
<cffunction name="init" >
		<cfset super.init() />
		
		<cfset usesLayout(template="/landinglayout", only="login") />
		
	</cffunction>
```

```
<!--- Base.cfc  extends Controller--->
<cffunction name="init" >
	<cfset super.init() />
		
	<cfset usesLayout(template="/masterlayoutwithsidebar") />
</cffunction>

It seems that landing layout is used no matter what action i hit under account. Could it be beacuse the parent doesn't specify a layout?

**Comment by perdjurner** [comment]
Does the "only" argument work as expected on controllers without the super.init() calls?

**Comment by jkeczan** [comment]
Yes it does

**Comment by perdjurner** [comment]
I can't replicate this unfortunately.

Can you send me a ZIP file containing CFWheels 1.3.3 and only the code needed to reproduce this issue?

**Comment by perdjurner** [comment]
Any update on this?

**Comment by jkeczan** [comment]
I will get you an example of this as soon as I can.

**Comment by perdjurner** [comment]
Closing, please feel free to open if / when you have an update though.
