### ISSUE TITLE
Issue with plugins Ubuntu 14.04/CF11/Apache

### ISSUE THREAD

**Issue by jkeczan** [cfwheels/cfwheels#448]
From Google Group thread:
https://groups.google.com/forum/#!topic/cfwheels/nBWYk1-nCp4

I am having issues with plugins on Ubuntu 14.04. The site works as advertised on my development (OSX) but not my linux staging box. The plugins do not seem to unzip on reload. I do not have any settings that override the default behavior and the plugin zip files are named correctly.

DatePicker-1.2.zip

If I unzip manually, it finds the plugin directory but fails to load the .cfc. I am assuming this is a naming convention issue but I am not sure what is the issue.

Info:

Plugin zip: DatePicker-1.2.zip
unzip dir: datepicker
cfc inside: DatePicker.cfc

Any help would be appreciated.

I will definitely open a ticket you. I did about 5 hours worth of research on it yesterday and there are several gotchas that occur during that process. I will drop the list here and include the list on the open ticket. I was able to resolve all of them with some manual processes.

1. The plugins .cfc components much be name properly. for example DatePicker.cfc had to be either Datepicker.cfc OR datepicker.cfc. That was the only way ubuntu would find the plugins for me. I went through and did all the renaming manually for the time being on each plugin.

2. Your project folders must match up according. I had issues to were project folder was labeled 'Chimera' but the system was looking for 'chimera'. When the plugins were unpacked, there put in WEB_ROOT/chimera whereas my webroot was Chimera. This was the most frusting thing on the planet to figure out. Renaming my folder did the trick.

3. Permissions for the folder must be accurate and the user coldfusion runs under must have correct permissions established as the apache server, otherwise what ColdFusion generated with <cfzip> will not have the same permissions as apache and apache will not serve the files. I had to make sure the ColdFusion and Apache ran under the same user.

4. Finally, my testbox uses Jenkins and the JUnify controller to due the testing automatically. (Thanks Adam!). You also have to ensure that Jenkins permissions are the same as coldfusion as well otherwise when gets checkout into the web root won't be accessible by coldfusion/apache.

**Comment by perdjurner** [comment]
@chrisdpeters Do you think your recent fixes solves anything mentioned on this issue?

**Comment by chrisdpeters** [comment]
I believe the first issue is fixed with v1.4.5. The plugin CFC name must match the one reflected in the zip file name:

-  `DatePicker-0.1.zip` :arrow_right: `DatePicker.cfc`
-  `coldroute-0.3.zip` :arrow_right: `coldroute.cfc`

I don't quite understand the problem outlined the 2nd issue that you list. Did you not have the casing right in the Apache config?

Numbers 3 and 4 can't really be solved by CFWheels, I don't think. You just kind of have to know what you're doing. We could perhaps document this in the Plugins guide though.

**Comment by neokoenig** [comment]
I still think we should just rename everything to lowercase; So ignore camelcasing and force lcase() on the foldername when unzipped and on the CFC. That would probably break a load of stuff though :(

**Comment by chrisdpeters** [comment]
@neokoenig Yeah, we kept it as-is for now because what you describe would in fact be a breaking change for most plugins.

**Comment by perdjurner** [comment]
@chrisdpeters Close due to lack of response?
