### ISSUE TITLE
includeSoftDeletes with included argument do not work correctly

### ISSUE THREAD

**Issue by jonmbrose** [cfwheels/cfwheels#451]
Looking at 2 previous issues, https://code.google.com/p/cfwheels/issues/detail?id=762 and http://code.google.com/p/cfwheels/issues/detail?id=823, I believe this has yet to be corrected. From my testing, it appears that the issue is that $selectClause() is building the classes associations array and does not include the attribute includeSoftDeletes. By the time $fromClause() is executed, loc.classAssociations[loc.name].join already exists so it ignores creating the correct join with includeSoftDeletes being set.

I have added includeSoftDeletes to $selectClause() and $createSQLFieldList() and that has resolved this issue.

Now, if someone wants to pick and choose which associations to include soft deletes, that is a different story.

**Comment by perdjurner** [comment]
Can you do a pull request or just post the code that fixed it here please?

Thanks.

**Comment by jonmbrose** [comment]
Added a PR. I may have attempted a commit to the cfwheels repo, if I did, I apologize for that. Been a while since I have used Git.

**Comment by perdjurner** [comment]
It looks like you did it right and it passed all our tests too so I'll have a look at this soon.

Thank you.

**Comment by jonmbrose** [comment]
Great.

**Comment by perdjurner** [comment]
Backport to 1.3.5.

**Comment by perdjurner** [comment]
Changed my mind, the changes between 1.3 and 1.4 will be so minor that an upgrade can be done easily and therefore there is little need for backporting this.
