### ISSUE TITLE
Valid use of 'AS' in GROUPBY clauses shouldn't be removed

### ISSUE THREAD

**Issue by jduteau** [cfwheels/cfwheels#453]
We have a use case where we are doing some casts in user-defined model fields:

<cfset property(name="first_name", sql="CAST(AES_DECRYPT(EncryptedFirstName, UNHEX('#hexkey#')) AS CHAR)") />
<cfset property(name="last_name", sql="CAST(AES_DECRYPT(EncryptedLastName, UNHEX('#hexkey#')) AS CHAR)") />

When doing a findAll and asking for distinct, if either of these two fields are in the select, then the query fails because the "AS CHAR" part is removed by lines 189 in wheels/model/sql.cfm:
	loc.returnValue = REReplaceNoCase(loc.returnValue, " AS [a-z0-9-_]*", "", "all"); 

There is a workaround as MySQL has the equivalent CONVERT function:
<cfset property(name="first_name", sql="CONVERT(AES_DECRYPT(EncryptedFirstName, UNHEX('#hexkey#')), CHAR)") />
<cfset property(name="last_name", sql="CONVERT(AES_DECRYPT(EncryptedLastName, UNHEX('#hexkey#')), CHAR)") />

Perhaps the CONVERT is standard and then, instead of worrying about it in the code, we should warn about it in the documentation?

**Comment by perdjurner** [comment]
Sounds like a bug to me as Wheels shouldn't touch anything in the "sql" argument.

**Comment by jduteau** [comment]
I can understand why it is in there - if I've defined aliases on my fields, you want that there for the SELECT clause but not in the GROUP BY clause.

Here is the comment that was before that line:
      // this is a little ugly because I want to contain any possible issues to group by for 1.3.x releases 
      // for 2.0.x we should probably strip out the " AS x" part in the $createSQLFieldList function instead

**Comment by perdjurner** [comment]
Can you try the changes in my commit and reopen if it didn't fix your issue?

Thanks.
