### ISSUE TITLE
Obfuscating URLs not working when using a route with URL rewriting turned off

### ISSUE THREAD

**Issue by Maowse** [cfwheels/cfwheels#455]
When using a route in a linkTo, params are not being obfuscated if the following conditions are met:

"is a route AND NOT URLRewriting: WILL NOT OBFUSCATE
is a route AND URLRewriting: WILL OBFUSCATE
is not a route WILL OBFUSCATE"

Related Google Groups post: https://groups.google.com/forum/#!topic/cfwheels/-9WPIowh0qg

**Comment by perdjurner** [comment]
Reopening since we need to backport this to a 1.3.x release.

**Comment by perdjurner** [comment]
Backport to 1.3.5.

**Comment by perdjurner** [comment]
Changed my mind, the changes between 1.3 and 1.4 will be so minor that an upgrade can be done easily and therefore there is little need for backporting this.
