### ISSUE TITLE
Revisit coding guidelines

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#458]
/docs/creating-custom-view-helpers is a bit out of date and could do with some polishing on readme.io

**Comment by neokoenig** [comment]
I put a link to /docs/creating-custom-view-helpers but really meant the coding guidelines which has now been removed.

**Comment by perdjurner** [comment]
Still there I think (I moved it up to "Working with CFWheels").

**Comment by neokoenig** [comment]
Ah, my bad.

**Comment by perdjurner** [comment]
I made some changes to it as well I think, probably not enough to close this one quite yet though.

**Comment by perdjurner** [comment]
Ok, I think it's good now:
http://cfwheels.readme.io/v1.4/docs/contributing-to-cfwheels
