### ISSUE TITLE
Update documentation guidelines

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#459]
With a move to readme.io, /docs/documentation-guidelines will need updating to reflect this.

**Comment by perdjurner** [comment]
Let's remove that chapter instead.

Unfortunately we've never had enough people contributing for such a chapter to be needed.

At this point I'm happy with *any* contribution, even if it breaks every rule of our guideline ;)

**Comment by perdjurner** [comment]
Removed on readme.
