### ISSUE TITLE
Add parameter monthNames to dateSelect()

### ISSUE THREAD

**Issue by tapirus** [cfwheels/cfwheels#461]
Hi,
I would suggest to add the parameter
monthNames="Januar,Februar,März,April,Mai,Juni,Juli,August,September,Oktober,November,Dezember",
with a list of names of months to dateSelect() function to enable easy internationalization.
Regards

**Comment by perdjurner** [comment]
Good idea.

**Comment by perdjurner** [comment]
Done:

https://github.com/cfwheels/cfwheels/commit/a360d932c34b6e464a7729ea8ec237c560c24728
