### ISSUE TITLE
Better debugging info

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#463]
Output stuff like the following in the debug area at the bottom when running in design / development mode:
- Whether the controller action was called or if it went straight to the view file.
- If a "data function" was called for a partial and which arguments it passed through.
  Etc.

**Comment by chapmandu** [comment]
Gold!

**Comment by jkeczan** [comment]
For this what would be really great would be to allow custom parameters to appear in the debugging info. Right now, it looks like the only way to do so is by editting the wheels/events/onrequestend/debug file which will be overridden on upgrade. Maybe there is a way to do it I am unaware of, but this would be really helpful.

**Comment by neokoenig** [comment]
One idea might be to have some sort of "scope watcher" which allows you to specify either whole scopes or specific keys within the scope to debug; So in your `config/design/settings.cfm` you might have `set(showinDebug="request.myscope")`, then in the debug footer, you could do `structkeyexists` for all `showinDebug` values. Or something.
