### ISSUE TITLE
Add param excludeFields="field_a,field_b" to findOne(), findByKey() and findAll()

### ISSUE THREAD

**Issue by tapirus** [cfwheels/cfwheels#467]
Hi,
sometimes I don't wan't to return all fields of a query by the cfwheels ORM.
I could use select="" to specifiy all the fields I want, but this could be tedious.
It would be in some cases easier to define via excludeFields="" only the fields not to include.
This would be usefull for findOne(), findByKey() and findAll()

**Comment by chapmandu** [comment]
Similar to https://github.com/cfwheels/cfwheels/issues/122

**Comment by perdjurner** [comment]
Running out of time for this to be in 1.4, postponing.

**Comment by perdjurner** [comment]
I think #122 is enough of an improvement here and I feel an excludeFields parameter would make the API more complex for not enough of a return.
