### ISSUE TITLE
Add "where" to hasMany() and hasOne()

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#469]
This is so that we can customize associations better.

Blog:
hasMany("posts")
hasMany(name="archivedPosts", where="archived=1")

The specified "where" clause would now be added on to any findAll(include="archivedPosts") and blog.archivedPosts() calls.

I think the defaultScope plugin has similar functionality.

**Comment by chapmandu** [comment]
I think the SingleTableInheritance plugin does something similar also

**Comment by neokoenig** [comment]
+1, would love this.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
