### ISSUE TITLE
Possibility to allow dynamic error messages in model validations

### ISSUE THREAD

**Issue by tapirus** [cfwheels/cfwheels#470]
Hi,
I would like to see the possibility to have dynamic error messages in model validations.
This would be useful for localization.
I know it is possible with plugins like
https://github.com/ellor1138/Localizator
but I would prefer to have this bit in the core functionality.

Regards
tapirus

**Comment by perdjurner** [comment]
Can you give me an example please?

**Comment by tapirus** [comment]
I found the corresponding thread I opened a while ago.
https://groups.google.com/forum/#!topic/cfwheels/bV6gPCTJhUU

**Comment by perdjurner** [comment]
Ok, I think we can do a similar solution to what is done under "Evaluating Filter Arguments at Runtime" on http://cfwheels.org/docs/1-3/chapter/filters.

It would end up being something like this:
validatesPresenceOf(property="name", message="##application.errors.presenceOf[session.country].message##")

Where application.errors is a struct the developer sets up.

**Comment by tapirus** [comment]
Cool! Thanks Per!
