### ISSUE TITLE
Improve naming

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#472]
We need to improve naming of functions and arguments in general.

One example:

table() / tableName()

Vs.

setTableNamePrefix() / getTableNamePrefix()

Makes no sense of course.

Other inconsistencies:
- belongsTo() vs table()

Renaming table() to mapsTo() is one possible solution to that.

If we rename anything we need to keep the old functions / arguments in the code for a while (just reroute them to the new function / rename the argument).

**Comment by perdjurner** [comment]
One note related to this:

Since we don't namespace the Wheels functions we need to be careful about what we name them and how many new ones we add. It might be better to have a few important functions like belongsTo, validates etc and then move all setter / getter stuff into generic set() / get() functions (this being an example for the model code).

**Comment by jkeczan** [comment]
StoredAt or StoredIn is another possible option for table that makes sense as well. Stored At makes sense has it has the same format as your createdAt,updatedAt,deletedAt columns

**Comment by perdjurner** [comment]
@chrisdpeters Any thoughts on this issue?

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
