### ISSUE TITLE
validatesFormatOf(property="Homepage", allowBlank=true, type="URL") does not accept umlauts like äüö

### ISSUE THREAD

**Issue by tapirus** [cfwheels/cfwheels#473]
Hi the model validation function validatesFormatOf(property="Homepage", allowBlank=true, type="URL") does not accept umlauts like äüö.
Probably other special character are also not possible like ß for example.
Regards
tapirus

**Comment by neokoenig** [comment]
`validatesFormatOf` uses the inbuilt `isValid()` function of the underlying CFML engine I think. So the easiest way round would be to write your own validation function, as I don't think writing a whole bunch of custom validation functions specifically for cfwheels is a great idea (or rather, would be quite a large job).

**Comment by perdjurner** [comment]
I agree with Tom, especially since it's fairly easy to work around this ColdFusion bug (use the "regEx" argument instead).

**Comment by tapirus** [comment]
OK, I will use regEx. Thanks!
