### ISSUE TITLE
Pass param names only

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#475]
When setting "params" on linkTo(), paginationLinks() etc you should be able to pass in a list of parameter names (e.g. "sort,filter") and Wheels would fill in the values from the current params struct.

**Comment by perdjurner** [comment]
Could also params=true to just include all current params.

**Comment by chapmandu** [comment]
params=true, exclude="notThis,notThat" would also be handy.

**Comment by perdjurner** [comment]
Duplicate (#608), closing.
