### ISSUE TITLE
Document NULL / blank string

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#478]
Make sure this is documented somewhere (intro to ORM would be a good place):

"I have a very simple findAll query:
users = model("User").findAll(where="something = ''")  <-- i want to search for empty strings..
The resulting SQL ends up as:
WHERE something IS NULL
I'm not after NULLS, I want empty strings"

"I think it's always been like this and it's because there is (or wasn't at the time) no concept of null / nil in CFML.
Therefore we made the decision that the CFWheels ORM should equate an empty string in CFML with a NULL in the database."

**Comment by jkeczan** [comment]
I made a suggestion for this in the documentation to document this in the ORM intro. Wanted to try out readme.io. Seemed to work really well.

**Comment by perdjurner** [comment]
Thanks!

I simplified / changed it a little since during my testing I had no problems using where="something = ''" for example (it did not translate to NULL).

Some old info I found in case this needs to be looked into more:
https://code.google.com/p/cfwheels/issues/detail?id=609
https://code.google.com/p/cfwheels/issues/detail?id=642
