### ISSUE TITLE
ORA-00909

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#479]
https://groups.google.com/forum/#!topic/cfwheels/KJNripiL8o8

The issue is likely with line 166 in calculations.cfm (the list changes based on depending on if setPrimaryKey() is used).

**Comment by perdjurner** [comment]
I can only replicate this when setPrimaryKey() has been used to set the key to a column name that is not in the database table.

Can you do this:

1) Post your setPrimaryKey code here.
2) Do a dump of propertyNames() on the model with the problem and post the results here.

Thanks.

**Comment by perdjurner** [comment]
Running out of time to get this done for 1.4, postponing to a later release.

**Comment by mrjayviper** [comment]
I just did more testing and it seems the problem lies when I use BOTH setprimarykey and property on the same field.

e.g.
		<cfset setPrimaryKey("key_no")>

		<cfset property(name="avstartdate", column="start_dt") />
		<cfset property(name="avkeynumber", column="key_no") />
		<cfset property(name="avtopicunits", column="units") />

my findAll command would work if I don't have the property code for key_no.

**Comment by perdjurner** [comment]
Ok, can you answer my questions above too please?

Thanks.

**Comment by mrjayviper** [comment]
this is a snippet of my model file.

	<cffunction name="init">
		<cfset table("flin_avails_publish_vw")>
		<cfset setPrimaryKey("avail_key_no")>

this is the result propertynames

avyear,TOPIC_CODE,TOPIC_SUBJ,TOPIC_NUMB,TOPIC_TITLE,avtopicunits,AVAIL_DESCRIPTION,AVAIL_ENROL_QUOTA,AVAIL_ALLOWABLE_COURSES,AVAIL_SEMESTER,AVAIL_LOCATION,AVAIL_LOCATION_MATCH,AVAIL_LOCATION_DESC,AVAIL_NO,AVAIL_ATTENDANCE_MODE,AVAIL_ATTENDANCE_MODE_DESC,avenrolstartdate,avenrolenddate,avcensusdate,avwithdrawnofaildate,AVAIL_KEY_NO,avenrolquota,avtopicsubject,avtopictitle,avlocationdescription,avlocationmatch,avattendmodedescription,avenrolenddatedisplay,avtopiccode,avenrolstartdatedisplay,avattendmode,avnumber,avdescription,avcensusdatedisplay,avsemester,avallowablecourses,avwithdrawnofaildatedisplay,avlocation,avtopicnumber

**Comment by perdjurner** [comment]
You said:
"the problem lies when I use BOTH setprimarykey and property on the same field"

However, in your code here:
property(name="avkeynumber", column="key_no"
setPrimaryKey("avail_key_no")

I don't see how this is referencing the SAME field, can you explain?

**Comment by mrjayviper** [comment]
when I originally posted the code, I renamed some of the fields to make it short. But in my actual code, it's really "avail_key_no". apologies for that.

**Comment by perdjurner** [comment]
So, like this:

property(name="avkeynumber", column="avail_key_no"
setPrimaryKey("avail_key_no")

**Comment by perdjurner** [comment]
If my above assumption is correct, this is not a Wheels bug.

Here's what's happening:

When you call property(name="avkeynumber", column="avail_key_no") Wheels will map the avkeynumber property to the avail_key_no column.

At this point Wheels has no knowledge of a property named avail_key_no (since you renamed / mapped it).

So, when you call setPrimaryKey("avail_key_no") Wheels doesn't know what avail_key_no is.

What you should be doing is call setPrimaryKey("avkeynumber") since that is the property name that Wheels know.

Please let me know if that doesn't solve it and I will reopen this.

**Comment by mrjayviper** [comment]
In my code, I have setPrimaryKey before property. Not sure if that makes a difference.

**Comment by perdjurner** [comment]
I don't think the order matters, but if it does, let me know and I'll open a separate issue for that.
