### ISSUE TITLE
validatesUniquenessOf() should ignore current record when checking

### ISSUE THREAD

**Issue by randallmeeker** [cfwheels/cfwheels#480]
On the off chance that two duplicate values get inserted into a database field that has validatesUniquenessOf(). This function validate by returning only a single record. If that record happens to be the same as the one being validated, then it will validate as TRUE. 

Instead the validatesUniquenessOf() needs to use the PK to skip that record being checked when querying the database. 

Discussion found here
https://groups.google.com/forum/#!topic/cfwheels/FtLyqDj3fzw.

**Comment by perdjurner** [comment]
Fixed in https://github.com/cfwheels/cfwheels/commit/1b45e12dcb07e2ecb5381b839942d1880db752a2
