### ISSUE TITLE
Remove single quote requirement

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#484]
Instead of the developer wrapping strings with single quotes, shouldn't Wheels be able to figure this out and put them in?

Both of the below should then work:
name = "Per";
findAll(where="firstName = '#name#'");
findAll(where="firstName = #name#");

**Comment by neokoenig** [comment]
This would be nice. Also, same with dates.

**Comment by chapmandu** [comment]
Sounds nice.. lists of strings and IN could be tricky?
Eg: 
mylist = "foo,bar"
where="mycolumn IN (#mylist#)"
currently becomes:
where="mycolumn IN ('foo,bar')"
but should be:
where="mycolumn IN ('foo','bar')"

I have to use the code below to have the statement evaluated as desired..
where="mycolumn IN (#ListQualify(mylist, "'")#)"

Food for thought..

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
