### ISSUE TITLE
Bug with includeSoftDeletes

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#485]
See this:
https://groups.google.com/forum/#!topic/cfwheels/gXRCs9zPxAM

It seems that the "includeSoftDeletes" argument does not apply to included associations but it probably should, right?

**Comment by andybellenie** [comment]
Yes I agree that is a bug

**Comment by perdjurner** [comment]
:+1: (Hi Andy)

**Comment by neoplay** [comment]
Thank you @perdjurner for posting the bug!

**Comment by perdjurner** [comment]
I think this has been fixed already (but not yet released):
https://github.com/cfwheels/cfwheels/commit/746f5e1304eaf346a6de89a98688beb7220dfa31

Please give those changes a try or wait until we release 1.4 and test at that time.

If the issue remains, please reopen this ticket.
