### ISSUE TITLE
Add nested properties support for `belongsTo` associations

### ISSUE THREAD

**Issue by chrisdpeters** [cfwheels/cfwheels#491]
Currently, you can only set nested properties on `hasOne` and `hasMany` associations. If you want to have nested properties-like functionality on `belongsTo` data, you need to write callback logic manually to handle it. :(

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
