### ISSUE TITLE
validatesUniquenessOf triggers afterFind() callback

### ISSUE THREAD

**Issue by andybellenie** [cfwheels/cfwheels#492]
validatesUniqueness() calls findOne() to check the db for the unique property. However this doesn't have callbacks disabled so afterFind() get called and may behave oddly as only the id is being selected.

This is a simple check so I don't think callbacks are necessary. I think the method should probably just call exists() and not findOne().

Thoughts?

And yes, I'm back. Woo :)

**Comment by andybellenie** [comment]
Actually, exists() calls findOne() anyway so an unnecessary step. But still, callbacks don't make any sense here.

**Comment by perdjurner** [comment]
Woo :)

Yeah, callbacks makes no sense there.

Exists() also needs to have callbacks=false then I guess.

**Comment by andybellenie** [comment]
Yes I think so :+1:

**Comment by perdjurner** [comment]
Oops, didn't see that you had assigned yourself to this until just now.

Let me know if my fix was OK (I found a few other places where it's not necessary to run callbacks).

**Comment by andybellenie** [comment]
Looks good, very happy for you to do my work for me :+1: :dancer:

**Comment by perdjurner** [comment]
beersOwned++;

**Comment by chrisdpeters** [comment]
Did this make it into 1.4.2? I just tried removing my workaround using 1.4.2 and still get an error.

**Comment by chrisdpeters** [comment]
afterFind callback code:
```coldfusion
<cffunction name="$setBalanceAfterFind" access="private" returntype="struct" output="false">
	<cfset arguments.balance = arguments.amount - arguments.approvedFundingRequestsTotal - arguments.pendingFundingRequestsTotal>			
	<cfreturn arguments>
</cffunction>
```
Error when saving a new record:
```
Element AMOUNT is undefined in ARGUMENTS.
```
Snippet of workaround:
```coldfusion
<!--- TODO: Shouldn't need this if logic after upgrading to CFWheels 1.4.2 --->
<cfif
	StructKeyExists(arguments, "amount")
	and StructKeyExists(arguments, "approvedFundingRequestsTotal")
	and StructKeyExists(arguments, "pendingFundingRequestsTotal")
>
	<cfset arguments.balance = arguments.amount - arguments.approvedFundingRequestsTotal - arguments.pendingFundingRequestsTotal>			
</cfif>
```

**Comment by chrisdpeters** [comment]
Nevermind. I re-downloaded the 1.4.2 zip, and it worked this time. I wonder if Tom hadn't changed the zip file the link was pointing to on the download page, or if it was cached or something.

**Comment by neokoenig** [comment]
Oi! I changed it! :) :P

**Comment by chrisdpeters** [comment]
Ha, busted!
