### ISSUE TITLE
application.applicationName

### ISSUE THREAD

**Issue by roessera** [cfwheels/cfwheels#499]
In root/wheels/events/onSessionEnd.cfm in the function onSessionEnd(), the line:  
```
loc.lockName = "reloadLock" & application.applicationName;
```
might want to be changed to something like: 
```
loc.lockName = "reloadLock" & isDefined("application")? application.applicationName : this.name;
```
Application scope isn't always around on sessionEnd. The "this" scope is. 

We use a netscaler, which pings our server every 5min to make sure the server is up. This is how I came across this issue.

**Comment by perdjurner** [comment]
Good catch!

The arguments scope is passed in to that function so I believe the fix we'll will be to reference it like this:

arguments.applicationScope.applicationName

**Comment by perdjurner** [comment]
Fixed for next release.

**Comment by roessera** [comment]
Works, thanks.

**Comment by perdjurner** [comment]
Thanks, what's your last name btw (so I can give you credit in the change log)?
