### ISSUE TITLE
Unbelievable errors with a model called "tea"

### ISSUE THREAD

**Issue by DommoD** [cfwheels/cfwheels#501]
I have a simple application for testing with the models "tea" and "type". A "type" has many "teas" with "dependent = deleteAll" and a "tea" belongs to a "type".

If I want to delete a type, I get the following error message:
"The method deleteAllteas was not found in the type model."

But I can load the objects with the dynamic shortcut method "type.teas()".

If I rename everywhere "tea" into "teadrink", all functions works fine and as desired.

Is it possible that "tea" and/or "teas" is a reserved key word in CFWheels? I couldn't find something about that in the code or the documentation.

**Comment by DommoD** [comment]
I did again some tests. If I define in the association "dependent = removeAll" instead of "dependent = deleteAll", then all works fine. The foreignkeys are set to NULL.

I'm totally confused...!

**Comment by perdjurner** [comment]
What version of ColdFusion / Railo / Lucee and Wheels are you running?

**Comment by DommoD** [comment]
CF 11, Wheels 1.4.1 and MSSQL

**Comment by perdjurner** [comment]
If you create your own deleteAllteas method, does it find it?

**Comment by DommoD** [comment]
Also tested with Railo 4.2.1.008, Wheels 1.4.1 and MySQL...

**Comment by DommoD** [comment]
I'll try with the own method.

**Comment by perdjurner** [comment]
Also, try naming the CFC both Tea.cfc and tea.cfc please.

**Comment by DommoD** [comment]
CFWheels finds the own deleteAllteas method which I have defined in the model "Type.cfc".

**Comment by perdjurner** [comment]
Can you also try renaming type to something else (just to make sure the word "type" does not cause any problems).

**Comment by DommoD** [comment]
I renamed type/types into kind/kinds and it didn't work.

Also naming the model Tea.cfc or tea.cfc has no impact.

**Comment by perdjurner** [comment]
What's your name (so I can give you credit in the change log)?

Thanks.

**Comment by DommoD** [comment]
Thanks for solving this issue. I will test it later, but I trust in you ;-)
My name is Dominik Hofer.
