### ISSUE TITLE
Model call should be able to deal with trailing whitespace

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#503]
Model call should be able to deal with trailing whitespace

This Breaks: (note trailing whitespace) with Wheels.QueryParamValue The value for cfqueryparam cannot be determined.

    test=model("event").findAll(where="start >= '#params.start#' ");

This Works:

    test=model("event").findAll(where="start >= '#params.start#'");

**Comment by perdjurner** [comment]
Your example can be solved (in Wheels) by just trimming the entire where string.

But maybe you meant that Wheels should be able to handle white space between parameters too?

**Comment by perdjurner** [comment]
This regex should solve it:

variables.wheels.class.RESQLWhere = "\s*(#variables.wheels.class.RESQLOperators#)\s*(\('.+?'\)|\(((?:\+|-)?[0-9\.],?)+\)|'.+?'()|''|((?:\+|-)?[0-9\.]+)()|NULL)((\s*$|\)|\s*(AND|OR)))";

Would be great if you (and anyone else reading this) could try that out for a while.
It passes all tests of course but it would be good to get some "in the wild" testing done as well.
