### ISSUE TITLE
Umlaut in addRoute pattern argument does not work

### ISSUE THREAD

**Issue by tapirus** [cfwheels/cfwheels#506]
Hi, the Umlaut, in this case "ü" in the pattern argument leads to an error
Wheels.ViewNotFound

Could not find the view page for the index action in the BerUns controller.

addRoute(name="about", pattern="/über-uns", controller="users", action="about");

Regards
Thorsten

**Comment by perdjurner** [comment]
Add this to the top of the config/routes.cfm file:
<cfprocessingdirective pageEncoding="utf-8">

**Comment by perdjurner** [comment]
Leaving this open with some notes in case we need to fix in the Wheels code, or document etc.

Setting the file to UTF-8 with BOM also fixes the issue. We could possible re-save all files like that. This still leaves it up to the developer to create any new files the correct way so it might be better to just document this requirement instead.

**Comment by perdjurner** [comment]
More useful info here:
https://forums.adobe.com/thread/930550

**Comment by perdjurner** [comment]
Let's document this, ideally in a new chapter called Localisation where we can also mention other things like how you change Jan, Feb etc to your language.

**Comment by neokoenig** [comment]
Closing, as now started Localisation Chapter: https://guides.cfwheels.org/v2.0/docs/localisation
