### ISSUE TITLE
Null properties cause create/update to fail

### ISSUE THREAD

**Issue by andybellenie** [cfwheels/cfwheels#507]
It is possible to have a null value in CF (e.g. returned from a JSON object). Passing in a properties struct with null keys will cause an error:

    <cfset test = {title = javaCast("null", 0)}>
    <cfset model("payment").new(properties=test)>

**Comment by perdjurner** [comment]
Do you get this error?

"Element TITLE is undefined in a CFML structure referenced as part of an expression"

**Comment by perdjurner** [comment]
The following fixes (well, it skips setting the property) for me on CF 8:

Wrap line 400 in properties.cfm with:

if (StructKeyExists(arguments.properties, loc.key))
{
  loc.rv[loc.key] = arguments.properties[loc.key];
}

**Comment by andybellenie** [comment]
No I get: 
"the value from key [TITLE] is NULL, which is the same as not existing in CFML"

This is a Railo error

**Comment by andybellenie** [comment]
I think we should wrap the whole block inside the loop, there's no need to take any action when the key is null

**Comment by perdjurner** [comment]
I agree.

**Comment by perdjurner** [comment]
Done.
