### ISSUE TITLE
Increase Travis-CL lucee version number

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#513]
This is more of a question as to best practice and whether we should actually do it - 

Current Travis Lucee version is `4.5.0.042` (the first stable release).

Should we be following the current stable version? i.e, increment to `4.5.1.022` ? Is this generally the practice? Or is there a way to add more than one lucee version to the test suite? i.e, use current stable + development release? Might help flag up issues in advance maybe.

**Comment by perdjurner** [comment]
We can add more than one Lucee version, I have no idea how that's done though.

We should only have the version(s) that we officially support running. No need to run a development release for example. We could do that of course but I don't think that it should be part of the automated testing process in that case.

**Comment by perdjurner** [comment]
I can't make sense of their release process.

They say they released a version containing an important security patch so ideally we should support that as the minimum version number.

However, their main page still lists 4.5.1.000.

We of course want to avoid a situation where someone downloads Lucee from their site (4.5.1.000 likely then) and then can't get Wheels to run on it.

**Comment by neokoenig** [comment]
Yeah there's currently a conv on slack about this. It's either that their downloads page needs to be updated, or there's the assumption that the user will run the updater from within lucee admin (which will patch it to 022).

I think we should set 022 as the minimum version, as it does contain a security patch, and it's the latest patch on the stable release provider. That would at least encourage those behind 022 to patch/upgrade.

There's a good discussion on their release pattern here - http://lang.lucee.org/t/semver-and-dev-preview-stable-a-proposal/176

**Comment by perdjurner** [comment]
I agree.

Hopefully they'll decide to change their download page too. It would make more sense to me to just make the download 4.5.1.022 rather than relying on users to run the updater.

**Comment by andybellenie** [comment]
We should encourage use of the latest stable version, it's up to them to
sort out their download page.

**Comment by perdjurner** [comment]
I've set the minimum Lucee version to 4.5.1.022.

Tom, can you look into setting that as the version we test against on Travis?

How do you guys think we should handle Railo?

We currently support 3.1.2 and up.
Their latest release is 4.2.1.008.
Keep in mind that Railo is essentially dead and there won't be any more releases.

**Comment by neokoenig** [comment]
I'd probably leave Railo as is for now, after all, there are still a lot of people using it (myself included) even with the security issue recently.

Re: Lucee version on Travis, presumably it's just a matter of updating `<luceeVersion>4.5.0.042</luceeVersion>` in `pom.xml` ? Assuming the correct version number .jar exists..

**Comment by neokoenig** [comment]
Just checked, `https://bitbucket.org/lucee/lucee/downloads/lucee-4.5.1.022.war` exists, so I *think* that's all that's required??

**Comment by perdjurner** [comment]
Done, let's see what happens...

**Comment by perdjurner** [comment]
There are some weird bugs in older versions of Railo that it would be nice to not have account for though. Wonder if we can at least require having a more recent version of Railo?

**Comment by neokoenig** [comment]
Agreed, there are a few work arounds in the core specifically about railo 3.x bugs - (not so much 4.x), so I'd push it to at least 4.x, if not 4.2.x ...

**Comment by perdjurner** [comment]
It looks like we only test against one version of Railo through Travis, right?
For some reason I thought we were still testing against 3.1.2 as well.

**Comment by neokoenig** [comment]
Yep, looks like 4.2.1.x was set as the min version by Singghih on Jul 16, 2014..!

**Comment by perdjurner** [comment]
Ok, we might as well set that as the minimum version for Wheels too then, since we don't test against older ones anyway.

**Comment by perdjurner** [comment]
All done now then.

For reference, here are the current required minimum version numbers:

Railo 4.2.1.008
Lucee 4.5.1.022
ACF 8.0.1.195765 (with a special requirement to have 10.0.4+ if running the 10 release).
