### ISSUE TITLE
Automatically set property label for association columns

### ISSUE THREAD

**Issue by andybellenie** [cfwheels/cfwheels#514]
Current model init() required to configure associations and property labels, assuming conventions:

```
<cffunction name="init">
    <cfset belongsTo(name="Post")>
    <cfset property(name="postId", label="Post")>
</cffunction>
```

This second line is unnecessary. We can safely assume that the property label for an belongsTo or hasOne association is the same as the association name.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
