### ISSUE TITLE
Add #labelFor()# helper

### ISSUE THREAD

**Issue by andybellenie** [cfwheels/cfwheels#515]
e.g.

```
#labelFor(objectName="comment", property="postId")#
```

**Comment by perdjurner** [comment]
What's the use case? Is it because of limitations when using textField()
for example?

**Comment by andybellenie** [comment]
Yes that's one example. Another is when outputting property values in a view. Why type out the label again when it's already defined elsewhere? Could be useful in localization too.

    Post Title: #post.title#

...becomes:

    #labelFor(objectName="post", property="title")#: #post.title# 

Could also add a class option for wrapping.

**Comment by perdjurner** [comment]
So, you're not talking about the label HTML element?

**Comment by andybellenie** [comment]
Yes, actually. perhaps #labelTag()# would make more sense. Is it ok HTML to use a <label> element in the example above, do you think?

**Comment by perdjurner** [comment]
To use a label HTML element you mean?
Only if it's in a form, related to an input.

I do think adding a helper for outputting just the label text makes sense.
Just worried it's so easily confused with labels on forms.

How about this:

#label(objectName="post", property="title")#
<label for="post-title">Post Title</label>

#label(objectName="post", property="title", wrapperElement=false)#
Post Title

Not sure if that makes it any better, thoughts?

**Comment by andybellenie** [comment]
I think labelFor() is clearer, less obviously a label tag, similar to errorMessageFor()

Yes to the wrapper element.

**Comment by perdjurner** [comment]
Just posting another suggestion:

#label(objectName="post", property="title")#
&lt;label for="post-title"&gt;Post Title&lt;/label&gt;

#labelText(objectName="post", property="title")#
Post Title

(or perhaps labelTextFor)

label() would call labelText() internally.
In the code we can likely replace $createLabel() with label().

**Comment by kmd1970** [comment]
Should we not use this function .$label?

```javascript
object = model('object').new();
idLabel = object.$label('id');
```

I've also written my own label function.

```javascript
public string function propertyLabel(required obj, required prop){
		if ( obj.hasProperty(prop) ){
		  return obj.columnDataForProperty(prop).label;
		} else {
		  return 'No Label';
		}
    }  
```

**Comment by brandner** [comment]
I like the idea of this enhancement. Using .$label for now.
label() and labelText() seem like a good solution.

**Comment by chrisdpeters** [comment]
My opinion...

`#label(objectName="user", property="lastName")#` should be for outputting the HTML `<label>`. I think sometimes you do need that flexibility outside of the other form helpers.

`#user.labelFor("lastName")#` could be for outputting just the data (label text) for the scenario that [Andy outlines](https://github.com/cfwheels/cfwheels/issues/515#issuecomment-119228545), except it just outputs the label text, not the value of the property. That would require something like this:

```coldfusion
<cfoutput>
#HtmlEditFormat(user.labelFor("lastName"))#:
#HtmlEditFormat(user.lastName)#
</cfoutput>
```

Thoughts?

P. S. I really miss the `h` helper, so I usually just add it back to my apps in `Controller.cfc`.

**Comment by brandner** [comment]
Agreed with @chrisdpeters most recent suggestion. Seems consistent.

**Comment by neokoenig** [comment]
Seems a relatively easy thing to pull out for a 2.x release

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
