### ISSUE TITLE
Remove depth limit when using include=xx for findBykey()

### ISSUE THREAD

**Issue by andybellenie** [cfwheels/cfwheels#516]
How about we remove this artificial limit on findByKey()? I wonder if it's a huge technical issue under the hood. If a developer wants to create a massive object, let them. The advantage is only having to hit the db once to produce a lot of data.

Thoughts?

**Comment by perdjurner** [comment]
I think there is a technical problem actually. It's been so long since we
put the limit in place though so I can't remember what it is.

Maybe try it out and see what happens? Or did you try already perhaps?

**Comment by perdjurner** [comment]
When removing that limit the $serializeQueryToStructs function fails.

It would have to be rewritten to loop through the include argument properly (right now it just assumes it's a simple comma delimited string and that all associations are on the current model).

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
