### ISSUE TITLE
validatesPresenceOf is not automatically set for primary keys

### ISSUE THREAD

**Issue by andybellenie** [cfwheels/cfwheels#517]
This is fine when using an identity specification for an integer key (convention) but if it is a string key then existence should be automatically checked before saving.

**Comment by perdjurner** [comment]
Does cfdbinfo return that info (if it's an identity column)?

**Comment by andybellenie** [comment]
Yes there is an is_autoincrement key

**Comment by perdjurner** [comment]
Can't find any documentation on that.
Hope it works across engines / databases.

**Comment by andybellenie** [comment]
Done a little more testing and it looks more complicated than that. The is_autoincrement key is for mysql. For mssql there is a type_name column which has identity in it. I don't have test beds for other dbs setup.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
