### ISSUE TITLE
Add param query.name to wheels orm queries (findAll() etc.)

### ISSUE THREAD

**Issue by tapirus** [cfwheels/cfwheels#518]
Hi,
I would like to see the param query.name to wheels orm queries (findAll() etc.).
I would help to match queries in the coldfusion/railo/lucee debugging with the corresponding code in wheels.
I guess in the coldfusion logs it would also appear.
Which functions are targeted? Maybe findAll(), findOne(), findByKey(), dynamic finders?
What should be the name of the param? Maybe query.name, queryName, name?
Thorsten

**Comment by chapmandu** [comment]
+1

**Comment by andybellenie** [comment]
I like this. Would be great to default to something useful for debug, e.g.

post.findall
post.findone
blog.update

etc.

**Comment by perdjurner** [comment]
Done.

Pass in handle="something" and CFWheels will use that as the variable name for the query.

It also defaults to useful stuff like UserFindAllQuery for example.
