### ISSUE TITLE
Allow controllers and views to be located in subdirectories 

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#526]
This would be a very handy enhancement for project organisation. Coldroute does subdirectories (namespaces) but seems overkill for just this feature and doesn't seem to be actively maintained. Unless coldroute functionality is brought into core.

Thoughts?

**Comment by tapirus** [comment]
Definetly yes. There should be a few years old request for this feature.

**Comment by chrisdpeters** [comment]
The ColdRoute plugin allows for this with scopes and namespaces. You probably already knew that though.

**Comment by chapmandu** [comment]
Yes, though I think it is overkill if one only wants to use namespaces to organise large codebase. I am concerned about ColdRoute's compatibility with future versions of wheels.

**Comment by perdjurner** [comment]
With the plan to integrate ColdRoute we can close this issue, right @chapmandu?

**Comment by chrisdpeters** [comment]
See #609. :tada:
