### ISSUE TITLE
Unable to use a LIKE operator (with single quotes and %) on integer columns in FindAll(where=)

### ISSUE THREAD

**Issue by kmd1970** [cfwheels/cfwheels#527]
version 1.4.1

Issue: Single quotes passed in around search values are being automatically removed when the column datatype is integer. (varchar is untouched) 

The "Employees" table : 
```sql
CREATE TABLE [dbo].[Employees](
	[EMPLOYEE_ID] [int] NOT NULL,
	[LAST_NAME] [varchar](100) NULL )
```

**1.** With ```parameterize = false``` 
```php
thesql = "employee_id LIKE '%0'";
employees = model("Employee").findAll(parameterize = false , where = thesql );
```
I get this error: 

**[Macromedia][SQLServer JDBC Driver][SQLServer]Incorrect syntax near '0**

and this SQL:

```sql
SELECT employee.EMPLOYEE_ID,
              employee.EMPLOYEE_NUMBER 
FROM employee WHERE employee.EMPLOYEE_ID LIKE %0 
```

**2.** With ```parameterize = true```
```php
thesql = "employee_id LIKE '%0'";
employees = model("Employee").findAll(where = thesql );
```
 I get this error: 

**Invalid data %0 for CFSQLTYPE CF_SQL_INTEGER**

Surprisingly using two single quotes on either side of the search value with an integer column works:

```php
 thesql = "employee_id LIKE ''%0''";
 employees = model("Employee").findAll(parameterize = false , where = thesql );
```
```sql
SELECT employee.EMPLOYEE_ID,
              employee.EMPLOYEE_NUMBER 
FROM employee WHERE employee.EMPLOYEE_ID LIKE '%0'
```

**I need to be able to use the LIKE operator (and %) on any column to do a global search.**

Am I doing this wrong? Any advise/help would be appreciated.

**Comment by perdjurner** [comment]
I think the right way to do this would be to convert your column to a varchar using a calculated property and then do the LIKE on that.

Docs:
http://docs.cfwheels.org/docs/calculated-properties

Please feel free to reopen this if you disagree though :)

If you need help with the code for a calculated property please ask on the Google group.

**Comment by kmd1970** [comment]
Thanks for the reply. I had more conversions to do so I used a View instead.
