### ISSUE TITLE
Cascade Properties Call

### ISSUE THREAD

**Issue by normancesar** [cfwheels/cfwheels#529]
I have a suggestion that it might be nice to be able to cascade the properties call to wheels models that are properties of a wheels model.  

This would give it similar behaviour to when you call a find method with returnAs set to "structs".

I would suggest that the ability to cascade the call would be switched on via an argument passed to properties() with the default not cascading so as to not affect existing code that uses the function.

I have written the code to do it already as I am debugging lots of models that contain other models and it is nice to just see all the properties without everything else.

**Comment by chapmandu** [comment]
Sounds great.. You mean something like this? ;)

https://github.com/chapmandu/simpleproperties-cfwheels-plugin

**Comment by normancesar** [comment]
Yeah something like that :)

Although it could do with checking the property that is an object has the function simpleProperties... Belt & braces :)

**Comment by perdjurner** [comment]
@chapmandu This was integrated into core, right?

**Comment by chapmandu** [comment]
This is now the default for model properties.
