### ISSUE TITLE
Where clause modified with "AND" is not in uppercase

### ISSUE THREAD

**Issue by andrew-dixon** [cfwheels/cfwheels#530]
If you use "and" instead of "AND" in a findAll it changes the resulting query where clause instead of  erroring.

This:

```
model("page").findAll(where = "parent_id = 1996 AND active = 1", order = "title");
```

works correctly and adds

```
parent_id = 1996 AND active = 1
```

to the SQL query, however when it is:

```
model("page").findAll(where = "parent_id = 1996 and active = 1", order = "title");
```

it adds

`parent_id = 1`

to the query instead.

It should not modify the where clause it should error out telling you that the operators, like AND, need to be in uppercase.

**Comment by perdjurner** [comment]
I think this is sort of a catch 22 situation at the moment.

We do not support "and" because our reg ex can't detect it.
So unfortunately we can't detect "and" for the purpose of giving an error message either.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
