### ISSUE TITLE
Can't use == operator in conditions argument

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#531]
This failed on CF 8 (need to investigate why):
validatesPresenceOf(property="x", message="x", condition="x == 1");

This works:
validatesPresenceOf(property="x", message="x", condition="x IS 1");

**Comment by neokoenig** [comment]
That operator can only be used within cfscript in cf8.. Might be why?

**Comment by perdjurner** [comment]
Looks like a CF 8 bug.

This works fine:
<cfscript>
x = 1;
str = "x is 1";
res = Evaluate(str);
WriteOutput(res);
</cfscript>

But changing x IS 1 to x == 1 causes an "Invalid CFML construct" error.
