### ISSUE TITLE
Test.cfc should not be required

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#532]
To get the test suite running you currently need to place a file named Test.cfc in the tests folder.

This should not be required, or if there's a reason that it's required we need to document it and possibly include that file in the Wheels release ZIP.

**Comment by neokoenig** [comment]
This is probably required now, as the newer test suite has additional functions which you can add: i.e

```
component extends="wheels.Test" output=false {

	/*
	 * Executes once before the test suite runs.
	 * Populates the test database on reload or if there are no tables in the database.
	 */
	function beforeAll() {
	}

	/*
	 * Executes before every test case if called from the package via super.superSetup().
	 */
	function setup() {

	}

	/*
	 * Executes after every test case if called from the package via super.superTeardown().
	 */
	function teardown() {

	}

	/*
	 * Executes once after the test suite runs.
	 */
	function afterAll() {

	}

}
```

I think we should add it

**Comment by perdjurner** [comment]
If it's not technically required, do you think we should add it anyway (as opposed to just documenting how to use it)?

**Comment by neokoenig** [comment]
I figure since we're setting up the test folders anyway, then yes, but I'm probably easily persuaded

**Comment by perdjurner** [comment]
Good point, makes sense to me.

**Comment by chrisdpeters** [comment]
You'll probably want to add a note to each of those comments stating that child test CFCs that extend and override them will probably want to call `super`.

So in the child component:

```coldfusion
component extends="Test" {
  function setup() {
    super.setup();
    // Then the rest of the logic
  }

  function test_the_thing() {
  }
}
```

I don't think that's something that RocketUnit "takes care of for you," is it?

**Comment by perdjurner** [comment]
I'm going to commit a complete sample setup, then we can scale down from there if we think it's too verbose.

**Comment by perdjurner** [comment]
Any thoughts on what's here now?
https://github.com/cfwheels/cfwheels/tree/master/tests

**Comment by neokoenig** [comment]
I like it. Certainly makes it clear, and means you don't need to do much to get up and running quickly.

**Comment by perdjurner** [comment]
We may want to have all the functions commented out perhaps?

**Comment by chapmandu** [comment]
I think you can scrap tests/wheels.cfc. Then make tests/test.cfc extend wheels.test.

If you want to keep the initial boilerplate even leaner, you can ditch tests/test.cfc and just make your packages extend wheels.test. It just means you can't use the new tests events (beforeAll etc) without getting test.cfc and  reworking the extends attributes of your packages.

**Comment by chapmandu** [comment]
I'd lean towards the first option.

**Comment by perdjurner** [comment]
> I think you can scrap tests/wheels.cfc. Then make tests/test.cfc extend wheels.test.

It's the way it is now so it's consistent with how the controllers and model folders look (they avoid the use of the "wheels" mapping).

> If you want to keep the initial boilerplate even leaner, you can ditch tests/test.cfc and just make your packages extend wheels.test. It just means you can't use the new tests events (beforeAll etc) without getting test.cfc and reworking the extends attributes of your packages.

Right, that was sort of the point I think, to add the code for the developer so they see how it works without having to read / copy code from the docs. Keeping it lean isn't the goal here I mean, if that were the case we could just delete everything and have the developer set it up the way they want by reading the docs.

**Comment by chapmandu** [comment]
Fair enough, I still think the tests/wheels.cfc is bloat and should be removed in favour of extending wheels.test in the tests/test.cfc 

Why the aversion to using the wheels.test mapping?

**Comment by perdjurner** [comment]
> Why the aversion to using the wheels.test mapping?

I think at some point in the past it was necessary for Wheels to run without any mappings set up. This is why controllers and models extend Wheels.cfc in the same folder which in turn includes the files with the functions.

I'm not against changing it but then I would prefer that we change it in all areas (controllers, models, tests etc) at once.

So, just a consistency thing for now :)

**Comment by perdjurner** [comment]
Although, since we're doing a major / breaking release now would be a good time to get rid of all those bloat `Wheels.cfc` files and rely on the mapping instead.

For controllers it would just mean that the parent `Controller.cfc` would extend `wheels.Controller` instead of `Wheels` (and same change for models).

I'll think about it...

**Comment by chrisdpeters** [comment]
Looks great! Of course, consistency is key, which was another reason why a boilerplate `Test.cfc` was a great idea (to keep it consistent with the `controllers` and `models` folders.

I think it would be nice to get rid of those extra `Wheels.cfc` files myself.

**Comment by perdjurner** [comment]
Done.
