### ISSUE TITLE
Don't show parent folders as test packages

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#533]
When viewing tests it is showing folders up the tree as test packages:

Example:

App lives in inetpub/wwwroot/subfoldder

It is now showing "subfolder" as a test package.

**Comment by perdjurner** [comment]
https://github.com/cfwheels/cfwheels/commit/be2bffd0439c12181d1f231384ed1f25c11cb4cc

**Comment by chapmandu** [comment]
Did this make it into the 1.4.2 release?

**Comment by perdjurner** [comment]
No, everything related to the test suite is planned for 2.0.
