### ISSUE TITLE
Naming for $getRedirect

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#534]
That should not have the $ sign since it's the function is part of the Wheels API.

**Comment by perdjurner** [comment]
Same with $processAction.

**Comment by perdjurner** [comment]
As an alternative, create a public function specifically for testing that wraps these private ones:

For example...

Old way:

var loc = {};
loc.params = {controller="store", action="search"};
loc.controller = controller(name="Store", params=loc.params);
loc.controller.$processAction();
redirect = loc.controller.$getRedirect();

New way:
result = testControllerAction(controller="store", action="search", params=x)

result should now contain a struct with "response" (HTML) and redirect (details for the redirect call).

**Comment by perdjurner** [comment]
The result struct could also contain anything in the flash for easy testing of that as well.

**Comment by chapmandu** [comment]
I do like testControllerAction()

**Comment by perdjurner** [comment]
Done (or in the works in other open issues).
