### ISSUE TITLE
Mock post requests in tests

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#536]
If you know the internals of the Wheels framework you can just do request.cgi.request_method = "post" before running the test and then setting it back afterwards but we need a better way to do this.

**Comment by jkeczan** [comment]
Just a thought on this one. When we split out our tests we put all tests that require "post" in one file. Then we use setup and teardown to set/unset the post. It seems to work for us.

We also created helper functions, makePost() and resetRequest() to assist with this.

**Comment by perdjurner** [comment]
This is now possible in the new `processRequest(method="post")` function.
