### ISSUE TITLE
Document test framework

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#537]
Important:

- Document with real world examples (as opposed to explaining how to test stuff that Wheels should just do for you anyway).

- Make a category for test related functions (controller, processAction and getRedirect are specifically for testing and we need to make this very clear).

Some existing info to use:
https://code.google.com/p/cfwheels/wiki/TestingFramework
http://blog.sidic.net/2014/06/how-to-test-cfwheels-app-step-by-step.html

**Comment by chapmandu** [comment]
https://github.com/cfwheels/cfwheels/issues/133

**Comment by chapmandu** [comment]
http://docs.cfwheels.org/v2.0/docs/testing-your-application

**Comment by neokoenig** [comment]
Small note:
`http://docs.cfwheels.org/v2.0/docs/testing-your-application`

"In order to run tests against your application, you must first create a tests directory off the root of your CFWheels application" - not true in `2.x`? as in, those directories are created for you.
