### ISSUE TITLE
Add argument for cf_sql_type to calculated properties

### ISSUE THREAD

**Issue by andybellenie** [cfwheels/cfwheels#538]
Add following property to a model, referencing a mysql timestamp column:

<cfset property(name="datestamp", sql="DATE(payments.timestamp)")>

The run following finder:

<cfset test = model("foo").findAll(where="datestamp='#Now()#'")>

Returns nothing as it is performing a string comparison. You have to format the date as a string to get it to work, i.e.

<cfset test = model("foo").findAll(where="datestamp='#DateFormat(Now(), "yyyy-mm-dd")#'")>

It would be good to be able to define the sql type as part of the property method, then the db should be able to do type based comparisons.

**Comment by perdjurner** [comment]
You mean like this:
https://github.com/cfwheels/cfwheels/commit/1b8ba33f56e9b3b2ecfeb16de1eee7f48a2eadaa

Use "dataType" argument on the property() call to test it.

**Comment by andybellenie** [comment]
Nice :)
