### ISSUE TITLE
Merge ObjectRollback plugin into core

### ISSUE THREAD

**Issue by chrisdpeters** [cfwheels/cfwheels#539]
The plugin rolls back primary keys on nested properties when the validation or callback chain fails. Otherwise, you end up with a form with errors that references primary keys that don't exist because they were rolled back in the database transaction.

Will work on tests that expose this bug in a new branch.

https://github.com/liquifusion/cfwheels-object-rollback/blob/master/ObjectRollback.cfc

**Comment by chrisdpeters** [comment]
Was trying to get Lucee 4.5.1.022 running in Docker but am blocked by chapmandu/lucee-docker#2. Guess I can just hack my local copy of CFWheels to allow patch 000 for now until I can get that resolved. Sorry for the holdup.

**Comment by chrisdpeters** [comment]
@perdjurner I have committed failing tests to the [issue_539 branch](https://github.com/cfwheels/cfwheels/tree/issue_539).

One thing I also uncovered is that parent records' primary keys aren't being blanked out/rolled back in this situation either. Do you think that should be fixed? Or do you think this is only isolated to nested properties?

**Comment by perdjurner** [comment]
It should probably be rolled back if it was set on the database side with an auto increment value but not when set before the save by the developer.

That rule should apply to both parent and nested child objects.

Makes sense?

**Comment by chrisdpeters** [comment]
Makes sense to me. There are failing tests for that in the issue_539 branch too.

**Comment by perdjurner** [comment]
Trying to understand the "test_parent_primary_key_rolled_back_on_parent_validation_error".

Why does that test against an already existing object (loc.author.findOneByLastName(value="Peters", include="profile"))?

Should we not be testing against newly created objects instead (loc.author.new())?

There's never a reason to roll back the primary key for an object that's already in the database, right?

Anyway, I have committed some code for what I understand about this so far (commented out ´though so you can keep writing failing tests).

https://github.com/cfwheels/cfwheels/commit/28e9ac54fb58aacdb9c4e71d5eff9f7b03e912e6

**Comment by chrisdpeters** [comment]
I probably didn't take close enough of a look at the setup method. I'll look into it this morning.

**Comment by chrisdpeters** [comment]
OK, I believe I've corrected the test data to have the parent model objects as new objects. Their primary keys should be rolled back on validation errors.

@perdjurner Let me know if this looks better.

**Comment by perdjurner** [comment]
There's only 4 test failures now though, you had 7 before I think.

Was that intentional?

**Comment by chrisdpeters** [comment]
I added more than 4 tests, but only 4 of them are failing. I believe if we can get those 4 to pass, we should be all good.

**Comment by perdjurner** [comment]
I fixed the has_many tests by merging in the code from the plugin.

Not sure why the has_one tests fail though, can you see any reason why @chrisdpeters?

**Comment by chrisdpeters** [comment]
The tests were setup incorrectly. (Sorry!) The fixes have been committed.

I would like to revisit this later and add some tests for create vs. update. Most of the tests I've written cover creates only.

Can you give it a shot now? If the tests pass, I say let's close this issue.

**Comment by perdjurner** [comment]
@chrisdpeters Can you just add something to the change log that sums up what we've fixed please?

Thanks.

**Comment by chrisdpeters** [comment]
I'm not seeing 1.4.2 in the CHANGELOG for master. Should I add it to the 1.4 branch?

**Comment by perdjurner** [comment]
Add it to both.

**Comment by perdjurner** [comment]
Sorry, my bad, put it in the 1.4 branch then.

**Comment by perdjurner** [comment]
Never mind, I've back-ported our fixes and added some info about it in the correct place now.

**Comment by chrisdpeters** [comment]
Thanks. Hadn't had a chance to get to that yet, so I'm glad you went ahead and took care of it.

**Comment by liferealized** [comment]
I'd assume ObjectRollback will soon be obsolete? Is this tagged for a specific release after 1.4.5?
