### ISSUE TITLE
cfwheels application JRun 500 error on first load

### ISSUE THREAD

**Issue by joelisfunk** [cfwheels/cfwheels#54]
When my cfwheels application first loads it hangs for two minutes or so and then returns a 500 JRun server error. (coldfusion.runtime.RequestTimedOutException: The request has exceeded the allowable time limit Tag: cfoutput) 

When reloading the page again it works normally. I'm only experiencing this issue which cfwheels applications on my server.

**Comment by leeish** [comment]
Encountered this problem today running 1.4.4. The app has reloaded tons of times before on both dev server and prod server, now I can't get it to reload on prod, but dev is still fine. Running CF10/Win Server 2008/IIS7.5.

**Comment by perdjurner** [comment]
Most likely a hung thread, kill that and reloading should work fine afterwards.

Unless you are saying that you can't even reload directly after a CF service restart with no other traffic hitting the server?

**Comment by leeish** [comment]
I think you must have been correct. I took off and went home and when I got there I was able to reload. CF must have killed the thread after it passed it's timeout period. I'm making a page to output running threads so if it happens again I can see if it is indeed a thread stopping it from reloading.
