### ISSUE TITLE
partialView() data function weird behaviour

### ISSUE THREAD

**Issue by Tyf0x** [cfwheels/cfwheels#540]
I had to port old code from CF8 to CF11 and upgrade cfwheels from 1.0.X to 1.4.1 and obviously had to fix a few issues of compatibility, nothing special.

However a part of the code just stopped working and I narrowed it down to a includePartial() call.

This includePartial() automatically calls a data function that returns a struct containing a few text fields and a query result. But when the data was sent to the partial view, the query was missing: actually, some of it's fields were merged in the data structure.

Here is the partial view data function:

``` Coldfusion
<cffunction name="partialView" returntype="struct" access="private">
    <cfset var data = {} />     
    <cfset var testqry = QueryNew("id, other")/>
    <cfset QueryAddRow(testqry)/>
    <cfset QuerySetCell(testqry, "id", 1)/>
    <cfset QuerySetCell(testqry, "other", "test1")/>
    <cfset QueryAddRow(testqry)/>
    <cfset QuerySetCell(testqry, "id", 2)/>
    <cfset QuerySetCell(testqry, "other", "test2")/>
    <cfset data.query = testqry />
    <cfset data.title = "Partial View Title" />
    <cfset data.desc = "blah blah blah" />
    <cfreturn data />
</cffunction>
```

and the partial view just dumps the "arguments" variable:

``` Coldfusion
<cfoutput>
<h2 class="tit">#arguments.title#</h2> 
<p>#arguments.desc#</p>
<cfdump var="#arguments#"/><cfabort/>
</cfoutput>
```

Here is the result of the dump:

![shot 2015-08-12](https://cloud.githubusercontent.com/assets/6980921/9214656/cef728e2-40e3-11e5-83fe-f2a032d67730.png)

I would have expected to see the query, but instead find one of the rows merged into the structure.

If I modify the controller code as follow:

``` Coldfusion
<cffunction name="partialView" returntype="struct" access="private">
    <cfset var data = {} />     
    <cfset var testqry = QueryNew("id, other")/>
    <cfset QueryAddRow(testqry)/>
    <cfset QuerySetCell(testqry, "id", 1)/>
    <cfset QuerySetCell(testqry, "other", "test1")/>
    <cfset QueryAddRow(testqry)/>
    <cfset QuerySetCell(testqry, "id", 2)/>
    <cfset QuerySetCell(testqry, "other", "test2")/>
    <!--- <cfset data.query = testqry /> --->
    <cfset data.otherRandomName = testqry />
    <cfset data.title = "Partial View Title" />
    <cfset data.desc = "blah blah blah" />
    <cfreturn data />
</cffunction>
```

I get:

![shot 2015-08-12 1](https://cloud.githubusercontent.com/assets/6980921/9214697/3ffec220-40e4-11e5-9f45-87989a7e22fe.png)

Did I miss something or is it indeed a bug?

**Comment by neokoenig** [comment]
The reason looks to be Line 210
``` arguments.query = arguments.$partial; ```
https://github.com/cfwheels/cfwheels/blob/1008cc642fb0e5da6d0d5b392714fd143c866371/wheels/controller/rendering.cfm

i.e, your arguments.query is being overwritten?
?

**Comment by perdjurner** [comment]
Can you post your includePartial call as well please?

Thanks.

**Comment by Tyf0x** [comment]
I unfortunately deleted the sample project made to demonstrate the issue, but my includePartial was simply called in the "view/controller/test.cfm" view:

```Coldfusion
[...]
<cfoutput>
<div class="container">
	<div class="left">
		#includePartial("partialview")#
	</div>
</div>
</cfoutput>
[...]
```

with a route like

```Coldfusion
<cfset addRoute(name="home", pattern="", controller="controller", action="test")>
```

**Comment by perdjurner** [comment]
Can you check if it has to do with naming the variable "query".

What if you name it "query2" instead for ezample, same problem?

**Comment by Tyf0x** [comment]
Yes, I can confirm that the issue is only occurring when the variable is named "query". Changing the name to anything else (like "query2") works as intended.

**Comment by perdjurner** [comment]
I don't think this is a bug but we do need to document it better.

The "query", "object" and "objects" arguments are special arguments and should not be used for other purposes than what's documented here:

http://docs.cfwheels.org/docs/partials

- Using Partials with an Object
- Using Partials with a Query
- Using Partials with an Array of Objects

**Comment by perdjurner** [comment]
Documented here:
https://guides.cfwheels.org/v2/docs/partials#section-passing-in-data
