### ISSUE TITLE
Plugin directory Exception during first application load

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#541]
Exception:
directory [/var/lib/tomcat8/webapps/root/plugins/simpleproperties] already exist

File:
wheels/Plugins.cfc:90
wheels/Plugins.cfc:24
root.cfm:5

Environment:
Wheels 1.4.1, Linux, environment="production"

I can see there is a DirectoryExists() check so this error shouldn't happen.. but alas!

My guess is that the inital load failed, and this exception is happening on the next request.

I would usually ignore this error and just 'reload=true' except this exception has occurred several times on the instance health check script during an application deployment to an AWS load balanced app.

**Comment by perdjurner** [comment]
Could be a race condition issue; 2 requests got inside the if statement, the first one created the folder and the second got an error.

Might be best to just wrap that in try / catch instead of checking if the folder exists.

**Comment by perdjurner** [comment]
Although thinking more about it, the entire request should already be locked when you do a reload request so there should be no race condition.

Do you have a setting for "cachePlugins"?

If that's set to false then there is still a chance of a race condition.

**Comment by chapmandu** [comment]
The only plugin settings I use are:

set(overwritePlugins=false);
set(deletePluginDirectories=false);

As I want to deploy the plugins already unzipped.
