### ISSUE TITLE
disable railo testing on Travis-CI

### ISSUE THREAD

**Issue by scahyono** [cfwheels/cfwheels#542]
also upgrade Adobe ColdFusion 11 to update 5 on Viviotech test server.

**Comment by scahyono** [comment]
I have done both on travis-railoless branch.
However, it seems the tests fails on Adobe ColdFusion 9.

Path	wheels/tests/view/assets
...
imagetag	height only	78	Error
Element ONLYPATH is undefined in ARGUMENTS.
 C:\inetpub\wwwroot\wheels\view\assets.cfm line 217

**Comment by perdjurner** [comment]
We can actually stop testing ACF 8 and 9.

We only support the following now:
ACF 10.0.16+
ACF 11.0.5+
Lucee 4.5.1.022+

**Comment by scahyono** [comment]
hmm... ACF10 is so slow on test server, I will have to temporary disable testing it.

**Comment by scahyono** [comment]
Hi admins, 
If you happens to have latest update of ACF10 installers, please upload it to zebrinny like on c:\installer\ or somewhere.
I would like to re-install it and see if performance improves.
Otherwise, we have to disable ACF10 testing for now.

**Comment by perdjurner** [comment]
I think we can probably skip testing on CF 10, as testing on CF 11 is likely good enough (we can  always test manually on CF 10 servers every now and then as needed).

We need to keep this as simple as possible so that hopefully we can find someone to take over this work from you Singgih :)

**Comment by perdjurner** [comment]
@neokoenig or @chrisdpeters Any chance one of you can get Adobe ColdFusion 11 updated to Updater 5?

**Comment by scahyono** [comment]
The ACF 10 and 11 on test server has the latest hot fix now. ACF9 has no new hot fixes.
I have enabled again ACF10+Oracle testing. So, this issue can be closed.

**Comment by chrisdpeters** [comment]
:+1:
