### ISSUE TITLE
Custom response http codes in renderWith() method for web API application

### ISSUE THREAD

**Issue by larshorner** [cfwheels/cfwheels#549]
I am currently working on a project that uses CFWheels for the application layer and I was asked to create a web API to allow for 3rd party integration.  We have the requirement to send custom response codes to indicate success and failure on api calls (i.e. 200 success, 403 not authorized, 500 error occurred) and currently the renderWith method does not support such a thing.

My suggestion is to add a new argument of type numeric, not required and default 200 to the current renderWith() method.  This argument can be checked for existence and used to set response header as required.

Please give me your thoughts.

**Comment by tapirus** [comment]
Maybe habe a look at taffy how it's solved there.

**Comment by larshorner** [comment]
This is what I have done in my code base for now.

I modified the /wheels/controller/provides.cfm
add 	this to line 55
<cfargument name="responseCode" type="numeric" required="false" default="200">

and this to line ~99
if(structKeyExists(arguments, 'responseCode')){
	getPageContext().getResponse().setStatus( arguments.responseCode );
}

now I call it like this: renderWith(data = {some:'data'}, responseCode = 403);

Works great for me, If you like my idea I will put it in a pull request.

Lars

**Comment by perdjurner** [comment]
Does it make sense to make this more generic and add to renderWith, renderPage, renderText etc?

**Comment by andybellenie** [comment]
I like that idea. 

How about handling status text also?

**Comment by chrisdpeters** [comment]
You may find these resources from Ruby useful:

*  [Rack's numeric codes to status text](https://github.com/rack/rack/blob/1.5.2/lib/rack/utils.rb#L544)
*  [List of Rails status code symbols](http://billpatrianakos.me/blog/2013/10/13/list-of-rails-status-code-symbols/)

I find the Rails one with symbols to be rather useful and more readable within the code. But perhaps some people would rather enter the numeric code.

Possible example of how it could work in CFWheels:

```coldfusion
<!--- This... --->
<cfset renderWith(data=myData, status="unprocessableEntity")>

<!--- and/or this... --->
<cfset renderWith(data=myData, status=422)>
```

**Comment by andybellenie** [comment]
:)

**Comment by tapirus** [comment]
Nice! I like the idea to have the choice to either enter text or the code. 

    Andrew Bellenie <notifications@github.com> schrieb am 16:17 Dienstag, 2.Februar 2016:
 

 :)—

**Comment by neokoenig** [comment]
ok, so `renderWith()` can now accept a status argument; 

Either by numerical value, i,e:
`renderWith(data=data, status=200);`

or via text value:
`renderWith(data={}, status="No Content");`

...which sets the cfheader values appropriately.

The latter is essentially a reverse lookup of the former, so only really useful if you know the appropriate http status text. I imagine most people will use "ok", or "Not Found", or "No Content" etc; If you pass in `00007` or `THECAKEISALIE` is will throw an appropriate Wheels error

**Comment by neokoenig** [comment]
Added to docs http://docs.cfwheels.org/v2.0/docs/renderwith
