### ISSUE TITLE
1.4.2 Error - Column 'x' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#554]
Since upgrading to wheels 1.4.2 I am getting the error below

Column 'iscompany' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.

The model call and arguments look like this:
model("Contact").findOne(argumentCollection=arguments);

Scope Arguments

include 1 
    string Owner,SecondaryOwner 
WHERE 2 
    string (contactid IN (31825)) 

The contact model has a calculated property as such..

property(name="contactname", sql="CASE WHEN (contacts.iscompany = 1 AND LEN(contacts.companyname) > 0) THEN contacts.companyname ELSE (ISNULL(contacts.firstname,'') + ' ' + ISNULL(contacts.lastname,'')) END");

**Comment by perdjurner** [comment]
Can you narrow it down a little, for example, does it produce the same error without the "include" and "where" arguments?

Can you post the SQL it produces?

**Comment by chapmandu** [comment]
I can't post the full statement but am trying to create a failing test case.

**Comment by chapmandu** [comment]
It would appear that calculated properties are not being written into the group by clause.. but will confirm.

**Comment by perdjurner** [comment]
Could have something to do with this perhaps?

Change:
https://github.com/cfwheels/cfwheels/commit/fae3d8147f949a3b07179d07665cb791632aff4e

Test:
https://github.com/cfwheels/cfwheels/commit/503c7cbadecf816c52a0272d948d8bfc8b6c80a4

Discussion:
https://groups.google.com/forum/#!topic/cfwheels/VlFKfeaN6T4

**Comment by chapmandu** [comment]
Looks very much like it, but I'm not using distinct=true

**Comment by perdjurner** [comment]
Ok, hopefully you can create a test case and we'll take it from there.

**Comment by chapmandu** [comment]
Okay.. It's caused by using distinct=true with calculated properties on included models. I've created a failing test and will submit a PR.

**Comment by chapmandu** [comment]
Just FYI. This error occurs when upgrading from 1.4.1 to 1.4.2

**Comment by perdjurner** [comment]
Getting closer...

I think the correct fix will be to skip calculated properties that are aggregate SQL functions in the GROUP BY clause.

The test I added shows that the issue exists on a non included model as well.

**Comment by perdjurner** [comment]
@chapmandu Can you confirm that this is now fixed for you as well?

**Comment by chapmandu** [comment]
@perdjurner This does indeed fix the issue. Sorry for the delay.
