### ISSUE TITLE
1.4.1 variable [$WHEELS] doesn't exist during startup/first load

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#556]
I have a load balanced application where when restarting, the healthcheck url is pinged every x seconds to see whether it is a candidate for load balancing. During this period i always receive this exception.

Message: variable [$WHEELS] doesn't exist
Name: onApplicationStart

wheels/plugins/injection.cfm:39
wheels/global/cfml.cfm:111
wheels/events/onapplicationstart.cfm:381

The health check url is simply "/health"

**Comment by perdjurner** [comment]
I don't see a line 39 in wheels/plugins/injection.cfm in 1.4.2.

Is it on 1.4.1 then?

**Comment by chapmandu** [comment]
Yes, 1.4.1.. Like in the subject ;) 

If there are updates in 1.4.2 that might resolve it, I'm happy to work around these exceptions for now... but i can't upgrade until #554 is resolved as this breaks my application.

**Comment by perdjurner** [comment]
Haha, sorry, missed that :)

No, upgrading likely won't solve it.

**Comment by neokoenig** [comment]
You could exclude health from the URL rewriting, so taking wheels out of the health check: after all you're just checking the cfml engine is up, so have a standard cfm file in there?

**Comment by chapmandu** [comment]
Hmm... Not sure that would solve my problem as once the cfml engine was up, I'd just be moving the unloaded application into the load balancer.. I'd imagine the problem would be magnified as it would be dealing with x requests per second rather that one every 10 seconds from the health checker.. 

But I'm more than happy to be corrected..

**Comment by neokoenig** [comment]
Sorry, was assuming your app was setup similar to mine (i.e, AWS EB + EC2)!

**Comment by perdjurner** [comment]
Can you delete the following line and see if it fixes it?
StructDelete(variables, "$wheels");

**Comment by perdjurner** [comment]
Got any update on this @chapmandu ?

**Comment by perdjurner** [comment]
Assumed fixed in this commit:
https://github.com/cfwheels/cfwheels/commit/d352b84826234f95ad05e29420fdf4e5d5cf782a

Please re-open if not fixed.

Thanks.
