### ISSUE TITLE
Document Tuckey URL rewrite + Lucee

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#557]
Whilst Tuckey isn't officially supported, I think it would be good to have something in the docs, as Lucee seems to be being distributed with Tomcat (express version + installers) by default. Since the 1.4.x branch (or was it 1.3?) changed the URL rewrite method, there needs to be a newer version of the rewrite rules for Tuckey.

I've got a (working! Hah!) version of `urlrewrite.xml` rules, but ideally before I write up the documentation, it would be good for a sanity check. They don't deal with ".format" extensions, i.e `params.format` though.

See https://gist.github.com/neokoenig/8e3802cd14387a6ddb82

**Comment by timsayshey** [comment]
Thanks, I dealt with Tuckey a long time ago and gave up. Will look for this next time I run into it.

**Comment by chapmandu** [comment]
I'm using Tuckey, with Lucee and CFWheels with great success (based on your blog @neokoenig ).. 

Though I am looking into using Tomcat rewrite rules as they seem very similar to Apache.

**Comment by neokoenig** [comment]
This can probably be closed, as I added a urlRewrite section to http://docs.cfwheels.org/docs/url-rewriting

**Comment by perdjurner** [comment]
Thanks.
