### ISSUE TITLE
validatesUniquenessOf is causing other validations to be skipped

### ISSUE THREAD

**Issue by chrisdpeters** [cfwheels/cfwheels#558]
Using CFWheels 1.4.2 + SQL Server on Windows. I will be working to pinpoint the bug with failing test(s).

This is what I've witnessed though... If a model has a validatesUniquenessOf validation, other validations are skipped. So when I submit a blank form for a model that should have validatesPresenceOf checks, I get a SQL error complaining about saving NULL data for NOT NULL columns (which should have been picked up anyway by CFWheels automatic validations).

Obviously, if anyone wants to fix this while I work to make time to write the tests, I figured I'd post this issue first.

**Comment by perdjurner** [comment]
Any progress on this @chrisdpeters  ?

Would be nice to get looked at for 1.4.3 which I plan to release soon.

**Comment by chrisdpeters** [comment]
I can't seem to replicate it with a failing test. I'll need to poke around with our app on Monday to see if I can figure out what the heck is going on.

**Comment by chrisdpeters** [comment]
See the sample app we had discussed at [liquifusion/cfwheels-validatesuniquenessof-issue](https://github.com/liquifusion/cfwheels-validatesuniquenessof-issue).

The good news is that this functionality is only broken if I'm using the edge version from the master branch. I had started with CFWheels 1.4.2 and couldn't make the error happen from there. It was after I moved in the `wheels` folder from master that the problem started happening.

Let me know if you have any questions!

**Comment by chrisdpeters** [comment]
:tada: Thank you!

I think 1.4.3 and on will be a great release with this fix.

**Comment by chrisdpeters** [comment]
I still can't get a failing test for this.

Any ideas why this wouldn't trigger the error before your commit?

```coldfusion
<!--- Model with uniqueness validation --->
<cfcomponent extends="Model">
	<cffunction name="init">
		<cfset belongsTo("User")>
		<cfset validatesUniquenessOf(property="id1", scope="id2")>
	</cffunction>
</cfcomponent>

<!--- Test --->
<cffunction name="test_validatesUniquenessOf_with_blank_integer_values">
	<cfset loc.combiKey = model("combiKey").new(key1="", key2="")>
	<cfset assert("not loc.combiKey.valid()")>
</cffunction>
```

**Comment by perdjurner** [comment]
Try:

<cfset loc.combiKey = model("combiKey").new(id1="", id2="")>

**Comment by chrisdpeters** [comment]
Damn! That fixed it. I am trained to instantly translate "id" to "key" in my head as a CFWheels developer. ;)

Thanks.
