### ISSUE TITLE
Model instance isPersisted() and propertyIsBlank() methods

### ISSUE THREAD

**Issue by chrisdpeters** [cfwheels/cfwheels#559]
Rails has `#persisted?`, which is the inverse of `#new_record?` to help avoid "negative" boolean logic.

For example, `if user.persisted?` is easier to process than `if !user.new_record?` or `unless user.new_record?`.

I propose that we add `isPersisted()` for the same reason.

If there are no objections, I'd be glad to implement and document this for CFWheels 2.0.

**Comment by chrisdpeters** [comment]
@perdjurner @neokoenig Thoughts?

**Comment by perdjurner** [comment]
Sounds like a good improvement.

Maybe we should take this opportunity to review other similar functions?

exists()
hasChanged()
hasErrors()
hasProperty()
isAjax()
isClass()
isGet()
isInstance()
isNew()
isPost()
isSecure()
propertyIsPresent()
valid()

**Comment by perdjurner** [comment]
To follow up...

isClass() and isInstance() are already the opposites of each other so we can remove those from the list.

I think we can also remove isGet(), isAjax(), isPost() from the list to review since I think it's rare that you would want to use the oppose of any of those.

This leaves us with:

exists()
hasChanged()
hasErrors()
hasProperty()
isNew()
isSecure()
propertyIsPresent()
valid()

**Comment by chrisdpeters** [comment]
Interesting idea.

This may be a good time to come up with an alias for `valid` too. I understand why it can't be called `isValid` because of the built-in CF function, but it's the only one that doesn't read as a boolean.

`passesValidation` -> `failsValidation`

Many of those I cannot think of antonyms for, which could be a challenge.

`exists` -> ?
`hasChanged` -> `hasUnchanged`
`hasErrors` -> ?
`hasProperty` -> ?
`isNew` -> `isPersisted`
`isSecure` -> `isInsecure`
`propertyIsPresent` -> `propertyIsBlank`
`valid`/`passesValidation` -> `failsValidation`

**Comment by perdjurner** [comment]
Are you avoiding using the word "not" for a specific reason?

If not, wouldn't:

hasChanged -> hasNotChanged

be easier to read than:

hasChanged -> hasUnchanged

**Comment by chrisdpeters** [comment]
Yes, I am. I'd hate to see code that looks like this:

```coldfusion
<cfscript>
if (!this.hasNotChanged()) {
}
</cfscript>
```

Or even better:

```coldfusion
<cfif not this.hasNotChanged()>
</cfif>
```

Am I being too pessimistic?

**Comment by perdjurner** [comment]
I do think you are being too pessimistic here.

We should provide the best options for creating readable code, and do our best to use it in documentation so developers can pick up on it.

In that regard I prefer something.hasNotChanged() over something.hasUnChanged().

**Comment by neokoenig** [comment]
We need to be careful with double negatives.

Good:
`if ( this.hasChanged() ){}` or `if ( ! this.hasChanged() ){}`

Not good:

`if (! this.hasNotChanged() ){}

"unChanged" I don't think is a clear term.

I'm definitely more of a fan of `is` statements being positive assertions, and using a `!` or `not` operator . Personally, that's clearer to me, but there you go.

**Comment by chrisdpeters** [comment]
Rails doesn't implement any of these other than the equivalent to what would be our `isPersisted()` and `propertyIsBlank()`.

Though I'm glad we took a minute to explore it, I feel like the other ideas are forced. Including the word "Not" in the name probably isn't any easier to parse mentally than the `!` or `not` boolean operators when reading the code as a developer.

**Comment by chrisdpeters** [comment]
Docs:
-  [isPersisted](http://docs.cfwheels.org/v2.0/docs/ispersisted)
-  [propertyIsBlank](http://docs.cfwheels.org/v2.0/docs/propertyisblank)
