### ISSUE TITLE
Make `pagination` global

### ISSUE THREAD

**Issue by chrisdpeters** [cfwheels/cfwheels#560]
I've needed to use the `pagination` method from within the model. @perdjurner Any objections to making it global so it can be accessed in both the controller and model?

**Comment by perdjurner** [comment]
I think it already is global actually.

**Comment by chrisdpeters** [comment]
It appears to be mixed in to the controller but not the model:
https://github.com/cfwheels/cfwheels/blob/87c52e8a1c1d15ae07a451d74d69581a1bb70616/wheels/controller/miscellaneous.cfm

**Comment by perdjurner** [comment]
Sorry, I was thinking of setPagination.

Go ahead and make it global.

**Comment by perdjurner** [comment]
This can be done as a bug fix since setPagination is global.

**Comment by perdjurner** [comment]
Done.
