### ISSUE TITLE
model.COUNT() only firing once per action. (the same Column Statistic will only fire once per action?) 

### ISSUE THREAD

**Issue by kmd1970** [cfwheels/cfwheels#562]
When I call this `test` action I expect to get `0 1` as the output from each model `count()`, however I always get `0 0`. 

When I check my debug, only one SQL `count(*)` is executed and and then two SQL `inserts` right after. Shouldn't all code be executed in the order written? 

I am expecting one SQL `count(*)` statement right before each SQL `insert` to return the number of similar items inserted. I've tried adding `save(transaction='commit')` and using `create()`, but the results are the same. Confused?

```html 
<cffunction name="test" output="true">
 <cfscript> 
    var test = model("test").new();
    test.value = "test";
    test.parent_id = "99";
    var count = model("test").count(where="parent_id = '99'");
    writedump(count);
	
    test.save();
    //model("test").create(test);
    
    var test = model("test").new();
    test.value = "test";
    test.parent_id = "99";
    var count = model("test").count(where="parent_id = '99'");
    writedump(count);

    test.save();
    //model("test").create(test);
</cfscript>
</cffunction>
```
This results in only one SQL count(*) being executed, because the WHERE clause is the same.

```html
<cffunction name="test" output="true">
       <cfscript> 
           var count = model("test").count(where="parent_id = '99'");
           var count = model("test").count(where="parent_id = '99'");
           var count = model("test").count(where="parent_id = '99'");
        </cfscript>
</cffunction>
```

My Table
```sql
CREATE TABLE [dbo].[TESTS](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[uuid] [char](36) NOT NULL DEFAULT (newid()),
	[value] [char](36) NULL,
	[updatedat] [datetime] NULL,
	[updated_by] [varchar](36) NULL,
	[created_by] [varchar](36) NULL,
	[deletedat] [datetime] NULL,
	[createdat] [datetime] NULL,
	[parent_id] [char](36) NULL,
 CONSTRAINT [PK_TESTS] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)  ON [PRIMARY]

GO
```

**Comment by andybellenie** [comment]
All model queries are cached for the duration of the request

To force a reload, add reload=true to the model call, i.e.
model("test").count(where="parent_id = '99'", reload=true);

**Comment by kmd1970** [comment]
Hi Andy, Thanks for the quick reply. 

The `reload` parameter should be added to the `count()` documentation. I assumed `reload=true` was only to reload the object from the database once an insert/update has completed.

**Comment by perdjurner** [comment]
Reopening so we can document.

**Comment by chrisdpeters** [comment]
Got this documented.
http://docs.cfwheels.org/v1.4/docs/count

Also replaced the "See docs for findall" references with the appropriate descriptions.

**Comment by perdjurner** [comment]
Great, thanks Chris.

**Comment by kmd1970** [comment]
Thanks.
