### ISSUE TITLE
MariaDB support

### ISSUE THREAD

**Issue by AlexeiCF** [cfwheels/cfwheels#563]
I'm using MariaDB JDBC connector. CFWheels doesn't support it, because it returns *MariaDB* as an adapter name. MariaDB is fully compatible with MySQL in terms of syntax but is actively developing and has some performance improvements.

I suggest adding support of MariaDB by doing the following:
1) In wheels/Connection.cfc
add line 44 to 47
```
else if (FindNoCase("MariaDB", loc.info.driver_name))
	{
		loc.adapterName = "MariaDB";
	}
```
2) Copy-paste and rename wheels/model/adapters/MySQL.cfc -> MariaDB.cfc

**Comment by perdjurner** [comment]
If you're just planning to copy and paste the MySQL.cfc without making any changes to it, then it might be better to just accept "MariaDB" as one of the driver names that loads the MySQL.cfc file.

**Comment by chapmandu** [comment]
MariaDB and MySQL are beginning to diverge as of MySQL version 5.7. The MySQL adapter is currently compatible with Maria but this may change in future.

Would it be worth creating a separate adapter or just add Maria to the existing MySQL condition?

**Comment by chapmandu** [comment]
Until there is a significant disparity between engines, the MySQL adapter should suffice.

**Comment by chapmandu** [comment]
https://github.com/cfwheels/cfwheels/commit/91b17539c78c81c1bc5103bc0297c72dd64c544a
https://github.com/cfwheels/cfwheels/commit/809d20aa41d520a5e8f8bacdd41af53c8ac46c23
