### ISSUE TITLE
Allow mailParams to be passed through unchanged, when not using "file", to sendEmail()

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#565]
This may well be a lucee issue, but I feel this should work.
https://gist.github.com/neokoenig/4191d933cfeb0eb282f2

```
<cfscript>
yourEmail="test@domain.com";
cfdocument(format='pdf', name="test1",  fontembed="true"){
    writeOutput("TEST");
};   
fileWrite("ram://Sample.pdf", test1); 
if(fileExists("ram://Sample.pdf")){ 

    /* Throws smtp.yoursmtp.net java.lang.NullPointerException on Lucee*/
    sendEmail(to=yourEmail, from=yourEmail, 
        template="/email/myTemplate", subject="Test", 
        file="ram://Sample.pdf", 
        spoolenable=false, 
        remove=false);   
} 
</cfscript> 
```

I've set Spoolenable to false deliberately as the physical file won't exist. 
Only tested on lucee, but would be curious if this happens on CF10/11 too.

**Comment by neokoenig** [comment]
Ok, looks like it might be a lucee issue. 

```
<cfmail to="me@domain.com" from="me@domain.com" subject="Test" spoolenable="false"> 
    <cfmailparam file = "ram://Sample.pdf" type="application/pdf">  
</cfmail>
```
Also fails. Maybe I'm just doing it wrong :)

**Comment by ellor1138** [comment]
I did a test with the code below work on CF9 and the PDF is sent successfully.

```
<cfmail to="me@domain.com" from="me@domain.com" subject="Test" spoolenable="false"> 
    <cfmailparam file = "ram://Sample.pdf" type="application/pdf">  
</cfmail>
```

I also did a quick test to see it it's possible to send a "ram" file via the sendEmail function and it did not work. I suspect the problem occurs between these lines: https://github.com/cfwheels/cfwheels/blob/master/wheels/controller/miscellaneous.cfm#L111-L115.

Wheels check if there's a directory delimiter in the "file" attribute, if so, wheels automatically append the filePath. This throw an error as the "ram" file do not exists in the "files" directory. A quick way to fixe the problem, would be to create a new attribute to be pass with the sendEmail function (i.e. virtual=true) and add an additional check, in the sendEmail function. If virtual=true, Wheels would not append the filePath and the file should be send without any issue.

```
sendEmail(to=yourEmail, from=yourEmail, 
        template="/email/myTemplate", 
        subject="Test", 
        file="ram://Sample.pdf", 
        spoolenable=false, 
        remove=false,
        virtual=true);
```

I did a test where I removed the directory delimiter check, in the sendEmail function, and the "ram" file was sent successfully.

**Comment by neokoenig** [comment]
Thanks @ellor1138 - v helpful. I think either a 'virtual' flag, or the ability to directly pass an array of mailParams in (or both) would be a nice way forward.

As file resets the arguments.mailparams to [], we'd need to bypass that too if passing in MailParams directly (and append them to any additional 'file' requests.

Don't mind doing the work, but just wanted to check that ram:// works in principle.

@perdjurner - is it worth me putting together something in a branch for you to consider?

**Comment by perdjurner** [comment]
"the ability to directly pass an array of mailParams in"

That should work already, just don't use the "file" argument at all and I think it will work.

**Comment by neokoenig** [comment]
Thanks @perdjurner  - actually, `mailparams` isn't in the `loc.mailTagArgs` list, so it's getting stripped out and never arrives in the `$mail` function. Adding it that list means it works when passing an array:

```
mailParams[1]["file"]= "test.pdf"; 
mailParams[1]["type"]= "application/pdf";
mailParams[1]["content"]= test1; 

	sendEmail(to="tom@foo.co.uk", from="tom@foo.co.uk", 
		template="/email/tickets", subject="Test", 
		mailParams=mailParams, 
		spoolenable=false, 
		remove=false);  
```

**Comment by perdjurner** [comment]
Ah, good catch, didn't see that.

So, that sounds like a good solution then, right?
The ability to pass through "mailParams" unchanged I mean.

**Comment by neokoenig** [comment]
Yeah, perfect;

**Comment by neokoenig** [comment]
Might be worth documenting when it's changed too.

**Comment by neokoenig** [comment]
Ps, for anyone who finds this later, I've filled a lucee bug about the ram:// resource issue - https://luceeserver.atlassian.net/browse/LDEV-614

**Comment by neokoenig** [comment]
reopening for docs.

**Comment by perdjurner** [comment]
Think you can back-port to the 1.4 branch and update both change logs too?

By the way, this can't cause any side effects can it?
I don't see how it could myself...

**Comment by neokoenig** [comment]
I can't forsee any issues; put it this way, if anyone was passing in mailParams, they'd have been deleted/removed/overridden if there was a file, and then just not passed through. the $mail function appears to handle this just fine, and is already using the same technique to handle normal files.

The only thing is you've got to pass an array with a struct in for it to work; which is a little 'unwheels-y', but not a game changer; just think we need to document this clearly.

Re: backports - I've not idea how to do that :) is the master branch 2.0 now? I must confess the amount of "master/new-master" etc branches confuses the hell out of me...

**Comment by perdjurner** [comment]
Just put your code change in the 1.4 branch as well.
Then update the change log in both 1.4 and master.

I consider your change a bug fix which is why it should be included in a 1.4.4 release.

Yes, master is 2.0 (or whatever the next version with any new features will be).

You can forget about the new-master branch completely, not in use anymore.

**Comment by neokoenig** [comment]
Funky, ok, will do.

**Comment by perdjurner** [comment]
Also, ignore the fact that the 1.4 branch doesn't pass any tests. That's a problem with the test suite and not the code.

**Comment by neokoenig** [comment]
Closing : https://guides.cfwheels.org/docs/sending-email updated with `mailParams` example plus some other bits
