### ISSUE TITLE
Allow sendFile() to support ram:// resources

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#566]
There's a fairly easy change which can be made to sendFile() to allow it to send ram based resources;
Essentially, you just check for ram:// in the args and then bypass the physical file check.

I've got the code for this, but before I add it, just wanted to poll whether 
a) should this be classed as a new feature and be saved for 2.0?
b) should we also check for S3:// resources (and indeed, with sendFile, is that even possible?) Afraid I don't use S3:// much, so don't really have much to test against.

Being able to do `sendFile("ram://foo.pdf")` is actually really useful....

**Comment by perdjurner** [comment]
a) that would be a new feature in my opinion.
b) no, that sounds more like plugin material.

**Comment by neokoenig** [comment]
It's going to have to be 2.0 where we're dropping CF8, as ram:// isn't supported on that, so you couldn't create a passing test for it. I'll write a couple of tests and pop it in master if there are no objections.

**Comment by perdjurner** [comment]
:+1:

**Comment by neokoenig** [comment]
Code in master + a couple of tests. Leaving open to document

**Comment by neokoenig** [comment]
Closing. Documented in https://docs.cfwheels.org/v2.0/docs/sending-files and a code example in the core
