### ISSUE TITLE
findAll() with returnAs = "structs" not including alias columns

### ISSUE THREAD

**Issue by kmd1970** [cfwheels/cfwheels#567]
These two findALL() calls are practically the same, however employees1 does not include the SQL Alias columns (ID, TEXT) in the returned array of structs. I would assume it should return all data you requested. 

Alias columns ID, TEXT not returned in array of structs.
 
```html
<cfset employees1 = model("Employee").findAll(select="employee_number AS id, display_name AS text, phone,email,display_name,employee_number", where="display_name LIKE '%#lcase(params.term)#%'", returnAs="structs")>
```
Alias columns ID, TEXT returned in query.
```html
<cfset employees2 = model("Employee").findAll(select="employee_number AS id, display_name AS text, phone,email,display_name,employee_number", where="display_name LIKE '%#lcase(params.term)#%'")>  
```

**Comment by perdjurner** [comment]
I've looked at the code and this behavior looks intentional.
The solution is to use calculated properties instead.

**Comment by andybellenie** [comment]
Why isn't this a bug? I'd expect returnAs="structs" to be exactly the same as returnAs="query" except as an array of structs.

**Comment by perdjurner** [comment]
My thinking was that when you get objects / structs back you build those based on the model object (i.e. database columns and calculated properties).

The fact that Wheels allows a developer to pass in completely custom SQL to the SELECT clause is a separate feature to me.

**Comment by andybellenie** [comment]
Ok

**Comment by kmd1970** [comment]
The reason this came up is because I am querying the database, then converting the query data to an array of structures with a custom function. The data is rendered as JSON later.

I eventually noticed that using returnAs="structs" returns that same array of structures as my function, except it omits aliased columns. I guess I will have to continue to use my custom function on queries for this purpose.

**Comment by andybellenie** [comment]
As Per suggested, calculated properties will solve this for you.

Add the following to your model init() and the column aliases will be returned in all queries for this model

<cfset property(name="id", sql="employee_number">
<cfset property(name="text", sql="display_name">
