### ISSUE TITLE
findAll can't select columns the when re-using model

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#568]
I have this setup.

models/User.cfc
models/Relationships.cfc
models/Friend.cfc (table="users")

When I select specific columns from the UsersFriend model, they are ignored

model("User").findAll(select="firstname, lastname, friendsfirstname, friendslastname", include="Relationships(Friends)")

Only the firstname and lastname columns are returned.

Omitting the select statement will select these columns, but causes me other 'ambiguous column name' errors.

**Comment by perdjurner** [comment]
Is this a typical many-to-many setup?

If so, should it not be:

User.cfc:
hasMany("relationships")

Relationship.cfc:
belongsTo("user")
belongsTo("friend")

Friend.cfc
hasMany("relationships")

include="relationships(friend)"

Note the singular form on Relationship.cfc and "friend" in the include.

**Comment by chapmandu** [comment]
My examples were really just pseudo code.. I have the models correctly setup and working.. 

It's a fairy simple one to many relationship apart from the users table being used in the contact and friend models.

**Comment by perdjurner** [comment]
In the "select", should it not be "friendlastname" instead of "
friendslastname" (singular).

**Comment by chapmandu** [comment]
Yes, most likely.. but these are only examples.

What I did was omit the select argument, copy the column names that were generated by wheels on the "friend" model, and use those in the select argument.. those columns were not returned in the resulting query.

**Comment by perdjurner** [comment]
Can you create a failing test please?

**Comment by perdjurner** [comment]
Thanks for the test.

You use 3 non standard things as far as I can tell:

- The "useExpandedColumnAliases" setting.
- The table() name function.
- The "foreignKey" argument.

If you can remove the usage of these things and add them back one-by-one, checking which one causes the bug it would help me narrow things down.

**Comment by chapmandu** [comment]
I was able to come up with a much less contrived test. Seems the issue is much less 'edge-case' than I first thought.

https://github.com/chapmandu/cfwheels/blob/9e5658a168391a58a7b4974d150e441fc9602833/wheels/tests/model/crud/select.cfc

**Comment by perdjurner** [comment]
I don't think this is a bug actually.

You can do "createdAt, createdAt" and it brings back the right columns.

I agree that we probably should support "createdAt, commentCreatedAt" though.

**Comment by perdjurner** [comment]
Adding "docs" label so we can check / add documentation for this.

**Comment by andybellenie** [comment]
If I remember correctly, you need to specify the columns with their table names, rather than the Wheels created aliases.

The below works in one of my apps:

    <cfset test = model("Location").findAll(
        select="locations.id, locationimages.id AS locationimageid", 
        include="LocationImages"
    )>

**Comment by chapmandu** [comment]
@perdjurner "createdAt, createdAt" .. Wow.. I never knew that was possible, this has been my interim solution. 

What if I wanted to use where="commentCreatedAt < '#Now()#'"  ?

@andybellenie Using the table names won't work for me as calculated properties are ignored.

**Comment by chapmandu** [comment]
Closing due to my complicating what is essentially a small enhancement.. Will create a new issue.
