### ISSUE TITLE
Cannot use update() within an afterSave() callback on a new model

### ISSUE THREAD

**Issue by andybellenie** [cfwheels/cfwheels#569]
Controller
````
<cfset test = model("Test").create(description="a test")>

````

Test model

````
<cffunction name="init">
	<cfset afterSave(method="calculateTotal")>
</cffunction>

<cffunction name="calculateTotal">
	<cfset this.update(total=10, callbacks=false)>
</cffunction>
````

This will fail with a key error, because on the update() call Wheels thinks that the insert has yet to take place, so instead of generating an update query, will try and run the insert again.

**Comment by perdjurner** [comment]
Does it work if you call this.clearChangeInformation() before the this.update() call?

**Comment by perdjurner** [comment]
Or another option, call this.reload() before the this.update() call, does that work?

**Comment by andybellenie** [comment]
Yes, clearChangeInformation() works, but reload() still produces the error.

**Comment by perdjurner** [comment]
Ok, it would be nice if this worked without having to call clearChangeInformation() but I think the reason it doesn't is that we wanted the object to considered new through out the callback chain, so that you could do stuff based on the fact that the object was just saved.

**Comment by andybellenie** [comment]
Ok I understand thanks for the help
