### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mwells3456** [cfwheels/cfwheels#573]
It would be awesome if you guys could do what Laravel did for php tags, where they replaced php with "@". The code would be so much cleaner and quicker to type out with an @include("pagehere") or #include("pagehere"), or something similar instead of cfinclude template="pagehere"

You could make this a great platform for those of us who are transitioning from php to CF and simplify the way the tags are handled, which tend to be really annoying and repetitive for most modern developers. 

Just a suggestion. Thanks!

**Comment by perdjurner** [comment]
We do have includePartial as a wrapper for cfinclude:
http://docs.cfwheels.org/v1.4/docs/includepartial

You were probably just using cfinclude as an example though.

Do you have any other examples where it would make sense to turn them into functions, or are you saying all tags should be provided as functions?

**Comment by mwells3456** [comment]
Thanks for the quick response! Sorry, I didn’t mean include specifically. I was really talking about the <cf….> tags in general. A few examples would be:

@set or #set (something comparable) instead of <cfset></cfset>

@if instead of <cfif></cfif>

@output instead of <cfoutput></cfoutput>

If an @output or #output needs to be closed, you could figure out a close for it like @endoutput or #endoutput maybe. 

Another idea would be to use @set (<cfset>) like a script tag, where you could list what you are setting bellow (if you have multiple cfset variables without having to repeat that stupid tag every time.

Like this:

@set
	thisIsFun = “fun”,
	thisIsEasy = “easy”,
	thisIsAwesome = “Awesome”
@endset

I don’t know if that is possible, but that seems more intuitive to me. 

Whether you use @ (like Laravel does for <php>) or # or ## or whatever you want to use, it would just be cool to get the repetitive code out in the CF tags. As someone new to CF, it’s a lot cleaner looking to me. 

Again, just thought I’d throw that idea out there. It would be something that no other framework is doing on a large level, and might be a really cool way to help encourage php and .NET developers to make the switch to CF using your framework. Most developers nowadays (like you guys) are trying to simplify code and remove repetition. Just thought that would be a really cool next step in obtaining that goal. 

I’d love to hear your thoughts on this!! Take a look at Laravel for php as an example. They’ve done a slam up job and made php relevant again. Lots of really cool stuff! :-)

Mark

**Comment by neokoenig** [comment]
I think this is more of an engine level change. Lucee, and it's new incarnation of lucee 5.x is basically  trying to do a lot of stuff like this. i.e, removing the `<cf>` requirement, and just haveing `<:set>`. 

In order for wheels to be interoperable between CF engines, there's a level of backwards compatibility required, and a change like this, where there's a whole new syntax specific to cfWheels, I think would be counter-intuitive.

You mentioned you're new to CFML - I think a  lot of what you're asking for is actually already there, just in cfscript. i..e

```
<cfscript>
if(foo=1){
bar=2;
};

// or

writeOutput("foo"); etc

// or 

foo = 1;
bar = "something";
</cfscript>
```

CFML has a legacy as a tag based language, whereas the reality is that modern CFML is mainly in script. The two are easily confused! Either way, language level changes aren't really the place of a framework such as wheels I think.

**Comment by mwells3456** [comment]
AAAH! Good to know! Thanks so much for the info! We are actually moving to Lucee, so maybe they will do what you are saying and coupled with your framework, we can make CF much more modern developer friendly. Good stuff!

I think you are right about the cfscript tag too. That is more like Javascript, which I like!

Mark

**Comment by neokoenig** [comment]
If your only exposure to CFML has been tags, I'd go and bookmark this immediately: https://github.com/adamcameron/cfscript/blob/master/cfscript.md 

Script support is available (in various guises) from CF9 onwards if you're on ACF, or lucee does script syntax (slightly) more comprehensively. If you've got any languages queries, the CFML slack channel is a great place to start - get an invite here: http://cfml-slack.herokuapp.com/
