### ISSUE TITLE
Prepend some SQL to model finder SQL statements

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#574]
I'd like to be able to prepend hints or comments to SQL statements prepared by the ORM.. and possibly append.. but I've not personally had any need for it as yet.

Eg: 
model("User").findAll(prepend="SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED"); // handy when wanting to avoid transaction deadlocks when dirty reads are acceptable
or 
model("User").findAll(prepend="/\* the quick brown fox etc.. */"); // this would be handy in debugging & server monitoring tools

**Comment by perdjurner** [comment]
Got a better (real world) example?

Since transactions should already be handled within the framework.

Thanks.

**Comment by chapmandu** [comment]
The transaction isolation level is probably not so important after seeing the options available.. (how would one set isolation level to uncommitted using the ORM? The docs are a little unclear) 

It's would still be handy for debugging.. but i suppose there would need to be more votes than just mine..

**Comment by andybellenie** [comment]
It's not possible to set the transaction level at the moment, you can only choose 'commit', 'rollback' or 'none'

**Comment by chapmandu** [comment]
It seems it can be done with http://docs.cfwheels.org/v1.4/docs/invokewithtransaction though it looks like it would be a workaround..

**Comment by andybellenie** [comment]
That's interesting. All internal wheels methods use invokewithtransaction so maybe they pass it through.

**Comment by perdjurner** [comment]
@chapmandu Do we need to document anything here? If not, I am closing this.

**Comment by perdjurner** [comment]
Closing.
