### ISSUE TITLE
Reload / clear model info

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#577]
Sometimes it's useful to clear cached information for a model without reloading the entire site. If you make a database change and want it to be picked up by Wheels right away for example.

This code works:
StructDelete(application.wheels.models, "modelName")
model("modelName")

Perhaps we should create an API method for that, something like model("modelName").reload() perhaps.

Or maybe we already have this capability and I'm just forgetting how it's done?

**Comment by andybellenie** [comment]
What's the use case?

**Comment by perdjurner** [comment]
If I remember correctly it was because I wanted to be able to rename or remove a column and immediately have Wheels pick up on those changes so that findAll would not attempt to use it in the select clause.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
