### ISSUE TITLE
Update rocketunit to 2.0

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#578]
Looks like there's an updated version of RocketUnit which doesn't require quotes around assert statements - could consider upgrading for 2.0?
https://github.com/robinhilliard/rocketunit

**Comment by neokoenig** [comment]
Looking at the code for rocketunit 2.0 it uses cfscript components, so will break CF8, so recommend delaying till wheels 2.x

**Comment by chrisdpeters** [comment]
@neokoenig Would it be too much effort to create a copy that's converted to tag syntax and then choose which file(s) to include at runtime based on CF version? This would be an example of something that we could include in a possible v1.5 but then delete after v2.0 is released.

**Comment by chrisdpeters** [comment]
@neokoenig Or of course, like you said, just wait until v2.0 to do it.

**Comment by neokoenig** [comment]
Oh I'm sure we could do that, just seemed something which was 'nice but not essential at the moment' :)

**Comment by perdjurner** [comment]
@neokoenig Can you assign this to yourself if you plan on doing it?

(Otherwise let's remove it from the roadmap until someone steps up.)

**Comment by perdjurner** [comment]
By the way, I wouldn't consider this a breaking change since the test suite has never been a documented part of Wheels as far as I know.

**Comment by neokoenig** [comment]
Sure, I think we can put this on hold for now. I'd rather not break the whole testing suite before 2.x too :)

**Comment by chapmandu** [comment]
I'd be happy to hack away at this unless there is something more pressing

**Comment by perdjurner** [comment]
"I'd rather not break the whole testing suite before 2.x too"

That is a very good point actually, now is not a good time to work on the test suite I I think (maybe we can do it in a 2.1 release instead).

**Comment by neokoenig** [comment]
Looking at this further, it appears 2.0 isn't compatible with 1.x written tests:
Specifically, `assert("myVar")` now *needs* to be `assert(myVar)` from what I can tell, which means potentially rewriting _**Every single test's assert() call**_... hmm. Yes, let's leave this one for now.

**Comment by robinhilliard** [comment]
`s/assert\("(.+?)"\)/assert(\1)/g` or similar regex replace should do the trick if that's what you're worried about.

**Comment by chapmandu** [comment]
I have some core tests working with RocketUnit 2.0. I'll make the wheels core tests compatible.

**Comment by chapmandu** [comment]
Sticking with the forked version of 1.0
