### ISSUE TITLE
Issue with findAll query when using paging and order parameters

### ISSUE THREAD

**Issue by Maowse** [cfwheels/cfwheels#579]
We are having an issue with the select statement being incorrectly built when using a findAll query with order and paging options set.

For example:

```
<cfset someResults = model("SomeModel").findAll(select="id, column1, column2, column3", 
order="column1 DESC",where="isActive = true", 
maxRows="1000",page=somePageParameter, 
perPage=50,
handle="someHandle")/>
```
This results in a select query being built as follows:

```
SELECT id FROM (SELECT TOP 50 id FROM (SELECT TOP 50 id, column1 ORDER BY column1
DESC,id) AS tmp1 ORDER BY ) AS tmp2 ORDER BY
```
The second and third order by clauses are incorrect.

Are we building our findAll query incorrectly?

Thanks!

**Comment by perdjurner** [comment]
You should use either the page / perPage combo or maxRows, not all three.

Not sure if that fixes it, but give it a try.

**Comment by Maowse** [comment]
Thanks for the clarification, but removing the maxRows option results in the same issue.

**Comment by perdjurner** [comment]
Ok, simplify some more and tell me if it starts producing a correct ORDER BY clause please:

- remove "handle".
- remove "where".
- remove "page" and "perPage".

Also, this is on MS SQL Server and using the latest version of Wheels, correct?

**Comment by Maowse** [comment]
I believe I have narrowed it down a bit further. Removing the options you specified resulted in a correct query. However, anytime I attempt to use a 'CONVERT' in the order option, along with the paging options, results in the issue.

To summarize, I believe you can reproduce this by using the paging options and attempting to order based on a converted value, for example: CONVERT(DATETIME, column1).

**Comment by perdjurner** [comment]
Is that CONVERT set using a calculated property?

http://docs.cfwheels.org/docs/calculated-properties

**Comment by Maowse** [comment]
Right now, it is directly in the order option. I will try setting it via calculated property and let you know if that changes anything.

**Comment by Maowse** [comment]
Using a calculated property fixes the issue. I've used one as follows:

```
<cfset property(name="testProperty",sql="CONVERT(DATETIME,column1)")>
```
Using the calculated property in the order parameter results in a correct query being built.
