### ISSUE TITLE
Select ambiguous column name using the wheels alias

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#580]
The commentcreatedat column below cannot be used in a select statement. 

`model("Post").findAll(select="createdat,commentcreatedat", include="Comments");`

A test for this enhancement has been written here:

```
<cffunction name="test_select_ambiguous_column_name_using_alias">
    <cfset loc.query = model("Post").findAll(select="createdat,commentcreatedat", include="Comments")>
    <cfset loc.columnList = ListSort(loc.query.columnList, "text")>
    <cfset assert('loc.columnList eq "commentcreatedat,createdat"')>
</cffunction>
```

**Comment by perdjurner** [comment]
Check if this should be considered a bug before releasing 1.4.5.

**Comment by perdjurner** [comment]
Going to consider this a bug for now as I'm pretty sure this was intended functionality to begin with.

**Comment by zainforbjs** [comment]
@chapmandu @perdjurner This should only be for specific columns like id,createdat,updatedat and deletedat, right? 

Or should it be for all columns in the included table? For example. if there is a content column, then using commentcontent will return that column or not?

In my opinion, it should only be for specific columns that are set by default in migrations, namely what are mentioned above.

**Comment by zainforbjs** [comment]
@chapmandu @perdjurner  I made some changes for fixing this as I did not find any existing logic to achieve this.

I added a new variable in class called aliasedPropertyList which will contain the column names with the model’s name prepended to them. For now, I added a condition that will only add the model’s name to specific default columns namely (id,createdAt,updatedAt,deletedAt).

Then, I used that variable to compare with the passed in select arguments in the findAll() function and if an entry is found then separate the model name from the column and get the column from the included table and return that.

Here is a PR with the changes. https://github.com/cfwheels/cfwheels/pull/1253

**Comment by chapmandu** [comment]
Wow, this is an oldie! I'm pretty sure it should be available on any  column. Eg 'notes' is a good example.

**Comment by zainforbjs** [comment]
@chapmandu I see. 
So I will remove the condition for the 4 specific columns that I added and prepend the model name to all the columns in the list that I created.
That way any column name prepended with the model name passed in the select clause will return the corresponding column in the relevant table.

**Comment by zainforbjs** [comment]
@chapmandu Added a new commit and removed the 4 specific column condition from it.
