### ISSUE TITLE
Clear server cache on reload

### ISSUE THREAD

**Issue by andybellenie** [cfwheels/cfwheels#585]
clearServerCacheOnReload is set to true in the application config for production environments. This calls the flush action of cfcache.

I may be mistaken here but doesn't that empty the cache for all applications running on the same server, not just the wheels app? In which case should this really be set to true?

Also, if it's set to false, how can action/page level caches be cleared? I'm looking for a manual way to clear action caches without affecting other sites on the same server.

**Comment by perdjurner** [comment]
I thought cfcache was tied to cfapplication.

Can you test it?

I don't think there is a programmatic way to clear page caching in Wheels when using the "static" argument.

**Comment by andybellenie** [comment]
Ok I've tested clearing a cfcache from one application to another and it appears that you are right, it's tied to the application.

I was getting confused with <cfobjectcache action='clear' />

I've done some more digging. If I change the url rewriting to pass through the path_info as a query string parameter it works fine.

    <action type="Rewrite" url="/rewrite.cfm/{R:1}?path_info={R:1}" />

I can programatically clear the cache by running this in onrequeststart.cfm

    <cfparam name="application.flushCache" type="boolean" default="true">
    <cfif application.flushCache>
    	<cfcache action="flush" />
    	<cfset application.flushCache = false>
    </cfif> 

If I set application.flushCache to be true anywhere else in the app, on the next request it gets cleared.

Now I just need to figure out a way to add to the query string when there are existing url params...

**Comment by andybellenie** [comment]
There's definitely an issue here. Here's the code in onapplicationstart.cfm

````
// clear query (cfquery) and page (cfcache) caches
if (application.$wheels.clearQueryCacheOnReload)
{
	$objectcache(action="clear");
}
if (application.$wheels.clearServerCacheOnReload)
{
	$cache(action="flush");
}
````

That first line calls cfobjectcache with the clear argument. This will clear all cached queries on the server. Not good in a shared environment.

The correct way to clear cached queries is to pass in a cachedwithin attribute of #CreateTimeSpan(0, 0, 0, 0)#

**Comment by andybellenie** [comment]
I suggest we remove this setting completely. It's too dangerous for a shared environment. If a developer really wants to flush the whole server cache they can add a cfobjectcache call manually to onapplicationstart.cfm easily enough.

**Comment by andybellenie** [comment]
Hi Per any thoughts on this?

**Comment by perdjurner** [comment]
"I'm a bit confused here. Wheels caches finder calls in application.wheels.cache which is already cleared on reload, so this only applies to custom queries that use the cachedWithin attribute."

When you use the cache argument on a finder it actually sets a cachedWithin attribute on the query (loc.finderArgs.cachedWithin = $timeSpanForCache(arguments.cache)).

In other words it does not only apply to custom queries.

Reading the docs on cfobjectcache it states that it "clears queries from the cache in the Application scope". Sounds like it is also tied to the application scope then and should not affect other sites on the server, right?

**Comment by andybellenie** [comment]
See the following:
http://www.coldfusionmuse.com/index.cfm/2010/2/17/cfobjectcache

I've run the tests myself and confirmed the issue. I also noticed while testing that setting the cachedWithin attribute to 0 in one app forced a refresh in the other. There appears to be no application level isolation of query caching at all.

**Comment by perdjurner** [comment]
Ok, I'm fine with removing all usage of cfobjectcache then.

**Comment by andybellenie** [comment]
Problem there is we lose the ability to clear out cached queries on reload.

I've got a workaround but it's a an ugly hack. If we set a application variable as a unique string we can insert it into the query as a comment. That changes the SQL so as far as cfquery is concerned it's a new query. When we reload the application we change the unique string - voila all cached queries reload. 

Tested and works:

![screen shot 2016-02-16 at 22 48 17](https://cloud.githubusercontent.com/assets/147703/13081429/684682c2-d4ff-11e5-91ee-95ef39d46a83.png)

**Comment by perdjurner** [comment]
Brilliant, do it!

**Comment by andybellenie** [comment]
:)

**Comment by perdjurner** [comment]
I remember using that trick for something else in Wheels.

Can't remember what it was or if it even made it into core code though.

**Comment by perdjurner** [comment]
@andybellenie Is there any way we can keep the clearQueryCacheOnReload setting? Maybe the cache key you set only resets on application start when clearQueryCacheOnReload is set to true or something?

**Comment by andybellenie** [comment]
That's how it's working now, check the commit :)

**Comment by andybellenie** [comment]
Note the rename of clearServerCache to clearTemplateCache for more clarity

**Comment by perdjurner** [comment]
If I rename that setting back I can put this in 1.4.5...

**Comment by perdjurner** [comment]
I was able to back-port in a safe way (keep name for setting and check for cachekey before using).

https://github.com/cfwheels/cfwheels/commit/7253b9687cab6889ed7dfc4ace0da2c6613a6a75

Code in master can remain as is.
