### ISSUE TITLE
Add appendToKey to finder calls to allow custom cache keys

### ISSUE THREAD

**Issue by andybellenie** [cfwheels/cfwheels#587]
The caches() method has the appendToKey argument to allow an evaluated string to be added to the hash key. 

It would be useful to have the same option in finders.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
