### ISSUE TITLE
Why Can't I remove the "rewrite.cfm" from the url using LinkTo()???

### ISSUE THREAD

**Issue by mwells3456** [cfwheels/cfwheels#589]
**When I use:**

#linkTo(text="List", controller="Phone", action="lists")#

**it returns in the url as:** http://localhost**/rewrite.cfm**/phone/lists

**Why is that, and how can I fix this??**

**This is what I have in my .htaccess file:**

Options +FollowSymLinks
RewriteEngine On
RewriteCond %{REQUEST_URI} ^.*/index.cfm/(.*)$ [NC]
RewriteRule ^.*/index.cfm/(.*)$ ./rewrite.cfm/$1 [NS,L]
RewriteCond %{REQUEST_URI} !^.*/(flex2gateway|jrunscripts|cfide|cfformgateway|cffileservlet|railo-context|lucee|files|images|javascripts|miscellaneous|stylesheets|robots.txt|favicon.ico|sitemap.xml|rewrite.cfm)($|/.*$) [NC]
RewriteRule ^(.*)$ ./rewrite.cfm/$1 [NS,L]

**Comment by perdjurner** [comment]
I would recommend upgrading to the latest version of Wheels, then if you still have an issue, post on the Google Group (more people will see it there so you have a better chance of getting help).

Thanks.
