### ISSUE TITLE
Getting error when trying to install a plugin "Could not find the ColdFusion component or interface plugins.cfwheels.cfwheels."

### ISSUE THREAD

**Issue by mwells3456** [cfwheels/cfwheels#590]
When I try to download a plugin in the plugins folder while **using the .htaccess code given in CFWheels:**

Options +FollowSymLinks
RewriteEngine On
RewriteCond %{REQUEST_URI} ^.*/index.cfm/(.*)$ [NC]
RewriteRule ^.*/index.cfm/(.*)$ ./rewrite.cfm/$1 [NS,L]
RewriteCond %{REQUEST_URI} !^.*/(flex2gateway|jrunscripts|cfide|cfformgateway|cffileservlet|railo-context|lucee|files|images|javascripts|miscellaneous|stylesheets|robots.txt|favicon.ico|sitemap.xml|rewrite.cfm)($|/.*$) [NC]
RewriteRule ^(.*)$ ./rewrite.cfm/$1 [NS,L]

I get this error:

"Could not find the ColdFusion component or interface plugins.cfwheels.cfwheels."

**IF I USE THIS CODE:**

Options +FollowSymLinks
RewriteEngine On

RewriteCond %{REQUEST_URI} !^.*/(flex2gateway|jrunscripts|cfide|cfformgateway|railo-context|files|images|javascripts|miscellaneous|stylesheets|robots.txt|sitemap.xml|rewrite.cfm)($|/.*$) [NC]
RewriteRule ^(.*)$ /rewrite.cfm/$1 [L]

I don't get the error, but it doesn't download the plugin either. The .zip file just sits there in the folder and is never extracted.
<img width="1437" alt="screen shot 2016-02-11 at 4 44 20 pm" src="https://cloud.githubusercontent.com/assets/10353096/12994629/4c2e2e06-d0df-11e5-9bc7-e5ef1c51619c.png">

**Comment by chrisdpeters** [comment]
Are you able to attach the plugin zip file to this issue?

If not, can you explain in general terms what happens when you unzip the file? Does a subfolder appear, or do you get the plugin's CFC file extracted into the current folder?

**Comment by perdjurner** [comment]
Please sort out the other issue you posted first as it's most likely related. Then open up this issue again if you still have a problem.

Thanks.
