### ISSUE TITLE
Unnecessary 'offset' query when using pagination

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#592]
When using pagination and the number of records returned is less than the perpage value, the 'offset' query runs for no reason..

Eg:
`users = model("User").findAll(perPage=10, page=1)`

This executes the "count" query, the 'find' query... then executes the 'offset' query.

There seems no reason to run the 'offset' query, just return the 'find' query

Wheels 1.4.4
MSSQLServer 2012

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
