### ISSUE TITLE
RenderWith is altering some bigint values

### ISSUE THREAD

**Issue by leeish** [cfwheels/cfwheels#593]
I'm working on creating a isolated example to submit for testing, but I currently have a query object that has two columns with data that is 17 characters in length. They are numeric when pulled from the DB, for example: 10090000000405129. If I output the page as normal (no renderWith), I can dump the data on the page and the value is as stated above.

I have a different controller method that returns data from the same model, even the same method from the model, and returns it to a view using renderWith/ajax and the data is changed by one digit to 10090000000405128. I've dumped the query right before the renderWith method and it's 29 but on the other end when I "receive" the data via ajax it's 28. It's doing it to other large numbers as well.

In my model I casted the column as a char(17) and it came across using renderWith at 29. 

So the renderWith function is somehow altering numeric values. 

More oddly, some come across unaltered, some altered by 1 digit and others for example is changed -151476781488064845 to -151476781488064830 which is 5 digits.

I'm going to quickly try to throw together a isolated function with a manually created query to recreate the issue on demand, but it is happening and I'm checking the data before and after the function call.

**Comment by perdjurner** [comment]
Have you had a look at "Best Practices for Providing JSON" here:
http://docs.cfwheels.org/docs/responding-with-multiple-formats

Maybe if you specify it to render as a string, it would work?

**Comment by leeish** [comment]
That sounds defeatist, and I accept your answer and appreciate your help, but is there a reason this is happening? I did a quick test and at 17 characters the issue starts. At 16, no problem, but at 17 it starts rounding or something strange. 

`<cfset qTest = queryNew('charTest,bigIntTest','VarChar,BigInt') />
<cfset queryAddRow(qTest) />
<cfset querySetCell(qTest,'charTest','12345678901234567') />
<cfset querySetCell(qTest,'bigIntTest',12345678901234567) />
<cfset data = {} />
<cfset data.query = qTest />
<cfset renderWith(data=data,layout="false") />`

**Comment by perdjurner** [comment]
No, don't know, I'll flag this as a bug.

**Comment by leeish** [comment]
This is a custom query I am going with so I used Ben Nadel's QueryToStruct to convert it, then rendered that struct, instead of the query directly, and the the issue persists. The data was converted to an array of structs but those 17 digit numbers still get edited. The "fix" for now is to cast that data in my query as a char, but that can then cause other issues if those queries are used for other things like QoQ. I'll have to then cast on any comparisons, etc. 

If it's just a CFML bug and not a Wheels bug I'm fine with that, but if it's a wheels bug it seems better to get it fixed possibly.

**Comment by perdjurner** [comment]
What data type is the column with these numbers in the database?

**Comment by leeish** [comment]
bigint

**Comment by chapmandu** [comment]
What is returned when you dump SerializeJson(qry)? 

Are you using ACF or Lucee?

**Comment by leeish** [comment]
I just ran a test similar to my comment above but I dumped the query, dumped the serialized query and then dumped the deserialized result, and all act as expected.

If I visit the URL in my browser with ?format=json the displayed json is correct.

If I call the URL with javascript the data is changed.

I am using ACF.

So if you put this in a controller method:

`<cffunction` name="test">
	<cfset qTest = queryNew('charTest,bigIntTest','VarChar,BigInt') />
	<cfset queryAddRow(qTest) />
	<cfset querySetCell(qTest,'charTest','12345678901234567') />
	<cfset querySetCell(qTest,'bigIntTest',12345678901234567) />
	<cfset data = {} /> <cfset data.query = qTest />
	<cfset renderWith(data=data,layout="false") />
</cffunction>`

Then visit the page with ?format=json and call the page via javascript, do you get different results as well? I'm curious if this is something server side in IIS, browser specific, or some combination.

**Comment by leeish** [comment]
Just found this: http://stackoverflow.com/questions/8663298/json-transfer-of-bigint-12000000000002539-is-converted-to-12000000000002540 Seems to be a javascript issue. I guess it's just something I'll have to take into account.
