### ISSUE TITLE
Don't cache queries during a request by default

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#595]
I wonder if we should change this setting so that if you run two identical queries in the same request the query actually executes twice instead of just caching and reusing the first result?

A common problem is that you have a loop where you get an object, make a change and then save it back. This won't work well with caching and you typically have to solve it by passing in reload=true to the finder call.

I've seen this a lot on the Google Group and I even run into it myself quite often.

**Comment by neokoenig** [comment]
Perhaps only with call which would return a model (i.e, not findAll()) ?

**Comment by perdjurner** [comment]
Yes, makes sense for me at least, I've never run into this problem with findAll.

**Comment by chapmandu** [comment]
I rely a lot on the "two identical queries in the same request".. particularly for findAll. Not so much findOne etc..

Would this be considered a breaking change?

**Comment by perdjurner** [comment]
I don't think it would since I can't see how this change could break anyone's code.

**Comment by andybellenie** [comment]
I agree. This has caught me out many times. I am in favour of removing this entirely. If someone needs to reuse a query or model they can save it into a variable. This feature is an overly aggressive and invibsle form of optimisation.

**Comment by andybellenie** [comment]
Just to check, would this change affect the use of dynamic finders, e.g:

````
#post.blog().title#
#post.blog().author#
````

Maybe you could clarify the scope?

**Comment by perdjurner** [comment]
Yes, I think it should affect those as well.

**Comment by andybellenie** [comment]
Hmm I'm not so sure then. It could potentially have a big impact on the performance of existing apps. I think it's a breaking change. If there's 10 such calls in a view (perfectly reasonable and in accordance with the current documentation) then we go from 1 query to 10. That's not trivial.

**Comment by perdjurner** [comment]
Ok, postponing for later.

**Comment by perdjurner** [comment]
Possible improvement:

Instead of storing the query result in `request.wheels`, start storing them in `request.wheels.author` (for an author model) instead.

Then when any query runs that changes the database (INSERT, UPDATE, DELETE), clear the `request.wheels.author` struct.

**Comment by andybellenie** [comment]
This is similar to how Hibernate's secondary cache works, might be worth reading up on

**Comment by perdjurner** [comment]
Done.

With this in place I wonder if the `reload` argument can be removed? There should very rarely be a need to use it now (and there is a new `clearRequestCache()` function that can be used then).

**Comment by andybellenie** [comment]
I agree it is no longer necessary

**Comment by perdjurner** [comment]
I'm keeping `reload` and changing `clearRequestCache` to be private. We can always improve later but the main issue I wanted to address for 2.0 has been taken care of:

> A common problem is that you have a loop where you get an object, make a change and then save it back. This won't work well with caching and you typically have to solve it by passing in reload=true to the finder call.

**Comment by andybellenie** [comment]
The reload argument can still be removed from create, update, and save methods.

**Comment by perdjurner** [comment]
Docs updated.

Setting to 3.0 since that is the earliest we can look at possibly removing the `reload` argument.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
