### ISSUE TITLE
Redirect away from URLs containing `reload=true[&password=mypassword]`

### ISSUE THREAD

**Issue by chrisdpeters** [cfwheels/cfwheels#596]
This is a minor security enhancement.

This would be default behavior for the `production` and `maintenance` environments. This way the `reload` and `password` query params would be less likely to appear in tools like Google Analytics. (See my blog post, [Restrict Key CFWheels URL Variables from Google Analytics](http://www.chrisdpeters.com/restrict-key-cfwheels-url-variables-from-google-analytics/), for reasons why this could be a problem.)

Examples:

/my-controller/my-action?reload=true&password=123456 -> does reload -> /my-controller/my-action

/my-controller/my-action?lastname=har&reload=true&password=123456 -> does reload -> /my-controller/my-action?lastname=har

We could have a setting like `set(redirectAwayFromReloads=true)` that is `false` in `design`, `development`, and `test`. (Sometimes you want to "refresh the reload" while you're working on something in development.)

This would also only apply to `GET` requests with the reload params.

**Comment by neokoenig** [comment]
It's worth pointing out that you do now have to implicitly set `set(allowedEnvironmentSwitchThroughURL=true);` for this to be an issue, and I think the cfwheels default is off - but I agree, a ?reload request show redirect to home or something :)

**Comment by chrisdpeters** [comment]
I still think it would be an issue for someone in marketing to run the reload URL and keep reloading the app, even if they weren't switching the environment in the request (e.g., `reload=true`, not `reload=maintenance`).

And what if they accidentally share a screenshot with someone else containing the reload password?

**Comment by perdjurner** [comment]
@neokoenig Where is that setting? I don't see it.

**Comment by neokoenig** [comment]
Ahhh my bad, this is something which crept into my code from the old `1.2` branch!
Ignore me!!

**Comment by perdjurner** [comment]
Can this go in 1.4.5?

**Comment by chrisdpeters** [comment]
@perdjurner Committed. Can you take a look at this to make sure I didn't break any CF8isms? I have completely forgotten what's allowed vs. not in CF8. :frowning:

Also, a review would be nice to make sure I didn't do something dumb.

Note to self: need to document the new `redirectAfterReload` setting after v1.4.5 goes live.

**Comment by chrisdpeters** [comment]
Documented for v2.0. I believe that we had decided not to put this in 1.4.x since it's a change in functionality that could causes some surprises for users.
