### ISSUE TITLE
Error Element SESSIONMANAGEMENT is undefined in a Java object of type class coldfusion.runtime.StructBean.

### ISSUE THREAD

**Issue by kmd1970** [cfwheels/cfwheels#598]
I am getting the following exception error in wheels 1.4.4

11:45:15.015 - Expression Exception - in C:/inetpub/wwwroot/wheelstesting/wheels/controller/verifies.cfm : line 61

Element SESSIONMANAGEMENT is undefined in a Java object of type class coldfusion.runtime.StructBean.

**App.cfm:**

``` html
<cfscript>
    this.name = "testing." & ReplaceList(trim(cgi.server_name),"_,-",",") ;

        this.loginStorage = "session";
        this.setClientCookies = true;
        this.setDomainCookies = false;
        this.sessionTimeout = CreateTimeSpan(0,0,30,0);
        this.applicationTimeOut = CreateTimeSpan(7,0,0,0);
        this.SessionManagement = true;
</cfscript>
```

**Comment by andybellenie** [comment]
Hi, what version of CF are you using, on what server? Are sessions enabled at the CF server level? I'm guessing this is a CF configuration issue.

**Comment by kmd1970** [comment]
Sorry, I am using CF 11 on local machine and CF 10 on a remote development machine.

I just checked and **Use J2EE session variables** and **Enable Session Variables** are checked and my test page has existing session variables.  Very strange. 

Both servers have the same error. I will continue to debug.

Placing this code on any page generates the error:

```javascript
loc.sessionManagement = application.getApplicationSettings().sessionManagement;
```

**Comment by kmd1970** [comment]
Ok, after a quick google search I found this comment:

```javascript
application.getApplicationSettings().sessionManagement;
```

"CF10 no longer has this value in the getApplicationSettings() returned structure."

http://www.bennadel.com/blog/943-ask-ben-testing-for-coldfusion-session-management.htm (last post)

**Comment by perdjurner** [comment]
application.getApplicationSettings().sessionManagement is inside a try / catch in the Wheels code so it should not cause any problems for you.

Are you getting this error in the browser or just in a log file (which could mean the try / catch logs it but it doesn't actually cause any errors for users)?

**Comment by kmd1970** [comment]
I wouldn't care, however I am getting the message in the browser, under **Exceptions**, directly below **Execution time**. If the try/catch is working, why am I seeing the exception?

http://imgur.com/t3DerT0.jpg

**Comment by perdjurner** [comment]
The code in the try block fails and is logged as an exception in the CF debug area.
This is normal behavior and should not cause any issues for "real" users of your app.
