### ISSUE TITLE
Should filters be cached in development mode?

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#599]
It would appear that controller filters are cached in development mode.

I can understand models being cached.. but developing with cached filters can be a little painful.

Food for thought..

**Comment by perdjurner** [comment]
Do you mean the entire init function or just the filters?

**Comment by chapmandu** [comment]
Good question.. I didn't dig that far in. Is the caching at the controller init function or are the filter functions themselves cached? 

Either way, are there any immediate downsides to not caching these?

**Comment by perdjurner** [comment]
It's only the configuration (i.e. running "init") that is cached (except in design mode where it runs the configuration on every request).

If anything else is happening, it's a bug.

**Comment by chapmandu** [comment]
Certainly not a bug.. more just floating the idea of removing the init caching on controllers as an 'enhancement'. It may have undesired side-effects. I keen to hear others' thoughts?

**Comment by perdjurner** [comment]
You said they are cached in "development" mode though which sounds like a bug to me as I believe the intention is for them to only be cached in "design" mode.

**Comment by chapmandu** [comment]
Definitely cached in "development" mode

**Comment by perdjurner** [comment]
Sorry, I meant the other way around of course, they should be cached in "development" mode but not in "design" mode!

Generally speaking, "design" mode is where the least amount of caching is happening.

Also, I believe you can control this with the "cacheControllerInitialization" setting.

**Comment by chapmandu** [comment]
Oh nice..
