### ISSUE TITLE
variable [$WHEELS] doesn't exist onApplicationStart

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#600]
I see a number of these exceptions during a (deployment) restart of the Tomcat service. It usually only occurs once per startup.. and is generally not seen again until the service is restarted. It specifically when the AWS Elastic Beanstalk health checker ping's an instance to see if it's alive. 

Side note: The latest version of coldroute is installed, though I'm not sure this plugin is relevant as it's not showing in the stack trace..

CFWheels Version
1.4.4
Lucee Version
4.5.2.018

Message:
variable [$WHEELS] doesn't exist

Name:
onApplicationStart

Stack Trace:
wheels.plugins.injection_cfm$cf.call(/var/lib/tomcat8/webapps/ROOT/wheels/plugins/injection.cfm:39)
wheels.global.cfml_cfm$cf.udfCall1(/var/lib/tomcat8/webapps/ROOT/wheels/global/cfml.cfm:111)
wheels.events.onapplicationstart_cfm$cf.udfCall(/var/lib/tomcat8/webapps/ROOT/wheels/events/onapplicationstart.cfm:385)

**Comment by perdjurner** [comment]
Can you put up a blank Wheels app to see if it happens there as well (would rule out it being an issue with your own code or a plugin)?

Thanks.

**Comment by chapmandu** [comment]
I have a feeling this is caused when initialising the coldroute plugin. I would imagine this will be exposed when bringing coldroute into the core #609.

**Comment by chapmandu** [comment]
Perhaps it's not couldroute..

https://groups.google.com/forum/?fromgroups=#!topic/cfwheels/ID2WvFmusQE

**Comment by chapmandu** [comment]
I'm not alone..

https://travis-ci.org/cfwheels/cfwheels/jobs/157088276

**Comment by perdjurner** [comment]
Closing, please reopen if you get this on 2.0.
