### ISSUE TITLE
Incorrect finder results when using "select" and "returnAs"

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#601]
model("something").findAll(include="somethingElse", returnAs="structs", select="id, createdAt")

If id and createdAt exist on both models it will use the properties from the first model for the second as well.

Can be corrected by doing select="id, createdAt, id, createdAt" instead.

Same issue exists when returning objects.
Issue is present for both belongsTo and hasMany.

Needs a failing test added before attempting to fix.

**Comment by zainforbjs** [comment]
@perdjurner Should we just add the included table's name as a prefix to that column to make it distinct?

For example, if a comment table is included, then alias "id" column as "commentid" to make it distinct?

**Comment by zainforbjs** [comment]
@perdj I think this is similar to the issue #580 . 
I created a PR (#1253) for that which also has a test case written. The test is working correctly without breaking any of the others.

Can you have a look at that and see if that fixes this one as well?

**Comment by zainforbjs** [comment]
@bpamiri This has been already fixed in our recent merges, we can close this.
