### ISSUE TITLE
Columns added using afterFind callback not returned in findAll(returnAs="structs")

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#605]
Any additional columns which are created using the afterFind model callback.. eg:

```
// MyModel.cfc
public void function init() {
    afterFind("myCallback");
}

private struct function myCallback() {
    arguments.foo = "bar";
    return arguments;
}
```

The foo column is not returned in a controller findAll call like this:

`myQuery = model("MyModel").findAll(returnAs="structs");`

but IS returned using:

`myQuery = model("MyModel").findAll();`

**Comment by zainforbjs** [comment]
@chapmandu I reviewed the process and it seems like the function **$serializeQueryToStructs** in file **wheels/model/serialize.cfm** is not registering the afterFind callback like it is doing in case of returnAs="object" or returnAs="query".

I made some changes in file to fix this. Added the callback registration of afterFind in the function.

I created a pull request with the fix. https://github.com/cfwheels/cfwheels/pull/1245
