### ISSUE TITLE
Improve Params passthrough for urlFor()

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#608]
Just noting this enhancement request which has come up:

"When I want to paginate a recordset of search results where the search params are variable, I find generating the params argument a bit painful.. I am constantly needing to remove the route,controller,action,page params, then create a querystring of the remaining values.";

Could be better to do : 
`params=true` and / or `params="name1,name2"`

e.g, assuming the `params` struct has `myVar1,myVar2,myVar3` already defined in the request:

`linkTo(route="search", params=true, text="search")`

might result in:

`<a href="/search?myVar1=1&myVar2=2&myVar3=foo">search</a>`

Alternatively in the same page:

`linkTo(route="search", params="myVar2", text="search")`

might result in:

`<a href="/search?myVar2=2">search</a>`

If we do this in `urlFor()` then it should hopefully be able to propagate down to pagination, meaning that you can much more easily paginate responses with say, custom search queries and filtering.

**Comment by chrisdpeters** [comment]
@neokoenig I think this would be nice, but I'm wondering if it would be better to do it as its own separate argument. Your solution assumes that I either want to copy the existing query string or use my own. What if I want to append to the existing one?

Perhaps something like this?

```coldfusion
<cfoutput>
<!--- Keep existing query string. --->
#urlFor(route="search", keepParams=true)#

<!--- Keep existing query string and append another value. --->
#urlFor(route="search", keepParams=true, params="foo=bar")#
</cfoutput>
```

Also, you may be causing yourself a lot of pain using the `params` struct instead of `cgi.QUERY_STRING`.

Here is what I do for `paginationLinks`:

```coldfusion
<cffunction name="$buildSearchParams" access="private" returntype="string" hint="Returns param string to pass into pagination links." output="false">
	<cfargument name="except" type="string" required="false" default="" hint="List of keys to exclude when building the query string.">

	<cfset local.searchParams = "">

	<cfloop list="#cgi.QUERY_STRING#" delimiters="&" index="local.param">
		<cfset local.key = ListFirst(local.param, "=")>

		<cfif
			local.key is not "page"
			and not ListFindNoCase(arguments.except, local.key)
		>
			<cfset local.searchParams = ListAppend(local.searchParams, UrlDecode(local.param), "&")>
		</cfif>
	</cfloop>

	<cfreturn local.searchParams>
</cffunction>
```

Then you can call it like this:

```coldfusion
#paginationLinks(route="search", params=$buildSearchParams())#
```

Looks like the `$buildSearchParams` helper I have there could be the behavior if `keepParams=true`, and `paginationLinks` could by default set `keepParams=true` (which the rest of `urlFor`-based helpers would default it to `false`).

**Comment by chapmandu** [comment]
@chrisdpeters I think the params structure will need to be used in cases where a recordset is a result of params from a form post.. 

I have a very similar helper which acts upon the params scope.. I'll dig it up next time I'm at my computer.

**Comment by chrisdpeters** [comment]
@chapmandu Can you give me an example of when it would ever be a good idea to post to a view that needs to show pagination links? 99% of the time, the request should be via `GET`.

**Comment by chrisdpeters** [comment]
P. S. I found [this to be an interesting solution](http://stackoverflow.com/questions/297470/use-get-or-post-for-a-search-form) for that other 1% and hope to keep it in mind for ridiculously large search forms.

**Comment by chapmandu** [comment]
@chrisdpeters You know what.. After thinking about it, I cannot give you an example. I've just "always done it that way".. You've changed my thinking on search forms..

**Comment by neokoenig** [comment]
The only time I can think of you'd want to POST to a search is when you want to not make the result (easily) book markable.

**Comment by chrisdpeters** [comment]
@neokoenig Right, which really against the HTTP spec and anti-user in my opinion. :smile:

**Comment by neokoenig** [comment]
I'll look into implementing this; I think I'm favouring Chris's `keepParams=true` approach; 

Something like this?

```
// Keep existing query string.  
// Before :  search?q=asd
// After:     search?q=asd
#urlFor(route="search", keepParams=true)#

// Keep existing query string and append another value. 
// Before :  search?q=asd
// After:     search?q=asd&foo=bar
#urlFor(route="search", keepParams=true, params="foo=bar")#

// Remove existing query string, as keepParams would be false by default
// Before :  search?q=asd
// After:     search
#urlFor(route="search")#

// Remove existing query string , as keepParams would be false by default, and replace with implicit value(s). 
// Before :  search?q=asd
// After:     search?foo=bar
#urlFor(route="search", params="foo=bar")#
```

Hopefully this would then filter down to `paginationLinks()`, but as chris mentioned, set the default of keepParams to false - so you could do `#paginationLinks()#` which would then autopickup the query string and append the paging variables. 

Sound good?

**Comment by chrisdpeters** [comment]
It's kind of nice that we just let this sit there for a while so I could take a look at it with fresh eyes.

The thing that jumps out to me is the label `keepParams`, which I don't think is specific enough. The `params` struct is more than just a query string; the query string is a subset of that. So I'm wondering if it should be `keepQueryString` or `keepQueryParams`? Hmm...

**Comment by chrisdpeters** [comment]
Though, on 2nd thought, `keepParams` matches the `params` argument for the helpers.

**Comment by neokoenig** [comment]
Yeah, fair point: it is indeed a subset.. but as you say, not sure if it's worth renaming params= as that would be a major breaking change just for the sake of it!

**Comment by perdjurner** [comment]
I like this idea.

What about when you want to keep all params except one though?
You'd have to pass in a list of params to keepParams, right?

Some other functions in Wheels deal with that same issue by using "except" and "only" arguments.

Wonder if we can use something similar:

params=true, except="something"
params=true, only="something,somethingElse"
params=false

**Comment by chrisdpeters** [comment]
`onlyParams` and `exceptParams`?

**Comment by perdjurner** [comment]
Missed the deadline on this, removing milestone.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
