### ISSUE TITLE
Integrate ColdRoute plugin into core

### ISSUE THREAD

**Issue by chrisdpeters** [cfwheels/cfwheels#609]
It is time. :tada: 

Here is the plugin: [dhumphreys/cfwheels-coldroute](https://github.com/dhumphreys/cfwheels-coldroute)

I propose that only these public methods be ported into the core:

-  `mapper` (obviously)
-  `resources`
-  `resource`
-  `get`
-  `post`
-  `patch`/`put`
-  `delete`
-  `scope`
-  `namespace`
-  `root`

The other methods like `controller` I believe encourage bad practice and controller bloat, and we really need to be forcing developers to consider which HTTP verb they are using for each endpoint in their applications. This becomes even more important with #613.

To "link" to deletes, the default implementation that we'd encourage should be to create a form with a submit button that posts the deletion request. We'd then suggest that developers style the submit button to appear and behave like an `<a>` if that's what they want in the UI.

I'm not sure if it's still there, but I've also witnessed some issues with the RegEx patterns used to lookup routes in certain builds of Lucee 5. I believe Travis will pick those issues up, however.

Note: We may also want to consider adding a deprecation for use of the `addRoute` helper, or adding a required `method` argument that forces the developer to mark it `get` vs. `post` (and perhaps use `patch`, `delete` as options ala ColdRoute as well). It may be time to force the developer to use the new routing helpers though, keeping the community unified.

- [x] Integrate plugin
- [x] Change starter `config/routes.cfm` to have common examples
- [x] Write tests
- [x] Write documentation
  - [x] [Routing](http://docs.cfwheels.org/v2.0/docs/routing) chapter in guides
  - [x] Update [Linking Pages](http://docs.cfwheels.org/v2.0/docs/linking-pages) chapter to demonstrate how to link to new routing structure (encourage only doing `DELETE`s via forms/`buttonTo`)
  - [x] Update [Form Helpers and Showing Errors](http://docs.cfwheels.org/v2.0/docs/form-helpers-and-showing-errors) chapter with new routing structure
  - [x] API docs
    - [x] mapper
    - [x] resources
    - [x] resource
    - [x] get
    - [x] post
    - [x] put
    - [x] patch
    - [x] delete
    - [x] root
    - [x] wildcard
    - [x] namespace
    - [x] scope
    - [x] end
- [x] Remove `addRoute` and add to upgrade guide
- [ ] Separate CFWheels UJS plugin for allowing `DELETE`s via links and for grabbing CSRF token for AJAX requests
- [x] Rewrite `wildcard()` mapper to limit methods allowed
- [x] Remove `Path` and `Url` helpers
- [x] Change `module` terminology to `package`
- [x] `package` scoping method
- [x] Rename `drawRoutes()` to `mapper()`

**Comment by chrisdpeters** [comment]
@cfwheels/core-team How do you think we should handle the existing `addRoute`? Should we keep it in the core or require the upgrade path to the new routing helpers?

If we keep it in the core, I think we should add a required `method` argument that forces the developer to choose which HTTP method is allowed for the request. (Perhaps it could also accept a list like `addRoute(name="authenticate", controller="sessions", action="create", methods="get,post")` that forces the developer to opt into a foolish path if they really want it.)

My opinion is to be opinionated and ditch `addRoute`, but perhaps that's an indication that we should deprecate it until 2.1 or 3.0?

**Comment by perdjurner** [comment]
I have no problem with ditching it.

**Comment by neokoenig** [comment]
yeah, hammertime.
We will need to document this well with *lots* of examples though.

**Comment by chapmandu** [comment]
Ditch it..

**Comment by chapmandu** [comment]
What do you think about renaming drawRoutes() to addRoutes() so it resembles the obsolete addRoute() function?

**Comment by perdjurner** [comment]
I do like "add" better than "draw" in general.

**Comment by chrisdpeters** [comment]
Rails has it like this, which is why I think Don chose the name:

```ruby
Rails.application.routes.draw do
  resources :users
end
```

Anyway, I'm good with `addRoutes`.

**Comment by liferealized** [comment]
@chrisdpeters I'm going to create a new branch to start on this and will comment further about your suggestions once I've dug in and reviewed.

**Comment by chapmandu** [comment]
@lifrealized On the subject of regex.. I've had a few occurrences of coldroute failing ungraciously when a single quote is added to the end of a route pattern. 

Eg: `/foo'`

**Comment by liferealized** [comment]
@chrisdpeters If I'm understanding you correctly, you want to remove the ability to disable restful-ness and http methods?

**Comment by liferealized** [comment]
@chapmandu I'll add some tests to see what happens

**Comment by liferealized** [comment]
Here is where I'm at so far -> https://github.com/liferealized/cfwheels/commits/coldroute

More tomorrow.

**Comment by chrisdpeters** [comment]
@liferealized Correct. We need to strongly encourage developers to think about HTTP verbs. If they want to define everything as `get`, then fine, but that's something that they're opting into by explicitly calling `get`.

**Comment by chrisdpeters** [comment]
"Secure by default."

**Comment by liferealized** [comment]
Ok. since mapper.controller() is only a scoping mechanism, I would think that it can stay.

As far as the restfulness and http methods settings in the mapper, by default they are both set to true so the routing mapper is both restful and uses http verbs. The settings are there though so that a developer *could* opt out of both, falling back to the wheels old style if necessary.

Does this work for "secure by default"?

**Comment by chrisdpeters** [comment]
@liferealized Yes, that will work well.

Honestly, I don't understand the purpose of `mapper.controller`. Why was that added when it doesn't exist in Rails? My preference would be to leave it out of core.

**Comment by liferealized** [comment]
`mapper.controller` is a helper function to `mapper.scope` that allows all nested calls to inherit what you set with it. We can certainly take it out if you would like, but I do not see it as necessarily being bad.

**Comment by chapmandu** [comment]
I've found the current coldroute plugin causes some problems when unit testing controllers. It appears that when testing a namespaced controller, the controller's `init()` function is not invoked.

My workaround for this is below, but took much head scratching and bothering of @rip747 to discover.

```
_params = {
  controller=arguments.controller,
  action=arguments.action
};
actual = controller("Users", _params);
actual.init();	// this is a workaround.. testing coldroute namespaced controllers doesn't call the controller's init method
actual.$processAction();
```

**Comment by liferealized** [comment]
Ok. Just want to make sure that I have the facts straight.

* `init()` is not called only for unit testing
* `init()` is called during a web request
* in both instances, the method `controller()` is being used

@chapmandu Could you please explain further what you mean by "namespaced"? Are you referring to controllers that are nested under the controllers folder like `controllers/admin/Controller.cfc`?

**Comment by liferealized** [comment]
For anyone who is watching, the `linkTo()` method in coldroute overrides the default functionality for `arguments.confirm` to make it a data attribute instead of putting JS into the onclick attribute. This will clearly break old functionality unless wheels defaults to including a JS library to make these work.

I guess I'm looking for opinions on the way forward here. Mine would be to make thing unobtrusive and break old habits. Since this is part of 2.0, now would be the time to do it.

**Comment by andybellenie** [comment]
+1

**Comment by perdjurner** [comment]
If I remember correctly I think we've decided to just get rid of all JavaScript code in 2.0.
Possibly replace with plugins instead.

**Comment by liferealized** [comment]
i guess this means you'd also like to get ride of `arguments.spamprotection` in `startFormTag()` as well?

**Comment by perdjurner** [comment]
Yes.

**Comment by chrisdpeters** [comment]
It would be good to break any of the JS-powered stuff into a "CFWheels UJS" plugin.

**Comment by liferealized** [comment]
There is a test in `dispatch.$request` named `test_route_without_format_should_ignore_fullstops` that asserts that a route should match `/users/foo.bar` to a username. I believe this test should fail and be changed/removed due to formats being an integral part of coldroute.

Specifically, the test should add a constraint to the match so that the variables username should be replaced when creating the regex to match without taking a dot into account.

Does anyone else have any opinions on this?

**Comment by liferealized** [comment]
I've updated test and I think it should be -> https://github.com/liferealized/cfwheels/commit/69d85097e7a366b59ac54c3a1e9e18f005ede288#diff-2c582cf709a0d9083ec7038ea58bdfa6R48

**Comment by liferealized** [comment]
Maybe I need to sleep on this one, but is there any reason to have the ability to turn url rewriting off anymore?

**Comment by chrisdpeters** [comment]
That's actually a really good question. It seems that this would require at least partial URL rewriting.

**Comment by neokoenig** [comment]
The one time I've found it useful is for open source apps, where I wanted to force URL rewriting off, as all there were multiple hard coded Jquery calls in the app, which would have broken with URL rewriting on; I appreciate that's a bit of an edge case though :)

**Comment by chrisdpeters** [comment]
Technically, you could still get to a controller and action without URL rewriting on, right?

```
PATCH /index.cfm?controller=admin.users&action=update&key=1234
```

Or?
```
PATCH /index.cfm?controller=admin/users&action=update&key=1234
```

**Comment by chrisdpeters** [comment]
Not sure that Wheels could enforce the `PATCH` there though. You'd lose that.

**Comment by liferealized** [comment]
After thinking about this a little more, we could possibly do something like

`/index.cfm?route=adminUsers&key=1234`

Where we only allow a route to be set via the url when rewriting is off. This way nothing would change with the structure of a route, we'd only skip `$findMatchingRoute` when in dispatch, just validating that the route exists.... maybe....

**Comment by liferealized** [comment]
I must say this is the first big wrinkle that I've found porting this over. So close!

**Comment by chrisdpeters** [comment]
That's true if you're passing `route` in the URL instead of `controller`/`action`.

**Comment by liferealized** [comment]
I'm definitely sleeping on this and will come up with some tests in the morning.

**Comment by chapmandu** [comment]
@liferealized Regarding `init()` not being called when creating an instance of a controller.. Having looked into this, I can't say for sure whether this is specific to coldroute, as I have never unit tested controllers without coldroute. 

Here are the proposed wheels 2.0 docs for testing controllers..
http://docs.cfwheels.org/v2.0/docs/testing-your-application#testing-your-controllers

This may just be a matter of having to require calling `init()` on the controller if one wants to test controllers.. Thoughts?

**Comment by liferealized** [comment]
So sleeping helps everything. No problems exist and the coldroute branch now has 100% current tests passing. Need to add some more testing from my notes, but we seem to be close.

**Comment by liferealized** [comment]
If any wants to checkout the branch and play around, you'll notice a new link in the debug section "View Routes" that will show you all of the routes loaded into the application scope. This is similar to the coldroute functionality but I've added in the regex that the mapper creates so that a developer can see the matching used and validate that the regex is valid if necessary.

**Comment by liferealized** [comment]
merge request submitted. 

I've taken the liberty of adding URL globing functionality into routing. This allows you to match multiple url segments with a single variable. Example:

`match(pattern="books/*[seoslug]/[key]")`

`match(pattern="*[before]/foo/*[after]")`

I only see a few features that could still be added, but should probably have feedback on first.

* Should we add redirecting directly into routes? aka `match(pattern="/photos/*[anything]" redirectTo="/images/*[anything])"

**Comment by perdjurner** [comment]
> Should we add redirecting directly into routes? aka match(pattern="/photos/*[anything]" redirectTo="/images/*[anything])

I like that feature.

**Comment by neokoenig** [comment]
Whilst you're looking at this, can I throw in a curve ball? One of the routing things on the *box frameworks that I do like is the ability to specify an integer within the route:

> ColdBox gives you also the ability to declare numeric only routes by appending -numeric to the variable placeholder so the route will only match if the placeholder is numeric.
> /blog/:year-numeric/:month-numeric?/:day-numeric?

Which might equate to 

```
match(pattern="books/[action]/[key-numeric]")
```

Or perhaps we could do it like

```
// Force key to be an integer
match(pattern="books/[action]/[key:int]")
// Force key to be a string
match(pattern="books/[action]/[key:string]")
```

The reason this is so useful, is that it not only saves you having to constantly check `key` is numeric, but also means you can more easily alias ses style routes with the same base, i.e

```
/books/view/125/
/books/view/my-book-name/
```

Thoughts?

**Comment by chapmandu** [comment]
+10 for route parameter typing

**Comment by andybellenie** [comment]
👍

**Comment by andybellenie** [comment]
One issue here is what happens if the key is not of the correct type. Throw an error? Display the 404 page? Some control here is useful.

**Comment by neokoenig** [comment]
I think the route should either just not match: that way you could still end up at the catchall route?

**Comment by liferealized** [comment]
@neokoenig @chapmandu @andybellenie great news on this front. Since the router now matches all incoming urls based on regex, you have the ability to craft routes that can do exactly what you are asking for. I'll give an example.

```coldfusion
drawRoutes()
  .resources(name = "user", constraints = { key = "\d+" })
.end();
```

The above will get you routes for the Users controller and any of the routes created that need a key will only match digits for that key. For example `users/asdfd/edit` would NOT be matched and would create a Wheels.RouteNotFound error (404 in production) while `users/1234/edit` would be matched successfully.

Since coldroute was nearly a direct port of the rails 3 routing update, you can read all about the features of our new routing system @ http://guides.rubyonrails.org/routing.html

**Comment by liferealized** [comment]
> I like that feature.

Anyone else care to have redirects directly in routing?

**Comment by chrisdpeters** [comment]
@perdjurner Hope you don't mind my reopening. I'll assign to myself and take on some of those check boxes in the project description. Especially important is documentation.

**Comment by perdjurner** [comment]
Yeah, no problem, didn't realize that merging would close this issue actually.

**Comment by liferealized** [comment]
@chrisdpeters I was hoping to get your help with documentation!

**Comment by chrisdpeters** [comment]
You've got it!

**Comment by chapmandu** [comment]
@liferealized FYI There was mention from Don Humphrey some time ago that some colleagues of his had made significant performance improvements to coldroute and he was going to see about open sourcing these updates.. I don't know where that ended up. 

https://groups.google.com/forum/m/#!topic/cfwheels/b2vVHRRLqUw

**Comment by liferealized** [comment]
@chapmandu I've reviewed the code and matching on url patterns is happening sub 5 milliseconds. Building the routes takes about 100ms BUT this happens during reload which shouldn't be too big of an issue.

Either way, I've posted a comment on that thread to see if there is any update.

**Comment by liferealized** [comment]
@chapmandu after looking that the thread more, I can see where the optimization was. Currently for a resource, the mapper creates 14 routes. I can probably bring this down considerably with some more regex magic. 

I'll put together some tests in the morning to recreate Don's situation and make sure that matching stays fast.

**Comment by liferealized** [comment]
Should we now have a method param omnipresent in the params similar to route/controller/action?

@chapmandu I've added tests for dispatch that creates over 4k routes in `application.wheels.routes` and I find matching to be done in acceptable amounts of time. My computer is pretty beefy though so I may get better performance than others.

**Comment by dbelanger** [comment]
Hey guys.  I'm testing the new routing (quite thoroughly indeed) and I'm getting errors while testing nested namespaces on IIS.  They work perfectly on Apache but for some reason, I keep getting 404s on IIS.  Here's a [link](https://groups.google.com/forum/#!topic/cfwheels/K1keLO1a4z4) to the google group topic.  I wasn't sure whether to post it there or here.

**Comment by chrisdpeters** [comment]
First stab at documenting the new routing functionality can be found in the newly-updated [Routing Requests chapter](http://docs.cfwheels.org/v2.0/docs/routing-requests).
