### ISSUE TITLE
Strong Parameters

### ISSUE THREAD

**Issue by chrisdpeters** [cfwheels/cfwheels#610]
CFWheels and its documentation currently does little to discourage mass assignment vulnerabilities.

Consider a simplistic user object with 2 properties: `name` and `isAdmin`. Let's say that we want for unprivileged users to be able to edit their own `name`, but we don't want for them to mess around with the `isAdmin` property. Yes, we can restrict anyone from mass-assigning `isAdmin` using `accessibleProperties` or `protectedProperties`, but this becomes a major PITA once your model grows in complexity.

Enter [Strong Parameters](https://github.com/rails/strong_parameters). Rather than centralizing mass assignment rules in the model, the decision is made by each controller, which is the layer that is supposed to have all of the authentication/authorization knowledge anyway.

We can then have an `admin.users` controller that permits editing of `isAdmin`:

```javascript
component extends="controllers.Controller" {
  function init() {
    super.init();
    filters(through: "authorizeAccess");
  }

  function update() {
    user = model("user").findByKey(params.key);

    if (user.update(userParams())) {
      // ...
    }
  }

  private function userParams() {
    return params.require("user").permit("name,isAdmin");
  }
}
```

The less-privileged `profiles` controller only allows updating `name` and will ignore any attempts to change `isAdmin`:

```javascript
component extends="Controller" {
  function update() {
    user = model("user").findByKey(params.key);

    if (user.update(userParams())) {
      // ...
    }
  }

  private function userParams() {
    return params.require("user").permit("name");
  }
}
```

Authorization logic could also be used to define which properties are allowed to be modified. Any logic really:

```javascript
private function userParams() {
  local.props = ["name"];

  if (hasPermission("modify-user-isAdmin")) {
    ArrayAppend(local.props, "isAdmin");
  }

  return params.require("user").permit(ArrayToList(local.props));
}
```

This will change the controller so that `params` is initialized as an object instead of a struct. Because the keys will still be set as public properties, it should "feel" similar to the CFWheels 1.x `params` struct. The main difference is that the model will be picky about what can be passed in via `setProperties`, `new`, `create`, `update`, and similar methods.

TODO:

- [ ] Implement new `params` object with methods `require` and `permit` (and perhaps anything else that may be useful from Rails's implementation)
- [ ] Integrate into model (perhaps the `setProperties` method) to enforce use of `permit` to whitelist allowed properties
- [ ] Create a setting to turn this on or off - default to on for new version of CFWheels
- [ ] Deprecate `accessibleProperties` and `protectedProperties` model initializers
- [ ] Write tests
- [ ] Update all documentation involving controllers to use strong parameters

I will be authoring this as a [plugin](https://github.com/liquifusion/cfwheels-strong-parameters) to start with so I can use in our 1.4 apps. This gives us the option to play around with the functionality and decide if it should ultimately land in the core.

**Comment by chrisdpeters** [comment]
First draft: [liquifusion/cfwheels-strong-parameters](https://github.com/liquifusion/cfwheels-strong-parameters)

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
