### ISSUE TITLE
CSRF Protection

### ISSUE THREAD

**Issue by chrisdpeters** [cfwheels/cfwheels#613]
If all goes well with our [CSRF Protection plugin](https://github.com/liquifusion/cfwheels-csrf-protection), we may want to implement this for the next major release.

Suggested task list if we decide to go forward with this:
- [x] Integrate into core
- [x] Add call to `protectFromForgery` to default `controllers/Controller.cfc` file included in framework zip
- [x] Add call to `csrfMetaTags` to default `views/layout.cfm` file included in framework zip
- [x] Write tests
  -  [x] Write tests for including token as `X-CSRF-Token` HTTP header
- [x] Write documentation
  -  [x] `protectFromForgery`
  -  [x] `csrfMetaTags`
  -  [x] `authenticationTokenField`
  -  [x] Upgrading - add `protectFromForgery` to controllers/Controller.cfc, add `csrfMetaTags` to layouts, configure AJAX calls to post with `X-CSRF-TOKEN` HTTP header
- [x] Add config settings for storing `authenticityToken` in session (default) or encrypted cookie
  - [x] Implement in plugin first (liquifusion/cfwheels-csrf-protection#4)
  - [x] Document new `csrf*` settings in Configuration and Defaults chapter
  - [x] Implement cookie storage adapter
- [x] Make arguments for `protectForForgery` configurable via `set`
- [x] Update CHANGELOG

**Comment by chrisdpeters** [comment]
Added related `isOptions` and `isHead` methods in 8a81e85c62ba700eafb119240d6a20ec7a4211a4. Work on this has begun!

**Comment by chrisdpeters** [comment]
Docs for [`protectFromForgery`](http://docs.cfwheels.org/v2.0/docs/protectfromforgery)

**Comment by chrisdpeters** [comment]
Docs for [`csrfMetaTags`](http://docs.cfwheels.org/v2.0/docs/csrfmetatags)

**Comment by chrisdpeters** [comment]
Docs for [`authenticityTokenField`](http://docs.cfwheels.org/v2.0/docs/authenticationtokenfield)

**Comment by chrisdpeters** [comment]
Start to [upgrading instructions](http://docs.cfwheels.org/v2.0/docs/upgrading). After I get things a little more solidified, I'd like to move the info from the plugin page into the core docs.

**Comment by chrisdpeters** [comment]
I'm happy to report that I finally have a cookie adapter implemented in [v0.1.0](https://github.com/liquifusion/cfwheels-csrf-protection/releases/tag/v0.1.0) of the plugin. Now I will work to port this to the core, write tests, and finish up the docs.

**Comment by chrisdpeters** [comment]
(I also want to "battle test" this new cookie adapter in our production apps as well. If there are any problems, we usually learn of them pretty fast.)

**Comment by chrisdpeters** [comment]
Docs for new settings:
http://docs.cfwheels.org/v2.0/docs/configuration-and-defaults#csrf-protection-settings

**Comment by chrisdpeters** [comment]
This has now landed in master! 🎉 

I don't have time to look into the failing tests. The ones I looked into didn't make any sense.

**Comment by neokoenig** [comment]
I managed to kick your tests through - passing!

**Comment by chrisdpeters** [comment]
I'm sure you've explained before, but remind me what I need to do when I run into a situation like that?

**Comment by neokoenig** [comment]
RDP in, open chrome and click on the "Redeploy" bookmark, then to be sure, click on the CF10 tests bookmark which will run them locally: I usually find it good to run them locally just to check it not throwing any genuine failures: then restart the test from Travis.

**Comment by chrisdpeters** [comment]
@neokoenig Thanks!
