### ISSUE TITLE
Add Array support for flash message scope

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#615]
`flashMessages()` only checks for simple values to display and just use a simple struct-key

It's very useful to be able to do the equivalent of:

```
errorArray=[];
arrayAppend(errorArray, "Something happened here");
... snip...
arrayAppend(errorArray, "Something happened over here too");
.. more code...
arrayAppend(errorArray, "And here..");
flashInsert(error=errorArray);
```

Where flashMessages() is clever enough to look for an array and create a `ul` with child `li` elements for each message if it's not a simple value.

**My question is, do people use the flash to store complex data for other reasons? Is there a reason we can't output an array this way?**

I have this working in a plugin, but wanted to see whether the array issue is a deal breaker.
###

**Comment by perdjurner** [comment]
If people do use it for complex data they wouldn't use flashMessages() to display it anyway, right?

**Comment by neokoenig** [comment]
Ah, but you're assuming that they don't use flashMessages() and use a custom system or individual keys to output their stuff.

But let's say they're using arrays for "something else" but still using flashMessages(): If you suddenly put array support in, and flash messages starts displaying that array data , that could be bad depending what they're storing. I have *no* idea if anyone actually does this though.

**Comment by perdjurner** [comment]
I see, yes, could be bad.

I don't know if it's common but I remember seeing someone on the Google Group that used it for complex data.

**Comment by kmd1970** [comment]
I second this! :+1: 

I recently had a need to store (and later display) more than one flash message at a time, then pass the output to Toastr (js) notifications for display. 

https://codeseven.github.io/toastr/

Toastr has 4 built-in notification types success, info, warning and error. I can use those values as `flashinsert()` keys, but what if wanted to display 2 error messages or 2 info messages at the same time? Currently, `flashinsert()` uses structs, so creating two messages with the same "error" or "info" key won't work. 

That's why I created `FlashAppend()`

Basically it checks the flash for a duplicate key value and increments and appends a number automatically (error, error1, error2, info1, info2, etc) before adding to the struct.

 usage (display 2 info messages at once) :
```javascript
<cfset flashAppend(key="info", message="Record created")>  
<cfset flashAppend(key="info", message="Email sent.")>  
```

```javascript
 <cffunction name="FlashAppend" access="public" output="true"  hint="appends a message to a flash">
    <cfargument name="key" type="string" required="yes"  hint="Flash key" />
    <cfargument name="Message" type="string" required="yes"  hint="Message" />
    <cfargument name="Title" type="string" required="no"  hint="Title" default="" />
    
	<cfscript>
      local.search = 0;
	  local.next = '';
	  local.keylist = '';
  
	  if(flashcount() gt 0 ){
		local.flashes = flash();
	    local.keylist = ReReplaceNoCase(Structkeylist(local.flashes),"[^A-Z,]","","ALL");
		local.search = ListValueCountNoCase(local.keylist,arguments.key);
		if(local.search){
		 local.next = (local.search + 1);
		}
		argumentCollection[arguments.key&local.next] = { message = trim(arguments.message), title = trim(arguments.title)};
	    flashInsert( argumentCollection = argumentCollection  );
	  }else{
		argumentCollection[arguments.key] = { message = trim(arguments.message), title = trim(arguments.title)};
	    flashInsert( argumentCollection = argumentCollection  );
	  }
    </cfscript>
    
   </cffunction>
 ```

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
