### ISSUE TITLE
Ability to map the wheels folder outside of webroot

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#616]
No idea if this is even do-able yet, but will attempt to give it a go. It might be easy, or not.

Marking this as a potentially breaking change, as it will probably involve editing the root `root.cfm`,`index.cfm` and `application.cfc` files, and may well involve some application level mappings etc; not sure yet.

The idea would be that you could have wheels outside the webroot (or wherever), and possibly add configurations for additional mappings for other folders (maybe). We already have mappings for stylesheets + javascripts, so would need to evaluate the need for others.

Important note: I'm proposing that this would be a change via some configuration, where the default is as current, with wheels in the webroot, so 90% of the time that's probably what people will want.

**Comment by neokoenig** [comment]
Had a (very) quick stab at this. There's a *lot* of including going on which is all folder relative. This causes issues as you can't use absolute paths in `cfinclude` ; other issues are root component locations outside the wheels folder, (i.e, `controllers/Wheels.cfc`) which reference wheels.

So do we think my best plan of attack is to:
- Define as close to the beginning as humanly possible, a struct with all the relative paths to important folders (which, as it's outside the webroot, could be user configured) and try and go from there, OR
- Set everything up as an application mapping?

The latter seems to fail when you want to use dot notation, i.e wheels.plugins etc .

Any particular thoughts for the best approach here?

**Comment by perdjurner** [comment]
User configured options sounds like the best approach.

**Comment by neokoenig** [comment]
hmm. This is tricky. Current approach is that I've got a function which generates the relative URL of any two given absolute URLs: so each include call now has to be replaced with the function IF the include is outside it's mapped folder...and as I'm trying to make it so that any folder can "be" anywhere, it just means "relative" now has to go back to the this/application preferences of absolute paths each time. Fiddly.

**Comment by neokoenig** [comment]
Going to give up on this, as it's too much work for 2.x ; maybe can add this later, but there's just too much on for now.
