### ISSUE TITLE
Setup edge docs for 2.0

### ISSUE THREAD

**Issue by chrisdpeters** [cfwheels/cfwheels#617]
Does Readme.io allow you to fork existing docs for a 2.0 version? May as well get that into place so we can start picking at it.

**Comment by neokoenig** [comment]
Yep. And you can assign it as beta;
But it *is* a fork, and I'm not sure you can resync from upstream, so once created, changes *may* have to be done in two places if appropriate.

**Comment by chrisdpeters** [comment]
@neokoenig I think that would be OK. We'll continue to support 1.4 docs until we decide to stop backporting security/bug fixes to it.

**Comment by neokoenig** [comment]
okey doke,http://docs.cfwheels.org/v2.0 now exists, and i've added a version switcher (the version is marked as Beta).

**Comment by chrisdpeters** [comment]
:+1:
