### ISSUE TITLE
Auto-generated model property labels should drop "ID" from end

### ISSUE THREAD

**Issue by chrisdpeters** [cfwheels/cfwheels#618]
If a property is set up as `userid`, for example, the auto-generated label should be "User," not "User Id."

If the column is called `id`, then it should be displayed as "ID" (all caps).

I understand that this could lead to some erroneous labels, but I think it would be an edge case. (Trying to think of a word that ends with `id` where it would break: `lid`, `hid`, `amid`, `squid` `quid`, `slid`. Not many examples.) I'm still going to label this as breaking though because there's always something I haven't thought of.

**Comment by andybellenie** [comment]
Can we re-open this until the suggested change is complete?

**Comment by chrisdpeters** [comment]
@andybellenie I tried addressing the issues in your comments on b330990db9923a08c10173f4ee1278e67799848e and couldn't quite get at the info that I needed to inspect associations in that stage of initialization. Would you have any interest in looking at this?

**Comment by andybellenie** [comment]
Ok

**Comment by perdjurner** [comment]
Need to look at this before RC 1.

**Comment by andybellenie** [comment]
Sorry for slow response, not working much atm

I've created a pull request
