### ISSUE TITLE
Split plugins chapter into 2 separate chapters

### ISSUE THREAD

**Issue by chrisdpeters** [cfwheels/cfwheels#624]
http://docs.cfwheels.org/docs/using-and-creating-plugins

Split into these separate guides:

-  Installing and Using Plugins
-  Developing Plugins

**Comment by chapmandu** [comment]
http://docs.cfwheels.org/v2.0/docs/installing-and-using-plugins
http://docs.cfwheels.org/v2.0/docs/developing-plugins
