### ISSUE TITLE
Mark properties argument as required in validatesUniquenessOf docs

### ISSUE THREAD

**Issue by chrisdpeters** [cfwheels/cfwheels#625]
Just wanted to make sure that I didn't miss anything. But isn't the `properties` argument required in `validatesUniquenessOf`?

http://docs.cfwheels.org/docs/validatesuniquenessof

Make sure that the v1.4 and v2.0 docs are both updated since it is now forked.

**Comment by chrisdpeters** [comment]
@perdjurner Is this just a typo that I can fix?

**Comment by perdjurner** [comment]
Correct, "properties" is required.

However, you can also use "property" which isn't documented.

Also, this is missing for all validation helpers it seems, not just validatesUniquenessOf().

**Comment by chapmandu** [comment]
Documented in both versions.
