### ISSUE TITLE
Failing tests on ACF10 Windows

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#626]
I need to test that the page has set an appropriate http response code;
This works on lucee/Java8 windows, but fails on our test box:

`getPageContext().getResponse().getStatus()` (equals 404 or whateveer)

What's the 'safe' equivalent of this?

Commented out tests are here: https://github.com/cfwheels/cfwheels/blob/master/wheels/tests/controller/provides/renderwith.cfc

**Comment by perdjurner** [comment]
I don't see any obvious way to get this on CF 8 (which is what I had available to test with).

**Comment by neokoenig** [comment]
Fixed! needed to use getFusionContext() for ACF
