### ISSUE TITLE
CFWheels UJS Plugin

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#627]
This is to remove any javascript from the core.

What will the plugin be called?
Should it be owned by the cfwheels organisation?

**Comment by neokoenig** [comment]
"jsconfirm" or something?

Owned by cfwheels should be fine.

**Comment by chrisdpeters** [comment]
@chapmandu See my last check box in #609.

This should probably be modeled after [rails/jquery-ujs](https://github.com/rails/jquery-ujs). We'd probably want to name it `jquery-cfwheels`, similar to `jquery-rails`. Heck, it could probably be a copy and paste of [`rails.js`](https://github.com/rails/jquery-ujs/blob/master/src/rails.js). Just need to make sure that the markup generated by the plugin is the same.

Anyway, I'd recommend waiting until #609 is further along. (Haven't started but will get moving soon.)

**Comment by chrisdpeters** [comment]
Note from @liferealized in #691:

A cursory glance shows these methods being effected.

-  startFormTag
-  buttonTo
-  linkTo
-  buttonTag
-  submitTag

**Comment by chapmandu** [comment]
I think this issue is divided into 2 parts, one is a plugin to re-implement the removed javascript

https://github.com/chapmandu/confirmerdisabler

and second is a UJS plugin for impelementing javascript "data-*" attributes?

**Comment by chrisdpeters** [comment]
@chapmandu Ahh, right. Perhaps I should reopen that other issue. Sorry about hijacking this issue.

Perhaps we should keep this issue about the "obtrusive" solution, and I'll re-open the other one?

**Comment by perdjurner** [comment]
These plugins should take care of the `confirm` and `disable` code.
https://github.com/perdjurner/cfwheels-js-disable
https://github.com/perdjurner/cfwheels-js-confirm

But what's the status for:

> second is a UJS plugin for impelementing javascript "data-*" attributes

?

Setting to RC 1.

**Comment by perdjurner** [comment]
@cfwheels/core-team I'm closing this since we have a solution without JavaScript documented here: https://guides.cfwheels.org/v2.0/docs/linking-pages#section-linking-to-a-delete-action.

Please reopen if I'm wrong.
