### ISSUE TITLE
Call custom validation functions and pass the property name as argument 

### ISSUE THREAD

**Issue by tapirus** [cfwheels/cfwheels#630]
Wouldn't it make sense to extend Wheels 2.X to have the possibility to call custom validation functions and pass the property name as argument to it?
like

validate(method="checkPhoneNumber", property="phonenumber");

[https://groups.google.com/forum/#!topic/cfwheels/917rIx7w7y4](url)

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
