### ISSUE TITLE
Problem with afterFind / findAll

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#632]
See this:

https://groups.google.com/forum/#!topic/cfwheels/nKM8X4sVp0Y

Appears to be happening on CF 2016.

**Comment by perdjurner** [comment]
Did some testing on this...

This works fine:
arguments.enrolledat = DateAdd("yyyy", 1, arguments.enrolledat);

This does not work:
arguments.enrolledat = DateFormat(arguments.enrolledat, "mm/dd/yyyy");

In CF 2016, it looks like you can only write back values of the same type as the query column.

**Comment by chrisdpeters** [comment]
@perdjurner Can you use `JavaCast` to cast the value back to a date? I assume that `DateFormat` returns a string.

**Comment by chrisdpeters** [comment]
@perdjurner (Deleted my last dumb comment.)

This is another good reason to do date formatting in the view layer instead of the model layer.

**Comment by perdjurner** [comment]
Well, I think the real problem is that the dev reporting this really wanted it to be a string, not a date (for use in a form).

**Comment by perdjurner** [comment]
> This is another good reason to do date formatting in the view layer instead of the model layer.

Yep, going to close this as not a bug I think, just unfortunate that it changed from CF 11 to CF 2016.

**Comment by perdjurner** [comment]
Add a line about this in the docs.

**Comment by chrisdpeters** [comment]
You can note that we plan on fixing this in #633.

**Comment by perdjurner** [comment]
Added a "callout" here:
http://docs.cfwheels.org/v2.0/docs/object-callbacks
