### ISSUE TITLE
QoQ Throwing error only in production and maintenance.

### ISSUE THREAD

**Issue by leeish** [cfwheels/cfwheels#634]
I've got a QoQ like the following in my model for a custom method:

```
SELECT
    tbla.id
    ...
    tbla.startTime,
    ...
FROM tbla, tblb
WHERE tbla.id = tblb.id
ORDER BY tbla.startTime
```

In design, development, and testing no error. When I load the page in production or maintenance I get an error page/email from the system but the Error: is blank. When I put a try/catch around the QoQ the error I get is java.lang.ArrayIndexOutOfBoundsException.  Why would a QoQ act different in those two environments. I can fix the issue by changing ORDER BY tbla.startTime to ORDER BY startTime.

Now that it's throwing an error I'm not even sure which is the correct Query of Query syntax for ordering on a joined QoQ but regardless why an error in one environment but not the other.

**Comment by chrisdpeters** [comment]
@leeish This is a long shot, but can you update your code snippet to include the entire method? There may be something about the context of how you're running this query that could further help us understand what's going on here.

**Comment by chrisdpeters** [comment]
It's been over a week with no response. I will reopen if you can provide more details.

**Comment by leeish** [comment]
Sorry. Please close for now. Very busy with new application. When I circle back I may provide an update. Thanks.
