### ISSUE TITLE
Error: 22

### ISSUE THREAD

**Issue by leeish** [cfwheels/cfwheels#637]
Not sure what to think of this at the moment. My error email from wheels just says Error: 22. The Location of the error points to lines of code but they seem unrelated to each other.

Example:

Line 863 in models\Quiz.cfc
Line 328 in controllers\Center.cfc
Line 319 in controllers\Center.cfc
Line 285 in controllers\Center.cfc

Line 285 is a closing </cfif> tag.
Line 319 is a <cfset renderPage
Line 328 is a call to a custom model method. (which by the way is inside an if block that wouldn't be run if it was trying to run line 319.
Line 863 in the model is a QueryAddColumn function.

Like the error lines don't really act like they are tracing anything.

**Comment by chapmandu** [comment]
You might have better luck with replies posting this to the cfwheels google group perhaps with some code samples and a little more info about your environment.

**Comment by leeish** [comment]
I can't ever post on there. It's just gives me a strange error every time I try to post or comment. I don't know if I'm supposed to be added somehow or what. Sorry.

**Comment by perdjurner** [comment]
Just send an email to cfwheels@googlegroups.com.
