### ISSUE TITLE
add arguments for styling buttonTo input element

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#638]
Adding style/class arguments to the `buttonTo()` helper end up as attributes in the `form` element. It would be nice to have something like `buttonClass` or `inputClass` so the button itself can be styled.

**Comment by chapmandu** [comment]
I'm thinking that perhaps `style` and `class` argument should be applied to the `button` tag rather than implementing new arguments. If for some reason, the form tag needed styling (why?), it could be applied with css with the `id` selector.

**Comment by chapmandu** [comment]
@perdjurner beat me to it... about a year ago..

https://github.com/cfwheels/cfwheels/commit/ca8e2214c35eaac6c24dfc510d8efceac3681a96#diff-9eb694be5cbad04cd25f75a8c5dc88a6R71

I suppose this be documented...

**Comment by chapmandu** [comment]
Documented..  http://docs.cfwheels.org/v1.4/docs/buttonto

**Comment by neokoenig** [comment]
Reminder that any doc changes to 1.4 will need to be done to 2.x fork too

**Comment by chapmandu** [comment]
http://docs.cfwheels.org/v2.0/docs/buttonto
