### ISSUE TITLE
Problem with Column Statistics 'sum()'

### ISSUE THREAD

**Issue by zulhelmi** [cfwheels/cfwheels#640]
Here my sample code
`<cfset subtotal = model("registration").sum(property="priceperperson",include="type(eventtypes)",where="eventid = #cookie.eventid# AND status = 0 AND memberid = #Session.Participant.id#",ifNull=0)>`

The error

> [Macromedia][Oracle JDBC Driver][Oracle]ORA-00909: invalid number of arguments

Query return

```
SELECT SUM() AS priceperpersonsum
 FROM tbl_registrations INNER JOIN tbl_types ON tbl_registrations.TYPEID = tbl_types.ID LEFT OUTER JOIN tbl_eventtypes ON tbl_types.ID = tbl_eventtypes.TYPEID
 WHERE
 tbl_registrations.EVENTID =
 (param 1) 
 AND 
 tbl_registrations.STATUS =
 (param 2) 
 AND 
 tbl_registrations.MEMBERID =
 (param 3) 
```

The problem is the SUM() is empty. It should be SUM(priceperperson)

**Comment by neokoenig** [comment]
Which version of wheels? I assume Oracle and some version of ACF?

What happens when you do this?:
```
subtotal = model("registration").findAll(
  select="SUM(priceperperson) AS sumpriceperperson", 
  include="type(eventtypes)", 
  where="eventid = #cookie.eventid# AND status = 0");
```

**Comment by zulhelmi** [comment]
It run ok

Here the some details
CFWheels 1.4.5
Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production
Adobe ColdFusion 10,0,20,299202

**Comment by perdjurner** [comment]
@zulhelmi, can you reduce this to the least amount of code that still produces the error please?

Remove include, where, ifNull etc.

Also post your models/Registration.cfc code please, and do the same for that, reduce it to the least amount of code possible that still produces the error.

Thanks.

**Comment by perdjurner** [comment]
No response, closing.
