### ISSUE TITLE
When caching an action, the filters of that controller are not being executed

### ISSUE THREAD

**Issue by RobaAdmin** [cfwheels/cfwheels#642]
Hey guys

I'm not sure if it's a bug, or I'm missing something. I spent a lot of time studying the docs, but I cannot make sense out of it:

Environment: development
In my Controller products.cfc I have following code:

```
<cfcomponent extends="Controller">


    <cffunction name="init">
        <cfset caches(actions="getAllNodes,getAllNodesByApplicationArea", time=10)>
    </cffunction>

	
	<cffunction name="viewStructure">
		<cfset contentFor(Title='Products')>
		<cfset leftNavigationMenu = "leftnavProducts">
		<cfset leftNavigationSize = 3>
     </cffunction>

	<cffunction name="getAllNodes">
         ...
       </cffunction>
```
I want to cache getAllNodes because it's quite query heavy.

Now when I'm calling any action within that controller, my filters set in the Controller.cfc are not being executed.

Controller.cfc
```
<cfcomponent extends="Wheels">
	
	<cffunction name="init">
		<cfset filters(through="checkLogin", except="login,register,create,signin,verifyemail,sendEmailVerificationMail,BaseStructureIntern,getAllNodes,getAllNodesForGraph,getAllNodesByFunction,getAllNodesByApplicationArea")>
		<cfset filters(through="handleNotifications", type="before", except="login,register,create,signin,verifyemail,sendEmailVerificationMail")>
		<cfset filters(through="getAllMyChannels", except="login,register,create,signin,verifyemail,sendEmailVerificationMail")>
	</cffunction>
```

Now the weird thing is, event though I'm calling the "viewStructure" action, which is not in the cache argument, the filters are being ignored.

Interesting fact: When switching to "production" environment with the this cache initialization, I get an error 500 from my IIS. 

When removing the cache-init from my controller, everything works normally.

I have no idea where to look for my mistake.... Glad for any assistance.

**Comment by perdjurner** [comment]
Your Products.cfc controller is overriding its parent's (Controller.cfc) init function. Therefore your calls to filters() never execute.

The solution is to call Controller.cfc's init function from Products.cfc like this:

```
<cffunction name="init">
  <cfset caches(actions="getAllNodes,getAllNodesByApplicationArea", time=10)>    
  <cfset super.init()>  
</cffunction>
```

**Comment by RobaAdmin** [comment]
Thanks mate!

Of course! You know the feeling, when your coding for hours straight without a break and you don't see the most obvious? ;)

Working like a charm!
