### ISSUE TITLE
Model instantiation skipped due to Linux file case sensitivity

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#643]
Calling `models/MyModel.cfc` using `foo = model("myModel")` does not instantiate the model due to file case sensitivity. 

It seems it must be called as `foo = model("MyModel")` to work as desired (model name must be referenced using exactly the same case as the model file name).

This issue only occurs on Linux, works as expected on Windows and OSX.

I would expect that I be able to call the model with any case and it be returned.

**Comment by chapmandu** [comment]
Added a failing test for this issue https://github.com/cfwheels/cfwheels/commit/03cbca575171340a38a62fea76e9f1c423d85365

Oddly, the tests pass on OSX.

**Comment by chapmandu** [comment]
The issue seems to be here..

https://github.com/cfwheels/cfwheels/blob/master/wheels/global/internal.cfm#L664

`loc.file = $fileExistsNoCase(ExpandPath(loc.fullObjectPath & ".cfc"));`

On Linux, `ExpandPath(loc.fullObjectPath & ".cfc"))` returns something like `/Users/foo/cfwheels/wheels/foo/cfwheels/wheels/_assets/model/`

Removing the `ExpandPath()` get the committed test above passing, but breaks about 40 other tests.

**Comment by chrisdpeters** [comment]
See [this comment](http://www.bennadel.com/blog/2519-expandpath-works-with-coldfusion-s-per-application-mappings.htm#comments_43175):

> One thing to be careful about expand path is, it doesn't work if the file or directory doesn't exist. It doesn't throw error, but it returns wrong path. So, something like this fileExits(expandPath('/mydir/myfile')) may or may not work.

**Comment by chapmandu** [comment]
Test package model.miscellaneous.$objectFileName still failing on Linux on ACF11.. investigating..
