### ISSUE TITLE
wheels callbacks.cfm $callbacks funtion error

### ISSUE THREAD

**Issue by adrox37** [cfwheels/cfwheels#645]
There is an loc is not defined in the function and occasionally causes error.  Adding var loc = {};
fixes the issue.

version: 	CFWheels 1.4.5

Error:
You have attempted to dereference a scalar variable of type class java.lang.String as a structure with members.

 
The error occurred in /Projects/wheels/model/callbacks.cfm: line 148
Called from /Projects/wheels/model/callbacks.cfm: line 172
Called from /Projects/wheels/model/create.cfm: line 66
Called from /Projects/wheels/model/serialize.cfm: line 59
Called from /Projects/wheels/model/serialize.cfm: line 13
Called from /Projects/wheels/model/read.cfm: line 223
Called from /Projects/wheels/model/read.cfm: line 290
Called from <generated>: line 1
Called from /Projects/wheels/model/onmissingmethod.cfm: line 110

**Comment by chrisdpeters** [comment]
@adrox37 Thanks for reporting. Can you submit a pull request with the fix?

**Comment by adrox37** [comment]
@chrisdpeters i don't have permissions to create a pull request.  Otherwise I would have created the request.

**Comment by chapmandu** [comment]
@adrox37 All you need to do is fork the cfwheels repo, make the change in your fork, then submit a pull request.. Happy contributing!

**Comment by adrox37** [comment]
Thanks @chapmandu worked great.

**Comment by chapmandu** [comment]
#646
