### ISSUE TITLE
Add flashMessages() to default layout

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#650]
I propose adding `#flashMessages()#` to the default layout file:

```
<html>
	<body>
		<cfoutput>
                 #flashMessages()# 
                 #includeContent()#
                </cfoutput>
	</body>
</html>
```

Most / All applications probably use them, and it might be helpful for newbies. Objections?

**Comment by perdjurner** [comment]
Makes sense to me.

**Comment by neokoenig** [comment]
Added. Closing, no need to document this apart from in Changelog.
