### ISSUE TITLE
Proposal -  Add new event methods to Test Framework

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#651]
New methods:

`beforeAll()` - executes once per request before the first has run
`afterAll()` - executes once per request after all tests have finished
`packageSetup()` - executes once per package before the first has run (and before `setup()`
`packageTeardown()` - executes once per package after tests have run (after `teardown()`)

So in this sequence...
```
beforeAll()

/* Foo.cfc package */
packageSetup()

setup()
test_something()
teardown()

setup()
test_something_else()
teardown()

packageTeardown()
// end Foo.cfc

/* Bar.cfc package */
packageSetup()

setup()
test_something()
teardown()

packageTeardown()
// end Bar.cfc

afterAll()
```

- [x] `beforeAll()`
- [x] `afterAll()`
- [x] `packageSetup()`
- [x] `packageTeardown()`
- [x] Document new functions
- [x] Document tests request lifecycle (order of function execution)
- [x] Document `processAction()`
- [x] Document `getRedirect()`
- [x] Document `format` parameter [html|junit|json]

**Comment by neokoenig** [comment]
Yes, great idea; This would really help tracking down those really odd caching things in-between tests which occasionally crop up too.

**Comment by chapmandu** [comment]
http://docs.cfwheels.org/v2.0/docs/testing-your-application
