### ISSUE TITLE
Commandbox install cfwheels not showing empty folders when delivered from cache

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#652]
This is more of a note to Commandbox  users than a wheels bug: in Commandbox, if you do `install cfwheels` at present, you'll get 1.4.5 correctly. If you do `install cfwheels` again, it'll serve from the artifacts cache.

However in CB 3.x, due to the change of endpoints, the result is cached via a .zip file generated by lucee. There's a bug in lucee that empty folders won't get zipped (this is different behaviour to ACF2016). So the result is a wheels install which doesn't have `stylesheets,javascripts` etc - i.e any empty folder.

There is a solution which is just to clear the cache using `artifacts remove cfwheels` which will force a fresh copy to be downloaded.

See https://ortussolutions.atlassian.net/projects/COMMANDBOX/issues/COMMANDBOX-417 and https://luceeserver.atlassian.net/browse/LDEV-941 for updates.

**Comment by perdjurner** [comment]
Maybe we should have a readme.txt in all empty folders which explains why the folder is there and what to use it for?

This way they can go in releases too I mean (doesn't really make sense to keep the .keep files in releases)

**Comment by neokoenig** [comment]
Fixed as we've added .keep
