### ISSUE TITLE
Columns missing when self joining

### ISSUE THREAD

**Issue by andybellenie** [cfwheels/cfwheels#653]
````
CREATE TABLE `events` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parentId` int(11) DEFAULT NULL,
  `title` varchar(100) NOT NULL
  PRIMARY KEY (`id`),
) 
````

Event.cfc
````
<cfcomponent extends="Model" output="false">

	<cffunction name="init" returntype="void" output="false">
		<cfset belongsTo(name="Parent", modelName="Event", jointype="outer", foreignKey="parentId")>
	</cffunction>

</cfcomponent>
````

Now run the following:
````
<cfset events = model("Event").findAll(include="Parent")>
````

The query runs fine but it is missing the title column from the parent event. Expected behaviour is for the column to be aliased as parentTitle

**Comment by perdjurner** [comment]
Related to this:
https://github.com/cfwheels/cfwheels/issues/309

Can you check that issue and let me know if you think that would solve your problem posted here?

**Comment by andybellenie** [comment]
Yes it's the same issue, closing
