### ISSUE TITLE
Add bCrypt and associated wheels helper functions for password hashing

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#655]
Since bCrypt is basically the industry standard for hashing, I can’t help feel we should be offering a few new functions and include bCrypt in a standard installation – i.e:

- `bCrypt.hashpw(params.password, bCrypt.gensalt()` - hashed string
- `bCrypt.checkpw(params.password, user.password)` - boolean

The catch is bycrypt is a `.class` file – thankfully, CF10 upwards supports:
```
this.javaSettings = {
 	LoadPaths = ["/miscellaneous"]
};
```
Which means you can add bCrypt via one line: CreateObject( "java", "BCrypt" );

How do we feel about including bCrypt in 2.x ? I reckon we should provide the developer with as many built into tools to promote good security as possible...

**Comment by andybellenie** [comment]
Personally I don't think this is the kind of thing Wheels as a framework
should be doing. Any developer can easily do this themselves if necessary,
we shouldn't be making decisions on the developer's behalf for which third
party tools they use.

**Comment by neokoenig** [comment]
It's a fair point; it might be something I reserve for the CLI (so just an option when you install) maybe.

**Comment by perdjurner** [comment]
I agree with Andy, this feels more like a job for a plugin.

**Comment by neokoenig** [comment]
No problem; I think I'll stick this as an option in the CLI to install. There's no point having it as a plugin really, as you'd have to add all the configuration manually (i.e, load paths) which kinda negates the point :)
