### ISSUE TITLE
Refactor using cfscript and local scope

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#657]
**STYLE GUIDE**

```
/**
* Javadoc style hints on private core functions only
*/
public string function $coreFunction(required string arg1, required string arg2) {
    // note the removal of loc scope
    local.rv = "foo";
    return local.rv;
}

// More than 2 arguments should be wrapped
public boolean function $coreFunction(
    required string arg1,
    required string arg2,
    required string arg3,
    required string arg4
) {
    // note the removal of loc scope
    local.rv = true;
    return local.rv;
}

// test cases don't require access or return type declarations
function test_actual_equals_expected() {
    loc.actual = 1 + 1;
    loc.expected = 2;
    assert("loc.actual eq loc.expected");
}
```

**HOW TO**
- Install Commandbox http://docs.cfwheels.org/v2.0/docs/commandbox
- Fork and clone the cfwheels github repository 
- cd to your new cfwheels directory
- run "box start cf10" on the command line
- Setup a 'wheelstestdb' database & datasource
- Update a CFWheels tag based file to cfscript
- Click the "Run all tests" link in the cfwheels debug
- Commit & push
- Submit a pull request

**APPLICATION**
- [x] Application.cfc
- [x] config/app.cfm
- [x] config/design/settings.cfm
- [x] config/development/settings.cfm
- [x] config/environment.cfm
- [x] config/maintenance/settings.cfm
- [x] config/production/settings.cfm
- [x] config/routes.cfm
- [x] config/settings.cfm
- [x] config/testing/settings.cfm
- [x] controllers/Controller.cfc
- [x] controllers/Wheels.cfc
- [x] events/functions.cfm
- [x] events/onapplicationend.cfm
- [x] events/onapplicationstart.cfm
- [x] events/onerror.cfm
- [x] events/onmaintenance.cfm
- [x] events/onmissingtemplate.cfm
- [x] events/onrequestend.cfm
- [x] events/onrequeststart.cfm
- [x] events/onsessionend.cfm
- [x] events/onsessionstart.cfm
- [x] index.cfm
- [x] miscellaneous/Application.cfc
- [x] models/Model.cfc
- [x] models/Wheels.cfc
- [x] rewrite.cfm
- [x] root.cfm
- [x] views/helpers.cfm
- [x] views/layout.cfm
- [x] views/wheels/layout.cfm
- [x] views/wheels/wheels.cfm

**CORE** 
- [ ] src/test/coldfusion/_oracle-emu.cfm
- [x] wheels/controller/appfunctions.cfm
- [x] wheels/controller/caching.cfm
- [x] wheels/controller/filters.cfm
- [x] wheels/controller/flash.cfm
- [x] wheels/controller/functions.cfm
- [x] wheels/controller/initialization.cfm
- [x] wheels/controller/layouts.cfm
- [x] wheels/controller/miscellaneous.cfm
- [x] wheels/controller/processing.cfm
- [x] wheels/controller/provides.cfm
- [x] wheels/controller/redirection.cfm
- [x] wheels/controller/rendering.cfm
- [x] wheels/controller/verifies.cfm
- [x] wheels/Controller.cfc
- [x] wheels/controller.cfm
- [x] wheels/dispatch/functions.cfm
- [x] wheels/dispatch/request.cfm
- [x] wheels/Dispatch.cfc
- [x] wheels/events/onapplicationend.cfm
- [x] wheels/events/onapplicationstart.cfm
- [x] wheels/events/onerror.cfm
- [x] wheels/events/onmissingtemplate.cfm
- [x] wheels/events/onrequest.cfm
- [x] wheels/events/onrequestend.cfm
- [x] wheels/events/onrequeststart.cfm
- [x] wheels/events/onsessionend.cfm
- [x] wheels/events/onsessionstart.cfm
- [x] wheels/functions.cfm
- [x] wheels/global/appfunctions.cfm
- [ ] wheels/global/cfml.cfm <--- This has the majority of the potentially troublesome CF10 compat tags - for discussion.
- [x] wheels/global/functions.cfm
- [x] wheels/global/internal.cfm
- [x] wheels/global/public.cfm
- [x] wheels/index.cfm
- [x] wheels/model/adapters/Base.cfc <-- still contains one tag function w/ cfquery
- [x] wheels/model/adapters/H2.cfc
- [x] wheels/model/adapters/MySQL.cfc
- [x] wheels/model/adapters/Oracle.cfc
- [x] wheels/model/adapters/PostgreSQL.cfc
- [x] wheels/model/adapters/SQLServer.cfc
- [x] wheels/model/associations.cfm
- [x] wheels/model/calculations.cfm
- [x] wheels/model/callbacks.cfm
- [x] wheels/model/create.cfm
- [x] wheels/model/delete.cfm
- [x] wheels/model/errors.cfm
- [x] wheels/model/functions.cfm
- [ ] wheels/model/initialization.cfm <-- [Fails on lucee4 / oracle](https://travis-ci.org/cfwheels/cfwheels/jobs/152338418) 
- [x] wheels/model/miscellaneous.cfm
- [x] wheels/model/nestedproperties.cfm <-- Needs revisiting due to scope naming collisions really
- [x] wheels/model/onmissingmethod.cfm
- [x] wheels/model/properties.cfm
- [x] wheels/model/read.cfm
- [x] wheels/model/serialize.cfm
- [x] wheels/model/sql.cfm
- [x] wheels/model/transactions.cfm
- [x] wheels/model/update.cfm
- [x] wheels/model/validations.cfm
- [x] wheels/Model.cfc
- [x] wheels/model.cfm
- [x] wheels/plugins/injection.cfm
- [x] wheels/Plugins.cfc
- [x] wheels/public/build.cfm
- [x] wheels/public/congratulations.cfm
- [x] wheels/public/layout.cfm
- [x] wheels/public/packages.cfm
- [x] wheels/public/plugins.cfm
- [ ] wheels/public/tests/json.cfm
- [x] wheels/public/tests.cfm
- [x] wheels/public/wheels.cfm
- [x] wheels/styles/footer.cfm
- [x] wheels/styles/header.cfm
- [x] wheels/Test.cfc
- [ ] wheels/vendor/toXml/toXML.cfc
- [x] wheels/view/assets.cfm
- [x] wheels/view/dates.cfm
- [x] wheels/view/errors.cfm
- [x] wheels/view/forms.cfm
- [x] wheels/view/formsassociation.cfm
- [x] wheels/view/formsdate.cfm
- [x] wheels/view/formsdateobject.cfm
- [x] wheels/view/formsdateplain.cfm
- [x] wheels/view/formsobject.cfm
- [x] wheels/view/formsplain.cfm
- [x] wheels/view/functions.cfm
- [x] wheels/view/links.cfm
- [x] wheels/view/miscellaneous.cfm
- [x] wheels/view/sanitize.cfm
- [x] wheels/view/text.cfm

**TESTS**

Use this to make refactoring tests a little more bearable..
https://gist.github.com/chapmandu/80fa5d25567d3930a940d04ace7002ed
- [x] wheels/tests/_assets/controllers/Controller.cfc
- [x] wheels/tests/_assets/controllers/ControllerWithModel.cfc
- [x] wheels/tests/_assets/controllers/ControllerWithModelErrors.cfc
- [x] wheels/tests/_assets/controllers/ControllerWithNestedModel.cfc
- [x] wheels/tests/_assets/controllers/Filtering.cfc
- [x] wheels/tests/_assets/controllers/Test.cfc
- [x] wheels/tests/_assets/controllers/Verifies.cfc
- [x] wheels/tests/_assets/controllers/Wheels.cfc
- [x] wheels/tests/_assets/models/Author.cfc
- [x] wheels/tests/_assets/models/AuthorSelectArgument.cfc
- [x] wheels/tests/_assets/models/City.cfc
- [x] wheels/tests/_assets/models/Classification.cfc
- [x] wheels/tests/_assets/models/CollisionTest.cfc
- [x] wheels/tests/_assets/models/CombiKey.cfc
- [x] wheels/tests/_assets/models/Comment.cfc
- [x] wheels/tests/_assets/models/Gallery.cfc
- [x] wheels/tests/_assets/models/Model.cfc
- [x] wheels/tests/_assets/models/NoPrimaryKey.cfc
- [x] wheels/tests/_assets/models/Photo.cfc
- [x] wheels/tests/_assets/models/Photo2.cfc
- [x] wheels/tests/_assets/models/PhotoGallery.cfc
- [x] wheels/tests/_assets/models/PhotoGalleryPhoto.cfc
- [x] wheels/tests/_assets/models/Post.cfc
- [x] wheels/tests/_assets/models/Profile.cfc
- [x] wheels/tests/_assets/models/Shop.cfc
- [x] wheels/tests/_assets/models/SqlType.cfc
- [x] wheels/tests/_assets/models/Tag.cfc
- [x] wheels/tests/_assets/models/TagFalseCallbacks.cfc
- [x] wheels/tests/_assets/models/TagWithDataCallbacks.cfc
- [x] wheels/tests/_assets/models/User.cfc
- [x] wheels/tests/_assets/models/User2.cfc
- [x] wheels/tests/_assets/models/UserAutomaticValidations.cfc
- [x] wheels/tests/_assets/models/UserBlank.cfc
- [x] wheels/tests/_assets/models/UserTableless.cfc
- [x] wheels/tests/_assets/models/ViewUserPhotoKeyPhotoGalleryId.cfc
- [x] wheels/tests/_assets/models/ViewUserPhotoKeyUserId.cfc
- [x] wheels/tests/_assets/plugins/dependant/TestPlugin1/TestPlugin1.cfc
- [x] wheels/tests/_assets/plugins/incompatible/TestPlugin1/TestPlugin1.cfc
- [x] wheels/tests/_assets/plugins/incompatible/TestPlugin2/TestPlugin2.cfc
- [x] wheels/tests/_assets/plugins/overwriting/testglobalmixins/index.cfm
- [x] wheels/tests/_assets/plugins/overwriting/testglobalmixins/TestGlobalMixins.cfcns
- [x] wheels/tests/_assets/plugins/standard/TestAssignMixins/TestAssignMixins.cfc
- [x] wheels/tests/_assets/plugins/standard/TestDefaultAssignMixins/TestDefaultAssignMixins.cfc
- [x] wheels/tests/_assets/plugins/standard/TestGlobalMixins/TestGlobalMixins.cfc
- [x] wheels/tests/_assets/plugins/standard/TestIncompatableVersion/TestIncompatableVersion.cfc
- [x] wheels/tests/_assets/sharedappname/Application.cfc
- [x] wheels/tests/_assets/sharedappname/test.cfm
- [x] wheels/tests/_assets/testframework/_UnderscoredPackage.cfc
- [x] wheels/tests/_assets/testframework/ValidTestPackage.cfc
- [x] wheels/tests/controller/caching/$addcachableaction.cfc
- [x] wheels/tests/controller/caching/$cachableactions.cfc
- [x] wheels/tests/controller/caching/$cachesettingsforaction.cfc
- [x] wheels/tests/controller/caching/$clearcachableactions.cfc
- [x] wheels/tests/controller/caching/$hascachableactions.cfc
- [x] wheels/tests/controller/caching/$setcachableactions.cfc
- [x] wheels/tests/controller/caching/caches.cfc
- [x] wheels/tests/controller/filters/$runfilters.cfc
- [x] wheels/tests/controller/filters/$runverifications.cfc
- [x] wheels/tests/controller/filters/filterchain.cfc
- [x] wheels/tests/controller/filters/filters.cfc
- [x] wheels/tests/controller/filters/setfilterchain.cfc
- [x] wheels/tests/controller/filters/setverificationchain.cfc
- [x] wheels/tests/controller/filters/verificationchain.cfc
- [x] wheels/tests/controller/filters/verifies.cfc
- [x] wheels/tests/controller/flash/cookieStorage.cfc
- [x] wheels/tests/controller/flash/flash.cfc
- [x] wheels/tests/controller/flash/flashclear.cfc
- [x] wheels/tests/controller/flash/flashcount.cfc
- [x] wheels/tests/controller/flash/flashdelete.cfc
- [x] wheels/tests/controller/flash/flashinsert.cfc
- [x] wheels/tests/controller/flash/flashisempty.cfc
- [x] wheels/tests/controller/flash/flashKeep.cfc
- [x] wheels/tests/controller/flash/flashkeyexists.cfc
- [x] wheels/tests/controller/flash/flashmessages.cfc
- [x] wheels/tests/controller/flash/setup.cfm
- [x] wheels/tests/controller/flash/teardown.cfm
- [x] wheels/tests/controller/initialization/$createcontrollerobject.cfc
- [x] wheels/tests/controller/initialization/$getcontrollerclassdata.cfc
- [x] wheels/tests/controller/initialization/$initcontrollerclass.cfc
- [x] wheels/tests/controller/initialization/$initcontrollerobject.cfc
- [x] wheels/tests/controller/initialization/$setcontrollerclassdata.cfc
- [x] wheels/tests/controller/initialization/general.cfc
- [x] wheels/tests/controller/miscellaneous/$callaction.cfc
- [x] wheels/tests/controller/miscellaneous/$performedRenderOrRedirect.cfc
- [x] wheels/tests/controller/miscellaneous/controllername.cfc
- [x] wheels/tests/controller/miscellaneous/helpers.cfc
- [x] wheels/tests/controller/miscellaneous/sendfile.cfc
- [x] wheels/tests/controller/miscellaneous/sendmail.cfc
- [x] wheels/tests/controller/provides/$requestcontenttype.cfc
- [x] wheels/tests/controller/provides/initialization.cfc
- [x] wheels/tests/controller/provides/renderwith.cfc
- [x] wheels/tests/controller/redirection/redirectto.cfc
- [x] wheels/tests/controller/rendering/$argumentsForPartial.cfc
- [x] wheels/tests/controller/rendering/includecontent.cfc
- [x] wheels/tests/controller/rendering/layouts.cfc
- [x] wheels/tests/controller/rendering/rendernothing.cfc
- [x] wheels/tests/controller/rendering/renderpage.cfc
- [x] wheels/tests/controller/rendering/renderpartial.cfc
- [x] wheels/tests/controller/rendering/rendertext.cfc
- [x] wheels/tests/controller/rendering/setup.cfm
- [x] wheels/tests/controller/rendering/specified_layouts.cfc
- [x] wheels/tests/controller/rendering/teardown.cfm
- [x] wheels/tests/controller/request/isajax.cfc
- [x] wheels/tests/controller/request/isdelete.cfc
- [x] wheels/tests/controller/request/isget.cfc
- [x] wheels/tests/controller/request/ishead.cfc
- [x] wheels/tests/controller/request/isoptions.cfc
- [x] wheels/tests/controller/request/ispatch.cfc
- [x] wheels/tests/controller/request/ispost.cfc
- [x] wheels/tests/controller/request/isput.cfc
- [x] wheels/tests/controller/request/issecure.cfc
- [x] wheels/tests/controller/request/pagination.cfc
- [x] wheels/tests/controller/request/setup.cfm
- [x] wheels/tests/controller/request/teardown.cfm
- [x] wheels/tests/dispatch/$request.cfc
- [x] wheels/tests/dispatch/createParams.cfc
- [x] wheels/tests/env.cfm
- [x] wheels/tests/global/caching.cfc
- [x] wheels/tests/global/cfml.cfc
- [x] wheels/tests/global/internal/$args.cfc
- [x] wheels/tests/global/internal/$cgiscope.cfc
- [x] wheels/tests/global/internal/$checkMinimumVersion.cfc
- [x] wheels/tests/global/internal/$hashedkey.cfc
- [x] wheels/tests/global/public/deobfuscateparam.cfc
- [x] wheels/tests/global/public/humanize.cfc
- [x] wheels/tests/global/public/obfuscateparam.cfc
- [x] wheels/tests/global/strings.cfc
- [x] wheels/tests/global/urlfor.cfc
- [x] wheels/tests/internal/model/validations/ValidatesLengthOf.cfc
- [x] wheels/tests/model/associations/belongsTo.cfc
- [x] wheels/tests/model/associations/composite.cfc
- [x] wheels/tests/model/associations/hasMany.cfc
- [x] wheels/tests/model/associations/hasOne.cfc
- [x] wheels/tests/model/calculations/average.cfc
- [x] wheels/tests/model/calculations/count.cfc
- [x] wheels/tests/model/calculations/maximum.cfc
- [x] wheels/tests/model/calculations/minimum.cfc
- [x] wheels/tests/model/calculations/sum.cfc
- [x] wheels/tests/model/callbacks/afterDelete.cfc
- [x] wheels/tests/model/callbacks/afterFind.cfc
- [x] wheels/tests/model/callbacks/afterFindNonLegacy.cfc
- [x] wheels/tests/model/callbacks/afterSaveProperties.cfc
- [x] wheels/tests/model/callbacks/afterSaving.cfc
- [x] wheels/tests/model/callbacks/beforeCreate.cfc
- [x] wheels/tests/model/callbacks/beforeCreateAndbeforeUpdate.cfc
- [x] wheels/tests/model/callbacks/beforeDelete.cfc
- [x] wheels/tests/model/callbacks/beforeSave.cfc
- [x] wheels/tests/model/callbacks/beforeUpdate.cfc
- [x] wheels/tests/model/callbacks/beforeValidation.cfc
- [x] wheels/tests/model/callbacks/beforeValidationOnCreate.cfc
- [x] wheels/tests/model/callbacks/beforeValidationOnUpdate.cfc
- [x] wheels/tests/model/callbacks/custom.cfc
- [x] wheels/tests/model/crud/binarydata.cfc
- [x] wheels/tests/model/crud/changes.cfc
- [x] wheels/tests/model/crud/create.cfc
- [x] wheels/tests/model/crud/deletes.cfc
- [x] wheels/tests/model/crud/findall.cfc <- contains cfquery tag
- [x] wheels/tests/model/crud/finders.cfc
- [x] wheels/tests/model/crud/findone.cfc
- [x] wheels/tests/model/crud/findonebyxxx.cfc
- [x] wheels/tests/model/crud/from.cfc
- [x] wheels/tests/model/crud/group.cfc
- [x] wheels/tests/model/crud/order.cfc
- [x] wheels/tests/model/crud/pagination.cfc
- [x] wheels/tests/model/crud/properties.cfc
- [x] wheels/tests/model/crud/select.cfc
- [x] wheels/tests/model/crud/transactions.cfc
- [x] wheels/tests/model/crud/updates.cfc
- [x] wheels/tests/model/crud/where.cfc
- [x] wheels/tests/model/errors/errors.cfc
- [x] wheels/tests/model/miscellaneous/$objectFileName.cfc
- [x] wheels/tests/model/miscellaneous/objectid.cfc
- [x] wheels/tests/model/miscellaneous/primaryKeys.cfc
- [x] wheels/tests/model/miscellaneous/properties.cfc
- [x] wheels/tests/model/miscellaneous/setPagination.cfc
- [x] wheels/tests/model/miscellaneous/tableName.cfc
- [x] wheels/tests/model/nestedproperties/has_many.cfc
- [x] wheels/tests/model/nestedproperties/has_one.cfc
- [x] wheels/tests/model/onmissingmethod/belongsto/hasobject.cfc
- [x] wheels/tests/model/onmissingmethod/belongsto/object.cfc
- [x] wheels/tests/model/onmissingmethod/hasMany/addobject.cfc
- [x] wheels/tests/model/onmissingmethod/hasMany/createobject.cfc
- [x] wheels/tests/model/onmissingmethod/hasMany/deleteallobjects.cfc
- [x] wheels/tests/model/onmissingmethod/hasMany/deleteobject.cfc
- [x] wheels/tests/model/onmissingmethod/hasMany/findoneobject.cfc
- [x] wheels/tests/model/onmissingmethod/hasMany/hasobjects.cfc
- [x] wheels/tests/model/onmissingmethod/hasMany/newobject.cfc
- [x] wheels/tests/model/onmissingmethod/hasMany/objectcount.cfc
- [x] wheels/tests/model/onmissingmethod/hasMany/objects.cfc
- [x] wheels/tests/model/onmissingmethod/hasMany/removeallobjects.cfc
- [x] wheels/tests/model/onmissingmethod/hasMany/removeobject.cfc
- [x] wheels/tests/model/onmissingmethod/hasone/createobject.cfc
- [x] wheels/tests/model/onmissingmethod/hasone/deleteobject.cfc
- [x] wheels/tests/model/onmissingmethod/hasone/hasobject.cfc
- [x] wheels/tests/model/onmissingmethod/hasone/newobject.cfc
- [x] wheels/tests/model/onmissingmethod/hasone/object.cfc
- [x] wheels/tests/model/onmissingmethod/hasone/removeobject.cfc
- [x] wheels/tests/model/onmissingmethod/hasone/setobject.cfc
- [x] wheels/tests/model/properties/accessibleproperties.cfc
- [x] wheels/tests/model/properties/columnforproperty.cfc
- [x] wheels/tests/model/properties/columns.cfc
- [x] wheels/tests/model/properties/defaults.cfc
- [x] wheels/tests/model/properties/hasChanged.cfc
- [x] wheels/tests/model/properties/hasproperty.cfc
- [x] wheels/tests/model/properties/key.cfc
- [x] wheels/tests/model/properties/propertyispresent.cfc
- [x] wheels/tests/model/properties/protectedproperties.cfc
- [x] wheels/tests/model/properties/timestamps.cfc
- [x] wheels/tests/model/properties/toggle.cfc
- [x] wheels/tests/model/raisedErrors/raisedErrors.cfc
- [x] wheels/tests/model/read/findallkeys.cfc
- [x] wheels/tests/model/read/findfirst.cfc
- [x] wheels/tests/model/read/findlast.cfc
- [x] wheels/tests/model/read/findorcreateby.cfc
- [x] wheels/tests/model/sql/whereclause.cfc
- [x] wheels/tests/model/validations/automatic_validations.cfc
- [x] wheels/tests/model/validations/conditional_validations.cfc
- [x] wheels/tests/model/validations/default_validations.cfc
- [x] wheels/tests/model/validations/low_level_validations.cfc
- [x] wheels/tests/model/validations/skip_validations.cfc
- [x] wheels/tests/model/validations/standard_validations.cfc
- [x] wheels/tests/model/validations/standard_validations_tableless.cfc
- [x] wheels/tests/model/validations/validation_error_messages.cfc
- [x] wheels/tests/model/views/views.cfc
- [x] wheels/tests/plugins/dependant.cfc
- [x] wheels/tests/plugins/incompatible.cfc
- [x] wheels/tests/plugins/injection.cfc
- [x] wheels/tests/plugins/overwriting.cfc
- [x] wheels/tests/plugins/removing.cfc
- [x] wheels/tests/plugins/standard.cfc
- [x] wheels/tests/plugins/unpacking.cfc
- [x] wheels/tests/populate.cfm <-- still contains one tag function w/ cfquery
- [x] wheels/tests/routing/$findMatchingRoute.cfc
- [x] wheels/tests/Test.cfc
- [x] wheels/tests/testframework/$cleantestcase.cfc
- [x] wheels/tests/testframework/$cleantestname.cfc
- [x] wheels/tests/testframework/$iscorefile.cfc
- [x] wheels/tests/testframework/$isvalidtest.cfc
- [x] wheels/tests/view/assets/assetDomain.cfc
- [x] wheels/tests/view/assets/assetQueryString.cfc
- [x] wheels/tests/view/assets/imagetag.cfc
- [x] wheels/tests/view/assets/javaScriptIncludeTag.cfc
- [x] wheels/tests/view/assets/styleSheetLinkTag.cfc
- [x] wheels/tests/view/content/includePartial.cfc
- [x] wheels/tests/view/dates/distanceOfTimeInWords.cfc
- [x] wheels/tests/view/dates/timeAgoInWords.cfc
- [x] wheels/tests/view/dates/timeUntilInWords.cfc
- [x] wheels/tests/view/errors/errorMessageOn.cfc
- [x] wheels/tests/view/errors/errorMessagesFor.cfc
- [x] wheels/tests/view/forms/$objectName.cfc
- [x] wheels/tests/view/forms/buttonTag.cfc
- [x] wheels/tests/view/forms/checkbox.cfc
- [x] wheels/tests/view/forms/checkBoxTag.cfc
- [x] wheels/tests/view/forms/endFormTag.cfc
- [x] wheels/tests/view/forms/fileField.cfc
- [x] wheels/tests/view/forms/fileFieldTag.cfc
- [x] wheels/tests/view/forms/hiddenField.cfc
- [x] wheels/tests/view/forms/hiddenFieldTag.cfc
- [x] wheels/tests/view/forms/htmlAttributes.cfc
- [x] wheels/tests/view/forms/label.cfc
- [x] wheels/tests/view/forms/passwordField.cfc
- [x] wheels/tests/view/forms/passwordFieldTag.cfc
- [x] wheels/tests/view/forms/radioButton.cfc
- [x] wheels/tests/view/forms/radioButtonTag.cfc
- [x] wheels/tests/view/forms/select.cfc
- [x] wheels/tests/view/forms/selectTag.cfc
- [x] wheels/tests/view/forms/startFormTag.cfc
- [x] wheels/tests/view/forms/submitTag.cfc
- [x] wheels/tests/view/forms/textArea.cfc
- [x] wheels/tests/view/forms/textAreaTag.cfc
- [x] wheels/tests/view/forms/textField.cfc
- [x] wheels/tests/view/forms/textFieldTag.cfc
- [x] wheels/tests/view/forms/yearSelect.cfc
- [x] wheels/tests/view/formsdate/$yearMonthHourMinuteSecondSelectTagContent.cfc
- [x] wheels/tests/view/formsdateobject/DateSelect.cfc
- [x] wheels/tests/view/formsdateobject/DateTimeSelect.cfc
- [x] wheels/tests/view/formsdateobject/TimeSelect.cfc
- [x] wheels/tests/view/formsdateplain/DateSelectTags.cfc
- [x] wheels/tests/view/formsdateplain/DateTimeSelectTags.cfc
- [x] wheels/tests/view/formsdateplain/DaySelectTag.cfc
- [x] wheels/tests/view/formsdateplain/HourSelectTag.cfc
- [x] wheels/tests/view/formsdateplain/MinuteSelectTag.cfc
- [x] wheels/tests/view/formsdateplain/MonthSelectTag.cfc
- [x] wheels/tests/view/formsdateplain/SecondSelectTag.cfc
- [x] wheels/tests/view/formsdateplain/TimeSelectTags.cfc
- [x] wheels/tests/view/formsdateplain/YearSelectTag.cfc
- [x] wheels/tests/view/links/paginationlinks.cfc
- [x] wheels/tests/view/miscellaneous/$addToJavaScriptAttribute.cfc
- [x] wheels/tests/view/miscellaneous/$element.cfc
- [x] wheels/tests/view/miscellaneous/$getobject.cfc
- [x] wheels/tests/view/miscellaneous/$tagId_and_$tagName.cfc
- [x] wheels/tests/view/miscellaneous/contentFor.cfc
- [x] wheels/tests/view/miscellaneous/cycle.cfc
- [x] wheels/tests/view/miscellaneous/resetcycle.cfc
- [x] wheels/tests/view/miscellaneous/tag.cfc
- [x] wheels/tests/view/text/excerpt.cfc
- [x] wheels/tests/view/text/h.cfc
- [x] wheels/tests/view/text/highlight.cfc
- [x] wheels/tests/view/text/simpleformat.cfc
- [x] wheels/tests/view/text/striplinks.cfc
- [x] wheels/tests/view/text/striptags.cfc
- [x] wheels/tests/view/text/titleize.cfc
- [x] wheels/tests/view/text/truncate.cfc
- [x] wheels/tests/view/urls/autoLink.cfc
- [x] wheels/tests/view/urls/buttonTo.cfc
- [x] wheels/tests/view/urls/linkTo.cfc
- [x] wheels/tests/view/urls/mailTo.cfc
- [x] wheels/tests/view/urls/pagination.cfc
- [x] wheels/tests/view/urls/urlFor.cfc

**Comment by chapmandu** [comment]
Reset all checkboxes to take `local` scope refactoring into account

**Comment by neokoenig** [comment]
I think we've scriptified everything we can reasonably do; the ones left as tags can't really be touched until we drop CF10. Close this?

**Comment by perdjurner** [comment]
Yes.
