### ISSUE TITLE
Make core test suite fail is wheelstestdb isn't setup

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#658]
At the moment, if you try and run wheels core tests when `wheelstestdb` datasource hasn't been added, it'll hang forever without giving a useful error. Would be good to try and do a simple DB check beforehand and throw an immediate error prior to testing. 

An example of where this is very easy to forget is if you trash a local commandbox server, which will reset the admin.

**Comment by chapmandu** [comment]
@neokoenig What cfengine/OS does this, I've tried this on CF10 and Lucee 4.5 on OSX and the missing dsn exception is immediate.

**Comment by neokoenig** [comment]
I've found this with OSX / lucee4 plus same on Windows10; it just sits there and hangs forever..

**Comment by neokoenig** [comment]
If you wrap the cfdbinfo call in `/wheels/tests/populate.cfm' with a try/catch, that fixes it for me
