### ISSUE TITLE
CF10 cfscript legacy issues

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#659]
Moving the core to CF10 presents a few issues with tags which aren't properly ported till CF11. Using this issue to keep a list of troublesome tags which might need some sort of wrapper.
- [ ] cfcontent (see wheels/public/tests/json.cfm: you can't run the core tests in CF10 returning JSON)
- [ ] cfinvoke seems to misbehave in CF10
- [x] cfquery - Uses wheels $query wrapper (no cfqueryparam support)
- [x] cfdbinfo - Uses wheels $dbinfo wrapper
- [ ] cfdocument
- [x] cftransaction - this one's fine with just `transaction {}`

**Comment by chapmandu** [comment]
Interesting.. 
https://github.com/CFCommunity/CFScript-Community-Components

**Comment by perdjurner** [comment]
FYI, there are some wrappers in the global/cfml.cfm file.

$content
$dbinfo
$invoke

**Comment by neokoenig** [comment]
Ah yes, but I'm going to have to script those too..
My biggest concern at the moment is cfquery, where the way the SQL is used / generated is completely different to queryExectute(); So would involve a hefty rewrite in the adapters/SQL generation :(

**Comment by perdjurner** [comment]
Maybe we should postpone the more problematic cfscript conversion until we can drop support for CF 10 (which I think will be 2017)?

**Comment by neokoenig** [comment]
Yeah, could do: would certainly make it easier. As it stands, it's just `wheels/global/cfml`, `wheels/model/adapters/*` and `wheels/model/initialization` which are the troublesome ones. so that's pretty good, like 97% of the core has been moved to script.

**Comment by neokoenig** [comment]
thoughts @chrisdpeters @chapmandu @timsayshey ?

**Comment by chapmandu** [comment]
Is it possible to isolate some the unscriptables into a separate include?

https://github.com/cfwheels/cfwheels/blob/master/wheels/tests/_assets/models/dbinfo.cfm

https://github.com/cfwheels/cfwheels/blob/6b3197923b563a44470628fe82e1b89e34ded826/wheels/tests/_assets/models/User2.cfc#L6

**Comment by perdjurner** [comment]
I don't think it's a good idea to include other files in functions like that.

I remember it's a little buggy (although can't remember any details) and it's probably considered bad practice in general.

**Comment by chapmandu** [comment]
@perdjurner Fair enough: https://github.com/cfwheels/cfwheels/commit/7c891074698b3c8625e3769b67b90f12d18910a7

**Comment by perdjurner** [comment]
> Maybe we should postpone the more problematic cfscript conversion until we can drop support for CF 10.

Dropping the 2.0 milestone on this since we've decided to keep supporting CF 10 for 2.x.

**Comment by timsayshey** [comment]
Relevant: http://blogs.coldfusion.com/coldfusion-10-core-support-ends-in-may-2017/ 

Supporting Coldfusion 10 even though it's no longer supported? Wouldn't it be a security issue to keep running Coldfusion 10 at this point?

**Comment by neokoenig** [comment]
Yes. We've got CF10 on the test server, and stuff passes on there, so by "support" we mean, it "works". So we should consider it deprecated I guess. Perhaps drop it for 2.1?

We need to figure out how to manipulate the travis setup first, so we can still test against oracle + MSSQL

**Comment by perdjurner** [comment]
Closing this as we don't really need a ticket for it :)
