### ISSUE TITLE
Funky textField values when passing a list to select(options=list)

### ISSUE THREAD

**Issue by chrisdpeters** [cfwheels/cfwheels#663]
This is generally what I'm doing with a `select` in CFWheels 1.4.5 on CF9:

``` coldfusion
<cfoutput>

#select(
  objectName="foo",
  property="bar",
  options="Website,Website (SP Referral),All AIMS users,FTRI staff,RDC",
  includeBlank="-- Add submitters --"
)#

</cfoutput>
```

But the list of `option`s generated ends up looking like this:

``` html
<option value="">-- All submitters --</option>
<option value="Website">Website</option>
<option value="Website (SP Referral)">Website ( SP Referral)</option>
<option value="All AIMS users">All  AIMSusers</option>
<option value="FTRI staff">FTRIstaff</option>
<option value="RDC">RDC</option>
```

Notice that the `value`s are OK, but there's weird stuff going on with spaces in the text displayed.

I doubt this makes a difference, but the list is being returned by a function. I don't see why that would matter though.

**Comment by kmd1970** [comment]
Is there a fix for this in version 1.4.6, for people who haven't made the jump to 2.0 as yet?

**Comment by perdjurner** [comment]
Yes there is.

**Comment by neokoenig** [comment]
https://github.com/cfwheels/cfwheels/releases/tag/v1.4.6
"Made humanize() keep spaces in input."

Nice one @perdjurner

**Comment by kmd1970** [comment]
I tested 1.4.6 before I posted. Looks like the issue remains.

![img](https://i.imgur.com/1GwVRDy.jpg)

**Comment by kmd1970** [comment]
FYI, my company firewall blocks the "cfwheels.1.4.6.zip" link for some reason, so I used the "Source code (zip)" link to download 1.4.6. Are they different?

**Comment by perdjurner** [comment]
File content should be the same (in terms of relevant code anyway).
Perhaps we didn't get the fix done properly then.
Are you able to run that test code you posted on Wheels 2.0 and see if it works?
Just want to make sure which versions are broken exactly.

Thanks.

**Comment by kmd1970** [comment]
My localhost is not worthy of 2.0. :)
"Adobe ColdFusion 11,0,08,298512 is not supported by CFWheels."

**Comment by kmd1970** [comment]
Ok, I was able to verify it's still broken in 2.0. Sorry for the delay.

**Comment by kmd1970** [comment]
This may fix the issue with Humanize()
```js
// add a space before every capitalized word
loc.rv = REReplace(arguments.text, "([[:upper:]])", " \1", "all");
// remove space after punctuation chars *Added*
loc.rv = REReplace(loc.rv, "([[:punct:]])+([[:space:]])", "\1", "all");
```

**Comment by kmd1970** [comment]
Found another issue.

```js
//test
#humanize("All AIMS users")#<br>
#humanize("FTRI staff")#<br>

//will output
All AIMSusers
FTRIstaff
```

Replace

```js
// fix abbreviations so they form a word again (example: aURLVariable)
local.rv = REReplace(local.rv, "([[:upper:]])([[:space:]])(?![a-z])", "\1", "all");

```

with

```js
// fix abbreviations so they form a word again (example: aURLVariable)
local.rv = REReplace(local.rv, "([[:upper:]]) ([[:upper:]])(?:\s|\b)(?![a-z])", "\1\2", "all");

//test
#humanize("Website (SP Referral)")#<br>
#humanize("Website ( SP Referral )")#<br>
#humanize("Website (( SP Referral))")#<br>
#humanize("All AIMS users")#<br>
#humanize("FTRI staff")#<br>
#humanize("aURLVariable")#<br>
#humanize("wheelsIsAFramework")#

//will output
Website (SP Referral)
Website ( SP Referral )
Website (( SP Referral))
All AIMS users
FTRI staff
A URL Variable
Wheels Is A Framework 
```

**Comment by perdjurner** [comment]
I think my last commit fixed that actually.

**Comment by kmd1970** [comment]
Oops, you are correct.
