### ISSUE TITLE
Redo internal CSS

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#665]
I'd like to redo the "wheels welcome" and internal pages CSS to be something a little more useful.
Bootstrap is perhaps a smidge overweight for our needs, but something where we can have responsive layouts and proper table formatting. 

DBmigrate for instance includes zurb foundation just to show a few tables etc.

**Comment by perdjurner** [comment]
If all our UI is used in dev mode only, maybe it's fine to get bootstrap
from a CDN? Would be nice for the tests UI too.

**Comment by neokoenig** [comment]
Until you need to work offline on a train or something :)

**Comment by chapmandu** [comment]
Agreed, having everything work offline is definitely a requirement for me.. Most of my OSS work is during my commute.. We don't have wifi on our steamtrains or horse &  carts down under.

**Comment by neokoenig** [comment]
I've set it to work offline except the fonts which are currently Google fonts; it's a bit tricky to serve non cf stuff inside the wheels folder, so I'll have to see how easy it is.
