### ISSUE TITLE
Drop IIS 6

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#668]
I think we can drop support for IIS 6, right?

In reality it only really means deleting the IsapiRewrite4.ini file I believe.

**Comment by neokoenig** [comment]
IIS6 went EOL last year, so I'd say yep. Also need to remove details from the docs.

**Comment by neokoenig** [comment]
Does this mean we can also drop ISAPI rewrite? https://github.com/cfwheels/cfwheels/blob/master/IsapiRewrite4.ini

**Comment by perdjurner** [comment]
Yes.

**Comment by neokoenig** [comment]
*sigh*. Would have helped if I'd properly re-read the top comment eh.
