### ISSUE TITLE
update min required lucee + ACF version

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#669]
Security releases, so we should set minimum versions to:

Lucee 4.5.3.020 and or/ 5.0.0.254
ACF 10/11 (not 2016) - http://forta.com/blog/index.cfm/2016/8/30/ColdFusion-Security-Update

**Comment by neokoenig** [comment]
Update, dropping CF10, also, with the bug fixes in CF11 latest, I think we should push for ACF to be 11.0.11 rather than 11.0.10, as these - https://helpx.adobe.com/coldfusion/kb/bugs-fixed-coldfusion-11-update-11.html#main-pars_text might have an impact.

**Comment by neokoenig** [comment]
This still needs confirming: I think we should set Lucee 4.5.5.006 as minimum. ideally we test for 5.0.1.85 as minimum in 5.x too, but I'm less fussy about that. ACF should be 11.0.11 

Any objections?

**Comment by neokoenig** [comment]
Note, we can't do this yet, as the test suite requires reconfiguring if we set minimum version ACF to 11, so I think this is best postponed and shouldn't hold up a beta launch

**Comment by perdjurner** [comment]
So, we've decided to support CF 10 and Lucee 4.

Here's what we have set as minimum now:
Lucee 4.5.5.006.
ACF 10.0.23.

Also note that when running ACF 11, update 12 is required (we should perhaps do something similar for Lucee 5 and CF2016).

**Comment by chapmandu** [comment]
Booo CF10!!

**Comment by perdjurner** [comment]
> we should perhaps do something similar for Lucee 5 and CF2016

Look into that for RC 1.
