### ISSUE TITLE
getColumnInfo function in Oracle Adapter needs additional filtering

### ISSUE THREAD

**Issue by shutterassault** [cfwheels/cfwheels#670]
I use Oracle for my database when developing in CFWheels. I noticed that the wrong table was being loaded in one of my applications.  After digging around to figure it out, I realized the table was in a completely different schema than I was expecting.  In the wheels/adapters/oracle.cfm file the getColumnInfo function was filtering only on table_name, not on the schema/owner as well.  So basically there were two tables with the exact same name, and it was loading the table outside of the expected schema.

My fix was to filter not just by tc.table_name, but tc.owner as well.  That loaded the correct table again.
![owner_oracle](https://cloud.githubusercontent.com/assets/8582208/18169368/d69d14a2-7027-11e6-84a0-4317d6d6855e.png)

**Comment by perdjurner** [comment]
Good find, any chance you can do a pull request?

**Comment by shutterassault** [comment]
I just submitted one (https://github.com/cfwheels/cfwheels/pull/671).  Go easy on me.  It's my first pull request lol.

**Comment by neokoenig** [comment]
Closing as Oracle support is dropped
