### ISSUE TITLE
Add onServerStart for 2.x

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#675]
Should add `events/onserverstart.cfm` for 2.x maybe (since we can now use it as we're starting at cf10) ?

**Comment by perdjurner** [comment]
Wonder how that works if you have two Wheels apps (in sub folders for example)?

**Comment by neokoenig** [comment]
Excellent question. From reading up on it, in ACF, it looks like you define the path from the CFadmin to the Server.cfc, so it might be something you can't really "set" in wheels per se. It only allow one entry; 

```
Specify the absolute path to a CFC having onServerStart() method, like "c:\server.cfc". 
Or specify a dot delimited CFC path under webroot, like "a.b.server". 
By default, ColdFusion will look for server.cfc under webroot.
```

Railo didn't have it,  lucee has from 5.0.x:

```
"The latest version of Lucee 5.0.1.024 contains a first implementation of web.cfc and server.cfc. 
There are a few things that need to be said here:

1.      It’s a hidden feature set (well not really anymore J)
2.      The server.cfc is loaded BEFORE all web contexts are loaded. 
This means that there will no application or so be available. Only to fill the server scope for instance or create files etc.
3.      The web.cfc is called for each web context, when it starts. 
It contains ONE method which will be onWebStart() so the cfc will look like this:

component {
     public function onWebStart() {
           doSomething…
     }
}
```

So I'm tempted to skip it, as I don't think it should be part of wheels per se: too inconsistent an implementation between engines...

**Comment by perdjurner** [comment]
> So I'm tempted to skip it, as I don't think it should be part of wheels per se: too inconsistent an implementation between engines...

I agree.

**Comment by neokoenig** [comment]
Closing with "won't fix" :)
