### ISSUE TITLE
Sublime plugin support

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#676]
Add Wheels support to this plugin:
https://github.com/jcberquist/sublimetext-cfml

**Comment by neokoenig** [comment]
Probably worth looking at FW/1 as an inspiration: https://github.com/jcberquist/sublimetext-cfml/tree/master/src/fw1

They've got a FW/1 "switch" which can turn on /off cfwheels support.

I've still got a database with all the functions in I think, so I could possibly generate this from that. It's times like this where I slightly regret moving the docs off to something we don't have full control over..

**Comment by chapmandu** [comment]
It would be cool to have some sort of json file in the cfwheels repo (not included in the build) which describes the api.. It would need updating with api changes (alongside the readme docs) 

This could be used by anyone to generate any manner of editor plugin or docset (eg dash). 

Could this be done using the database you have Tom?

**Comment by neokoenig** [comment]
Sounds like @timsayshey might be a good fit for this one, as he did port this across: https://github.com/timsayshey/Sublime-Text-CFWheels

**Comment by timsayshey** [comment]
Thanks @neokoenig but it was more of a desperate hack of an existing plugin. All credit really goes to @russjohnson for getting it working.
