### ISSUE TITLE
Improved support for tableless models with virtual properties

### ISSUE THREAD

**Issue by andybellenie** [cfwheels/cfwheels#677]
When using a tableless model, you can define virtual properties in the init() as usual, then validations, labels, etc are available.

These are stored in wheels.class.mappings but never included in wheels.class.properties, so they appear invisible to methods such as hasChanged()

I've been mapping a tableless model to a remote datastore, so property methods are really useful to make the remote persistence layer behave as closely as possible as a local db based model.

At the moment I'm just doing...

````
<cffunction name="mappingToProperties">
	<cfset StructAppend(variables.wheels.class.properties, variables.wheels.class.mapping)>
</cffunction>
````

... as an afterInitilization() callback and that seems to work well, also using $updatePersistedProperties() to maintain object state.

I think that virtual properties should be part of the main wheels.class.properties struct and persistence methods promoted to part of the public API.

Thoughts?

**Comment by perdjurner** [comment]
Maybe try it and see how many unit tests it breaks?

That way we get an idea of how complex the change would be.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
