### ISSUE TITLE
AfterInitilization not running in correct place

### ISSUE THREAD

**Issue by andybellenie** [cfwheels/cfwheels#678]
/wheels/model/create.cfm 

````
<cffunction name="$createInstance" returntype="any" access="public" output="false">
	<cfargument name="properties" type="struct" required="true">
	<cfargument name="persisted" type="boolean" required="true">
	<cfargument name="row" type="numeric" required="false" default="1">
	<cfargument name="base" type="boolean" required="false" default="true">
	<cfargument name="callbacks" type="boolean" required="false" default="true">
	<cfscript>
		var loc = {};
		loc.fileName = $objectFileName(name=variables.wheels.class.modelName, objectPath=variables.wheels.class.path, type="model");
		loc.rv = $createObjectFromRoot(path=variables.wheels.class.path, fileName=loc.fileName, method="$initModelObject", name=variables.wheels.class.modelName, properties=arguments.properties, persisted=arguments.persisted, row=arguments.row, base=arguments.base, useFilterLists=(!arguments.persisted));

		// if the object should be persisted, call afterFind else call afterNew
		if ((arguments.persisted && loc.rv.$callback("afterFind", arguments.callbacks)) || (!arguments.persisted && loc.rv.$callback("afterNew", arguments.callbacks)))
		{
			loc.rv.$callback("afterInitialization", arguments.callbacks);
		}
	</cfscript>
	<cfreturn loc.rv>
</cffunction>
````

See at the bottom - the comment doesn't match the code, and the functionality doesn't make sense either. To my understanding, the afterInitilization() callback should run, well, after initialisation of the model class, nothing to do with crud. The function about should be calling afterNew().

**Comment by perdjurner** [comment]
It runs afterFind or afterNew in the if statement itself.
The code and / or comment could be made clearer though.

**Comment by andybellenie** [comment]
Ok I see that now. I still don't understand what afterInitialization() is doing in there though - and why does it only run if either afterFind() or afterNew() has been run? Shouldn't it run at the end of model init()?

**Comment by andybellenie** [comment]
I think I understand what's going on here - afterInitialization() is meant to mean either afterFind() or afterNew(), in the same way that beforeSave() affects both beforeCreate() and beforeUpdate().

It really means 'run after an instance is created' and not 'run once the model is initialised'

So I think that the only way to run code after init() is to override it. Do you agree?

I think the docs need to be clearer.

**Comment by perdjurner** [comment]
That's correct and I agree.

We could add another callback called afterModelInitialization and rename afterInitialization to afterObjectInitialization perhaps.

That would at least make things more clear I think.

Not sure what to do about the confusion over the "init" method in general though. I've never really liked the naming of that, a more appropriate name would be "config" or something similar.

**Comment by andybellenie** [comment]
Setup? I second a change in name for 2.0, it's always been a point of
confusion for migrating  devs that it's not referring to normal object
instantiation.

**Comment by perdjurner** [comment]
Sure, perhaps with callbacks named beforeModelSetup / afterModelSetup, instead of afterModelInitialization that I suggested above.

If we even add callbacks at all that is. Not sure how much value it would add since it's fairly easy to just achieve the same thing by putting code in the Model.cfc.

There might also be a better term for afterInitialization but I can't think of anything right now.

**Comment by perdjurner** [comment]
We have renamed "init" to "config".
