### ISSUE TITLE
Show in design mode - Versions of installed plugins

### ISSUE THREAD

**Issue by tapirus** [cfwheels/cfwheels#68]
Wouldn't it be nice to have in design mode the version numbers of installed plugins displayed?
In the moment (wheels 1.1.8) there are only the names of installed plugin shown.

**Comment by neokoenig** [comment]
A mere 4 and a half years later: with 2.x we now have the plugin version number in the box.json file, so we could pull ancillary data from there: failing that we could then just read the version number off the corresponding .zip file... add to 2.x?

**Comment by perdjurner** [comment]
Sure, we're not in a feature freeze yet :)

**Comment by neokoenig** [comment]
Now done, if there's a corresponding `box.json` file (which all new plugins from 2.x should have). I've skipped the version number when there's no `box.json` as we want to encourage that for the future. There's now `application.wheels.pluginMeta` struct which includes the deserialized `box.json` content - so plugin authors can now easily use that information in their plugins if they want.

So to access the plugin meta, you can do 
```
// Version Number
application.wheels.pluginMeta["pluginName"]["version"];

// Meta Struct from box.json
application.wheels.pluginMeta["pluginName"]["boxjson"];
```

**Comment by neokoenig** [comment]
Noted in docs at https://docs.cfwheels.org/v2.0/docs/developing-plugins
Closing
