### ISSUE TITLE
Upgrade plugins to allow multiple override methods

### ISSUE THREAD

**Issue by liferealized** [cfwheels/cfwheels#682]
As discussed at the google group: https://groups.google.com/forum/#!topic/cfwheels/7JxEb5rb5IA

A current limitation in the wheels plugin system is that the system is restrictive in how many times a method can be overridden which currently stands at 1. As I see it, there are 4 things the plugins system is trying to accommodate including:

1. add processing logic on top of a framework method later calling the original method
2. completely override a method
3. use a framework method of the same name by getting it's return value then doing processing
4. add new functionality now currently in wheels

While the current plugin system accomplishes these goals, there are instances where **multiple plugins** should be able to add logic and keep passing the arguments down the chain. One glaring instance of this is `onMissingMethod` where multiple plugins should have the ability to add dynamic methods to models.

**Comment by neokoenig** [comment]
Leaving open to document

**Comment by liferealized** [comment]
So I've been thinking about this. Nothing with plugins changes as far as the documentation goes as the documentation does not  warn users about overriding methods between plugins. So should we add documentation that multiple plugins can override the same method and that devs will need to be careful about this when using many plugins?

@chrisdpeters any other ideas?

**Comment by chrisdpeters** [comment]
Can you explain how a developer would need to be careful? I'm not even sure I understand how it works.

For example, what problem did you solve with onMissingMethod? What does it "look like" when a developer overrides it twice?

**Comment by liferealized** [comment]
Before the update, only cfrel could override onmissingmethod. Any other plugin that tried to override the method would get an error.

Now, multiple plugins can override the same method. So cfrel can add some functionality, and if none of it is used, it defers to core.onmissingmethod. I've allowed any model plugin to add new helper methods with onmissingmethod without any crazy errors about only one plugin can override the method.

I concrete example in the world of @chrisdpeters would be the bootstrap plugin. Currently, you created new methods instead of overriding existing ones because you didn't want to step on other plugins toes. Now, you can override the same methods and defer to core.method and no toes mashed. Behind the scenes, I handle what plugin/core method gets deferred to next, seamlessly, without fuss.

**Comment by liferealized** [comment]
The "being careful" part is if you have multiple plugins that override the same method and do not defer to core.method. You can override functionality of another plugin and not realize it.

**Comment by chrisdpeters** [comment]
Conceptually, that sounds good. Can you show me some hypothetical and/or real-world code? Like what would it look like if CFRel were to override a method and choose to defer? Are there other scenarios that you could demonstrate with example code?

**Comment by liferealized** [comment]
https://github.com/liferealized/cfrel/blob/develop/plugins/cfwheels/cfrel.cfc#L342

We have cfrel installed. cfrel overrides `onMissingMethod()` to add new helper functionality for scopes. If there isn't a match, it defers to the next plugin method that overrides `onMissingMethod()`.

https://github.com/liferealized/cfwheels-hash-property/blob/master/hashproperty.cfc#L88

In our example, we also have hashproperty installed, so it's `onMissingMethod()` is called next. It checks to see if a check hash helpers was called, if not, defer to the core `onMissingMethod()`.

https://github.com/cfwheels/cfwheels/blob/master/wheels/model/onmissingmethod.cfm#L6

The framework function finally gets called as no other plugins override `onMissingMethod()`. It does all of it's checks and either finds a helper method to call or throws a nice wheels error that the method doesn't exist.

**Comment by liferealized** [comment]
I'm happy to report that I have 18 plugins running on 2.0 with no issues thus far. This is with an established application.

**Comment by neokoenig** [comment]
@liferealized any chance you could tell me why this  - 
https://github.com/neokoenig/cfwheels-shortcodes/blob/master/Shortcodes.cfc

fails after these plugin runner changes?

Had reports of this being triggered:

```
Wheels.MethodNotFound

The method $sc_REReplaceCallback is part of a plugin but was not found in the base object.

Error location

Line 5 in views\say\hello.cfm
3: </cfsavecontent>
4: <cfoutput>
5: #processShortcodes(mycontent)#
6: </cfoutput>
7:


Tag context

Error thrown on line 63 in wheels\plugins\runners.cfm
- called from line 152 in plugins\shortcodes\Shortcodes.cfc
- called from line 73 in wheels\plugins\runners.cfm
- called from line 28 in plugins\shortcodes\Shortcodes.cfc
- called from line 73 in wheels\plugins\runners.cfm
- called from line 5 in views\say\hello.cfm
- called from line 128 in wheels\global\cfml.cfm
- called from line 411 in wheels\controller\rendering.cfm
- called from line 147 in wheels\controller\rendering.cfm
- called from line 54 in wheels\controller\rendering.cfm
- called from line 140 in wheels\controller\processing.cfm
- called from line 95 in wheels\controller\processing.cfm
- called from line 146 in wheels\dispatch\request.cfm
- called from line 1 in wheels\index.cfm
- called from line 2 in index.cfm
- called from line 8 in wheels\events\onrequest.cfm
```

**Comment by perdjurner** [comment]
Added some docs here (feel free to improve on it):
https://guides.cfwheels.org/v2.0/docs/installing-and-using-plugins#section-due-diligence
