### ISSUE TITLE
Automatic Associations

### ISSUE THREAD

**Issue by andybellenie** [cfwheels/cfwheels#685]
This has been on my to-do list for a while. Get Wheels to inspect foreign keys to create basic belongsTo() and hasMany() associations, for more auto-magical wondrousness.

**Comment by andybellenie** [comment]
At the moment it only fully works when using conventions for the foreign table. This is because the setup code runs inside model init(), but custom table names are only available after each model has been initialized. As far as I can tell this never happens, models are initialized (and cached) when they are first called. 

To fix this we'd need to call init() on every model as part of app start-up. I'm open to other suggestions though.

**Comment by perdjurner** [comment]
That's pretty awesome.

I think we need to figure out how to make it work when not following conventions before merging.

**Comment by andybellenie** [comment]
Abandoning for now, sadly. This got way too complicated once dealing with models from different databases.

**Comment by perdjurner** [comment]
Oh, that's too bad :(

By different databases you mean getting it to work consistently across MySQL, SQL Server, Oracle etc?

**Comment by andybellenie** [comment]
No, I meant different datasources. I'll leave this open, I may take another look.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
