### ISSUE TITLE
Core JS + CSS assets in 2.x

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#690]
At the moment, if you try and serve CSS/JS/images from within a folder which is behind URL rewriting, or within the `wheels` folder, you obviously can't.

There are some notable places where I would find this useful: 
 - the future `wheels.js`, which ColdRoute #609 might use (and indeed any other specific core JS)
 - The test suite: there's an experimental ajax test runner
 - The DB migration screen: form validation etc
 - The main 'Welcome to Wheels' sections #665

At the moment for instance, the fonts + CSS for those internal framework pages are either hardcoded in, or using some sort of base64 encoded embed, or, as I've been doing, CDN delivered - which obviously isn't great for offline use.

So, I guess what I'm asking is, where could we put the framework specific JS/CSS/Images which aren't designed to be user accessed?

`/miscellaneous/wheels/assets/` ?

**Comment by andybellenie** [comment]
Couldn't we tweak the rewrite to allow access to a specific subfolder of
wheels?

**Comment by neokoenig** [comment]
I was wondering that: I'd be in favour of that solution if we could get that working with all the various systems...

**Comment by chrisdpeters** [comment]
No need to worry about that for the new routing system. It will all be built to run without JS.

**Comment by andybellenie** [comment]
This works in IIS to browse the license file so it should be possible for
other webservers:

<conditions logicalGrouping="MatchAll">
<add input="{PATH_INFO}" negate="true"
pattern="^/(assets|lucee|rewrite.cfm|wheels/license.txt)($|/.*$)" />
</conditions>

**Comment by neokoenig** [comment]
ok, so in Tuckey:
```
    <condition type="request-uri" operator="notequal">^/(flex2gateway|jrunscripts|cfide|cfformgateway|wheels/assets|cffileservlet|lucee|files|images|javascripts|miscellaneous|stylesheets|robots.txt|favicon.ico|sitemap.xml|rewrite.cfm|index.cfm)</condition>
```
works to access `/wheels/asset/test.js` or whatever, so maybe that will work

I imagine

```
RewriteCond %{REQUEST_URI} !^/wheels/assets/.*$
```

would work for apache..

**Comment by neokoenig** [comment]
Now moved to local `/wheels/public/assets` folder; this should make it a bit easier to deal with making the internal pages more pretty/useful. Also added a show "all|failed|passed" toggle, so when a test fails, instead of having to scroll to the error EVERY time, you can now just hide the passed tests.

**Comment by neokoenig** [comment]
NB, need to double check the URL rewriting for IIS - I've made a guess as to what it should be..

**Comment by chrisdpeters** [comment]
@neokoenig How do you feel about making the default for tests so that it only shows failed? That's what I'm used to from QUnit tests.

These are usually the 2 questions that I have:

1.  Did all of the tests pass?
2.  If not, which ones failed and why?

**Comment by neokoenig** [comment]
That would make sense to me....didn't want to blow everyone's minds straight away though :)

**Comment by chrisdpeters** [comment]
Expected user experience:

First run of tests on v2.0:

1.  "Where the f*** are all of the tests? I hate my life!"
2.  "Oh, I need to click the 'All' tab."

Second through infinity runs of tests on v2.0:

1.  "What should I have for lunch today?"

**Comment by neokoenig** [comment]
Whilst I'll carry on tweaking, closing this for now as it's basically done.

**Comment by reubenbrown13** [comment]
In case anyone runs into this... I needed to have the ability for static assets included in my plugins that I am building right now.  The problem is that w/ the default urlRewrite.xml, that won't work.  I tweaked it slightly so that it now recognizes the reserved words in ANY directory tree, so if you have a /stylesheets folder in your plugin's directory, it will load properly.

Here is the updated line:
    <condition type="request-uri" operator="notequal">^/.*(flex2gateway|jrunscripts|cfide|cf_scripts|cfformgateway|cffileservlet|lucee|files|images|javascripts|miscellaneous|stylesheets|wheels/public/assets|robots.txt|favicon.ico|sitemap.xml|rewrite.cfm)</condition>

The only change was the .* at the star.

**Comment by andybellenie** [comment]
I'm not sure this is ok. It means that /someprivatefolder/files would now be available which could be a security hole.

**Comment by reubenbrown13** [comment]
@andybellenie you bring up a good point.... so I updated it: 
<condition type="request-uri" operator="notequal">^/(flex2gateway|jrunscripts|cfide|cf_scripts|cfformgateway|cffileservlet|lucee|files|images|javascripts|plugins/*/javascripts|miscellaneous|stylesheets|plugins/*/stylesheets|wheels/public/assets|robots.txt|favicon.ico|sitemap.xml|rewrite.cfm)</condition>

Now it also accepts plugin/*/javascripts|plugin/*/stylesheets ..... this is working great to let my plugins have static content and addresses the security issue you mentioned.
