### ISSUE TITLE
CFWheels UJS Plugin

### ISSUE THREAD

**Issue by liferealized** [cfwheels/cfwheels#691]
From @chrisdpeters 

It would be good to break any of the JS-powered stuff into a plugin.

We'd do this to allow developers the ability to use 1.x features in 2.x.

A cursory glance shows these methods being effected.

* startFormTag
* buttonTo
* linkTo
* buttonTag
* submitTag

**Comment by neokoenig** [comment]
Also see #627

**Comment by chrisdpeters** [comment]
Let's go ahead and close this in favor of #627. I'll merge details from titles/descriptions/comments/etc.
