### ISSUE TITLE
Timestamp settings

### ISSUE THREAD

**Issue by andybellenie** [cfwheels/cfwheels#695]
Timestamps are currently set as datetime in local time. I'm always having to convert them to UTC. It would be useful to be able to specify a timestamp mode, local, utc, or epoch

**Comment by chapmandu** [comment]
YES!

**Comment by neokoenig** [comment]
Merged + fixed a typo for CF10. Leaving open to document.

**Comment by chapmandu** [comment]
Is this breaking change necessary?

**Comment by andybellenie** [comment]
We have to choose a default and UTC is a more appropriate choice. For a major release it's not a big deal to have to add the setting so long as it's documented in the change notes.

**Comment by andybellenie** [comment]
For reference, use `set("timeStampMode"="local")` to get the current behaviour

**Comment by chapmandu** [comment]
https://github.com/cfwheels/cfwheels/blob/master/CHANGELOG.md#breaking-changes-1

"Timestamping (createdAt, updatedAt) is now in UTC by default (set the global timeStampMode setting to local to reinstate the old behaviour)."

**Comment by perdjurner** [comment]
@chapmandu Is it documented somewhere else too?

**Comment by perdjurner** [comment]
Documented here:
https://guides.cfwheels.org/v2.0/docs/automatic-time-stamps#section-time-zones
