### ISSUE TITLE
Postgres adapter needs some love

### ISSUE THREAD

**Issue by liferealized** [cfwheels/cfwheels#699]
After getting commandbox setup and running all versions of servers against the latest wheels test with a postgres DB, there are around 50 errors that happen.

I'm creating this issue to start to dig in and figure out what is going on.

**Comment by neokoenig** [comment]
Yeah, we're only testing with Lucee 4 against Postgres. ACF + postgres is certainly a hole..

**Comment by liferealized** [comment]
I'm seeing errors on lucee4 as well.

**Comment by liferealized** [comment]
Ahhh, some test data was stale!

**Comment by liferealized** [comment]
CF10 has 24 failures and 9 errors...   CF11 has 24 failures and 9 errors   CF2016 has 24 failures and 9 errors

In all instances, when running the tests on existing data, there are 50 failures and 12 errors...
