### ISSUE TITLE
Tableless models with nested tableless models formhelper fail

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#707]
Just to check I'm not going mad; you can't have tableless model with nested properties on a tableless model can you? I mean, it works, in so much than you can setup `modelOne` and `modelTwo` with `table(false)`, but when you try and use it with form helpers

```
// ModelOne 
	table(false);
	hasMany("modeltwos");
	nestedProperties("modeltwos"); 

// ModelTwo 
	table(false);
	belongsTo("modelone"); 

// Controller 
       modelOne=model("modelone").new(modeltwos=[model("modeltwo").new()]);

// View:
       #includePartial(modelone.modeltwos)#

// Partial:
       #textField(objectName="modelOne", 
              association="modelTwos", 
              position=arguments.current,  
              property="myproperty", 
              label="Foo")#
```

it throws:

```
key [ADAPTER] doesn't exist
Stacktrace	The Error Occurred in
/wheels/model/sql.cfm: line 724 
called from /wheels/view/miscellaneous.cfm: line 377 
called from /wheels/view/formsobject.cfm: line 20 
called from /views/users/_modeltwo.cfm: line 10 
called from /wheels/global/cfml.cfm: line 128 
called from /wheels/controller/rendering.cfm: line 424 
called from /wheels/controller/rendering.cfm: line 231 
called from /wheels/controller/rendering.cfm: line 256 
called from /wheels/view/miscellaneous.cfm: line 173 
called from /views/users/myreachback.cfm: line 39 
called from /wheels/global/cfml.cfm: line 128 
called from /wheels/controller/rendering.cfm: line 434 
called from /wheels/controller/rendering.cfm: line 157 
called from /wheels/controller/rendering.cfm: line 53 
called from /wheels/controller/processing.cfm: line 141 
called from /wheels/controller/processing.cfm: line 95 
called from /wheels/dispatch/request.cfm: line 198 
called from /wheels/index.cfm: line 1 
called from /index.cfm: line 1 
called from /wheels/events/onrequest.cfm: line 1 
```

As `variables.wheels.class.adapter` doesn't exist.
So I guess the question is, if it's a true tableless model, shouldn't we skip all the SQL generation bits?

Any `1.4.x` workarounds for this anyone can think of?

**Comment by chrisdpeters** [comment]
@neokoenig Tableless models do not support associations. From what I best can tell, these are the main features that are supported:

-  Properties
-  Validations
-  Callbacks involving validations

I believe that you can "simulate" nested properties exactly the way that you have there, but just drop your calls to `hasMany`, `belongsTo` and `nestedProperties` from the initializers.

When manipulating these objects on "save" or whatever you're trying to do, it's up to you to do all of the logic manually within your tableless model. Hope that makes sense. I'm still working on refining how I do this, so I've refrained writing a blog post about it just yet.

**Comment by neokoenig** [comment]
Thanks chris, think I've coded around that then.!
