### ISSUE TITLE
updateAll() function doesn't automatically timestamp the updateAT column? Bug or Not

### ISSUE THREAD

**Issue by kmd1970** [cfwheels/cfwheels#708]
I've just noticed this behavior. The updateAll() function doesn't automatically timestamp the updateAT column? I've always assumed every update/save function would automatically do this. Is this a bug or not?

**Comment by chapmandu** [comment]
This is not a bug. The *all functions merely perform a database update. If you want to have the updatedat columns updated, use the `instantiate=true` (not recommended for a large number of rows)  or explicitly set updated=now() in your call to updateall().

**Comment by kmd1970** [comment]
I assume you meant set `updatedAT=now() `

**Comment by chrisdpeters** [comment]
I edited it to read correctly. I like how it says it was edited by "ghost." Spooky. 👻

**Comment by chapmandu** [comment]
Most likely.. Replying on my phone whilst walking through the supermarket.. ;)

**Comment by kmd1970** [comment]
Well am off to edit all of my updateALL() code :)

**Comment by andybellenie** [comment]
Hmm, I'm not sure I agree here. It seems entirely logical to me that updateAll will set the updatedAt timestamp. I don't see how instantiation comes into it, that's more to do with callbacks and validation.

**Comment by andybellenie** [comment]
Just checked the rails docs, and it behaves the same way as Wheels currently. I don't personally like it, but it is consistant
