### ISSUE TITLE
Clarify what model functionality is available to tableless models in the docs

### ISSUE THREAD

**Issue by chrisdpeters** [cfwheels/cfwheels#709]
#707 demonstrates some confusion caused by the sparse documentation on tableless models.

(See my comment regarding what is available in terms of callbacks, validations, sans associations, etc.)

Maybe add some examples and consider splitting it off into its own chapter.

**Comment by MvdO79** [comment]
@chrisdpeters, for this issue I'm thinking about the below addition:

At the bottom of this section: https://github.com/MvdO79/cfwheels/blob/develop/guides/database-interaction-through-models/object-relational-mapping.md#models-without-database-tables

Adding:

Features supported:

- Properties
- Validations
- Callbacks involving initialisation and validations

See [Building search forms with tableless models in CFWheels](https://www.chrisdpeters.com/blog/search-forms-tableless-models-cfwheels) for a worked-out example.

**Comment by chrisdpeters** [comment]
Hey @MvdO79, I like the plan. Instead of linking to my blog, what do you guys think about moving my post over to the cfwheels.org blog so you all can "own" the content from there? @bpamiri

**Comment by MvdO79** [comment]
That's very generous @chrisdpeters ! Let's see what others think about adding it, thanks.

**Comment by bpamiri** [comment]
I’m all for that. At the end of the day, the more content available to new Wheels developers the better experience they’ll have. Than you @chrisdpeters, let me know how you want to handle it. @MvdO79 let me know if you want to just add it to the guides directly or add it as a blog post then link to it from the guides.

**Comment by chrisdpeters** [comment]
Feel free to copy/paste into the CFWheels blog or wherever you want! I wouldn't mind being credited as the author if you put it into the blog. (You should be able to tie it to my old WP account.)

When it's published, I'll redirect my blog article URL to the new location.

**Comment by MvdO79** [comment]
> I’m all for that. At the end of the day, the more content available to new Wheels developers the better experience they’ll have. Than you @chrisdpeters, let me know how you want to handle it. @MvdO79 let me know if you want to just add it to the guides directly or add it as a blog post then link to it from the guides.

Awesome, I totally agree.

**Comment by MvdO79** [comment]
@chrisdpeters Thanks Chris, I will set it up and notify you.

**Comment by bpamiri** [comment]
I've added the article to the blog:
https://cfwheels.org/blog/building-search-forms-with-tableless-models-in-cfwheels/
I was able to activate Chris' account and post the article under his name and added a message at the top noting that the article was originally posted on Chris' personal blog and was being republished with his permission.

**Comment by MvdO79** [comment]
Thanks @chrisdpeters and @bpamiri , I will update the link in the guides!
