### ISSUE TITLE
Implement a `trim` model argument to `Trim()` all model object properties before save

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#712]
This would be a simple handy addition to perform some basic sanitisation of object property values.

I'm regularly dealing with data entered from mobile devices on which the keyboard adds spaces at the ends of values in anticipation of the next word.. which results in things like:
`"foo "` and `" bar "`.

It would be enabled by default and could be disabled either globally or per request/query using `model("Foo").save(trim=false);`

**Comment by perdjurner** [comment]
This feels like something that is better handled at the controller level.

**Comment by andybellenie** [comment]
Agreed, I always put this in onrequeststart.cfm

<cfloop collection="#form#" item="key">
<cfset form[key] = Trim(form[key])>
</cfloop>

Maybe we could auto-trim form inputs before they become part of the params
struct? Make it an app setting?

**Comment by neokoenig** [comment]
I do this:
```
// events/onrequeststart.cfm
url=trimScope(url);
form=trimScope(form);

// events/functions.cfm  
public function trimScope(struct scope){
	if(structCount(scope)){
		for(key in scope){
		       if(isSimpleValue(scope[key])){
				scope[key] = Trim(scope[key]);
			} else {
                    trimScope(scope[key]);
                }
			}
		}
		return scope;
	}
```

Which has the advantage of trimming nested structs too.

**Comment by andybellenie** [comment]
How do you end up with a struct in form/url scope?

**Comment by neokoenig** [comment]
I may well be misunderstanding how the `params` struct is created, but I was thinking of when you have nested properties, i.e form fields like `myModel[assocation][2][propertyname]` - I've always found if you dump the `params` scope it would nest that? Or does the merge of the `URL` + `form` scopes autonest those when it turns into `params`? Been such a while since I've done it I may well be wrong :)

**Comment by andybellenie** [comment]
Yes, the nesting is done when the params struct is created, if you look at
the form scope you will see the entries like "model[property][2]" etc are
just plain strings

**Comment by neokoenig** [comment]
Typical. Me overthinking it :) (or just getting it plain wrong)

**Comment by chapmandu** [comment]
Trimming the params scope resolves part of the issue.. but this assumes only params scoped variables are passed to `save()` functions. Data imports from spreadsheets, XML parsing and RESTful endpoints are a couple of examples which wouldn't be covered by trimming the params scope.

**Comment by andybellenie** [comment]
I agree with Per that input sanitisation is a controller task. On the other hand, if a model requires trimmed values then that is part of its domain logic so belongs in validation/callbacks.

I quite like the idea of model's auto-trimming any passed values, as long as you could turn it off. I also like the idea of having the params struct auto-trimmed too. 

Is both overkill?

**Comment by perdjurner** [comment]
Yeah, thinking some more about it, we already have some settings for business logic (like timestamps for example) so I don't see trimming as being that much different.

Implementing both sounds like a good idea.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
