### ISSUE TITLE
Assets not loading on welcome page

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#713]
Starting a server using "server start cf10" loads up the welcome page fine but if I then click "reload" in the footer it goes to:

http://127.0.0.1:60010/index.cfm/?reload=true

All of the assets breaks at that point.

For example it tries to load:

http://127.0.0.1:60010/index.cfm/wheels/public/assets/css/milligram.min.css

But that throws a "Wheels.RouteNotFound" error.

**Comment by neokoenig** [comment]
Are you trying this using the `urlrewrite.xml` file or is this with URL rewriting off?
Ta

**Comment by perdjurner** [comment]
No idea!

I Git cloned the repo and didn't change a thing.

**Comment by neokoenig** [comment]
No worries, I shall investigate. 
I will almost definitely need help testing the IIS rewrite rules for this by the way :)

**Comment by neokoenig** [comment]
After some exploration, it appears to be commandbox related - I've raised a bug: 
https://ortussolutions.atlassian.net/browse/COMMANDBOX-569

**Comment by perdjurner** [comment]
FYI, since my URL rewrite changes I can no longer reproduce this (since URL rewriting is either on or off with CommandBox, never partial).

Can we close this then?

**Comment by neokoenig** [comment]
Well, it exposed a different bug in commandbox, which , whilst highly intermittent, is annoying - but yes, I reckon close and it's not a wheels thing.

**Comment by perdjurner** [comment]
Ok.

**Comment by neokoenig** [comment]
FYI, this is apparently fixed in Commandbox 3.6.0 - it was an issue with https://github.com/cfmlprojects/regexpathinfofilter
