### ISSUE TITLE
Can't create migration file from GUI with new routing

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#714]
Need to fix: on `?controller=wheels&action=wheels&view=migrate` trying to create any migration file uses `POST`, which triggers `Wheels.RouteNotFound`

Wheels couldn't find a route that matched this request.
Make sure there is a route setup in your 'config/routes.cfm' file that matches the '' request.

```
Tag context
Error thrown on line 103 in wheels\dispatch\request.cfm
- called from line 168 in wheels\dispatch\request.cfm
- called from line 134 in wheels\dispatch\request.cfm
- called from line 1 in wheels\index.cfm
- called from line 2 in rewrite.cfm
- called from line 8 in wheels\events\onrequest.cfm
```

This is basically the only `POST` within the wheels folder from what I can tell :)

**Comment by neokoenig** [comment]
Yep, definitely needs
```
drawRoutes()
.post(name="dbmigrate", to="wheels##wheels")
.root(to="wheels##wheels", method="get")
.end();
```
to create or execute migration files.

So either we add this route by default (which may be confusing to first time users), or, I could rewrite the DBMigrate GUI to use the same system as the CLI - which is essentially a .cfm listening for a bunch of params, then returning JSON; It's already there, so probably not much work, and now we have jQuery available, should be fairly easy.

However, that definitely goes against the nature of the routing system, in that GET would be changing data.

Thoughts?

**Comment by perdjurner** [comment]
I don't mind another default route.

**Comment by neokoenig** [comment]
Note: this is also affecting CLI dbmigrate access.

So either a) we create some sort of exception for controller=wheels, or b) add some default routes to config/routes.cfm (which a user might remove by mistake) or c) hardcode them in to the route generation process so that they're (much harder) to remove.

**Comment by perdjurner** [comment]
When a developer has changed to `.root(to="wheels##wheels", method="get")` to their own controller / action, how does *any* of our internal Wheels pages work?

Confused...

**Comment by perdjurner** [comment]
Answering my own question...

It looks like the ?controller=mycontroller&action=myaction bypasses the routing and allows you to load the requested page.

So, this is why all our internal pages work without us having to create routes for them.

**Comment by perdjurner** [comment]
So, quick fix = use a GET request instead.
Longer term plan = Don't look for a matching route when we're specifically passing in controller=something and action=something.

**Comment by neokoenig** [comment]
Yeah, I've already got a script setup to do that for the CLI access, so it's no big deal. I'll rewrite the GUI so it uses jQuery instead of forms or something too.

**Comment by neokoenig** [comment]
Closing, as this is now fixed with a new GUI + additional helpers for dbmigrate automigration
