### ISSUE TITLE
Content-Type when sending JSON

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#718]
I need to set the Content-Type when sending JSON to "application/vnd.api+json" (according to http://jsonapi.org) but Wheels has it set to "application/json".

I found two solutions:

1) Send a cfheader call after renderWith (ugly).

2) Override the Wheels "formats" setting:

```
local.formats = get("formats");
local.formats.json = "application/vnd.api+json";
set(formats=local.formats);
```

Just thought I'd write it down here because I think we should perhaps improve this (argument to renderWith?) or document it better.

**Comment by neokoenig** [comment]
I just did 
```
addFormat(extension="json", mimeType="application/vnd.api+json");
```
in `/config/settings`, but that does mean every JSON request does it, so I dropped it. I need a way of allowing `.json` to return either mime type depending on controller/route etc

**Comment by perdjurner** [comment]
For maximum flexibility maybe we should allow something like this:

`provides(json="application/vnd.api+json");`
`renderWith(data=local.data, contentType="application/vnd.api+json");`

Then you can choose at what level to apply your content type.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
