### ISSUE TITLE
StylesheetLinkTag and JavascriptIncludeTag should respect subdirectory

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#720]
By Default, a link like `stylesheetLinkTag("foo")` will render
```
<link href="/stylesheets/foo.css" media="all" rel="stylesheet" type="text/css" />
```

When running wheels from a sub directory, this will then break; is there any reason not to prepend `application.wheels.webpath` instead of just assuming `/` when generating the `<link>` ? It appears we're always assuming that wheels is running in the root with this one. The reason this came up was trying to run an app in a subdirectory which can also run in root without any configuration/code change.

Same applies to `javascriptIncludeTag()`

**Comment by perdjurner** [comment]
Looking at the source it seems that we are prepending `application.wheels.webPath`.

Can you create a failing test for this (I think we have sub folder testing set up on Travis)?

**Comment by neokoenig** [comment]
ok, you're right - the tests are returning what I expect. must be an issue with my app - closing!
