### ISSUE TITLE
Test suite operators

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#726]
Make sure that we mention that you can't do:
`assert("result == expected")`

This works though:
`assert("result eq expected")`

Another thing to mention is that you can pass in any truthy value to assert to test things (might be preferable / cleaner to pass in Find, Compare etc).

**Comment by chapmandu** [comment]
The main reason for the `a eq b` style assertion is that if the test case fails, the test framework will try to evaluate and display the values of `a` and `b` in the failure info. Sometimes functions are not evaluated easily and you end up having to add your own debug info to see why the assertion failed.

**Comment by neokoenig** [comment]
@chapmandu Is this still the case? I notice from your docs at https://guides.cfwheels.org/v2.0/docs/testing-your-application that you use `==` in the examples. I can't remember if it's just an ACF thing or what..

**Comment by chapmandu** [comment]
Changed `==` to `eq` and made mention of "truthy" statements.
