### ISSUE TITLE
Select() parameters: textField and valueField must be used together

### ISSUE THREAD

**Issue by dbelanger** [cfwheels/cfwheels#730]
At first I thought this was a bug and then I dug a little deeper into wheels/view/formsobject.cfm (lines 337-361).

Basically, I'm using a UUID for certain objects in my app in lieu of a numeric ID.  I mention this because I believe I've found logic where it's assumed the ID is numeric.

Here's the issue: When I use the select() helper function in my view without any additional parameters like so:

`#select(objectname="asset",property="locationid",options=locations)#`

I correctly get a textField and a valueField that contain the location object ID.  However, when I'd like to specify the valueField as the name of the location like this:

`#select(objectname="asset",property="locationid",options=locations,textField="name")#`

I assumed that the valueField wouldn't change but the textField would.  That doesn't happen. I still get the location object ID for both.  But if I use both textField and valueField like this:

`#select(objectname="asset",property="locationid",options=locations,textField="name",valueField="id")#`

it works as intended.

I believe this is happening because there is logic on lines 345 and 349 which check for numeric values (assuming that the key is numeric I suppose).  If this is intentional and id as supposed to be numeric by convention, then we should leave it as it and make it clear in the docs that if you use textField you must use valueField and vice-versa.  If not, then should the logic work like this:

- If no textField and valueField parameters are supplied, use the object ID for both
- If only valueField is supplied, use that column value for the text and the object ID for the value
- If only valueField is supplied, use that column value for the value and the object ID for the text

**Comment by chapmandu** [comment]
What does the options argument look like? 

Another option is to create an array of structs (with value & text keys) in your controller and pass this to the options argument. 

Your suggestion would be a breaking change for those cases where a recordset containing an id & string column is passed to options and using select() default arguments.

**Comment by perdjurner** [comment]
I believe this behaviour is intentional so let's make the docs better.

@dbelanger, would be great if you can improve these docs:
https://github.com/cfwheels/cfwheels/blob/master/wheels/view/formsobject.cfm#L351
https://github.com/cfwheels/cfwheels/blob/master/wheels/public/docs/reference/select.txt
