### ISSUE TITLE
Add automatic java lib mappings

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#731]
Would make plugins more powerful if there was a way to have `/plugins/pluginName/lib/` automatically added to the this.javamappings: that way you could easily deploy javalib based plugins without additional configuration.

yay? nay?

**Comment by perdjurner** [comment]
Not familiar with this, can you give me a real world example?
Can the plugin itself add the mapping or is that impossible currently?

**Comment by neokoenig** [comment]
i.e, lets say you wanted to make a bCrypt plugin. The easiest way is via 
```
this.javaSettings = {
    	LoadPaths = ["miscellaneous"]
  	};
```
in `config/app.cfm`

Chuck your `.class` file in,  the do `bCrypt = CreateObject( "java", "BCrypt" );`

So what I'm saying is it would be great if `/lib` or `/java` as auto-added to `this.javasettings` if it exists: that way you don't need to change code outside of the plugin to use it.

**Comment by neokoenig** [comment]
The more I think about this the more I like it: it means you could very easily add plugins which just expose java libs and add a few convenience functions. Bycrypt, iCal4J, MarkdownJ would be some easy wins for new plugins (I've actually already written these too).

I'll implement unless there are any strong objections.

**Comment by andybellenie** [comment]
I thought you could use a path on CreateObject() but I've just checked and it's a Lucee only feature, so I agree this would be useful.

I got this to work but recursing over plugin directories and adding them all to JavaSettings.LoadPaths. Then all a plugin author has to do is place the java file directly in a plugin directory or subdirectory.

**Comment by neokoenig** [comment]
Cool, that was pretty much my thinking. Have you done this got the code already? If so that would be fab, otherwise I'm happy to do it

**Comment by andybellenie** [comment]
No problem

````
if (DirectoryExists(ExpandPath("/#application.$wheels.pluginPath#"))) {
	param name="this.javaSettings.loadPaths" default=ArrayNew(1);
	for (folder in DirectoryList(path=ExpandPath("/#application.$wheels.pluginPath#"), recurse="true", filter="*.class|*.jar|*.java")) {
		ArrayAppend(this.javaSettings.loadPaths, GetDirectoryFromPath(folder)); 
	}
}
````

It needs to go in /wheels/events/onapplicationstart.cfm somewhere so as not to override any paths the user may have set themselves

**Comment by neokoenig** [comment]
hmm. I can get the folder path into the loadpaths array, but for the life of my can't work out why the .class etc files refuse to load. @andybellenie you're using this in lucee 4.5.x?

**Comment by andybellenie** [comment]
Lucee 4.5.3.020

**Comment by neokoenig** [comment]
Added in 3c4a2318ecce2d2a5d734fc89d7d499a283ccfcc 
Leaving open to document
