### ISSUE TITLE
Outer transaction rollback not working

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#732]
Wheels doesn't seem to respect my transaction block / rollback, it always commits to the database.

Example:

```
transaction {
  // Let's say that someFunc calls model("user").deleteByKey(1) internally for example.
  // I know I can pass in the transaction argument to the model methods but that gets messy quick.
  someFunc();
  transaction action="rollback";
}
```

I think the reason is that invokeWithTransaction does a specific transaction action="commit" rather than just exiting the transaction block.

**Comment by perdjurner** [comment]
@andybellenie 

Do you think that changing:

```
if (IsBoolean(local.rv) and local.rv) {
  transaction action=arguments.transaction;
}
```

To:

```
if (IsBoolean(local.rv) and local.rv) {
  if (arguments.transaction != "commit") {
    transaction action=arguments.transaction;
  }
}
```

in the switch statement in invokeWithTransaction would be a good solution?

**Comment by andybellenie** [comment]
How about:

````
if (!IsBoolean(local.rv) or !local.rv or arguments.transaction eq "rollback") {
	transaction action="rollback";
}
````

**Comment by andybellenie** [comment]
I like it, btw. We could clean up a lot of the testing code

**Comment by perdjurner** [comment]
Can you make a pull request?

You know this part of the code better than me so whatever you come up with is probably best :)

**Comment by andybellenie** [comment]
I did, but it was a long time ago, and that was before some cfscript lunatic came in and vandalised my lovely cfml :)

All done. Couple of tests failing on my local copy but seem unrelated

**Comment by perdjurner** [comment]
https://github.com/cfwheels/cfwheels/pull/733
