### ISSUE TITLE
Autogenerating Javadoc Documentation for Core + App

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#734]
Putting this here to remind me to document.

The Wheels API is now available via an inbuilt docs viewer (follow the `[View Docs]`) debug footer link).
All wheels core functions (will/are) be marked up in javaDoc like this `autolink()` example:

```
/**
 * Turns all URLs and email addresses into hyperlinks.
 *
 * [section: View Helpers]
 * [category: Text Functions]
 *
 * @text The text to create links in.
 * @link Whether to link URLs, email addresses or both. 
 * @relative Should we autolink relative urls.
 *
 */
function autoLink(... blah
```

From this, we can extract the function hint (`Turns all URLs and email addresses into hyperlinks.`), a section and category via the `[section]` and `[category]` markup, and also the function parameter hints.

#### Extended Code Examples

Extended code examples are available at `/wheels/public/docs/reference/SCOPE/FUNCTIONNAME.txt` and are automatically included and escaped if they're there.

This enables us to render:

![image](https://cloud.githubusercontent.com/assets/381268/23752619/f7f2265c-04cd-11e7-9636-3d5686b84ffa.png)

#### Developer's own Docs

As this is all dynamic and done via some parsing of `getMetaData()`, we can then even allow a user's app to use the same system by implementing the same/similar markup. The `[section]` and `[category]` tags are dynamic, so they can add them as they see fit.

For instance, in my app, I might have a function which is called `f_getRoles()`, and exists in `controllers/Controller.cfc` - this will be automatically picked up.
```
/**
* Creates the `allroles` variable containing all roles
*
* [section: Application]
* [category: Global Filters]
*/
void function f_getRoles(){
	allroles=model("role").findAll();
}
```
You'll notice I've used a section called `Application` - this is a bit arbitary, I could have called it anything.
This is then displayed in the Application Section with a Category of Global Filters:

![image](https://cloud.githubusercontent.com/assets/381268/23752866/fa6232fa-04ce-11e7-9834-4a217d56f891.png)

#### Alt Format
The API docs are also available via JSON by changing the `format=json` param in the URL.

#### Filtering
The Main A-Z Function list can be filtered as you type
![image](https://cloud.githubusercontent.com/assets/381268/23752719/68444980-04ce-11e7-8a76-ecfb6fd79b3b.png) and clicking on a category or section on the left will filter the A-Z list / Function definition output too.

#### Bookmarking
And each function can be quasi permalinks via hashtag (which changes as you select the function for clarity): i.e to link to `javascriptincludetag()`  you can do `/rewrite.cfm?controller=wheels&action=wheels&view=docs&type=core#javascriptincludetag`

Functions are namespaced, so `#model.findAll` and also `#findAll` should work.

Other functions can be linked to with `[doc:functionName]`

**Comment by chapmandu** [comment]
Can we configure which directories the 'Application' docs are generated from?

I have a few directories containing helper function libraries that would be great to document.. what about controllers themselves? A 'self documenting' application would be nice!

**Comment by neokoenig** [comment]
Yeah, I was thinking about that. At the moment, it just inspects `app.models.Model` and `app.controllers.Controller` so the "user" functions are just those which are mixed in: so this won't currently display functions within specific controllers, only those which are available to all models and all controllers.

I think if we start having the list of controllers + models (and view helpers specific to certain directories) then I'd need to rethink the interface, as to load the single page would mean creating/inspecting the meta data on a potentially large number of files in one go.

I shall be giving it some thought though!

**Comment by perdjurner** [comment]
Just a suggestion, let's get the Wheels docs done for 2.0 but move the user app part of it to a 2.1 release maybe?

**Comment by neokoenig** [comment]
Sure - I think this probably should be two separate sections anyway.

**Comment by neokoenig** [comment]
Update, this now supports properly listing plugin based functions too (and marks them as such); Have also added an automatic uncategorized filter so that people can more easily what needs doing

**Comment by neokoenig** [comment]
Should I hide internal params? i.e, `dateSelectTags()` has an internal parameter of `$now` presumably for testing purposes.

**Comment by perdjurner** [comment]
Yes, probably best to hide those.

**Comment by neokoenig** [comment]
This is basically completed; whilst the internal docs need going through and improving, the output is pretty good now. Leaving open to document (ha!) in the guide so dev knows they can use this system if they want

**Comment by neokoenig** [comment]
https://guides.cfwheels.org/v2.0/docs/documenting-your-code added.
Closing
