### ISSUE TITLE
Change dataAttributeDelimiter default

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#741]
The default for this makes more sense as `A-Z.`

That would mean you pass in `dataHelloThere="x"` instead of passing in `data_hello_there="x"` (both translate to `data-hello-there="x"`).

**Comment by chrisdpeters** [comment]
That works as long as the CF engine doesn't translate it to `DATAHELLOTHERE`, which sometimes it has a tendency to do. Maybe it has improved in CF11+?

**Comment by andybellenie** [comment]
I'm not a huge fan of this syntax, I'd prefer to pass in a struct instead: 
``data={helloThere="x", byeBye="y"}``

**Comment by chrisdpeters** [comment]
Yeah, that's the Rails Way™️  to do it too.

That would also force case sensitivity too if you need it:

```
data: { "helloThere"="x", "byeBye"="y" }
```

(Again, not sure if this is a big issue on all of the engines that we support to begin with, though it has been a troublemaker in the past.)

**Comment by perdjurner** [comment]
Looks like we don't even need a setting for this anymore, both `data_dom_cache` and `dataDomCache` will work with the existing code. Must have been something we only needed for CF 8/9 or Railo.

**Comment by perdjurner** [comment]
Wasn't quite that easy, I was tricked by some hyphenize code that only worked for linkTo because of the new routing stuff. Sorted it out in this commit: https://github.com/cfwheels/cfwheels/commit/8935f09a35a1a34e6a173e4e708018d15b10b36b

**Comment by perdjurner** [comment]
No struct support added though.

**Comment by andybellenie** [comment]
Denied!

**Comment by andybellenie** [comment]
I'll create a separate issue :)
