### ISSUE TITLE
Allow use of a struct for html5 data attributes

### ISSUE THREAD

**Issue by andybellenie** [cfwheels/cfwheels#743]
`#textFieldTag(name="input", value="sometext", data={"foo"="bar"})#`

...produces

`<input name="input" value="sometext" data-foo="bar" />`

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
