### ISSUE TITLE
Document DBMigrate features 

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#744]

**Comment by chapmandu** [comment]
Are these docs enough?

https://guides.cfwheels.org/v2.0/docs/database-migrations-getting-started#section-migrator-configuration-settings

https://github.com/cfwheels/cfwheels/commit/26847398fd091ec3069b5c772a7b7feb876d7b26

**Comment by neokoenig** [comment]
Yeah, this will do for now.
Closing.
