### ISSUE TITLE
unify DBMigrate and Model Initialisation of Database adapter

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#746]
We currently have duplicate logic for assigning a DB adapter in DB Migrate and the Main Model initialization script; ideally these should use the same

**Comment by perdjurner** [comment]
Will have to wait until a later release.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
