### ISSUE TITLE
Change log changes

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#747]
Move it to the root, exclude in build script, convert to Markdown, link to issues.

Example:
https://github.com/angular/angular/blob/master/CHANGELOG.md

**Comment by chapmandu** [comment]
Bah.. thought github markdown would automatically link to issues

**Comment by chapmandu** [comment]
https://github.com/cfwheels/cfwheels/commit/03d2fa682b2e50a6a171e8d55b51dc887788dfdc
https://github.com/cfwheels/cfwheels/commit/b222aee8289ff94a52660a868c8db90007a1a07f
https://github.com/cfwheels/cfwheels/blob/master/CHANGELOG.md

**Comment by chrisdpeters** [comment]
Crazy question... do you think that the build should move it back into the `wheels` folder?

**Comment by neokoenig** [comment]
Yes, as when you then want to redistribute your wheels app, you will want your own changelog in the root.

**Comment by chrisdpeters** [comment]
As it stands, I think it's being omitted from the build altogether.

**Comment by perdjurner** [comment]
We could also make better use of the file itself, maybe display it using a link in the debug area.

**Comment by perdjurner** [comment]
> Crazy question... do you think that the build should move it back into the wheels folder?

And maybe do the same for the LICENSE file?

**Comment by chapmandu** [comment]
The changelog is now copied into the wheels directory during the build. I'll do the same for the license.

**Comment by perdjurner** [comment]
License move done, closing.
