### ISSUE TITLE
verifies() should allow paramTypes to apply to all without repetition

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#750]
Consider this (which works):
```
verifies(only="show", get=true, params="version,slug,foobar", 
    paramsTypes="string,string,string", handler="missingParams");
```

Seems like in this scenario, it would be nicer to just be able to pass in "string" and assume it'll be applied to all the items in the params list:

```
verifies(only="show", get=true, params="version,slug,foobar", 
    paramsTypes="string", handler="missingParams");
```
Yay?

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
