### ISSUE TITLE
New Routing doesn't match dots in URL

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#751]
Can someone else comfirm this behaviour I'm seeing?
I feel like URLS should support `.` in the path;

i.e, 
```
/v2.0/foo
```
But I can't get something to match that using
```
drawRoutes() 
   .get(name="foo", pattern="/[version]/[slug]", to="main##show")
   .get(name="foo", pattern="/[version]/", to="main##index")
.end();
```
Or am I being dense? (possible).

**Comment by chapmandu** [comment]
I can confirm.. I've tried the exact same thing, had to go with `/v1/foo`

**Comment by neokoenig** [comment]
ok, but you're with me that the regex/matching is wrong and that this should be expected behaviour? It's probably to do with how `.[format]` is matched; can't remember if this is an issue in `1.x` routing as well, or whether this is a new breaking change

**Comment by chapmandu** [comment]
Agreed all round!

**Comment by chrisdpeters** [comment]
I think that we may need to consider `/` and `.` to be "special characters" in routing. You could probably accomplish `v2.0` if it were hardcoded into the pattern rather than dynamic. Of course, that's less than desirable in certain situations (like if there are thousands of versions).

**Comment by chrisdpeters** [comment]
(Of course, an alternate path is to rewrite the regex to not care about dots as well. Feel free.)

**Comment by neokoenig** [comment]
Ah, found a work around. the `*` match:
```
.get(name="docFunction", pattern="/*[version]/[slug]", to="main##show")
.get(name="docVersion", pattern="/*[version]/", to="main##index")
```
Works with no additional stuff needed. That's good enough for me.
Note, we should document this though

**Comment by perdjurner** [comment]
> I think that we may need to consider / and . to be "special characters" in routing.

Given #762, I think maybe we should, at least for 2.0.

Thoughts?

**Comment by perdjurner** [comment]
Let's document that you can't use `.` and `/` in routing.
Then schedule it for improvement in a later version (2.1 maybe).

**Comment by perdjurner** [comment]
Added some info here:
https://guides.cfwheels.org/v2.0/docs/routing#section-pattern-and-parameters

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
