### ISSUE TITLE
'error', 'route' ,'controller' and 'action' parameters are not listed in the verifies() documentation

### ISSUE THREAD

**Issue by kmd1970** [cfwheels/cfwheels#752]
`error, route, controller, action` parameters are not listed int the verifies() documentation

**Comment by perdjurner** [comment]
I don't think they should be explicitly listed actually.

We do state that "all undeclared arguments will be passed to redirectTo() call if a handler is not specified".

In other words, `controller`, `action` etc are arguments of the `redirectTo` function and are documented there.

If you want to make a pull request to improve the documentation you can find the code in these locations:

https://github.com/cfwheels/cfwheels/blob/master/wheels/controller/verifies.cfm#L3
https://github.com/cfwheels/cfwheels/blob/master/wheels/public/docs/reference/controller/verifies.txt

Thank you.

**Comment by kmd1970** [comment]
Thanks.
