### ISSUE TITLE
Add 'error' parameter to the filters() method, like verifies()

### ISSUE THREAD

**Issue by kmd1970** [cfwheels/cfwheels#753]
It would be nice to have an `error` parameter in the filter() function. This parameter would work the same as with verifies().

```javascript
<cfset filters(through="filterThis", only="myAction" , error="You failed my filter")/>
```

**Comment by chrisdpeters** [comment]
@kmd1970 Why not just raise an exception within the filter itself with that message?

**Comment by chrisdpeters** [comment]
Or have the filter add the message via `flashInsert` and redirect somewhere?

It's not 100% clear to me what an `error` argument for `filters` should even do.

**Comment by kmd1970** [comment]
This parameter would work the same as with verifies().  If filter fails, add an error into The Flash (as a shortcut). But you are correct, right now I am having the filter add the message via flashInsert and redirecting. Just a thought.

**Comment by chrisdpeters** [comment]
@kmd1970 Really, I appreciate the suggestion! Thank you.

**Comment by kmd1970** [comment]
no problem.
