### ISSUE TITLE
Design mode removal

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#754]
We need to update the docs to not mention design mode now that it's been removed.
We should put an alert on the settings that are not thread safe (unless we decide to remove them completely): cacheRoutes, cacheModelInitialization, cacheControllerInitialization.
Add some text in appropriate places that a reload=true request is needed after making changes (can be placed in the config folder and possibly in an example model and controller file).

**Comment by andybellenie** [comment]
Why was this removed? I find design mode extremely useful. Does this mean there is no mode available where models are automatically reloaded each request?

**Comment by perdjurner** [comment]
It was a little confusing to have two modes to choose from when building an app.
Design mode also had some settings that were prone to race conditions.

The `cacheModelInitialization` setting is still available, set it to `false` to get the old behavior back.

**Comment by andybellenie** [comment]
Ok makes sense, we'll need to make the need for reloading very clear for newbies then

**Comment by neokoenig** [comment]
Closing, as I think this is done
