### ISSUE TITLE
Option to add .[format] (in matchers and as a global setting)

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#758]
In the new routing system if you do this:

```
drawRoutes()
  .root(to="main##index")
.end();
```
You get two routes, `/.[format]` and `/`
That seems odd to me?

**Comment by chrisdpeters** [comment]
This is probably a design decision for @cfwheels/core-team to make.

Right now, this is kind of inconsistent. I couldn't tell you which routes add the `.[format]` placeholder, and which don't. I'm sure that `resources` does, but I don't think the individual ones do (`get`, `post`, and friends). I believe that Rails adds the `.[format]` based routes to all.

If we were to remove it from `root`, I think it should only be for the app webroot. There are potential use cases where we'd want for it to draw it, like this one:

```coldfusion
<cfscript>
drawRoutes()
  .namespace("admin")
    .root(to="admins##index")
  .end()
.end();
</cfscript>
```

This would effectively give you a possible path of `/admin.json`, which I think it more realistic to expect than `/.json`.

**Comment by chrisdpeters** [comment]
Sorry, to make it clear what the "design decision" was that I mentioned. Shall we add the `.[format]` matcher to add mapping methods to make it consistent across the entire routing API? Hmm, @cfwheels/core-team?

**Comment by neokoenig** [comment]
I guess I don't mind it in the scenario above; it's just `/.json` which I think we should code around. I'd also like the ability to actually disable `.[format]` completely for a given resource though

**Comment by chrisdpeters** [comment]
Yeah, it would be good to not have it on the app webroot. I'll rename this task to match that scope.

I think we could add it as a setting and probably an argument that can be passed in.

(I think that we should stop with the enhancements until a later release though. :))

**Comment by perdjurner** [comment]
> I think that we should stop with the enhancements until a later release though.

Agreed, focus on getting the breaking changes in this release. If we keep format in the root for 2.0 then we technically can't remove it until 3.0 (semver).

**Comment by perdjurner** [comment]
Fixed, but keeping this issue open since we were discussing other changes as well.

**Comment by perdjurner** [comment]
Other changes, like adding mapFormat to all methods and as a global setting, will be done after 2.0.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
