### ISSUE TITLE
allow the method argument in buttonTo view helper

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#761]
When trying to use:

`#buttonTo(text="Delete", route="thingDelete", key=thing.key(), method="delete")#`

Wheels throws the following exception:
Wheels.IncorrectArguments
The method argument cannot be passed in since it will be set automatically by Wheels.

Workaround is to implement the form:

```
#startFormTag(route="thingDelete", key=thing.key(), method="delete")#
    #submitTag(value="Delete")#
#endFormTag()#
```

**Comment by andybellenie** [comment]
I don't understand this code. What are you trying to do?

**Comment by chapmandu** [comment]
With coldroute built into the core, I want to be able to use the buttonTo helper to use the pseudo delete method.

**Comment by neokoenig** [comment]
I thought it was meant to be `_method` ?

**Comment by chapmandu** [comment]
No, it should be `method` as can be used with `startFormTag(method="delete"...)` which renders the markup:

```
<form action="/things/123" method="post">
    <input id="_method" name="_method" value="DELETE" type="hidden">
</form>
```

**Comment by chapmandu** [comment]
https://github.com/cfwheels/cfwheels/commit/4838bcf65bf02b19c36d3894cbcbebbac7277cea

**Comment by chrisdpeters** [comment]
Very nice. I'll have to update the linking docs to use this method because it is much nicer than what I have in there right now.
