### ISSUE TITLE
2.x Routing with .format should only match when format is in approved list

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#762]
Consider these routes:

```
.get(name="docFunction", pattern="/*[version]/*[slug]/.[format]", to="main##show")
.get(name="docFunction", pattern="/*[version]/*[slug]", to="main##show")
```
which gives
```
/[version]/[slug].[format]
/[version]/[slug]
```
If `slug` contains a `.` this gets matched with `.[format]` : 

i.e, 

```
/v2.0.0/model.findall/
```
Will result in 
```
version  = v.2.0.0
slug  = model
format = findall
```
(Whereas I want it match the second route). 

Essentially, I want to be able to do:
```
/v2.0.0/model.findall.json
/v2.0.0/model.findall
/v2.0.0/findall.json
/v2.0.0/findall
```

I think `[format]` should only match formats which are allowed via `provides()`
Thoughts?

**Comment by neokoenig** [comment]
ps, there is a work around, but it involves *always* passing in the format attribute and requires `.html` in the URL which I was trying to avoid.

**Comment by chapmandu** [comment]
Makes sense to me..

**Comment by perdjurner** [comment]
Let's document that you can't use `.` and `/` in routing.
Then schedule it for improvement in a later version (2.1 maybe).

**Comment by perdjurner** [comment]
Added some info here:
https://guides.cfwheels.org/v2.0/docs/routing#section-pattern-and-parameters

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
