### ISSUE TITLE
URLFor() does not default to the current action

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#763]
When doing `#URLFor()#` on a page like `/mycontroller/myaction` it outputs just `/mycontroller`.

Pre 2.0 it would output `/mycontroller/myaction`.

@cfwheels/core-team anyone know when / why this changed?

**Comment by neokoenig** [comment]
And if that is the case - shouldn't this have failed some unit tests?

**Comment by chrisdpeters** [comment]
I can think of a feature that really messed around with `urlFor`...
