### ISSUE TITLE
Calculated properties should be able to override an existing property

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#764]
It appears that you can't use a calculated property to override an existing column. It appears that wheels ignores the `firstname` property below and just selects the column from the database unmolested.

```
component extends="Model" {

  function config() {
    property(
      name="firstname", 
      sql="IFNULL(firstname, 'These are not the properties you are looking for')"
    );
  }

}
```

**Comment by andybellenie** [comment]
Agreed it would be welcome to fix this, although I rarely use calculated properties anymore, preferring database specific tools (computed columns when available, triggers if not)

**Comment by perdjurner** [comment]
Yeah, I would consider this a bug.
