### ISSUE TITLE
Allow uppercase table names containing reserved substrings like OR AND

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#765]
Allow the use of table names such as `IMPORTS`, `CATEGORIES` and `BANDS`.

Porting legacy applications to cfwheels often prevents the use of wheels conventions. Databases that are table name case sensitive make workarounds (eg. `table("categories")` more difficult.

The following code using a table name of `CATEGORIES` throws an exception as the wheels sql parser is separating statements using `OR` as a delimiter.

`model("category").findAll(where="CATEGORIES.ID = 1");`

Wheels looked for the column mapped to the `IES.ID` property but couldn't find it in the database table. sql.cfm line 424

**Comment by chapmandu** [comment]
Failing test: https://github.com/cfwheels/cfwheels/blob/master/wheels/tests/model/crud/findall.cfc#L81

**Comment by perdjurner** [comment]
Is your database case sensitive?

If not, you can use `set(lowerCaseTableNames=true)` as a work-around I think.

**Comment by perdjurner** [comment]
Well, after having coffee I now realize that you can ignore my comment above :)

**Comment by perdjurner** [comment]
Is this happening on 2.0.1 as well?

**Comment by chapmandu** [comment]
I believe so.. There are commented out failing tests and my colleague has developed a fix. Leave this open and I'll commit.

**Comment by perdjurner** [comment]
Labeling as bug for now but we may need to simply make a rule that this is not supported and document it.
