### ISSUE TITLE
Allow for automatic database Migrations on application start

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#766]
This would comprise of several parts: 

- [x] Add ability to turn off environment switching via URL
 - Note: Dev should still be able to reload app via `?reload=true&password=foo`
- [x] Add environment setting of `allowEnvironmentSwitchViaUrl`, defaulting to `true`
- [x] Add an additional convenience method of `migrateToLatest()` for dbmigrate
- [x] Add environment setting of `autoMigrateDatabase`, defaulting to `false`

Why would you want this? Use cases would be:
 - You want to lock down environment switching, i.e, only ever allow `production` mode for security lockdown purposes: with "more" in the core now, i.e, Routing GUI, Migration GUI and internal embedded documentation, I can imagine this being popular.
 - You want to be able to migrate your database without having to switch to maintenance mode, then switching back again
- You want to update your db via migrate but you use elastic beanstalk/cluster/loadbalancer, and if you have a session-less app (like an api) you might not get routed to the same instance each time (thus some instances would be in maintenance mode and you can't easily get "back" to them)
 - You have a codebase where people update their code, and just want it to "work" - a la wordpress updaters etc.

Caveats:
 - This would fire for each node on a cluster and would fire on each application restart; however, I think the overhead is minimal.
 - Errors would be difficult to rectify; however, there is an assumption that the developer has run the migrations locally first at least..

Would welcome any further suggestions before I implement.

**Comment by chapmandu** [comment]
I don't have any suggestions but would be the fury to disable environment switching and enabling migration on application start!

**Comment by perdjurner** [comment]
Nice!

Only docs left?

Moving out of the Beta milestone then.

**Comment by neokoenig** [comment]
Yarp :)

**Comment by neokoenig** [comment]
This feature now documented at https://docs.cfwheels.org/v2.0/docs/migrations-in-production - still need to do the rest of the dbmigrate docs though
