### ISSUE TITLE
Implement dbmigrate redo command

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#767]
The dbmigrate `redo` task is a shortcut for doing a rollback and then migrating back up again as used in rails. 

Mainly a convenience method for developing migrations. It defaults to the latest version but could accept a version param. 

- [x] `redo()` function
- [x] redo from CLI
- [x] redo from GUI
- [x] revert dbmigrate version 001 in teardown in unit test

**Comment by neokoenig** [comment]
Basically done now - I'll leave @chapmandu to update the tests

**Comment by chapmandu** [comment]
Unit test passes in isolation but fails when run as part of the dbmigrate package. I can't see why?! 💢
