### ISSUE TITLE
hasManyCheckBox should throw exception if association does not exist

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#770]
As it is, configuring many-to-many nestedProperties and hasManyCheckBox is a challenge. This is made trickier when the `hasManyCheckBox()` will accept any `association` value with impunity. 

If an assocation called `foobars` does not exist on the `user` model wheels should throw an error with a message to that effect. This should provide some guidance at least.
 
Bonus points for also checking that the keys exist in the correct order on the "bridge" table.

```
#hasManyCheckBox(
	label=sections.name,
	objectName="user",
	association="foobars",
	keys="#user.key()#,#things.id#"
)#
```

**Comment by neokoenig** [comment]
Am I being stupid or are there no core tests for `hasManyCheckBox()`?

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
