### ISSUE TITLE
Redo migration error

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#771]
The dbmigrate.dbmigrate.redomigration test fails for me on MySQL with:

An exception occurred when committing the transaction.
...wheels\dbmigrate\functions.cfm line 219
The root cause of this exception was: java.sql.SQLException: Can't call commit when autocommit=true

**Comment by chapmandu** [comment]
@perdjerner Can you please try this again with the latest changes.. It may have been due to nested transactions.

**Comment by perdjurner** [comment]
Yep, all good now.
