### ISSUE TITLE
findAll Where clause issue with OR and an empty string

### ISSUE THREAD

**Issue by dbelanger** [cfwheels/cfwheels#774]
I just came across this error which I thought needs immediate attention.  I'm using the latest master and running MySQL 5.6.31.

I first discovered this because my connections weren't being deleted.  In my string, I was searching for a connection by **id OR hardwareid**.  When there is a value in each string, it works.  When there is a value in the first param (id=connectionID), but none in the second param, it works.  When there is no value in the first param but there is in the second, it fails. In effect, it should be passing '' to MySQL.

Please see the code below to see what gets output with an empty string (I used findAll to illustrate but it's the same problem with deleteAll).

`testVar = model("connection").findAll(where="id='#trim(PARAMS.connectionID)#' OR hardwareid='#trim(PARAMS.hardwareid)#'");`

When you look at the output, you'll see that the empty string is causing parameters to be incorrectly identified.

`SELECT connections.id,connections.hardwareid,connections.createdAt,connections.updatedAt,connections.deletedAt FROM connections WHERE ( connections.id = ? ) AND ( connections.deletedAt IS NULL )`
`1: ' OR hardwareid='12345`

Now, when I fill the first param and not the second, it works just fine.  Here's the output:

`SELECT connections.id,connections.hardwareid,connections.createdAt,connections.updatedAt,connections.deletedAt FROM connections WHERE ( connections.id = ? OR connections.hardwareid = ? ) AND ( connections.deletedAt IS NULL )`
`1:E9FEA20D-060B-B5A0-D266A221B685E67D`
`2:[empty string]`

**Comment by perdjurner** [comment]
The Wheels ORM doesn't support blank strings.

See this for more info:
https://guides.cfwheels.org/v1.4/docs/object-relational-mapping#section-blank-strings-and-null-values

Going to leave this open though as I think we should attempt to handle this better (ideally, when you do findAll(where="something = ''") we should convert that to findAll(where="something IS NULL")).

**Comment by perdjurner** [comment]
Fixed.

Your code should now work but it will be converted to `IS NULL` instead.

If you don't want that you can set `convertBlankStringToNull` to `false`.

**Comment by dbelanger** [comment]
Excellent.  I've tested this change and is does fix my problem.  I also agree that it keeps thing more consistent.
