### ISSUE TITLE
2.x Documentation Push

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#775]
Trying to get a list of all the things which the main 2.0 branch on [https://guides.cfwheels.org](https://guides.cfwheels.org) needs to be checked for..

- [ ] Convert all code samples into cfscript
- [x] Replace all `init()` in code samples to `config()` (except plugins)
- [ ] Replace direct links to functions/methods to reference `api.cfwheels.org`
- [ ] Add a new deployment chapter
- [x] Add new chapter on "documenting your code" to reference the new internal docs system
- [ ] Revisit most of the basic stuff with resource driven development in mind
- [x] Update testing guides to use new processRequest helpers etc
- [x] Remove all references to design mode

**Comment by perdjurner** [comment]
I've handled the init / config and design / development mode changes.

**Comment by neokoenig** [comment]
Closing as merging into #811
