### ISSUE TITLE
Simplify testing API / docs

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#778]
Look into whether it makes sense to make all low level functions like `processAction()`, `getRedirect()` etc private ($) in favor of using `processRequest()` instead.

Perhaps keep only `controller()` on the public scope so that controller helper functions can be tested separately (i.e. functions that are independent of a specific request).

This way we can perhaps set up a test structure consisting of these folders:
- requests
- functions

The `requests` folder would be where you use the `processRequest()` function to test requests / responses. The `functions` folder would be for testing directly against controller, model, and global functions on a lower level (e.g. `controller("test").myFunc()`, `model("user").doesThisWork()`, `someGlobalFunc()` etc).

**Comment by perdjurner** [comment]
I've made the folder naming changes.

Let's keep the `processAction()`, `getRedirect()` etc public but don't focus on them when writing docs (since if they're needed at all it would be in very edge cases).

All testing should be made through global functions, `processRequest()`, `model()` or `controller()` and that's what we should document.

**Comment by chapmandu** [comment]
Docs have also been updated:

https://dash.readme.io/project/cfwheels/v2.0/docs/testing-your-application

**Comment by perdjurner** [comment]
Great, thank you.
