### ISSUE TITLE
Review dbmigrate setting names

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#782]
Some have suggested that the `dbmigrate` prefix is a little odd.
```
dbmigrateTableName = "schemainfo"; // defines the table name where migration versions are stored
dbmigrateWriteSQLFiles = false; // whether to write .sql files when migrations are performed
dbmigrateObjectCase = "lower"; // define database object case
dbmigrateAllowMigrationDown = false; // whether to allow migrating "down" (rollback)
```

**Comment by perdjurner** [comment]
On a related note, I think we're planning on renaming dbmigrate.cfc, variables etc to "migrator".

**Comment by chapmandu** [comment]
With this in mind.. and using my unparalleled creativity, how about:
```
migratorTableName
migratorObjectCase
writeMigratorSQLFiles
allowMigrationDown
```

**Comment by neokoenig** [comment]
If we're removing all instances of dbmigrate, then we need to do some folder renaming too. Since everyone is going to have to update their templates anyway, I don't think this is a huge deal; but we should do it now before everyone starts using it!

**Comment by chapmandu** [comment]
What do you guys think about the current migrator table name `schemainfo`? It would make more sense to be something like `migrations` but could cause headaches for those already using the dbmigrate plugin.. Sure one could just rename the table in all environments, but would need to be timed carefully.

**Comment by perdjurner** [comment]
Yes, `migrations` makes a lot more sense to me (I remember being confused by `schemainfo` myself).

**Comment by chapmandu** [comment]
Is the name too common? Would it cause issues for people with duck tracking applications?

**Comment by neokoenig** [comment]
Changed to `migratorversions` as discussed on slack.
Leaving open to document breaking change

**Comment by chapmandu** [comment]
https://guides.cfwheels.org/v2.0/docs/database-migrations-getting-started#section-migrator-configuration-settings

https://github.com/cfwheels/cfwheels/commit/26847398fd091ec3069b5c772a7b7feb876d7b26
