### ISSUE TITLE
Missing var on loc variable in 1.4 version

### ISSUE THREAD

**Issue by dyakhnov** [cfwheels/cfwheels#783]
File: /wheels/model/callbacks.cfm
Function: $callbacks

has no declaration of var loc = {}; therefore returned object might be NULL randomly (I think once GC kicks in).

https://github.com/cfwheels/cfwheels/blob/1.4/wheels/model/callbacks.cfm#L142

**Comment by chapmandu** [comment]
What to do with this issue?

**Comment by perdjurner** [comment]
We should release 1.4.6 as soon as possible but we should probably back-port other stuff first.

**Comment by perdjurner** [comment]
We can close the issue itself though, if that's what you meant :)
