### ISSUE TITLE
Allow hasMany() to join on multiple columns

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#788]
This would be a nice feature that would allow you to specify multiple columns to join on.
Eg:
```
// modesl/User.cfc
hasMany(name="Posts", joinType="outer", joinAppend="someid = 2");
```

Would generate the join SQL:
`LEFT JOIN posts ON users.id = posts.userid AND someid = 2`

In theory, it may be quite a simple addition..

Below is a crude working (literal) example.. but I would imagine the proper solution would take property metadata into account.
```
if(StructKeyExists(loc.classAssociations[loc.name], "joinAppend")) {
  loc.toAppend = ListAppend(loc.toAppend, loc.classAssociations[loc.name].joinAppend);
}
```
Added to https://github.com/cfwheels/cfwheels/blob/master/wheels/model/sql.cfm#L647

* `joinAppend` is only a suggested name

@dyakhnov

**Comment by perdjurner** [comment]
Since we support composite primary keys, shouldn't this already work? Maybe if you pass in a comma separated list to the `foreignKey` argument?

**Comment by dyakhnov** [comment]
Proposed [joinAppend] does not refer to a key in other table, but rather simple numerical value.

Indeed, we can create dummy [some] table with [id] in there and use composite join =)

**Comment by perdjurner** [comment]
What's the use case for this?
A real world example would be great.
Thanks.

**Comment by dyakhnov** [comment]
[permissions]
id = PK
read = bit
write = bit
...

[users]
id = PK
name = varchar
...

[groups]
id = PK
name = varchar
...

[roles]
id = PK
name = varchar
...

[access]
id = PK
type_id = int (1 = user, 2 = group, 3 = role)
object_id = int (FK to user, group or role)

so [user] will have
hasMany(name="access", foreignKey="object_id", joinType="outer", joinAppend="type_id=1");

**Comment by perdjurner** [comment]
Thanks.

Is this suggestion essentially the same as this one:
https://github.com/cfwheels/cfwheels/issues/469
?

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
