### ISSUE TITLE
application.wheels does not exist creating default migrator table

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#791]
Message 	The key [WHEELS] does not exist, but there is a similar key with name [$WHEELS] available. Here is a complete list of all available keys: [$WHEELS,applicationname].
Stacktrace 	The Error Occurred in
/dev/wheels/migrator/functions.cfm: line 318

    316: } catch (any e) {
    317: $query(
    318: datasource=application.wheels.dataSourceName,
    319: sql="CREATE TABLE #application.wheels.migratorTableName# (version VARCHAR(25))"
    320: );

called from /dev/wheels/migrator/functions.cfm: line 149
called from /dev/wheels/migrator/functions.cfm: line 102
called from /dev/wheels/events/onapplicationstart.cfm: line 396 

Using `reload=true` has no effect.

**Comment by perdjurner** [comment]
For anything in the Migrator that can be called during application start we probably need to use the `$appKey()` function to get the correct struct key name to use (`wheels` or `$wheels`).

**Comment by chapmandu** [comment]
Closed via https://github.com/cfwheels/cfwheels/commit/fb0dbe8603f970eb88d0129589c66e27728a06ac
