### ISSUE TITLE
Fix encoding on buttonTo()

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#798]
This seems buggy, probably because we're calling `submitTag()` internally and not passing along the `encode` argument properly.

**Comment by neokoenig** [comment]
Still an issue when passing in HTML for icons: 
```
#buttonTo(
                text="<i class='fa fa-trash-o'></i>",
                route="myroute",
                encode="attributes",
                key=params.key,
                method="delete",
                class="inline",
                inputClass="text-danger btn btn-danger btn-xs no-border-radius",
                title="Delete"
            )#
```

Encode attributes still escapes what's going into `text=`

**Comment by perdjurner** [comment]
This doesn't work in 1.4.6 either, or perhaps it works but it makes no sense to pass in HTML to something that goes in the `value` attribute of an `input` element anyway, right?

Can you have a closer look at this and let me know what you think the final HTML should be for your buttonTo call?

**Comment by neokoenig** [comment]
Ok, I think you're absolutely right about the HTML value in the `input` element. I was thinking in my head that `buttonTo()` would create a `<button>stuff</button>` which it doesn't.

However, there's a sneaky work around for this which I've just discovered which means you can have icons in the value field from font awesome by using the unicode value:

```
// Note: we need to use double ##'s as we're in CFML, obvs. 
#buttonTo(
  text="&##xf014;",
  route="myRoute", 
  key=id,
  method="delete",
  class="inline fa",
  inputClass="text-danger btn btn-danger btn-xs no-border-radius",
  title="Delete"
)#
```

This renders:
```
<form action="/admin/bookings/39" class="inline fa" confirm="Are you Sure?" method="post" title="Delete">
<input id="_method" name="_method" type="hidden" value="delete">
<input class="text-danger btn btn-danger btn-xs no-border-radius" type="submit" value="">
<input id="authenticityToken" name="authenticityToken" type="hidden" value="o94yijlxy908vg3oxa8t6pswv9bs04boodroqp9p">
</form>
```

(Obviously the `` doesn't display in source code view, but it does render the trash icon from font awesome in this example) - so assuming you can use the unicode version of a font like this, it should actually cover most people's use cases in wanting to put HTML in the `<input>` - I think it's an acceptable workaround.

If people need more control, then they can do it via jQuery with the rails.js.

This might be worth documenting though - I think I'll do a blog post on how to do a basic CRUD interface in 2.x

**Comment by perdjurner** [comment]
Pretty cool!

No issues with encoding for that work-around then, right?

**Comment by neokoenig** [comment]
Nope, and you don't need `encode="attributes"` either..

**Comment by tsucaet** [comment]
If wheels could render the buttonTo() function to actually a `<button type="submit"></button>` tag (instead of `<input type="submit">`) then this could easily be fixed.

As an experiment I comment out this line https://github.com/cfwheels/cfwheels/blob/master/wheels/view/links.cfm#L137
and changed this line 
https://github.com/cfwheels/cfwheels/blob/master/wheels/view/links.cfm#L140 
into
`local.content &= buttonTag(argumentCollection=local.args, content=arguments.text);`

Now my delete button renders nice with a small Font Awesome 5 icon. 

```
#buttonTo(
  text='<i class="fas fa-trash"></i>',  
  route="myRoute",   
  method="delete", 
  key=id, 
  inputClass="btn btn-xs btn-danger", 
  encode="attributes"
)#
```
Probably this needs some code review, but this seems to be working if you want to render Font Awesome icons for the buttonTo() function.

**Comment by neokoenig** [comment]
Reopened: we really should change this for the next release.
See also https://groups.google.com/forum/?fromgroups=#!topic/cfwheels/jIyEr1y2zp8

**Comment by geirman** [comment]
Seems like a strange decision to go with `<form...><input type="submit"></form>` rather than what seems like the more natural `<form...><button type="submit"></form>` solution. I wonder what the original reasoning was.

**Comment by neokoenig** [comment]
That's the thing with a framework which has been going over 10 years. Occasionally you do hit something and think.. wtf? :)

**Comment by geirman** [comment]
😂 oftentimes, it's my own code! In cases like these, when you do the unexpected for a good reason, comments are gold!

**Comment by perdjurner** [comment]
> I wonder what the original reasoning was.

I think that back in the day, using `input` was more reliable across browsers in terms of what they POST back when sending the form. Probably safe to change it now.
