### ISSUE TITLE
afterFind callbacks cause returnIncludedAs="object" to be ignored

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#801]
Instead returns included object as struct. 

```
mypost = model("postWithAfterFindCallback").findOne(include="author", returnIncludedAs="object");
assert("IsObject(mypost.author)");
```

Added failing test:
https://github.com/cfwheels/cfwheels/blob/14bf40380fc84ca675c766670f2423e95e1cd082/wheels/tests/model/properties/properties.cfc#L147

**Comment by perdjurner** [comment]
Do you know when this bug was introduced?

**Comment by chapmandu** [comment]
It was introduced with the properties `returnIncludedAs` argument.. so 2.0

**Comment by perdjurner** [comment]
Is it possible to pinpoint the exact commit?

**Comment by chapmandu** [comment]
https://github.com/cfwheels/cfwheels/commit/7dd5a32ae4bd159a927c653f641c51dcde871b7f#diff-9e0d18cbc751a947667459daec47c8d3

**Comment by perdjurner** [comment]
The `returnIncludedAs` argument is not documented as being available on `findOne()`. Should it be, or is it only meant to be used when calling `properties()`?

**Comment by chapmandu** [comment]
Closed by removing `returnIncludedAs` argument from model `properties` method.

https://github.com/cfwheels/cfwheels/commit/15f6708926a80feab9a841930eb4e3dee7f36990
