### ISSUE TITLE
Wheels.RouteNotFound error (during Beginner Tutorial: Hello Database)

### ISSUE THREAD

**Issue by dogsoldier68** [cfwheels/cfwheels#805]
I followed all the steps to create the Beginner Tutorial: Hello Database, but I got a bug on the page after I submitted the  little form with name , email, and password.

Wheels.RouteNotFound

Could not find a route that matched this request.

Suggested action

Make sure there is a route configured in your config/routes.cfm file that matches the users/create request.

Tag context

Error thrown on line 111 in wheels\dispatch\functions.cfm
- called from line 177 in wheels\dispatch\functions.cfm
- called from line 143 in wheels\dispatch\functions.cfm
- called from line 5 in wheels\index.cfm
- called from line 2 in index.cfm
- called from line 5 in wheels\events\onrequest.cfm

**Comment by perdjurner** [comment]
On what version of Wheels was this?

**Comment by dogsoldier68** [comment]
*2.0.0 Beta 1*

**Comment by neokoenig** [comment]
I'm afraid that tutorial has not yet been updated to reflect the new routing system in 2.x
This is part of our job at the moment during beta, to go through and update all the documentation

**Comment by perdjurner** [comment]
Closing, will handle here instead:
https://github.com/cfwheels/cfwheels/issues/811
