### ISSUE TITLE
Add progress bar to test suite

### ISSUE THREAD

**Issue by tapirus** [cfwheels/cfwheels#807]
Hi,
wouldn't it be helpful to have a progress bar in the test suite?
One could see for example, still 80 from 200 tests to run - enough time to clean up the kitchen.
Also the current running test could be shown, or a list of all already run tests.
What do you think?

**Comment by chrisdpeters** [comment]
I don't think the test page even renders in the browser until all of the tests have completed.

**Comment by neokoenig** [comment]
It doesn't. However, there is an undocumented version of the test suite which fires off all the requests one after another via ajax. You even get a little 80/200 counter incrementing in realtime. However, if it get's stuck, you might have to have the developer console open to get the error message.

To get to it, just change the `view` parameter from `tests` to `ajax`, i.e:
`?controller=wheels&action=wheels&view=ajax&type=app`

This is all undocumented and quite unofficial, so YMMV.

**Comment by tapirus** [comment]
Cool! A hidden gem. I will try it out!

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
