### ISSUE TITLE
Circular Deadlock

### ISSUE THREAD

**Issue by cod-y** [cfwheels/cfwheels#809]
Hello,

I semi-frequently see cfwheels applications involved in a circular deadlock. I've attached a threaddump with the full stacktrace of the two requests involved in the deadlock. Is there an issue with cfwheels that is causing this? I've searched through the project's "Issues" history and I couldn't find anything about a deadlock.

If more information is required for troubleshooting, please let me know and I would be happy to provide what I have.

[deadlock-threaddump.txt](https://github.com/cfwheels/cfwheels/files/1191308/deadlock-threaddump.txt)

**Comment by perdjurner** [comment]
Wheels out of the box shouldn't cause any deadlock issues but perhaps a plugin could, do you have any installed?

**Comment by neokoenig** [comment]
Also - to confirm, exactly which version of wheels?

**Comment by cod-y** [comment]
I'm using version 1.1.8. The only thing in the plugins directory is "injection.cfm", which appears to be included with that version of cfwheels. Is support for such an older version likely or should I look at upgrading?

**Comment by neokoenig** [comment]
IIRC, 1.3.x fixed some thread related locking issues. Ideally, I'd look to jump to 1.4.5 as the work you'd need to do is the same as going from 1.1.8 ->1.3.x really.

**Comment by neokoenig** [comment]
Check https://github.com/cfwheels/cfwheels/blob/master/CHANGELOG.md for more detail

**Comment by cod-y** [comment]
I'll let the customer know. Hopefully they'll go with the upgrade. I'll follow up only if the issue persists after an upgrade to 1.4.5. Thanks 👍
