### ISSUE TITLE
Review and update all guides

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#811]
We need to read through (and code through) all guides and update them so they take into account all the new stuff we've added.

Things to look for:
 - Any links to `doc:functionName` references to be version agnostic permalinks: i.e, https://api.cfwheels.org/model.save.html (this will redirect to https://api.cfwheels.org/v2.0/model.save.html). However, links to other chapters in the guides should remain as `doc:someChapter` links
 - Any reference to `design` mode should be removed
 - `init()` to replaced with `config()` except in plugins
 - All code examples should use cfscript. Use the "javascript" colour formatting dropdown in readme and give each code block a title (even if that's just "Example")
 - Check all instances of `renderPage` -> `renderView`

INTRODUCTION

- [x] Frameworks and CFWheels
- [x] Requirements
- [x] Installation
- [x] Upgrading
- [x] Beginner Tutorial: Hello World
- [x] Beginner Tutorial: Hello Database
- [x] Tutorial: CFWheels, AJAX, and You
- [x] Screencasts

COMMANDBOX & CLI

- [x] Getting Started
- [x] CLI Commands - this is pretty much in Alpha development anyway. Have added a note to that effect

WORKING WITH CFWHEELS

- [x] Conventions.
- [x] Configuration and Defaults - NB added Migrator Settings/allowEnvironmentSwitchViaUrl
- [x] Directory Structure 
- [x] Switching Environments - added note on allowEnvironmentSwitchViaUrl, removed Design mode
- [x] Testing Your Application
- [x] Contributing to CFWheels

PLUGINS

- [x] Installing and Using Plugins
- [x] Developing Plugins
- [x] Publishing Plugins

HANDLING REQUESTS WITH CONTROLLERS

- [x] Request Handling - done, but I can't help feeling this needs to introducing routes earlier
- [x] Rendering Content
- [x] Redirecting Users
- [x] Sending Files
- [x] Sending Email
- [x] Responding with Multiple Formats
- [x] Using the Flash
- [x] Using Filters
- [x] Verification
- [x] Event Handlers
- [x] Routing
- [x] URL Rewriting
- [x] Obfuscating URLs
- [x] Caching
- [x] Add new subpage about nested controllers and models and use of 'app' mapping: added https://guides.cfwheels.org/v2.0/docs/nesting-controllers

DATABASE INTERACTION THROUGH MODELS

- [x] Object Relational Mapping
- [x] Creating Records
- [x] Reading Records
- [x] Updating Records
- [x] Deleting Records
- [x] Column Statistics
- [x] Dynamic Finders
- [x] Getting Paginated Data
- [x] Associations
- [x] Nested Properties
- [x] Object Validation
- [x] Object Callbacks
- [x] Calculated Properties
- [x] Transactions
- [x] Dirty Records
- [x] Soft Delete
- [x] Automatic Time Stamps
- [x] Database Migrations
- [x] Using Multiple Data Sources

DISPLAYING VIEWS TO USERS

- [x] Pages
- [x] Partials
- [x] Linking Pages
- [x] Layouts
- [x] Form Helpers and Showing Errors
- [x] Displaying Links for Pagination
- [x] Date, Media, and Text Helpers
- [x] Creating Custom View Helpers

**Comment by neokoenig** [comment]
URL rewriting updated - https://guides.cfwheels.org/v2.0/docs/url-rewriting now has sub pages for each server specific config and example markup for rewrite files.

**Comment by neokoenig** [comment]
Note to self. Change all `doc:functionName` references to be version agnostic permalinks: i.e, `https://api.cfwheels.org/model.save.html` (this will redirect to https://api.cfwheels.org/v2.0/model.save.html)

**Comment by neokoenig** [comment]
Done!
