### ISSUE TITLE
encode="attributes" does throw error on paginationLinks()

### ISSUE THREAD

**Issue by tapirus** [cfwheels/cfwheels#816]
Hi,
If I add endoce="attributes" to paginationLinks() it throws

Lucee 5.2.2.71-RC Error (expression)
--
Message | Can't cast String [attributes] to a boolean
Stacktrace | The Error Occurred in 					 						 						 						  							  							 			D:\websites\mysite.com\wheels\view\links.cfm: line 251 							 							  							 								249:  250: 	// Encode all prepend / append type arguments if specified. 251: 	if (arguments.encode && $get("encodeHtmlTags")) { 252: 		if (Len(arguments.prepend)) { 253: 			arguments.prepend = EncodeForHtml($canonicalize(arguments.prepend));

**Comment by perdjurner** [comment]
Are you calling just `paginationLinks()` or are you passing in any arguments to it?

**Comment by tapirus** [comment]
I use it in config/settings.cfm like this
set(functionName="paginationLinks", 			
			prepend="<ul class=""pagination"">", 
			append="</ul>", 
			prependToPage="<li>", 
			appendToPage="</li>", 
			linkToCurrentPage=true, 
			classForCurrent="active", 
			windowSize=3,
			anchorDivider="<li class=""disabled""><a href=""##"">...</a></li>");
and get the error above by adding encode="attributes"

Does this help?

**Comment by perdjurner** [comment]
Fixed in this commit I think:
https://github.com/cfwheels/cfwheels/commit/ed425d10ecf390e05e4b1b48467830532c88e461

Please try and make the same changes in your CFWheels copy and see if it fixes it for you.

Thanks.

**Comment by tapirus** [comment]
Hi Per, the error went away. Thanks for the fast fix. Thorsten
