### ISSUE TITLE
CFWheels 2.x beta - COALESCE() not evaluated in ORM query on SQL Server 2012

### ISSUE THREAD

**Issue by tapirus** [cfwheels/cfwheels#817]
Hi,

some of my ORM queries won't work anymore in cfwheels 2.x.
It seems that COALESCE() ist not evaluated anymore in cfwheels 2.x.

For example in the query
liftgroups = model("LiftGroup").findAll(                                
            select="ID,              
                COALESCE(Category_de_DE, Category_de_DE) AS Category",       
            group="ID,            
                COALESCE(Category_de_DE, Category_de_DE)",

will lead to
COALESCE(Category_de_DE, Category_de_DE),

and not to
Category_de_DE
anymore.

de_DE could be en_US, es_ES for example.

This is on Luce 5.x and SQL Server 2012.
My test cases with COALESCE in group do fail now.
I guess this is a regression, but I don't know, it COALESCE was officially supported in 1.x, but it used to work anyway.

**Comment by perdjurner** [comment]
I've done some testing and `COALESCE` still works fine when used in the `select` argument when you also pass in `AS` (the `AS` part is what tells Wheels that it should pass along the `SELECT`unchanged to the database).

`COALESCE` is not supported in the `group` argument (and never was).

I would recommend using calculated properties instead to see if that helps (or revert to using plain queries for this part of your app):
https://guides.cfwheels.org/v2.0/docs/calculated-properties
