### ISSUE TITLE
Mapping of Buttons "run all tests" and "reload test data"

### ISSUE THREAD

**Issue by michaeldiederich** [cfwheels/cfwheels#820]
The current links of the buttons "run all tests" and "reload test data" are not working without a mapping or an alias. If you could change the links to `/rewrite.cfm?controller=wheels&action=wheels&view=tests&type=app` so that the buttons would not cause an 404 any more. @neokoenig knows how to reproduce, just in case :) Thank you very much.

**Comment by michaeldiederich** [comment]
Line 21+22 are now the same as in 
\wheels\public\ajax.cfm
\wheels\public\packages.cfm

file: \wheels\public\tests\html.cfm

[html.cfm.txt](https://github.com/cfwheels/cfwheels/files/1370883/html.cfm.txt)

**Comment by neokoenig** [comment]
Fixed in 2.0.1
