### ISSUE TITLE
Need to set "dbname" when using custom connection string

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#822]
Wheels is currently using `cfdbinfo` internally without specifying `dbname`.

This works fine most of the time but not when you use a custom connection string it seems.

Example:
`connectionString: 'jdbc:mysql://example.com:3306/thedatabase?nullNamePatternMatchesAll=true'`

Now Wheels can't pick up on the fact that `thedatabase` is the database to use and instead returns all databases that the data source has access to. This typically includes the "information_schema" database, and if Wheels then tries to use that one for getting column and table details, everything breaks.

**Comment by perdjurner** [comment]
A possible fix is to explicitly set `dbname` in `$dbinfo` by filtering out "information_schema" and use whatever is left.

```
<cffunction name="$dbinfo" returntype="any" access="public" output="false">
	<cfset arguments.name = "local.rv">
	<cfif StructKeyExists(arguments, "username") && !Len(arguments.username)>
		<cfset StructDelete(arguments, "username")>
	</cfif>
	<cfif StructKeyExists(arguments, "password") && !Len(arguments.password)>
		<cfset StructDelete(arguments, "password")>
	</cfif>

	<!---
		Get database name to use (sometimes it's unknown because it's specified inside a connection string).
		When that happens CF will just get any of the database that the data source has access to (which can incorrectly be "information_schema" for example).
	--->
	<cfif arguments.type IS NOT "version">
		<cfset local.type = arguments.type>
		<cfset arguments.type = "dbnames">
		<cfdbinfo attributeCollection="#arguments#">
		<cfif local.rv.recordCount GT 1>
			<cfloop query="local.rv">
				<cfif database_name IS NOT "information_schema">
					<cfset arguments.dbname = database_name>
				</cfif>
			</cfloop>
		</cfif>
		<cfset arguments.type = local.type>
	</cfif>

	<cfdbinfo attributeCollection="#arguments#">

	<!--- Override name of database adapter when running internal tests --->
	<cfif arguments.type IS "version" AND StructKeyExists(url, "controller") AND StructKeyExists(url, "action") AND StructKeyExists(url, "view") AND StructKeyExists(url, "type") AND StructKeyExists(url, "adapter")>
		<cfif url.controller IS "wheels" AND url.action IS "wheels" AND url.view IS "tests" AND url.type IS "core">
			<cfset QuerySetCell(local.rv, "driver_name", url.adapter)>
		</cfif>
	</cfif>

	<cfreturn local.rv>
</cffunction>
```

I'll commit this later but wanted to see if anyone has any input first.

**Comment by neokoenig** [comment]
Nice find. I assume that's due to this: https://groups.google.com/forum/?fromgroups#!topic/cfwheels/Gi4wbC7NR0E ?

Is there a possibility that it could return multiple DB's (even after excluding schema_info?)

**Comment by perdjurner** [comment]
> Nice find. I assume that's due to this: https://groups.google.com/forum/?fromgroups#!topic/cfwheels/Gi4wbC7NR0E ?

Correct.

> Is there a possibility that it could return multiple DB's (even after excluding schema_info?)

Possibly, yes.

Maybe the new code I added should be in a try / catch so it only runs when there is in fact an issue. Then  there is a lot less risk of it breaking existing functionality.

**Comment by perdjurner** [comment]
Going to commit my code as is. I'm thinking that sometimes the information_schema tables will actually have tables with the same as the user tables so a try / catch would not always work then anyway.
