### ISSUE TITLE
Prevent user tampering with [key] when obfuscateURLs=true

### ISSUE THREAD

**Issue by kmd1970** [cfwheels/cfwheels#824]
If I have `obfuscateURLs=true` turned on, a sample URL with a [key] = 718 will render as 

`http://localhost/site/index.cfm/users/aa6d4/edit`

Unfortunately, I am still able to tamper with the URL by typing in the numeric [key] value manually. (any random key value could also work)

`http://localhost/site/index.cfm/users/718/edit`

It would be nice if CFWheels would reject any integer/numeric keys (passed into a controller, via URL) when `obfuscateURLs=true` is set.

OR

This could be added to verifies() as a special `Type` parameter value 

`verifies( params="key", paramsTypes="masked" , action="index", error="Invalid key");`

The new "masked" type could invoke `isValid ( "regex", value, pattern)` internally to verify [key] pattern or simply check `NOT IsValid("integer", value) and NOT IsNumeric(value)`.

OR 

Allow use of the `type = "regex"` by adding the `pattern` parameter

`verifies( params="key", paramsTypes="regex", pattern="[regex for valid key]", action="index", error="Invalid key");`

EDIT: looks like verifies() only has access to deobfuscated params.

**Comment by neokoenig** [comment]
Ok, there actually might be a solution for this with 2.x routing and regex

See https://github.com/cfwheels/cfwheels/issues/609#issuecomment-265144164 

This would for instance, only match numeric keys apparently:
```
mapper()
  .resources(name = "users", constraints = { key = "\d+" })
.end();
```

Have a look at http://guides.rubyonrails.org/routing.html , specifically Segment Constraints.

Full disclaimer, this is currently undocumented and untested. But I think the functionality is already there.... So it probably wouldn't be hard to write some regex to ignore pure integers etc. 

As you mention, we'd need to see where the obfuscateURL call happens (i.e, before or after the routing) so it might be this is a no-go, but again, probably worth a look!

**Comment by kmd1970** [comment]
This worked for me (but only with .wildcard commented out).  I get a `Wheels.RouteNotFound` error.
I am assuming the longest an obfuscateParam() value can be is 16 long?

```js
mapper()

.resources(name = "users", constraints = { key = "[A-Za-z_0-9]{5,16}" })
	
//.wildcard(mapKey=true)

.root( to="home##index", method="get")

.end();
```

**Comment by neokoenig** [comment]
"(I am assuming the longest an obfuscateParam() value can be is 16 long?)"
 - lol, no idea :)

"but only with .wildcard commented out"
- That makes sense.  Wildcard really is only there to get the basics working, and I'd recommend you ditch it asap for the most control.

Glad there's a solution though - nice :)

**Comment by neokoenig** [comment]
I think we need to provide more examples of this in the docs, and possibly double check `constraints` is the in the test suite, so I'm marking this as `docs` to follow up.

**Comment by neokoenig** [comment]
Marked as docs as I think `constraints` isn't mentioned - also, we should check it's in the test suite.

**Comment by neokoenig** [comment]
Added an example of restricting via contstraints in https://guides.cfwheels.org/v2.0/docs/obfuscating-urls

**Comment by MvdO79** [comment]
> Added an example of restricting via contstraints in https://guides.cfwheels.org/v2.0/docs/obfuscating-urls

Now here: https://guides.cfwheels.org/2.5.0/handling-requests-with-controllers/obfuscating-urls#what-url-obfuscation-does
