### ISSUE TITLE
Controller or model not ready / doesn't exist

### ISSUE THREAD

**Issue by blazer82** [cfwheels/cfwheels#826]
We have an issue with our application that when there's more than one concurrent request from a client, sometimes the controllers and sometimes the models don't seem to be ready yet.

This will lead to errors like:

```
lucee.runtime.exp.ExpressionException: key [ControllerName] doesn't exist
```

or

```
lucee.runtime.exp.ExpressionException: key [model] doesn't exist
```

for calls like:

```
model("model")
```

On a later requests the same code may work just fine.

Any ideas to what might be causing this are appreciated. Thanks!

**Comment by neokoenig** [comment]
What version of Wheels? Is it running in production mode or something else?

**Comment by blazer82** [comment]
Version 1.4.5 and it's in production mode, yes.

Thanks for the quick reply, by the way.

**Comment by neokoenig** [comment]
Sounds like a race condition / not thread safe issue - i.e, when the app starts, it needs to load a bunch of stuff into `application.wheels`, including the main controller/model calls etc. If it only happens when the application is restarting, that makes sense. If it's happening randomly, that's a bit more weird. TBH I thought most of these issues were fixed by 1.4.5

**Comment by perdjurner** [comment]
Have you changed any settings through `set()` calls?

**Comment by blazer82** [comment]
_Seems to be partly solved thanks to @perdjurner (see below)_

@neokoenig it is weird since the application shouldn't be restarting at that moment. It happens reproducibly without restarting or reloading - at least as far as I know. Is there a way to determine whether the application is restarting?

@perdjurner I haven't checked the settings yet, good call! We had settings like:

```
set(cacheModelInitialization=false);
set(cacheControllerInitialization=false);
set(cacheRoutes=false);
```

I changed them to `true` and the first test still failed. After that, the cache seemed to kick in and it worked repeatedly! I guess we may still run into the problem after restarting the application but I could live with that for now.

@neokoenig is right, it does sound like a race condition and I'd like for it to be investigated further.

**Comment by neokoenig** [comment]
Well, 
```
set(cacheModelInitialization=false);
set(cacheControllerInitialization=false);
set(cacheRoutes=false);
```
Is basically reloading everything in `/models` and `/controllers` and `config/routes.cfm` on every request, which should only ever been done in development, never on production as you'll get these exact sort of errors.

**Comment by blazer82** [comment]
I see. I'm changing the settings now. We had them because technically we're still in development. Thanks for your help! Guess the issue is resolved then.

**Comment by neokoenig** [comment]
Closing for now, please feel free to reopen if needed.
