### ISSUE TITLE
finders removing spaces from where clause value

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#831]
I have finder that looks like:

`model("Address").findAll(where="address = '4 Highbury Road, Burwood, VIC 3125'");`

which is evaluated as:

`WHERE address = '4 Highbury Road,Burwood,VIC 3125'`

Note the missing spaces after the commas.

**Comment by perdjurner** [comment]
Works for me in 2.0.

Are you sure it's not a plugin or callback changing it?

**Comment by chapmandu** [comment]
I should have mentioned this occurred using 1.4.5. Glad to hear it doesn't affect 2.0.

I don't believe there are any callbacks affecting the value.. There aren't any beforeFind events anyhow.

**Comment by perdjurner** [comment]
Closing since this is fixed, please send a pull request if you want this in a previous release (pull request to the old release branch that is).

Thanks.
