### ISSUE TITLE
imageTag encode accepting only boolean

### ISSUE THREAD

**Issue by Manaus** [cfwheels/cfwheels#833]
In the guides you suggest to use "attributes" as a value for `encode`.  
Still it seems to accept only boolean values, and using `encode='attributes'` in my code returns an error...

**Comment by neokoenig** [comment]
Agreed, imageTag should use `any`.
Ref: 
https://github.com/cfwheels/cfwheels/blob/3a6a7ff1f2062e80076071e7bc1394df6143c046/wheels/view/assets.cfm#L126

Should be an easy fix though

**Comment by neokoenig** [comment]
Actually, thinking about this, `<img>` doesn't have tag content, i.e, you don't do `<img src="foo.png">FOO</img>`, so the `attributes` value for `encode` would just be the same as `true/false` would it not? 

However, I do see the value of allowing attributes for consistencies' sake: it would however presumably need to apply to `javascriptIncludeTag` and `stylesheetLinkTag` (or indeed anywhere where encode is currently a boolean).

@perdjurner thoughts?

**Comment by perdjurner** [comment]
I think it should stay true / false since adding “attributes” to the mix gives the false impression that there are three possible outcomes when there are only two.

**Comment by perdjurner** [comment]
We need to update the docs.

When the argument is `boolean encode` we should not say "Set to `attributes` to only encode attribute values and not tag content."

**Comment by perdjurner** [comment]
I've mentioned this in the docs now.
