### ISSUE TITLE
2D Array in URL throws error

### ISSUE THREAD

**Issue by michaeldiederich** [cfwheels/cfwheels#836]
If you want to submit/request a page with an 2D Array as URL arguments, cfwheels (latest master branch) throws an error:

Lucee 5.2.4.37 Error (expression)
--
Message | Can't cast Object type [Array] to a value of type [Struct]
Detail | Java type of the object is lucee.runtime.type.ArrayImpl
Stacktrace | The Error Occurred in/home/[....]/wheels/dispatch/functions.cfm:
line 62
60: local.item = local.nested[local.i];
61: 
62: if (!StructKeyExists(local.struct, local.item)) {
63: local.struct[local.item] = {};
64: }

See attached screenshot for the parameters, example url:

http://[..]/index.cfm/kunde/overview?format=json&filter[0][]=firma_1&filter[0][]=contains&filter[0][]=preis&filter[]=and&filter[2][]=extern_id&filter[2][]=contains&filter[2][]=1&skip=0&take=12&reload=true

![965c8390623818ebb9aefbe12c5891e21ae875ee43d800ced7 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/15325153/34985877-d9e3bc6e-fab5-11e7-8859-63e7977da568.jpg)

**Comment by neokoenig** [comment]
This never worked in 1.4.x though did it? (As in, this isn't something which used to work and is now broken?)

`$createNestedParamStruct()` also handles form submissions such as `organisation[organisationcategories][6,5][_delete]` with `hasManyCheckbox()`, so I wonder if that's the issue - i.e, it's always expecting a struct

**Comment by michaeldiederich** [comment]
I never used 1.4.x.

**Comment by michaeldiederich** [comment]
Just to make sure: Why don't you parse the argument item and e.g. cast each of the array elements to the returning struct?
