### ISSUE TITLE
Testing Partials directly

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#839]
This came up on Slack, someone wanting to directly test `includePartial(partial="foo")`

At the moment there's no direct way to do with without doing:
```
component extends="tests.Test" { 
    function setup() {
          params = {controller="dummy", action="dummy"};
             _controller = controller("dummy", params);
    }

    function test_Test_IncludePartial(){ 
        result=_controller.includePartial(partial="/foo/bar/");
        assert("result CONTAINS 'foobar'");
    }
}
```

This is perfectly valid approach, but we should either document this as "the way" to do it, or perhaps create a helper function (maybe `processPartial()` to match `processRequest()`?) Usually I'd just test partials as part of their normal request cycle, but I can see the reasoning behind wanting to do this directly.

What do we think is better?

**Comment by perdjurner** [comment]
The includePartial function is coupled with controller / action information so that would be the correct way to test it I think (so, yes, I think we should document that approach).

**Comment by neokoenig** [comment]
Added to https://guides.cfwheels.org/docs/testing-your-application#section-testing-partials
