### ISSUE TITLE
Plugin issue where two digit version number not recognized by cfwheels correctly.

### ISSUE THREAD

**Issue by 18thAvenue** [cfwheels/cfwheels#840]
Using cfwheels 2.0 plugins that have this.version = "2.0"; still shows the red "this plugin might not be supported" in debug bar.  If you change the plugin to say this.version = "2.0.0" it goes away.

**Comment by neokoenig** [comment]
Think I've fixed this, but please check. It *should* do:
If plugin author has specified `2.0.0` then check against the full wheels version, as it should always be 3 parts long with semver; if they've put `2.0` then only check against the major/minor version

**Comment by 18thAvenue** [comment]
Hi,
It works! Thanks. I also tried both 2.0 and 2.0.0 and both work.
