### ISSUE TITLE
Plugin runner getting confused between plugin methods and controller actions

### ISSUE THREAD

**Issue by andybellenie** [cfwheels/cfwheels#841]
Getting following error when running AuthenticateThis plugin
https://github.com/andybellenie/cfwheels-authenticate-this

````
Wheels.MethodNotFound
The method resetPassword is part of a plugin but was not found in the base object.
````

When I look at the pluginRunner() code it thinks there are two resetPassword() functions when there is only one.

However, there is a resetPassword() function in my controller.

When I rename the controller function to resetPassword2() the problem is fixed.

**Comment by andybellenie** [comment]
@liferealized

**Comment by neokoenig** [comment]
This should be fixed in https://github.com/cfwheels/cfwheels/tree/isolate-wheels-internals but needs double checking

**Comment by neokoenig** [comment]
In my quick tests, this is now fixed, so closing - feel free to reopen if I'm wrong!
