### ISSUE TITLE
Nesting Models will cause the query to be stored incorrectly in the local variable scope

### ISSUE THREAD

**Issue by bawelter** [cfwheels/cfwheels#846]
When passing the argument for the query name, Coldfusion will store the result in a struct if given in dot notation as per it's documentation.  This causes issues when organizing the models subdirectories similar to how we are able to do this with controllers.  I was able to get around this by using isDefined and evaluate in place of structKeyExists and local[arguments.debugName]

```
<cfif StructKeyExists(local, arguments.debugName)>
	<cfset local.$wheels.rv.query = local[arguments.debugName]>
<cfelseif isDefined("local.#arguments.debugName#")>
	<cfset local.$wheels.rv.query = evaluate("local.#arguments.debugName#")>
</cfif>
```

The file is  wheels/model/adapters/cfquery.cfm

**Comment by bawelter** [comment]
Created a plugin to fix the issue until this is resolved.

https://www.forgebox.io/view/cfwheels-model-nesting
https://github.com/bawelter/cfwheels-model-nesting

**Comment by neokoenig** [comment]
@perdjurner Whilst we don't technically support nested models directories, is there any reason not to implement this in 2.1? I'm always wary of `evaluate()`, but that might just be me.

**Comment by perdjurner** [comment]
Wouldn't a better fix be to make sure that `arguments.debugName` is a valid variable name by removing spaces and periods (.) from it?

**Comment by bawelter** [comment]
The only reason I did the fix this way is lack of research into how debugName is being used.  Personally I wanted to removed debug name an use a static variable name for the query result returned and then put it into the returned struct with the debug name as the key to resolve the issue.
