### ISSUE TITLE
Cannot use <cfabort> in Lucee or no output generated

### ISSUE THREAD

**Issue by andybellenie** [cfwheels/cfwheels#848]
See https://dev.lucee.org/t/cfdump-not-rendering-when-output-false/3589

Newer Lucee versions disable the output buffer by default. So issuing a ``<cfabort>`` will stop any output being generated. This breaks, at a minimum, the missing template and maintenance handlers.

It can be manually re-enabled by setting `this.bufferOutput = true` in Application.cfc (or /config/app.cfm) but I'm not sure if this is the best option - as much as it's a frustrating change it is a makes sense from a performance perspective. I am told newer Adobe CF behaves the same but haven't tested.

**Comment by neokoenig** [comment]
Also worth noting this change was accidentally put in a in a 5.26 version (which has since been replaced by a patch release I believe) - but from 5.3 it will be the default behaviour.

**Comment by perdjurner** [comment]
What do we need to do exactly?

Just stop using abort (and come up with another way to avoid running code that shouldn't run)?

**Comment by neokoenig** [comment]
We *could* add `this.bufferOutput = true` by default for development mode... and then not set anything for the other modes...

**Comment by andybellenie** [comment]
Annoying as it is, I don't see how we can continue to use abort now that this is a recommended production option.

**Comment by reubenbrown13** [comment]
It is not pretty, but here is my fix in the onError file on lines 70 and 86: 
`
if ( StructKeyExists(server, "coldfusion") AND ListFirst(server.coldfusion.productVersion) GTE 2018 ) {
	WriteDump(arguments.exception);
	abort;
} else {
	Throw(object=arguments.exception);
}`

**Comment by perdjurner** [comment]
Possible fix for discussion.

![image](https://user-images.githubusercontent.com/160595/57070197-f58d7380-6cd6-11e9-96d3-25b199b8265a.png)

That fix is for maintenance mode but the general approach would probably apply to other places where `abort` is used as well.

Thoughts?

I can make a PR if you don't see any problems with it.

**Comment by neokoenig** [comment]
Good to see you around @perdjurner ! So basically force an early return? I like the idea - would need to be on a environment setting though presumably (i.e, returnContentOnAbort = set to true for development etc) ? @andybellenie @chapmandu @dbelanger ?

**Comment by perdjurner** [comment]
That's right, exiting the function early so that we don't have to call abort basically.

My proposed code there does exactly the same thing as before, just in a different way to avoid the abort call, so I don't even think an on / off setting for it would be needed.

**Comment by zainforbjs** [comment]
@andybellenie @perdjurner I am still not seeing anything if I abort in the code to see some dumps unless I set this.bufferOutput=true in app.cfm.
Is this issue fixed or does it need working on or do we always need this.bufferOutput set to true?

**Comment by perdj** [comment]
No, I don't think the issue is fixed.
It was only fixed for maintenance mode specifically.

**Comment by zainforbjs** [comment]
This issue is due to the change in the working of the lucee server. 
As they said in their Jira ticket linked [here](https://luceeserver.atlassian.net/browse/LDEV-1733), that the frameworks or applications that use lucee will have to either set "bufferOutput" to true in their framework code or manually enable "Buffer Tag Body Output" in the Lucee server settings for individual applications.

So there is no alternate for this for now until Lucee adds something new that we can add.

 @bpamiri This can be closed for now till futher Lucee updates
