### ISSUE TITLE
IncludePartial() Documentation needs updating

### ISSUE THREAD

**Issue by charlycontreras** [cfwheels/cfwheels#849]
On the Include Partials with Query documentation (https://guides.cfwheels.org/docs/partials#section-using-partials-with-a-query), it states you can just pass in the query and CFWheels will automatically include the correct partial.  However this was changed with #806 and is no longer valid. 

Additionally, the upgrade notes should make mention of this breaking change, meaning you can no longer just pass the query, but must now update it to include both the `partial` and `query` arguments when calling an `includePartial()` using a query.

**Comment by neokoenig** [comment]
https://guides.cfwheels.org/v2.0/docs/partials
https://guides.cfwheels.org/v2.0/docs/upgrading
now updated
