### ISSUE TITLE
More than one FlashMessage for each 

### ISSUE THREAD

**Issue by michaeldiederich** [cfwheels/cfwheels#850]
I insert a flashMessage with key error and when more than one error occurred, only the latest message will be shown:

```
        flashInsert(alert="test1");
        flashInsert(alert="test2");
```

flashMessages() should show all alerts.

**Comment by neokoenig** [comment]
Duplicate of https://github.com/cfwheels/cfwheels/issues/615
Agree, would be nice to sort this. Wheels should store this as an array of values and output each.

**Comment by neokoenig** [comment]
Fixed in https://github.com/cfwheels/cfwheels/pull/855; need to update docs

**Comment by neokoenig** [comment]
Added in https://guides.cfwheels.org/v2.0/docs/using-the-flash#section-appending-to-rather-than-replacing-the-flash
