### ISSUE TITLE
Only one after filter can be called

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#853]
i.e, 
```
component extends="Controller" {
	function config(){
		super.config();

        var filters = filterChain();
        var moreFilters = [
            {
                through="one"
            }, {
                through="two"
            }, {
                through="three", type="after"
            }, {
                through="four", type="after"
            }
        ];
        arrayAppend(filters, moreFilters, true);
        setFilterChain(filters);
	}

	function index(){

	}
	// Before
	private function one(){
		filterTest=[];
		arrayAppend(filterTest, "One");
	}
	private function two(){
		arrayAppend(filterTest, "Two");
	}
	// After
	private function three(){
		arrayAppend(filterTest, "Three"); 
	}
	private function four(){
		arrayAppend(filterTest, "Four");
		writeDump(filterTest);
		abort;
	}
}
```

`four()` will never get called. You can call `four()` from `three()` though.

**Comment by chapmandu** [comment]
It appears that after filter `three` is executed, `$performedRenderOrRedirect()` is returning true, which `break;`s the `after` filter chain.

https://github.com/cfwheels/cfwheels/blob/master/wheels/controller/filters.cfm#L129

**Comment by chapmandu** [comment]
What do y'al think of this solution (syntax aside).. basically separate logic for before and after filter types. The after filter now only checks for redirects. It passes all tests but I am conscious of introducing regressions.

```
local.result = $invoke(method=local.filter.through, invokeArgs=local.filter.arguments);
// If the filter returned false, we skip the remaining filters.
if ((StructKeyExists(local, "result") && !isNull(local.result) && !local.result)) {
	break;
}
if (arguments.type == "before" && $performedRenderOrRedirect()) {
	break;
} else if (arguments.type == "after" && $performedRedirect()) {
	break;
}
```

**Comment by chapmandu** [comment]
Also, the reason this was not picked up in unit tests is because the tests call the filter functions directly, whereas the bug occurs when filters are called as part of `processAction`. It would be worthwhile adding filter testing to the `processAction` test package.

**Comment by neokoenig** [comment]
Nicely done.

I don't think changing the after filter to to just check for redirects would be a big deal. Arguably I don't think after filters are actually something people have used a lot simply to due to the slightly inconsistent behaviour, so I'd be surprised if it breaks stuff for anyone, if anything, it might mean a second filter which they thought was being called but wasn't then *actually* gets called; so works as intended.

I'd like to see optional filter testing to `processAction` - e.g, let's say you have an action which is behind some simple authentication which is executed by filter: instead of having to mockup an authentication object and inject it just so the action runs, it might be nice to be able to do `processAction(includeFilters=true|false|before|after)` (defaulting to true) or something.
