### ISSUE TITLE
Test framework exceptions

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#858]
The exception below is thrown on subsequent tests after any tests that uses model functions.

Current workaround is to add `reload=true` param to every test request. I would be interested to know if this occurs with cfwheels 2 apps. I have backported the wheel2 test framework to my 1.4.5 app.

It seems to be caused by the copying and re-instating of the "wheels" application scope.

https://github.com/cfwheels/cfwheels/blob/master/wheels/test/functions.cfm#L449
https://github.com/cfwheels/cfwheels/blob/master/wheels/test/functions.cfm#L484

Exception:
No matching function [$OBJECTFILENAME] found

called from /var/www/myapp/wheels/model/create.cfm: line 29 
called from /var/www/myapp/tests/unit/controllers/mytests.cfm: line 7 
called from /var/www/myapp/wheels/Test.cfc: line 299
called from /var/www/myapp/wheels/Test.cfc: line 492
called from /var/www/myapp/root.cfm: line 5

**Comment by neokoenig** [comment]
I'm not sure I can replicate this; can you provide more specific steps to reproduce?

**Comment by neokoenig** [comment]
Still an issue @chapmandu ?

**Comment by chapmandu** [comment]
It is, I think I've resolved it on my app. I'll propose a change soon. It's caused by the test framework copying then rewriting the application scope.

**Comment by chapmandu** [comment]
resolved via c5b9780b816b10c5380058d9ed936fa8220e5ae6
