### ISSUE TITLE
component [adapters.MySQL] has no  function with name [addForeignKeyOptions]

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#862]
When trying to use `t.references("role");`  Migrator throws
component [adapters.MySQL] has no  function with name [addForeignKeyOptions]

Edit: seems it was an issue in dbmigrate aswell : https://github.com/tdm00/cfwheels-dbmigrate-plugin/issues/76

**Comment by geirman** [comment]
@neokoenig I just copied the `addForeignKeyOptions` function over from the [MicrosoftSQLServer.cfc](https://github.com/cfwheels/cfwheels/blob/master/wheels/migrator/adapters/MicrosoftSQLServer.cfc#L23-L33) and tested it with my migration definition and it worked like a charm.
