### ISSUE TITLE
Null integer not saving when form value is 0

### ISSUE THREAD

**Issue by strubenstein** [cfwheels/cfwheels#868]
Wheels is not saving a zero value for a nullable integer if the current value is null. It saves if the value is something other than zero.

1. Create an object with a nullable integer with a default value of null.

2. Submit a form to update the object with zero being an option (and other numbers) via a radio button.

3. If a non-zero value is checked, the form saves and the database is updated.

4. If zero is checked, not only is the database value still null, but it does not update the database at all based on UpdatedAt not being updated.

It will save if there are other form fields that changed, but the null value is still not updated to 0.

After object.save(), a dump reveals that the value was updated from blank to 0. But it never actually gets updated in the database.

I found another post that this same bug was reported back in 2011. It seems the bug has not been fixed.
https://groups.google.com/forum/#!topic/cfwheels/gqz3WRwTkLg

**Comment by neokoenig** [comment]
@perdjurner bit before my time this one - any memory? :)

**Comment by andybellenie** [comment]
Can you post some code? I've tried to replicate this from a controller perspective but it seems to be working fine.

**Comment by strubenstein** [comment]
1. I can try to post some code in a little while. And a cfdump from the controller says it worked, but a check of the database (or re-requesting the object) shows it does not.

2. No, we are not using checkBoxTag. It is actually a normal radio button.

3. I just realized this site is still using Wheels version 1.1.7 from 12/11/2011. (I had no idea.) So it is quite possible this bug has already been fixed, in which case I sincerely apologize.

**Comment by neokoenig** [comment]
ok, 1.1.7 is old! There are a number of things in https://github.com/cfwheels/cfwheels/blob/master/CHANGELOG.md which genuinely could be a fix for this.

I don't know your codebase, but it would be worth trying to update your wheels core:
https://guides.cfwheels.org/docs/upgrading

I'd try it in two or three steps: 1.17 -> 1.3.4 -> 1.4.6;
If you end up in 1.4.6 you'll be in a very stable place. There's a lot of apps still on 1.4.6, and that's fine. 2.x is more of a leap (but awesome) due to the routing.

**Comment by strubenstein** [comment]
Hey, I inherited this code base, thank you very much! :)

Upgrading is on our to-do list later this summer.

Thanks for the responses. Sorry again for not noticing beforehand the geriatric version of Wheels.

**Comment by neokoenig** [comment]
Not a criticism! :)
Good luck upgrading and jump on slack or the  mailing list if you need any help.

**Comment by neokoenig** [comment]
Closing, as assuming bug from earlier version. Please re-open if not the case!
