### ISSUE TITLE
commandbox didn't create urlrewrite.xml file

### ISSUE THREAD

**Issue by rucvan** [cfwheels/cfwheels#869]
Hi There,

i am new in cfwheels, when I try to create application with wheels new.
after finish the progress. There are no urlrewrite.xml file.

Anyone facing same problems?

**Comment by neokoenig** [comment]
Thanks - commandbox has recently been updated to version 4, and there's the odd pathing bug. I've now fixed this, so if you do `install cfwheels-cli` you should get `0.3.1` which has the fix in it.  If you need the urlrewrite.xml file straightaway, you can grab it from here: https://github.com/cfwheels/cfwheels/blob/master/urlrewrite.xml
