### ISSUE TITLE
Failed migrator transactions do not roll back

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#872]
Lucee 5.2.6
MySQL 5.6

```
addColumn(table='users', columnType='boolean', columnName='column_one', null=true);
addColumn(table='users', columnType='boolean', columnName='column_one', null=true);
```

The above example should fail with a "column already exists" error and should roll back, however `column_one` remains in the `users` table.

**Comment by perdjurner** [comment]
Is it a general problem with transactions when using migrations or just specific to this use case?

**Comment by chapmandu** [comment]
It's a general issue that I've noticed since porting from SQL Server to MySQL. I'm not sure if it's a MySQL transactions issue, or a wheels issue.

**Comment by chapmandu** [comment]
Mysql 5.6 doesn't support rollback of schema changes
