### ISSUE TITLE
function $orderByClause case-sensitivity

### ISSUE THREAD

**Issue by strubenstein** [cfwheels/cfwheels#883]
In FindAll(), if you specify order="COLUMN desc" it will ignore the "desc" unless it is all-caps "DESC".

To fix, in wheels/model/sql.cfm, function $orderByClause, line 90 should use FindNoCase instead of Find:

CURRENT: (lines 90-92)
if (!Find(" ASC", local.iItem) && !Find(" DESC", local.iItem)) {
   local.iItem &= " ASC";
}

FIXED:
if (!FindNoCase(" ASC", local.iItem) && !FindNoCase(" DESC", local.iItem)) {
   local.iItem &= " ASC";
}

**Comment by perdjurner** [comment]
That's not a bug actually but by design, documented here:
https://guides.cfwheels.org/docs/reading-records#section-order-argument

**Comment by strubenstein** [comment]
Oh. Sorry about that. It was not case-sensitive in Wheels 1.x.

Guess I need to change my code instead. Bummer.

**Comment by perdjurner** [comment]
No problem :)
