### ISSUE TITLE
Unable to duplicate a ColdFusion Component

### ISSUE THREAD

**Issue by dyakhnov** [cfwheels/cfwheels#889]
Spotted number of exception errors in CF 2016 logs with following logic:

Function onSessionEnd (with session and application scopes as parameters):
wheels/events/onsessionend.cfm:5
calling $simpleLock...

wheels/global/cfml.cfm:33
which is calling $invoke...

wheels/global/cfml.cfm:156
and while trying to duplicate(arguments)

failing with error:

"Unable to duplicate a ColdFusion Component.coldfusion.runtime.UndefinedVariableException: Variable APPLICATION is undefined. The specific sequence of files included or processed is: '', line: 156

It does not affect users, but would be nice to fix.

**Comment by neokoenig** [comment]
This is already fixed in master and should be in `2.1` (see https://github.com/cfwheels/cfwheels/issues/879 )

**Comment by dyakhnov** [comment]
This seems to be a different issue from what has been fixed...

Could be something to deal with ACF only:
> https://coldfusion.adobe.com/discussion/2552764/

Looks like you can't use Duplicate function on application or session scope while called in from onSessionEnd.

**Comment by perdjurner** [comment]
@neokoenig @chapmandu I believe the fix here is to delete everything related to $wheelsInvoked from here:
https://github.com/cfwheels/cfwheels/blob/389c4e1b0426124622d324aef00b5c3c15b13752/wheels/global/cfml.cfm#L156

As far as I can tell $wheelsInvoked is related to the reverted plugin runner code (and probably should have been deleted as part of that revert commit).

This will eliminate the Duplicate() call from the code which is what's causing the bug reported here.

**Comment by zainforbjs** [comment]
@perdjurner Should I remove the $wheelsinvoled related code and create a PR for that? Or have you already completed this?

**Comment by perdj** [comment]
I don't think it was completed.
A PR sounds great.

**Comment by zainforbjs** [comment]
@perdj I created a PR https://github.com/cfwheels/cfwheels/pull/1256 for you.
