### ISSUE TITLE
CF11 with CFWheel 2.0 coldfusion.compiler.ASTcfloop error

### ISSUE THREAD

**Issue by zulhelmi** [cfwheels/cfwheels#890]
coldfusion.compiler.ASTcfloop cannot be cast to coldfusion.compiler.ASTcftag
--
The error occurred in C:/ColdFusion11/cfusion/wwwroot/koperasi/wheels/global/cfml.cfm: line 117Called from C:/ColdFusion11/cfusion/wwwroot/koperasi/wheels/controller/rendering.cfm: line 474Called from C:/ColdFusion11/cfusion/wwwroot/koperasi/wheels/controller/rendering.cfm: line 225Called from C:/ColdFusion11/cfusion/wwwroot/koperasi/wheels/controller/rendering.cfm: line 66Called from C:/ColdFusion11/cfusion/wwwroot/koperasi/wheels/controller/processing.cfm: line 134Called from C:/ColdFusion11/cfusion/wwwroot/koperasi/wheels/controller/processing.cfm: line 91Called from C:/ColdFusion11/cfusion/wwwroot/koperasi/wheels/dispatch/functions.cfm: line 184Called from C:/ColdFusion11/cfusion/wwwroot/koperasi/wheels/index.cfm: line 5Called from C:/ColdFusion11/cfusion/wwwroot/koperasi/index.cfm: line 2Called from C:/ColdFusion11/cfusion/wwwroot/koperasi/wheels/events/onrequest.cfm: line 5
`115 : 	
116 : 	
117 : 	<cfsavecontent variable="local.$wheels"><cfinclude template="../../#LCase(arguments.$template)#"></cfsavecontent>
118 : 	<cfreturn local.$wheels>
119 : `

**Comment by neokoenig** [comment]
I can't recreate this. Can you specify exactly which version of CF11? Is this on a "blank" installation?

**Comment by zulhelmi** [comment]
ColdFusion 11 Update 14

**Comment by zulhelmi** [comment]
Error Occurred While Processing Request
--
Error casting an object of type coldfusion.compiler.ASTcfloop cannot be cast to coldfusion.compiler.ASTcftag to an incompatible type. This usually indicates a programming error in Java, although it could also mean you have tried to use a foreign object in a different way than it was designed.

**Comment by zulhelmi** [comment]
Ok i figure out what trigger this error. This code
#selectTag(name="status", label="Status",options={1="Pending",2="Approved",3="Submitted",4="Completed"})#
