### ISSUE TITLE
Using useLayout twice in config doesn't work

### ISSUE THREAD

**Issue by dbelanger** [cfwheels/cfwheels#891]
When trying to use "usesLayout" twice in a config, something goes wrong and it defaults to the system default layout.

Example
`usersLayout(template="/templates/layout1", except="show);`
`usersLayout(template="/templates/layout2", only="show);`

**Comment by neokoenig** [comment]
Worth exploring. Also note to self, there's some weird behaviour with `onlyProvides()` which needs exploring which may be related.
