### ISSUE TITLE
Issues With MariaDB

### ISSUE THREAD

**Issue by zulhelmi** [cfwheels/cfwheels#892]
1. I have set primary key on table but cfwheels show error not primary key. I need to declare primary key on model.

2. I get error <code>SELECT COUNT() AS count
FROM departments</code> showed that it still cannot find a primary key

CFWheels 2.0.1

Lucee 5.2.9.31 Error (database)
--
Message |  
Detail | You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AS countFROM departments' at line 1
SQL | SELECT COUNT() AS countFROM departments
DatabaseName | MySQL
DatabaseVersion | 5.5.5-10.3.9-MariaDB-1:10.3.9+maria~bionic-log
DriverName | MySQL Connector/J
DriverVersion | mysql-connector-java-8.0.11 (Revision: 6d4eaa273bc181b4cf1c8ad0821a2227f116fedf)
Datasource | oa_dev
Stacktrace | <code>The Error Occurred in/var/www/dev/wheels/model/adapters/cfquery.cfm: line 18 16: 17: </cfscript>18: <cfquery attributeCollection="#arguments.queryAttributes#"><cfset local.$wheels.pos = 0><cfloop array="#arguments.sql#" index="local.$wheels.i"><cfset local.$wheels.pos = local.$wheels.pos + 1><cfif IsStruct(local.$wheels.i)><cfset local.$wheels.queryParamAttributes = $queryParams(local.$wheels.i)><cfif NOT IsBinary(local.$wheels.i.value) AND local.$wheels.i.value IS "null" AND local.$wheels.pos GT 1 AND (Right(arguments.sql[local.$wheels.pos-1], 2) IS "IS" OR Right(arguments.sql[local.$wheels.pos-1], 6) IS "IS NOT")>NULL<cfelseif StructKeyExists(local.$wheels.queryParamAttributes, "list")><cfif arguments.parameterize>(<cfqueryparam attributeCollection="#local.$wheels.queryParamAttributes#">)<cfelse>(#PreserveSingleQuotes(local.$wheels.i.value)#)</cfif><cfelse><cfif arguments.parameterize><cfqueryparam attributeCollection="#local.$wheels.queryParamAttributes#"><cfelse>#$quoteValue(str=local.$wheels.i.value, sqlType=local.$wheels.i.type)#</cfif></cfif><cfelse><cfset local.$wheels.i = Replace(PreserveSingleQuotes(local.$wheels.i), "[[comma]]", ",", "all")>#PreserveSingleQuotes(local.$wheels.i)#</cfif>#chr(13)##chr(10)#</cfloop><cfif arguments.limit>LIMIT #arguments.limit#<cfif arguments.offset>#chr(13)##chr(10)#OFFSET #arguments.offset#</cfif></cfif><cfif Len(arguments.comment)>#arguments.comment#</cfif></cfquery>19: <cfif StructKeyExists(local, arguments.debugName)>20: <cfset local.$wheels.rv.query = local[arguments.debugName]></code>called from /var/www/dev/wheels/model/adapters/Base.cfc: line 422 called from /var/www/dev/wheels/model/adapters/MySQL.cfc: line 88 called from /var/www/dev/wheels/model/read.cfm: line 229 called from /var/www/dev/wheels/model/calculations.cfm: line 251 called from /var/www/dev/wheels/model/calculations.cfm: line 96 called from /var/www/dev/wheels/model/read.cfm: line 96 called from /var/www/dev/controllers/Departments.cfc: line 40 called from /var/www/dev/wheels/global/cfml.cfm: line 157 called from /var/www/dev/wheels/controller/processing.cfm: line 125 called from /var/www/dev/wheels/controller/processing.cfm: line 91 called from /var/www/dev/wheels/dispatch/functions.cfm: line 184 called from /var/www/dev/wheels/index.cfm: line 5 called from /var/www/dev/index.cfm: line 2 called from /var/www/dev/wheels/events/onrequest.cfm: line 5

**Comment by neokoenig** [comment]
Can you confirm
 - What model call you're using to trigger this?
 - That `SELECT COUNT() AS countFROM departments` isn't a typo and that's what wheels is actually creating?
 - That you've reloaded the app via ?reload=true 
 - That the PK is a just an autoincrement integer?
 - Which mySQL extension driver you're using in the Lucee Admin? (I still find `5.1.40` is the best one for both mySQL and mariaDB) - it looks like you're using `8.0.11`

**Comment by zulhelmi** [comment]
Problem solved by downgrade connector to 5.1.40. Thankz
