### ISSUE TITLE
Calculated property SQL data type is always char

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#894]
When using a calculated property (mainly aliasing for name clashes) the SQL data type seems to always default to `char`. This is not desirable for datetime columns as `findAll` produces where clauses such as `(posts.createdat) > '{ts ''2000-01-01 00:00:00''}' ` <-- note escaped single quotes.. this causes zero results to be returned.

To replicate in the tests, add the following calculated property to the posts model:
`property(name="createdAtAlias", sql="posts.createdat", select=false);`

Then add this test to `/model/sql/whereclause.cfc`

```
function test_sql_dates() {
	where = model("post").$whereClause(where="createdAt > '#CreateDate(2000, 1, 1)#'");
	aliasWhere = model("post").$whereClause(where="createdAtAlias > '#CreateDate(2000, 1, 1)#'");
	result = model("post").findAll(where="createdAtAlias > '#CreateDate(2000, 1, 1)#'");

	debug("where[4]", true);
	debug("aliasWhere[4]", true);
	debug("result", true);

	assert("where[4].datatype eq 'datetime'");
	assert("aliasWhere[4].datatype eq 'datetime'");
	assert("result.recordCount gt 0");
}
```
The relevant code is:
https://github.com/cfwheels/cfwheels/blob/master/wheels/model/sql.cfm#L439
https://github.com/cfwheels/cfwheels/blob/master/wheels/model/sql.cfm#L455

**Comment by neokoenig** [comment]
Wouldn't the above be solved by `property(name="createdAtAlias", sql="posts.createdat", dataType="datetime", select=false)`? Are you saying that `dataType` is being ignored for the calculated property or am I misunderstanding?

**Comment by chapmandu** [comment]
Well don't I look silly.. I was looking at the 1.4 docs.. I'll put that into my unit test and report back.

**Comment by chapmandu** [comment]
It's working as documented, I've added a unit test 7ab64b390b6916e37eadb5e170a54d4d76d5389c

**Comment by neokoenig** [comment]
PS, I've added something in the docs too: https://guides.cfwheels.org/docs/calculated-properties#section-specifying-a-data-type
