### ISSUE TITLE
ObfuscateParam fails on integer check when input string is a plus-prefixed integer value

### ISSUE THREAD

**Issue by jaakkop** [cfwheels/cfwheels#900]
ObfuscateParam fails to execute when when the input string is a plus-prefixed integer value.

For example when `arguments.param = "+123"` it passes the integer check. Next it throws an exception "The value 321+ cannot be converted to a number" when trying to execute line `loc.a = (10^loc.iEnd) + Reverse(arguments.param);` as it tries to sum an integer and a string.

**Comment by geirman** [comment]
Would this be an acceptable approach?

```
local.rv = ArrayToList(REMatchNoCase("[0-9]+",arguments.param),"");
if (arguments.param > 0 && Left(arguments.param, 1) != 0) {
		local.iEnd = Len(arguments.param);
		local.a = (10^local.iEnd) + Reverse(arguments.param);
		local.b = 0;
		for (local.i = 1; local.i <= local.iEnd; local.i++) {
			local.b += Left(Right(arguments.param, local.i), 1);
		}
		if (IsValid("integer", local.a)) {
			local.rv = FormatBaseN(local.b+154, 16) & FormatBaseN(BitXor(local.a, 461), 16);
		}
	}
```

Basically, I'm stripping away all non-numeric characters from the initial param and using whatever is leftover.
