### ISSUE TITLE
More informations for tests

### ISSUE THREAD

**Issue by michaeldiederich** [cfwheels/cfwheels#912]
If a test assert fails, it just shows the name of the function and something like

_assert failed: false_

It would be nice to see more informations like line number, a hint at the assert (like mxunit do) or what else failed.

**Comment by chapmandu** [comment]
You're right, it's very useful to get more information when tests fail. The stack trace is displayed when an exception occurs, though I suspect it would be very difficult to the same information for failed assertions as an exception is not thown (only a condition returns false). 

HOWEVER!... it is possible to show additional information about failed assertions by passing in additional arguments that can be evaluated and shown in the failed assertion output. And there's always the trusty `debug("actual")` helper.

Here is a contrived example:

```
function test_containsUnicode_with_line_breaks() {
    time = Now();
    foo = "bar";
    string = "I have a bad feeling#crlf()#about this...";
    actual = containsUnicode(string);
    expected = false;
    assert("actual == expected", "string", "time", "foo");
  }
```

**Comment by michaeldiederich** [comment]
Thank works fine, I close the issue.
