### ISSUE TITLE
Performance improvements: plugins

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#916]
A potential performance issue has been discovered with Wheels 2.x's plugin runner: in 2.x, the plugin system was made to do a lot of dynamic evaluation in order to allow a plugin to override a function multiple times in a "stack". Unfortunately this has resulted in an overhead which is multiplied for each plugin;

It's proposed to revert the plugin system to match the behaviour of 1.4.x - whilst this incorporates a breaking change, it's only the feature of being able to override a function multiple times by multiple plugins which would ultimately change; there have been no plugins "in the wild" which use this feature, so it's not proposed to bump the Wheels version number to 3.x, but either released in 2.1 or 2.2.

**Comment by neokoenig** [comment]
Now fixed in https://github.com/cfwheels/cfwheels/tree/isolate-wheels-internals and just awaiting a merge

**Comment by andybellenie** [comment]
Link is broken?

**Comment by neokoenig** [comment]
Sorry, that branch is now merged into master!
