### ISSUE TITLE
Performance Improvement: Scanning of Models and Controllers

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#917]
A potential performance issue has been discovered with Wheels 2.x where a case insensitive search is performed for the first request for a controller or model; the search isn't performant with a large number of files, i.e, 350 models.

It's proposed to scan the controller and model directories on startup and cache the results in the application.wheels scope.

**Comment by chapmandu** [comment]
Fixed. Though directories aren't scanned on startup but rather upon first request of a given directory.
