### ISSUE TITLE
Fix mySQL Drivers in Lucee 5

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#920]
Specifically, everything works with `5.1.40`, but later versions go nuts. Needs some investigation.

**Comment by geirman** [comment]
Ah, this must be why I'm getting this error...

> component [adapters.MySQL] has no  function with name [addForeignKeyOptions]

when I'm using...

> t.references('services');

Is there a way to force commandbox to run the 5.1.40 version? Or is there another work around? Or maybe I can help solve this problem...where would I start?

**Comment by neokoenig** [comment]
@geirman Actually, that one's a proper bug, and was in dbmigrate before it was integrated into the core: see https://github.com/cfwheels/cfwheels/issues/862 (and https://github.com/tdm00/cfwheels-dbmigrate-plugin/issues/76 - where I see you commented years ago!)

If you fancy sorting that out you'd get my undying admiration :)

This ticket is more about using mySQL driver versions and how they correspond to later versions of mySQL, like 8.x - we kinda need a matrix of what version of mySQL works best with which driver I think

**Comment by geirman** [comment]
Hey @neokoenig, just to let you know that on the latest version of Lucee (`v5.3.1.102`), I've successfully migrated a pretty extensive migration which included the creation of 15 tables using the column functions string, text, boolean, integer, datetime, references, timestamps, primaryKey and create. 


> **Note:** to get `references()` working, I monkey patched the MySQL adapter. (see PR #934)

**Comment by neokoenig** [comment]
FYI been running mysql-connector-java-8.0.19 (Revision: a0ca826f5cdf51a98356fdfb1bf251eb042f80bf) in production with no issues (against RDS mySQL 5.7.26 ) so I think it's working fine. 

Next step is to test wheels properly against mysql8 which is going to be much easier now docker is in place.
