### ISSUE TITLE
Cannot compare columns using where clause

### ISSUE THREAD

**Issue by ConfusedCitizen** [cfwheels/cfwheels#932]
Had an issue where I was trying to compare whether one column was less than another column on the same table to filter down my Query Result-set, but Wheels was throwing the error "The value for cfqueryparam cannot be determined".

Seems like maybe it's trying to paramaterise the second column?

**Comment by andybellenie** [comment]
Columns can't be compared like this in the where argument of a finder method. However you can setup a calculated property to hold the result and then filter against that, e.g.

````
property(name="isLessThan", sql="CASE WHEN [tablename].prop1 < [tablename].prop2 THEN 1 ELSE 0 END");
````

...then

````
result = model("foo").findAll(where="isLessThan=1");
````
