### ISSUE TITLE
dateTimeSelect does not render `prepend` and `append` as HTML

### ISSUE THREAD

**Issue by geirman** [cfwheels/cfwheels#935]
With a fresh 2.0.1 install, running on Lucee 5.3.1.102 with Bootstrap 3

This code (note that the tags:

```
#dateTimeSelect(objectName="quote", property="taretDateTime")#
```

## Actual Results
<img width="1313" alt="2019-04-05_1305" src="https://user-images.githubusercontent.com/1640318/55653491-96097a00-57a3-11e9-89cb-ab378ddecf11.png">

## Expected Results
The tags defined in `prepend` and `append` should render as HTML, not as strings.

## Additional Information

* Here's the definition in /config/settings.cfm

```
set(functionName="dateTimeSelect,dateSelect", prepend="<div class='form-group'>", append="</div>", timeSeparator="", minuteStep="5", secondStep="10", dateOrder="day,month,year", dateSeparator="", separator="");
```

* Things get a little weirder still when you add the `label` attribute, which unexpectedly (and undesirably) wraps each select element with a label rather than wrapping the entire group with just one label. 

> NOTE: I'm still exploring the options, so pretty sure this is just my lack of understanding at this point. 

<img width="1395" alt="2019-04-05_1312" src="https://user-images.githubusercontent.com/1640318/55653881-ac640580-57a4-11e9-8a66-184bc1070391.png">

* Same problem with `dateSelect`

**Comment by geirman** [comment]
This is happening with `checkBox` too
<img width="1336" alt="2019-04-05_1358" src="https://user-images.githubusercontent.com/1640318/55656144-e46e4700-57aa-11e9-84fe-3db448fde146.png">

**Comment by geirman** [comment]
TIL about the `encode` attribute. Apparently, setting this to `encode=false` solves this issue. It says it's for XSS vulnerabilities, but that should just apply to user entered data. I'm not sure if this should be true by default in these cases, so I'll leave this open for comment for now. However, for anyone stumbling on this issue looking for a solution, here's what I did. 

in `config/settings.cfm`

```
set(functionName="dateTimeSelect,dateSelect,checkBox", encode=false);
```

**Comment by neokoenig** [comment]
encode="attributes" should work too?
This is pretty common behaviour for 2.x which encodes everything by default

**Comment by neokoenig** [comment]
Closing for now, feel free to reopen
