### ISSUE TITLE
Wheels.QueryHandleNotFound: paginationLinks() handler NOT recognized by view

### ISSUE THREAD

**Issue by geirman** [cfwheels/cfwheels#941]
In the controller...

```
quotes=model("quote").findAll(order="createdAt DESC", page=params.page, perPage=5, handler="quotesQry");
```

In the view...

```
#paginationLinks(encode="attributes", handle="quotesQry")#
```

Result...

> 
> Wheels.QueryHandleNotFound
> 
> CFWheels couldn't find a query with the handle of quotesQry.
> Suggested action
> 
> Make sure your findAll call has the page argument specified and matching handle argument if specified.
> Tag context
> 
> Error thrown on line 237 in wheels/view/links.cfm

Line 237 of wheels/view/links.cfm is...
```
local.currentPage = pagination(arguments.handle).currentPage;
```
And the pagination function is found at [wheels/global/misc.cfm#375](https://github.com/cfwheels/cfwheels/blob/master/wheels/global/misc.cfm#L375-L386)

```
public struct function pagination(string handle="query") {
	if ($get("showErrorInformation")) {
		if (!StructKeyExists(request.wheels, arguments.handle)) {
			Throw(
				type="Wheels.QueryHandleNotFound",
				message="CFWheels couldn't find a query with the handle of `#arguments.handle#`.",
				extendedInfo="Make sure your `findAll` call has the `page` argument specified and matching `handle` argument if specified."
			);
		}
	}
	return request.wheels[arguments.handle];
}

```

I dumped `request.wheels` just inside the `pagination()` function and verified that there is no `quotesQry` key, but there is a `query` which is the generic name. So, my guess is that `findAll()` is not setting the handle property name correctly.

**Comment by chapmandu** [comment]
Shouldn't the argument in your controller be handle? Not handler..

**Comment by geirman** [comment]
Crap, I felt pretty confident that I read handler in the documentation, but you're right. I also thought I had tried handle just in case. I'll double check tomorrow.

**Comment by geirman** [comment]
Well, I'm an idiot. I'm not why I was so certain it was handler. I do feel like I double checked that, but apparently not. My bad.
