### ISSUE TITLE
Feature Request: Definable [key] in Routes

### ISSUE THREAD

**Issue by geirman** [cfwheels/cfwheels#946]
A common pattern in many apps is to use unique `slugs` in place of `keys` or `id` when referencing a data object. An example is...

https://blog.com/posts/my-great-post (where `my-great-post` is the `slug`, replacing the post's id as the key)

There are at least a couple benefits, probably more...

1. They're human readable
2. They don't offer any insight into the datastore

## The Challenge
Currently, CFW hard codes the `[key]` part of the routes, so replacing it with `[slug]` currently requires extra, manual effort. 

## The Solution
With just a few simple changes to the code, we can make this a trivial thing.

1. Add `keyName='key'` to the attributes list of both the `resources()` and `resource()` functions
2. Replace `[key]` of [/wheels/mapper/resources.cfm#L37](https://github.com/cfwheels/cfwheels/blob/master/wheels/mapper/resources.cfm#L73) with `[#arguments.keyName#]`
3. Update documentation

Done! And it's backwards compatible since it defaults to existing behavior. 

With this in place, generating a slug-based (rather than key-based) collection of routes would be trivial. 

```
.resources(name='posts', keyName='slug')
```

## Added Benefits?
Maybe debatable, but I think it would be nice to be able to do the following (if we wanted to) since it's more descriptive and searchable than generically referencing `key` everywhere...

```
.resources(name='posts', keyName='postId')
.resources(name='events', keyName='eventId')
.resources(name='jobs', keyName='jobId')
```

**Comment by neokoenig** [comment]
I do really like this idea. I'm aware that it moves away from the rails way of doing routing. (https://guides.rubyonrails.org/routing.html#resources-on-the-web) - so it's something worth thinking about a bit!

**Comment by geirman** [comment]
@neokoenig Totally understand. The change was easy enough, so I created a PR. Feel free to pull it in (or toss it) as you see fit. I'm aware rails was the inspiration, but I wasn't sure how closely aligned they've remained over time. I've never actually been a rails person, so all I know is CFW's implementation.

**Comment by andybellenie** [comment]
I don't understand this issue. 

'key' is any unique identifier for the record - it doesn't necessarily mean the primary key. There's nothing to stop you doing this already using existing methods, e.g. model("Post").findByTitle(params.key).

**Comment by geirman** [comment]
That's a great point, @andybellenie. In most places `key` will refer to the primaryKey, which makes sense. IMO, it makes less sense to refer to the `key` as a `key` when it's actually a slug, an email address, a token, etc. So, this may be more of an ergonomic issue meant to improve code readability and better communicate intent.

**Comment by andybellenie** [comment]
I'm in two minds over this. I don't like extraneous configuration options and I don't want to have to check the routes file to know what key a resource is using, params.key is standard throughout so I always know what it means across multiple CFW systems. However it's a fairly minor change, is backwards compatible, and might better communicate intent, as you say.

@neokoenig @perdjurner @dbelanger thoughts?

**Comment by andybellenie** [comment]
Bearing in mind CFW is nominally a convention-over-configuration framework, so in general we prefer as few options as possible.

**Comment by perdjurner** [comment]
My concern is that we have `key` hard-coded in a lot of places and we might miss a spot where we would now need to follow this new setting.

**Comment by dbelanger** [comment]
I've used just about everything for `key` from integers, CF UUIDs, MySQL UUIDs,  GUIDs and strings (in a "unique" primary key field).  There's nothing stopping you from creating a primary `id` field (following convention) of type **varchar** or **char** (assuming your DB allows it) and entering your slug name.  It needs to be unique anyway for routes to work. 

My main attraction to wheels was that: Convention over configuration.  Naturally, those are just my two cents.

**Comment by geirman** [comment]
Thanks everyone for indulging my request with this thoughtful discussion. The change is totally benign in that it adds the option for configuration but still follows the convention over configuration paradigm. Most everything in Wheels is this way. Going with the flow makes things easier. Start configuring things and you'll have to do things like "check the routes file to know what the key a resource is using". But, using dynamic functions still makes for pretty readable code. So, I don't know if it's worth fretting over...

```
event=model("event").findOneBySlug(params.key)
```

**Comment by andybellenie** [comment]
Looking at it from a classical MVC approach, params.key is a property of the controller, and has no implicit relationship with any model. Defining the key name in this way to map to a database column breaks this separation. I realise this is somewhat purist but it has value. If the dynamic finders are effective I recommend sticking with them and if you really want this functionality then you could always make a plugin.

**Comment by geirman** [comment]
I agree. Thanks again
