### ISSUE TITLE
Add errorEmailFromAddress

### ISSUE THREAD

**Issue by andybellenie** [cfwheels/cfwheels#95]
Allow a different from address to the to address in the error email config

**Comment by nialexsan** [comment]
I have noticed that there is no this change in the master branch. On error it is using the same var **errorEmailAddress** for **loc.mailArgs.from** and **loc.mailArgs.to** parameters in _wheels/events/onerror.cfm_

**Comment by perdjurner** [comment]
@nialexsan You're correct, this never made it into a release. You can open a pull request against the master branch if you want this added. Thanks :)
