### ISSUE TITLE
Configuration option to skip test package metadata check

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#950]
When large numbers of test packages are present, the $isValidTest() function that is called on each package can considerably slow down the listing of test packages (20+ seconds).

I propose a `validateTestPackageMetaData` setting that can be set to false if one is confident in one's test package validity and wishes to speed up the directory listing.

**Comment by chapmandu** [comment]
I've already done this work in another repo.. Just need approval to implement in the wheels core.

**Comment by neokoenig** [comment]
Good idea, do it I say

**Comment by chapmandu** [comment]
f3f2f1e8cb5c93e319b5945055ad036032d15de2
