### ISSUE TITLE
Beta GUI bugs

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#951]
- [x] Odd Behaviour for `/wheels/migrator`, `/wheels/migrator/templates/` and `/wheels/plugins` on linux: it might be my URL rewriting though. Basically hangs unless you've got a trailing slash? NB commandbox throws `[ERROR] runwar.context: Location: '/wheels/migrator' generated no content, maybe verify any errorPage locations? (status code: 302)` locally which is probably related.
- [x] Migrator templates doesn't yet correctly get the Migration File Template Prefix, and the form doesn't reset properly. 
- [x] Route parser should ignore query strings
- [ ] Migrator output doesn't preserve linebreaks on linux - leaving this as will probably redesign/change later
- [x] Test package filter
- [ ] Add Full width toggle - leaving this as will probably redesign later

**Comment by chapmandu** [comment]
I've noticed a couple of small issues:

1. Migration Prefix should default to the existing prefixes used
2. Route parser should ignore query strings

**Comment by chapmandu** [comment]
Not really a bug, but a small feature request I would find extremely useful is a test package filter similar to the route and docs filter.

**Comment by neokoenig** [comment]
> Not really a bug, but a small feature request I would find extremely useful is a test package filter similar to the route and docs filter.

Now added

**Comment by neokoenig** [comment]
@chapmandu I think the "All" tab isn't a great idea as it would require re-rendering/outputing the entire table. for the core tests that adds 1400+ rows, which in turn, assuming it was filterable would make that keyup JS filter probably not very responsive (as it would be attempting to filter all three tables)

**Comment by neokoenig** [comment]
@chapmandu also, could you test something for me on a linux box? If you hover over the Navigation link for Migrator, you should see `/wheels/migrator` with no trailing slash. However, when I click on it, I end up at `/wheels/migrator/` on my local d0ze box. On one of linux boxes, it doesn't add a trailing slash and just hangs. I can't work out whether this is simply a URL rewrite thing (as the linux boxes use htaccess vs urlrewrite.xml on my local box), or whether the wheels routing system is interfering...

**Comment by dbelanger** [comment]
@neokoenig The errors overrun the right side of the new GUI and there is no horizontal scroll to be able to see the whole line.  We may need a wrap on this or even better, we should put the errors directly into an empty DIV under your menu without any box around it.  I've attached a picture of what's happening.

![image](https://user-images.githubusercontent.com/7602820/58104489-d9cd0d00-7bb2-11e9-9721-1e5b7c36d98b.png)

**Comment by neokoenig** [comment]
@dbelanger interestingly, Lucee doesn't get the error location field! Testing in CF2016 I see what you mean. Have now patched it to at least do a scroll. 

![image](https://user-images.githubusercontent.com/381268/58106690-64783100-7be0-11e9-990d-4758b6aba3b6.png)

**Comment by chapmandu** [comment]
> @chapmandu also, could you test something for me on a linux box? 

I'm seeing no slash on the end using CentOS and tuckey rewriting.

**Comment by chapmandu** [comment]
Can we (you) make the layout full screen width? We have some long route patterns which push outside the container.. The menu is full width anyway.

Can the route pattern parser not require a method selection? It would be handy to be able to parse across methods.
