### ISSUE TITLE
Authenticity token causing Chrome warning

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#953]
If I use `startFormTag` twice on a page I get this warning in Chrome:

"Found 2 elements with non-unique id #authenticityToken"

I don't think the `id` attribute is needed at all so I removed it with this code (in the `authenticityTokenField` function):
```
// Create hidden field containing the authenticity token.
local.rv = hiddenFieldTag(name="authenticityToken", value=local.authenticityToken);

// Delete the id="authenticityToken" part of the string.
// There could be multiple forms on a page and duplicate "id" attributes are not allowed in HTML.
local.rv = Replace(local.rv, ' id="authenticityToken" ', " ");

return local.rv;
```

Any thoughts, good enough solution?

**Comment by chapmandu** [comment]
Makes sense.  Would a user want to explicitly set an id? Could it be made to only remove if not explicitly defined?

I'd personally be happy to remove it.

**Comment by neokoenig** [comment]
The only reason I can imagine you'd want an id on a hidden form field is an easier way to get it's value via JS: it's not as if there isn't a work around though.

**Comment by neokoenig** [comment]
Related: https://github.com/cfwheels/cfwheels/issues/851

**Comment by perdjurner** [comment]
https://github.com/cfwheels/cfwheels/pull/991
