### ISSUE TITLE
CFWheels 2.0.1 Site Becomes Unresponsive Randomly due to DeadLock Thread

### ISSUE THREAD

**Issue by Devinwhite** [cfwheels/cfwheels#954]
We've had an issue for awhile now where one of our client sites will stop responding and the only way to get it to recover is restarting cf instance.  

We installed Fusion Reactor to help pin point the issue we are having and we are able to see a deadlock thread causing the issue. 

It seems two threads are dependent on each other to clear yet both are in deadlock so neither can continue which causes all subsequent threads to be blocked. 

Below you can see the two Deadlock Thread Trace.

coldfusion.runtime.TemplateProxyFactory.resolveName(TemplateProxyFactory.java:221)
- waiting on <0x7b15a64b> (a coldfusion.runtime.AttributeCollection held by thread 154, ajp-nio-8016-exec-9)
coldfusion.runtime.TemplateProxyFactory.resolveComponentHelper(TemplateProxyFactory.java:377)
coldfusion.runtime.TemplateProxyFactory.resolveNameForDuplicate(TemplateProxyFactory.java:168)
coldfusion.cfc.ComponentProxyFactory.getProxy(ComponentProxyFactory.java:47)
coldfusion.cfc.ComponentProxyFactory.getProxy(ComponentProxyFactory.java:72)
coldfusion.runtime.ProxyFactory.getProxy(ProxyFactory.java:68)
coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2495)
coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)
coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
coldfusion.runtime.Struct.duplicate(Struct.java:210)
 - locked <0x5c0e46c6> (a coldfusion.runtime.Struct)
coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:102)
coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
coldfusion.runtime.Struct.duplicate(Struct.java:210)
 - locked <0x24fe2cf5> (a coldfusion.runtime.Struct)
coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:102)
coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:142)
coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:142)
coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
coldfusion.runtime.CFPage.Duplicate(CFPage.java:6734)
cfcfml2ecfm1402424480$func$INVOKE.runFunction(C:\inetpub\wwwroot\CLIENTSITE\wheels\global\cfml.cfm:156)
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:425)
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:538)
coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3483)
coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3464)
cfcfml2ecfm1402424480$func$SIMPLELOCK.runFunction(C:\inetpub\wwwroot\CLIENTSITE\wheels\global\cfml.cfm:33)
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:425)
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:538)
coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3483)
coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3464)
cfonsessionend2ecfm1534203156$funcONSESSIONEND.runFunction(C:\inetpub\wwwroot\CLIENTSITE\wheels\events\onsessionend.cfm:5)
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:425)
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234)
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:650)
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:596)
coldfusion.cfc.CFCProxyFilter.invokeAppEvent(CFCProxyFilter.java:102)
 - locked <0x2cd3eb2d> (a coldfusion.runtime.CFDummyComponent)
coldfusion.cfc.CFCProxyFilter.invoke(CFCProxyFilter.java:43)
coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
coldfusion.cfc.CFCProxy.doInvoke(CFCProxy.java:328)
coldfusion.cfc.CFCProxy.invoke(CFCProxy.java:302)
coldfusion.runtime.AppEventInvoker.onSessionEnd(AppEventInvoker.java:462)
coldfusion.runtime.SessionTracker.invokeOnSessinEnd(SessionTracker.java:292)
coldfusion.runtime.SessionTracker.cleanUp(SessionTracker.java:275)
coldfusion.runtime.SessionTracker.access$000(SessionTracker.java:43)
coldfusion.runtime.SessionTracker$SessionCleanUpAgent.run(SessionTracker.java:484)
coldfusion.scheduling.ThreadPool.run(ThreadPool.java:260)
coldfusion.scheduling.WorkerThread.run(WorkerThread.java:71)

--------------------------------------------------------------------------------------

coldfusion.runtime.Struct.get(Struct.java:128)
- waiting on <0x24fe2cf5> (a coldfusion.runtime.Struct held by thread 97, scheduler-1)
coldfusion.runtime.CfJspPage._resolve(CfJspPage.java:1892)
coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:2308)
coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:2288)
cfinjection2ecfm444718671.runPage(C:\inetpub\wwwroot\CLIENTSITE\wheels\plugins\standalone\injection.cfm:11)
coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:253)
coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:737)
coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:573)
coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3696)
cfController2ecfc1110466214.runPage(C:\inetpub\wwwroot\CLIENTSITE\wheels\Controller.cfc:6)
coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:253)
coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
coldfusion.runtime.TemplateProxyFactory.resolveComponentHelper(TemplateProxyFactory.java:542)
coldfusion.runtime.TemplateProxyFactory.resolveName(TemplateProxyFactory.java:237)
 - locked <0x7b15a64b> (a coldfusion.runtime.AttributeCollection)
coldfusion.runtime.TemplateProxyFactory.resolveComponentHelper(TemplateProxyFactory.java:377)
coldfusion.runtime.TemplateProxyFactory.resolveName(TemplateProxyFactory.java:237)
 - locked <0x5f4c93f1> (a coldfusion.runtime.AttributeCollection)
coldfusion.runtime.TemplateProxyFactory.resolveComponentHelper(TemplateProxyFactory.java:377)
coldfusion.runtime.TemplateProxyFactory.resolveName(TemplateProxyFactory.java:237)
 - locked <0x64b0ca1b> (a coldfusion.runtime.AttributeCollection)
coldfusion.runtime.TemplateProxyFactory.resolveName(TemplateProxyFactory.java:162)
coldfusion.runtime.TemplateProxyFactory.resolveName(TemplateProxyFactory.java:152)
coldfusion.cfc.ComponentProxyFactory.getProxy(ComponentProxyFactory.java:57)
coldfusion.tagext.lang.InvokeTag.doEndTag(InvokeTag.java:468)
coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3697)
cfroot2ecfm1312791191.runPage(C:\inetpub\wwwroot\CLIENTSITE\root.cfm:1)
coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:253)
coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:737)
coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:573)
coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3696)
cfinternal2ecfm758663335$func$CREATEOBJECTFROMROOT.runFunction(C:\inetpub\wwwroot\CLIENTSITE\wheels\global\internal.cfm:543)
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:425)
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:538)
coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3483)
coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3464)
cfinitialization2ecfm721025666$func$CREATECONTROLLEROBJECT.runFunction(C:\inetpub\wwwroot\CLIENTSITE\wheels\controller\initialization.cfm:18)
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:425)
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234)
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:650)
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:439)
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:409)
coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3097)
coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3074)
cfmisc2ecfm1671810281$funcCONTROLLER.runFunction(C:\inetpub\wwwroot\CLIENTSITE\wheels\global\misc.cfm:462)
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:425)
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:538)
coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3483)
coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3464)
cffunctions2ecfm1876356943$func$REQUEST.runFunction(C:\inetpub\wwwroot\CLIENTSITE\wheels\dispatch\functions.cfm:183)
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:425)
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234)
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:650)
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:439)
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:409)
coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3097)
coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3074)
cfindex2ecfm2017714708.runPage(C:\inetpub\wwwroot\CLIENTSITE\wheels\index.cfm:5)
coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:253)
coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:737)
coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:573)
coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3696)
cfrewrite2ecfm182375964.runPage(C:\inetpub\wwwroot\CLIENTSITE\rewrite.cfm:2)
coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:253)
coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:737)
coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:573)
coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3696)
cfonrequest2ecfm1579587420$funcONREQUEST.runFunction(C:\inetpub\wwwroot\CLIENTSITE\wheels\events\onrequest.cfm:5)
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:425)
coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234)
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:650)
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:439)
coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:409)
coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:114)
coldfusion.runtime.AppEventInvoker.onRequest(AppEventInvoker.java:307)
coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:480)
coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:43)
coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
coldfusion.filter.PathFilter.invoke(PathFilter.java:153)
coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:60)
coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
coldfusion.CfmServlet.service(CfmServlet.java:219)
coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
com.intergral.fusionreactor.j2ee.filterchain.WrappedFilterChain.doFilter(WrappedFilterChain.java:134)
com.intergral.fusionreactor.j2ee.filter.FusionReactorRequestHandler.doNext(FusionReactorRequestHandler.java:764)
com.intergral.fusionreactor.j2ee.filter.FusionReactorRequestHandler.doHttpServletRequest(FusionReactorRequestHandler.java:344)
com.intergral.fusionreactor.j2ee.filter.FusionReactorRequestHandler.doFusionRequest(FusionReactorRequestHandler.java:207)
com.intergral.fusionreactor.j2ee.filter.FusionReactorRequestHandler.handle(FusionReactorRequestHandler.java:801)
com.intergral.fusionreactor.j2ee.filter.FusionReactorCoreFilter.doFilter(FusionReactorCoreFilter.java:36)
sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
com.intergral.fusionreactor.j2ee.filterchain.WrappedFilterChain.doFilter(WrappedFilterChain.java:71)
sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
com.intergral.fusionreactor.agent.filter.FusionReactorStaticFilter.doFilter(FusionReactorStaticFilter.java:54)
com.intergral.fusionreactor.agent.pointcuts.NewFilterChainPointCut$1.invoke(NewFilterChainPointCut.java:41)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java)
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:355)
org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:510)
org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
 - locked <0xff4d3c0> (a org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
java.lang.Thread.run(Thread.java:745)

Locked ownable synchronizers: 
    - java.util.concurrent.ThreadPoolExecutor$Worker <0xf2f2cc1>

**Comment by chapmandu** [comment]
I noticed that onsessionend was one of the locks.. Fusion reactor peeps have commented about managing your sessions properly (eg setting sensible timeouts and not creating new sessions for every non logged in user). I got caught out by this and all ram was slowly being chewed up.. Could this be the issue?

**Comment by Devinwhite** [comment]
I don’t think so. I’ve got an 1.5 hour timeout and only logged in users have access and it’s software that’s been in use for 12 plus years but now just in the cfwheels framework. It’s by no means perfect code but this seems to be an issue where onsession end is doing something and onrequest is doing something and neither can complete because they are waiting on the other thread to complete.   Causing the system to just get backed up till it’s unresponsive. The memory is fine as well as CPU and cfusion administer and other sites will work as normal. But this cfwheels site is essentials hosed until I restart services. I’m just not familiar enough with what cfwheels is doing to understand the conflict.

**Comment by chapmandu** [comment]
How long is your application request timeout?

**Comment by Devinwhite** [comment]
1 hour 45 mins

**Comment by neokoenig** [comment]
Can you also confirm which Wheels version?

**Comment by Devinwhite** [comment]
Yes the release version of 2.0.1

**Comment by chapmandu** [comment]
I assume that's your session timeout.. What's your request timeout?

**Comment by Devinwhite** [comment]
Session timeout 1.5 hours
Application timeout 1.75 hours
Request Timeout 5min

**Comment by Devinwhite** [comment]
**LOCKED CODE**

LINE 11:  INJECTION.cfm

if (isDefined("application") && !StructIsEmpty(application[$wheels.appKey].mixins)) {


LINE 156: cfml.cfm
<cfset arrayPrepend(request.$wheelsInvoked, duplicate(arguments))>



The only correlation i'm seeing with these threads is both are doing a lock on a variable 

 ONREQUEST.cfm

**lock** name="reloadLock#**application.applicationName**#" type="readOnly" timeout="180" {
	include "#arguments.targetpage#";
}

ONSESSIONEND.cfm

local.lockName = "reloadLock" & **arguments.applicationScope.applicationName**;
	$**simpleLock**(name=local.lockName, execute="$runOnSessionEnd", executeArgs=arguments, type="readOnly", timeout=180);

Is it possible that the duplicate function is failing because the variable is locked? and the stuctIsEmpty cant complete because the application scope is some how locked due to the duplicate function failing?

This is a big stretch... I have no idea whats going on in the middle of these functions or there purposes.  But i thought it was interesting to see two places lock the same variable.

Thoughts?  I'm i way off base?

**Comment by Devinwhite** [comment]
I'm also suspicious of the Duplicate function in the CFML.cfm file on invoke.  

In this instance onsessionend sends application and session scope to this function.  

I'm not sure but if lets say session or application had recursive references to the same object or something.  Maybe duplicate is just stuck in a recursive loop trying to create copies of these?

To test my theory i'm commenting out this bit of code that inserts into the wheelsInvoked array.  If my problem persists  then I know its not an issue with the duplicate function.   

Thoughts?

**Comment by chapmandu** [comment]
I'm interested to hear about your results.. (though I use Lucee) What version of ACF are you running? Are the patches up to date?

**Comment by Devinwhite** [comment]
CF 2016 all patched up yes.  So far I haven't had a recurrence of the site being unresponsive.  But it has gone a full month previously without having the issue.  So I'll keep monitoring it and i'll update this issue once I have some clear results.

**Comment by Devinwhite** [comment]
Turns out it was not related to cfwheels at all.  It just locked the site up enough that cfweels processing pages was a symptom.   It was a bad set of pdf code that was using cfdocment and cfpdf and caused the server to hang.

**Comment by Devinwhite** [comment]
This still seems to be an issue. I'm reopening for now until I find out more .

**Comment by Devinwhite** [comment]
The server was locked up then when i commented out the duplicate code in cfml.cfm it freed up and started working again after receiving an error.  Which is calling the invoke that contains the duplicate code i commented out.  

"A timeout occurred while attempting to lock $mapperLoadRoutes. The specific sequence of files included or processed is: C:\inetpub\wwwroot\ClientFolder\rewrite.cfm, line: 32 "
coldfusion.tagext.lang.LockTag$TimeoutException: A timeout occurred while attempting to lock $mapperLoadRoutes.
	at coldfusion.tagext.lang.LockTag.doStartTag(LockTag.java:220)
	at cfcfml2ecfm1133311994$func$SIMPLELOCK.runFunction(C:\inetpub\wwwroot\ClientFolder\wheels\global\cfml.cfm:32)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:493)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:426)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:389)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:340)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:539)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3494)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3475)
	at cfinternal2ecfm1952109175$func$LOADROUTES.runFunction(C:\inetpub\wwwroot\ClientFolder\wheels\global\internal.cfm:824)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:493)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:426)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:389)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:340)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:235)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3553)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3533)
	at cfonapplicationstart2ecfm2011726901$funcONAPPLICATIONSTART._factor2(C:\inetpub\wwwroot\ClientFolder\wheels\events\onapplicationstart.cfm:461)
	at cfonapplicationstart2ecfm2011726901$funcONAPPLICATIONSTART.runFunction(C:\inetpub\wwwroot\ClientFolder\wheels\events\onapplicationstart.cfm:405)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:493)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:426)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:389)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:340)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:235)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:653)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:442)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:412)
	at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:114)
	at coldfusion.runtime.AppEventInvoker.onApplicationStart(AppEventInvoker.java:237)
	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:345)
	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:43)
	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
	at coldfusion.filter.PathFilter.invoke(PathFilter.java:153)
	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
	at coldfusion.filter.BrowserDebugFilter.invoke(BrowserDebugFilter.java:78)
	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:60)
	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
	at coldfusion.CfmServlet.service(CfmServlet.java:223)
	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:355)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:510)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Devinwhite** [comment]
Tonight was another lockup but this time the application scope variable died.

"Error","scheduler-2","06/27/19","18:06:15","","Element APPLICATIONSCOPE.APPLICATIONNAME is undefined in ARGUMENTS. The specific sequence of files included or processed is: '', line: 4 "

Which turns out to be on the same onsessionend function. 

Is it possible my timeouts are causing issues?  

Session timeout 1.5 hours
Application timeout 1.75 hours
Request Timeout 5min

**Comment by chapmandu** [comment]
FWIW, I have my application scope timeout set somewhat larger than yours:

`this.applicationTimeout = CreateTimeSpan( 365, 0, 0, 0 );`

Mind you, we restart our application server during the deployment process so the application scope rarely lives longer than a few days..

**Comment by Devinwhite** [comment]
Yeah i'm starting to suspect that might be the issue.

**Comment by neokoenig** [comment]
Apparently that application timeout only applies when no-one hits your application: i.e, it'll never restart if you're pinging it every 5 mins etc

**Comment by Devinwhite** [comment]
I haven't had any issues since i increased my application timeout.  So I think it was a timing thing where application would timeout right before session would or something so it would just be random.  I'm going to leave this issue open for a few more weeks just in case it comes up again.  But I'm hopeful that this is the fix to my issue.

**Comment by Devinwhite** [comment]
This was due to rapid application timeout.  Once i updated the timeout to be longer we have not seen this issue again.
