### ISSUE TITLE
Plugins route does not accept POST method

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#956]
Some plugins contain embedded forms that post to themselves, but the POST method is not accepted by the mapper for the plugin route.

**Comment by neokoenig** [comment]
This has presumably never worked for 2.x?
Or is this specifically to do with the new GUI?

**Comment by chapmandu** [comment]
I'm assuming it's never worked in 2.x.. But I had not tried it until recently. I suppose it depends on whether the old wildcard route accepted posts.
