### ISSUE TITLE
Add Favicon to Docs

### ISSUE THREAD

**Issue by geirman** [cfwheels/cfwheels#959]
I'm just getting tired of looking at the Firefox default icon...
![2019-07-21_1311](https://user-images.githubusercontent.com/1640318/61596486-3485e380-abb9-11e9-8333-f58f04385f33.png)

So, I thought I'd provide a `favicon.ico` to be dropped into the root of the documentation site.
[favicon.ico.zip](https://github.com/cfwheels/cfwheels/files/3415005/favicon.ico.zip)

It'll look something like this...
![2019-07-21_1303](https://user-images.githubusercontent.com/1640318/61596500-6a2acc80-abb9-11e9-91ac-e86df0f88d70.png)

**Comment by neokoenig** [comment]
lol, I'm sure I can sort that at some point :P

**Comment by neokoenig** [comment]
Done

**Comment by geirman** [comment]
![2019-09-28_1152](https://user-images.githubusercontent.com/1640318/65821151-aba5ac80-e1e6-11e9-9548-52715fdfa288.png)
