### ISSUE TITLE
Connecting to Oracle

### ISSUE THREAD

**Issue by debrajgh** [cfwheels/cfwheels#960]
I understood that cfwheels does not support Oracle anymore. Does that mean that with cfwheels version 2.0.1 I could nt connect to Oracle anymore.

We are going to start a new project on cfml and was considering cfwheels to use as the framework

Thanks

Debraj

**Comment by neokoenig** [comment]
We are vaguely considering adding it back in 2.1 https://github.com/cfwheels/cfwheels/pull/955

**Comment by debrajgh** [comment]
Does that mean if I create a connection in Coldfusion and put the connection name in config/settings.cfm, it will not connect

As mentioned, I am using cfwheels 2.0.1

**Comment by neokoenig** [comment]
Correct. It will most likely throw a 'database not supported error' at present, meaning you can't use it for the ORM etc. You could still use oracle via manual queries, as you'd be able to setup a standard datasource and then pass in the datasource name directly to cfquery, but you'd not be able to use all the 'findAll()` type of helpers. The routing etc would still work though.

We're considering putting it back for 2.1 beta if there's enough support/demand for it

**Comment by debrajgh** [comment]
Thanks for the update.
