### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by bawelter** [cfwheels/cfwheels#964]
You can still inject SQL if  `redacted` Its just an example of the security issue.

**Comment by bawelter** [comment]
Need have a way to leave actual params in the query and then populate them through cfqueryparam like model("user").findOne(where"email=$1 AND password=$2", parameters=[ ... ])

**Comment by neokoenig** [comment]
Hi @bawelter - I think I can see the issue; the params do escaped via cfqueryparam, but there's a potential for a `'` to add an additional parameter. I'll check with the rest of the team.

**Comment by bawelter** [comment]
Yes, regardless of how the where clause is parsed after it is passed in there will always be a risk of injection unless the parameters are passed as a separate array and then passed directly to the `cfqueryparam`.

**Comment by neokoenig** [comment]
Thanks Bryan - we're discussing this offlist and seeing what the best solution will be which doesn't massively break backwards compatibility.

**Comment by neokoenig** [comment]
Hi @bawelter Can you confirm which version of wheels you're running? We can only recreate this on the current Master branch so far.

**Comment by neokoenig** [comment]
Just an update, we've found the specific issue and will issue a security release in the next few days.
