### ISSUE TITLE
Problem with threading and sendEmail()

### ISSUE THREAD

**Issue by edthetechie** [cfwheels/cfwheels#970]
There seems to be an issue with the sendEmail() function when used inside a thread. 

System Information:
ColdFusion Version: 2018,0,05,315699
Operating System: Windows Server 2016  
CFWheels Version: 2.0.2

The symptom is that variables in the email are not being added correctly when looping over a list of user emails. It is also sending out more than double the amount of emails that it should. I've got some simple code to illustrate the problem:
```
<cfscript>
	// Simple dbase query to get a list of members
	members = model("member").findAll(where="email LIKE '%@cc.uk.com'", maxrows="5", order="email");
	// Create the variables for the sendEmail() function
	eshotArgs.to = params.emailto;
	eshotArgs.from = "tech@cc.uk.com";
	eshotArgs.subject = "Non-thread Test";
	// Loop over the members and send an email without a thread, works fine
	for (m in members) {
		eshotArgs.memberid = m.itemid;
		eshotArgs.memberemail = m.email;
		eshotArgs.layout = "/admin/emails/layouts/stsimple";
		eshotArgs.template = "threadtestemail";
		sendEmail(argumentCollection=eshotArgs);
	}
	// Do the same thing again inside a thread and weird stuff happens
	thread action="run" name="esImport#createuuid()#" {
		ntmembers = model("member").findAll(where="email LIKE '%@cc.uk.com'", order="email");
		eshotArgsThread = {};
		eshotArgsThread.to = params.emailto;
		eshotArgsThread.from = "tech@cc.uk.com";
		eshotArgsThread.subject = "Thread Test";
		for (m in ntmembers) {
			eshotArgsThread.memberid = m.itemid;
			eshotArgsThread.memberemail = m.email;
			eshotArgsThread.layout = "/admin/emails/layouts/stsimple";
			eshotArgsThread.template = "threadtestemail";
			sendEmail(argumentCollection=eshotArgsThread);
		}
	}
	abort;
</cfscript>
```
The email template is very simple:
```
<cfoutput>
  #memberemail#<br>
  #memberid#
</cfoutput>
```
The layout is simply some CSS and branding with no variables or anything in it.

I can provide a test URL via direct message if it's helpful. What I'm seeing is that the code not in a thread is fine. The code within the thread sends 11 emails instead of 5 and they all have the variables from the first user in them.

I've had Hostek, our hosting provider, take a look at this and their response was:

> We've reviewed this behavior extensively and are able to replicate without issue after a first request is made. The first request we made delivered the expected results. However, any subsequent requests resulted in the behavior reported in this ticket.
> 
> We believe that this behavior may be related to your CFWheels application and incompatibility in ColdFusion 2018. Are you running on the latest release of CFWheels? If not, we'd recommend that you plan an update to the latest release to ensure your codebase is compatible. Alternatively, you may wish to reach out to the CFWheels developers to see if this is behavior they've had reported before as it does not appear to be an issue directly related to your ColdFusion server configuration or settings..

I'm pretty sure this is an issue with CFWheels and ColdFusion 2018 because we recently switched from CF 2016 and this code worked on that without incident for a long time.

**Comment by chapmandu** [comment]
Does it make a difference if you "var" the eshotArgsThread, not members and m variables?

**Comment by edthetechie** [comment]
Unfortunately that didn't make any difference, I changed my code to:
```
<cfparam name="params.emailto" default="ed@cc.uk.com">
<cfscript>
	// Simple dbase query to get a list of members
	var members = model("member").findAll(where="email LIKE '%@cc.uk.com'", maxrows="5", order="email");
	// Create the variables for the sendEmail() function
	var eshotArgs = {};
	eshotArgs.to = params.emailto;
	eshotArgs.from = "tech@cc.uk.com";
	eshotArgs.subject = "Non-thread Test";
	// Loop over the members and send an email without a thread, works fine
	for (m in members) {
		var eshotArgs.memberid = m.itemid;
		var eshotArgs.memberemail = m.email;
		eshotArgs.layout = "/admin/emails/layouts/stsimple";
		eshotArgs.template = "threadtestemail";
		sendEmail(argumentCollection=eshotArgs);
	}
	// Do the same thing again inside a thread and weird stuff happens
	thread action="run" name="esImport#createuuid()#" {
		var ntmembers = model("member").findAll(where="email LIKE '%@cc.uk.com'", order="email");
		var eshotArgsThread = {};
		eshotArgsThread.to = params.emailto;
		eshotArgsThread.from = "tech@cc.uk.com";
		eshotArgsThread.subject = "Thread Test";
		for (m in ntmembers) {
			var eshotArgsThread.memberid = m.itemid;
			var eshotArgsThread.memberemail = m.email;
			eshotArgsThread.layout = "/admin/emails/layouts/stsimple";
			eshotArgsThread.template = "threadtestemail";
			sendEmail(argumentCollection=eshotArgsThread);
		}
	}
	abort;
</cfscript>
```
The result was the same. 5 perfect emails from the non-threaded code and 11 emails with the same email and user ID from the threaded code :-(

**Comment by neokoenig** [comment]
I think adam was referring to the `for (m in members) {` bit, i.e `for (var m in members) {`

**Comment by edthetechie** [comment]
Thanks for clearing that up Tom. I changed the threaded code as Adam suggested but it didn't have any effect, the emails come through in the same way:
```
thread action="run" name="esImport#createuuid()#" {
	var ntmembers = model("member").findAll(where="email LIKE '%@cc.uk.com'", order="email");
	var eshotArgsThread = {};
	eshotArgsThread.to = params.emailto;
	eshotArgsThread.from = "tech@cc.uk.com";
	eshotArgsThread.subject = "Thread Test";
	for (var m in ntmembers) {
		var eshotArgsThread.memberid = m.itemid;
		var eshotArgsThread.memberemail = m.email;
		eshotArgsThread.layout = "/admin/emails/layouts/stsimple";
		eshotArgsThread.template = "threadtestemail";
		sendEmail(argumentCollection=eshotArgsThread);
	}
}
```

**Comment by edthetechie** [comment]
I've also tried changing the syntax of the for loop, thusly:
```
thread action="run" name="esImport#createuuid()#" {
	var ntmembers = model("member").findAll(where="email LIKE '%@cc.uk.com'", order="email");
	var eshotArgsThread = {};
	eshotArgsThread.to = params.emailto;
	eshotArgsThread.from = "tech@cc.uk.com";
	eshotArgsThread.subject = "Thread Test";
	**for (i = 1; i <= ntmembers.recordCount; i++) {** 
	//for (var m in ntmembers) {
		**var eshotArgsThread.memberid = ntmembers["itemid"][i];
		var eshotArgsThread.memberemail = ntmembers["email"][i];**
		eshotArgsThread.layout = "/admin/emails/layouts/stsimple";
		eshotArgsThread.template = "threadtestemail";
		sendEmail(argumentCollection=eshotArgsThread);
	}
}
```
No effect :-(

**Comment by neokoenig** [comment]
Might be worth trying something like this:

```
<cfscript>
	
	// Simple dbase query to get a list of members
	var members = model("member").findAll(where="email LIKE '%@cc.uk.com'", maxrows="5", order="email");
	
	// Create the variables for the sendEmail() function
	var eshotArgs = {};
	eshotArgs.to = params.emailto;
	eshotArgs.from = "tech@cc.uk.com";
	eshotArgs.subject = "Non-thread Test";  

	thread action="run" name="esImport1" {
		var test = []; 
		var ntmembers = model("member").findAll(where="email LIKE '%@cc.uk.com'", order="email");
		var eshotArgsThread = {};
		eshotArgsThread.to = params.emailto;
		eshotArgsThread.from = "tech@cc.uk.com";
		eshotArgsThread.subject = "Thread Test";
		for (m in ntmembers) {
			var eshotArgsThread.memberid = m.itemid;
			var eshotArgsThread.memberemail = m.email;
			eshotArgsThread.layout = "/admin/emails/layouts/stsimple";
			eshotArgsThread.template = "threadtestemail";
			arrayAppend(test);
		}
		writeDump(test);
	}

	thread action="join" name="esImport1" timeout="600";

	writeOutput(esImport1.output);

	abort;
</cfscript>
```

This way we should be able to inspect what's happening in the thead in a bit more detail...
Interestingly I'm getting an error thrown on ACF2018 within the thread too (java.lang.NullPointerException at coldfusion.monitor.event.RequestMonitorEventProcessor.onThreadEnd) which you can see if you dump `esImport1` (rather than writeoutput) - so it may well be a bug in ACF..... The fact that it worked in 2016 kinda supports that maybe.

**Comment by edthetechie** [comment]
The line:
`arrayAppend(test);`
caused an error so I changed it to:
`arrayAppend(test, eshotArgsThread);`
When I dump out each array I get the exact same object for each one:
![image](https://user-images.githubusercontent.com/974402/68399556-76d62f00-016e-11ea-9a78-aba375b9ff3e.png)
This definitely feels like a bug in ACF 2018, we've had this code running on ACF 2016 for well over a year without any problems at all.

**Comment by neokoenig** [comment]
Which is weird. As a simple test, this works:
```
testArr = [1,2,3,4,5];
 thread action="run" name="myThread1" {
   test = []
	    for (t in  testArr) {
    	       arrayAppend(test, t);
	    }
	    writeDump(test);
	} 
	thread action="join" name="myThread1" timeout="600";
 	writeOutput(myThread1.output);
	abort;
```

My suspicion is there's something going on with how the var scope is accessed from within a thread - the data/looping isn't doing what you expect. Fundamentally, I don't think this is a wheels issue, so I'm going to close this issue, but please of course reopen it if you track down something which is wheels related!

**Comment by andybellenie** [comment]
Hi Ed!

When working with cfthread you can include properties to ensure correct
processing, you can't rely on any data in the calling page, e.g.

<cfthread name="#thread_name#" action="run" foo="#foo#" bar="#bar#">
... do stuff with foo and bar...
</cfthread>

I'm not sure what you're trying to do but I'd also avoid using cfquery
inside a thread, i'd usually do the query first then pass in the row I'm
working on as an argument

Andy

**Comment by edthetechie** [comment]
Hi Andy :-)

I will try using properties  to see what happens. In a nutshell this system is designed to sent a few thousand update emails to users who have requested them. The send happens via a browser click so I use cfthread to prevent issues with the user navigating away or the page timing out after they hit "send". It's a pretty simple system that I've used for ages without a problem, until we upgraded to CF 2018.
I tried what you suggested with taking the query out of the thread:
```
var ntmembers = model("member").findAll(where="email LIKE '%@cc.uk.com'", order="email");
thread action="run" name="esImport#createuuid()#" ntmembers="#ntmembers#" {
	var eshotArgsThread = {};
	eshotArgsThread.to = params.emailto;
	eshotArgsThread.from = "tech@cc.uk.com";
	eshotArgsThread.subject = "Thread Test";
	for (var m in ntmembers) {
		var eshotArgsThread.memberid = m.itemid;
		var eshotArgsThread.memberemail = m.email;
		eshotArgsThread.layout = "/admin/emails/layouts/stsimple";
		eshotArgsThread.template = "threadtestemail";
		sendEmail(argumentCollection=eshotArgsThread);
	}
}
```
But unfortunately the result is the same as when I have the query inside the thread :-(

Interestingly, Tom's last suggestion gave me strange results. When I dump the "m" variable to an array and then output that it seems that the 11 rows returned are all valid unique with @cc.uk.com and the "maxrows" in the findAll() function is completely ignored. This get stranger and stranger but I don't think it's a bug in CFWheels. Seems like ACF might finally have lost its marbles completely!
![image](https://user-images.githubusercontent.com/974402/68402066-a6873600-0172-11ea-8ff9-df68689e0e60.png)
I'm sharing the last two rows because the others all have sensitive information in the with the ID number. Suffice it to say that each email and ID is different. 

So if "m" actually has the correct values in it, why when I do m.email does it always give the details from the first row in the loop. It's the same as if I were get the row of the first query result and then loop over that row the number of rows in the query. Very strange indeed!

-= Ed

**Comment by edthetechie** [comment]
When I dump m.email to a second array it works fine but it's still ignoring "maxrows=5":
![image](https://user-images.githubusercontent.com/974402/68402946-14802d00-0174-11ea-81b1-8095db321913.png)
```
thread action="run" name="esImport1" {
	var test = []; 
	var testm = []; 
	var ntmembers = model("member").findAll(select="itemid, email",where="email LIKE '%@cc.uk.com'", order="email");
	var eshotArgsThread = {};
	eshotArgsThread.to = params.emailto;
	eshotArgsThread.from = "tech@cc.uk.com";
	eshotArgsThread.subject = "Thread Test";
	for (m in ntmembers) {
		var eshotArgsThread.memberid = m.itemid;
		var eshotArgsThread.memberemail = m.email;
		eshotArgsThread.layout = "/admin/emails/layouts/stsimple";
		eshotArgsThread.template = "threadtestemail";
		arrayAppend(test, m);
		arrayAppend(testm, m.email);
	}
	writeDump(test);
	writeDump(testm);
}

thread action="join" name="esImport1" timeout="600";
writeOutput(esImport1.output);
abort;
```

**Comment by neokoenig** [comment]
FYI your examples don't include maxrows in the findall call...

**Comment by edthetechie** [comment]
Yes I just realised that! I get the dumb arse of the day award!

**Comment by edthetechie** [comment]
I just tried a test with this code:
```
thread action="run" name="esImport1" {
	var test = []; 
	var testm = []; 
	var ntmembers = model("member").findAll(select="itemid, email",where="email LIKE '%@cc.uk.com'", order="email", maxrows="5");
	var eshotArgsThread = {};
	eshotArgsThread.to = params.emailto;
	eshotArgsThread.from = "tech@cc.uk.com";
	eshotArgsThread.subject = "Thread Test";
	for (m in ntmembers) {
		var eshotArgsThread.memberid = m.itemid;
		var eshotArgsThread.memberemail = m.email;
		eshotArgsThread.layout = "/admin/emails/layouts/stsimple";
		eshotArgsThread.template = "threadtestemail";
		sendEmail(argumentCollection=eshotArgsThread);
		arrayAppend(test, m);
		arrayAppend(testm, m.email);
	}
	writeDump(test);
	writeDump(testm);
	}
thread action="join" name="esImport1" timeout="600";
writeOutput(esImport1.output);
abort;
```
The data on screen is correct. The emails all have ed@cc.uk.com and my ID in them...

**Comment by edthetechie** [comment]
If I write the code like this the emails are correct:
```thread action="run" name="esImport1" {
	var test = []; 
	var testm = []; 
	var ntmembers = model("member").findAll(select="itemid, email",where="email LIKE '%@cc.uk.com'", order="email", maxrows="5");
	var eshotArgsThread = {};
	var eshotArgsThread.dynVars = {};
	eshotArgsThread.to = params.emailto;
	eshotArgsThread.from = "tech@cc.uk.com";
	eshotArgsThread.subject = "Thread Test";
	for (m in ntmembers) {
		var eshotArgsThread.dynVars.memberid = m.itemid;
		var eshotArgsThread.dynVars.memberemail = m.email;
		eshotArgsThread.layout = "/admin/emails/layouts/stsimple";
		eshotArgsThread.template = "threadtestemail";
		sendEmail(argumentCollection=eshotArgsThread);
		arrayAppend(test, m);
		arrayAppend(testm, m.email);
	}
	writeDump(test);
	writeDump(testm);
}

thread action="join" name="esImport1" timeout="600";
writeOutput(esImport1.output);
abort;```
