### ISSUE TITLE
routes.cfm redirect= not working.

### ISSUE THREAD

**Issue by mattcmiller** [cfwheels/cfwheels#971]
routes.cfm redirect= not working, but could be with my version I'm on 2.02 but in the documentation it states as of 2.1 (https://guides.cfwheels.org/docs/routing) but 2.02 is the latest. Am I missing something?

**Comment by neokoenig** [comment]
2.1 is pending release into beta. (And has been for some time - sorry!)
Documentation is updated when the feature went into the master branch, so it's technically true, this will work on 2.1, which doesn't exist yet :P

You can try it out with the current master branch - if you look at https://github.com/cfwheels/cfwheels/blob/master/CHANGELOG.md you'll see there's a Load of stuff in there.
