### ISSUE TITLE
How to achieve delete in CRUD via rails.js

### ISSUE THREAD

**Issue by asimakos** [cfwheels/cfwheels#972]
I want to implement a delete CRUD operation via the following JavaScript link
https://github.com/rails/jquery-ujs/blob/master/src/rails.js)  in cfwheels 2.0.2, but I had had no luck! When I pass the parameters confirm and method="delete" into link To nothing happens from the view page source. Not data-confirm etc. When I click the link, it redirects me to another page than the proper one as it uses the get method instead of delete. Any idea or definitely an example that would help me to achieve it?
I want to click the link, afterwards a confirm message and finally the delete operation that is mentioned in cfwheels docs.

Regards

**Comment by andybellenie** [comment]
Hi

This sounds like a javascript issue and not Wheels, however please post
your code and someone may be able to help

Andy

**Comment by asimakos** [comment]
The code is one line
#linkTo(text="Delete",route="user", key=id,method="delete",confirm="Do you want to delete?")#

I have also seen somewhere a video tutorial that uses the same script and it worked fine according to the performer. Any kind of help that might be wrong with the rails script or find a more suitable one.

Regards

**Comment by andybellenie** [comment]
I have the same usage in a Wheel 1.4.5 app and it works fine but it may have been removed in v2. @neokoenig?

Btw, I have no idea HOW it's working in my app, I can't find any JS relating to it...

**Comment by andybellenie** [comment]
Found it. By adding confirm="xxx" to the linkTo() function, it adds the following the html output:

````onclick="return confirm('xxx')````

@asimakos  can you check your html to see if this is happening?

**Comment by asimakos** [comment]
Yes I have already done it, but it does not appear the usual confirmation js dialog box. Besides I need the delete method to call in some way in order to accomplish the delete action.

**Comment by neokoenig** [comment]
@andybellenie If you recall we removed all the Javascript Confirm stuff out of the core for 2.x - it technically lives on in plugins; in 1.4.5 the `confirm` argument generated the javascript from within the core itself.

I've not used rails.js, but it would need to correctly identify the CRSF token in 2.x (Which 1.x didn't have by default) and also set the correct method for the js ajax call.

@asimakos I posted an answer to this in the slack channel; perhaps you missed it:
```
<!--- Example Link --->
#linkTo(route="User", key=id,  text="<i class='fa fa-trash'></i> Delete", class="btn btn-sm btn-danger deletelink", encode=false)# 

<!--- the example app, you can set arbitary javascript in a view file like this:--->
<!--- this simply looks at the generated link, gets the URL and sends a DELETE request along with the CSRF token --->
<cfsavecontent variable="request.js.deletelink">
<script>
$(".deletelink").on("click", function(e){
	e.preventDefault();
	console.log("Clicked");
	var targetUrl = $(this).attr("href");
	console.log(targetUrl);
	var csrftoken = $('meta[name=csrf-token]').attr("content");
	$.ajax({
    	url: targetUrl ,
	    type: 'DELETE',
	    data: {
	    	authenticityToken: csrftoken
	    },
	    success: function(result) {
	        // Refresh page
	        location.reload(); 
	    }
	});
});
</script>
</cfsavecontent>
```

**Comment by asimakos** [comment]
Yes, I remember this answer but you should fix it and deliberately I report it as a bug. I think that I should leave it here as a reminder for the next version of cfwheels to be fixed as you just said in the slack channel.
Regards

**Comment by andybellenie** [comment]
Hi @asimakos we appreciate the feedback but this isn't a bug, it was a deliberate choice to make Wheels JS agnostic and for features to not rely on JS being enabled in the browser. There is no plan to change this in future versions.
