### ISSUE TITLE
findLast() clashing with Lucee 5.3 latest builds

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#974]
findLast() has been added as an internal function in Lucee 5.3, which will clash with our version of it... This will need renaming.

**Comment by adamzenu** [comment]
Well that's just inconsiderate.. 😂

I suppose the options are finding a new adjective eg: findFinal or appending a noun eg: findLastRecord/Row/Object.

https://www.thesaurus.com/browse/last

**Comment by chapmandu** [comment]
Well that's just inconsiderate.. 😂

I suppose the options are finding a new adjective eg: findFinal or appending a noun eg: findLastRecord/Row/Object.

https://www.thesaurus.com/browse/last

Do we also need to review findFirst?

**Comment by andybellenie** [comment]
.findLastOne()?
.findOneLast()?
.first?
.fini()?
.damnYouLucee()?

**Comment by neokoenig** [comment]
I think we should hold back on this - I can't find any reference to it in the lucee source code, but it was announced at cfcamp apparently (see https://southofshasta.com/blog/cfcamp-notes-lucee-5-4-6-gert-franz-and-michael-offner-streit/ )

**Comment by neokoenig** [comment]
So to confirm, `lucee@5.3.4+77`, `lucee@5.3.4+80` are fine, it's `lucee@5.3.5+92` (the now latest release). This means I think we really have to actually remove that function completely, as it's being scanned in at /wheels/docs - so even if you don't use it in your code, it will throw a wobbly.

The question is technically when to remove it; within 2.1beta?

**Comment by chapmandu** [comment]
I like the idea of renaming it `findLastOne`.. which release though is up for debate.

**Comment by neokoenig** [comment]
`findLastOne` it shall be. Let's put it in 2.1, as otherwise it'll be ages till gets in.

**Comment by neokoenig** [comment]
Fixed in 2.1
