### ISSUE TITLE
docs - useExpandedColumnAliases - wrong default value

### ISSUE THREAD

**Issue by Steven737** [cfwheels/cfwheels#975]
I just noticed a small error in the documentations.

Docs:
ORM Settings -> useExpandedColumnAliases -> default: true

Code:
`application.$wheels.useExpandedColumnAliases = false;`

**Comment by neokoenig** [comment]
Cheers!
Now fixed on https://guides.cfwheels.org/docs/configuration-and-defaults#section-orm-settings
