### ISSUE TITLE
Columname list in db migrations should trim whitespace

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#976]
e.g `t.text(columnNames='ipaddress, pw, emad', default='', null=false);`

Should not allow preceding whitespace in column name: I can't think of a scenario where you'd want a column name starting with whitespace?

**Comment by chapmandu** [comment]
I'm fairly sure this is in the master branch..

https://github.com/cfwheels/cfwheels/blob/master/wheels/tests/migrator/migration/createtable.cfc#L10
