### ISSUE TITLE
Add ability to completely disable Flash

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#978]
If you're running wheels as a stateless API (i.e with no session management and using your own authentication cookies), you may not want to use flash at all, and deliberately don't want your API to set the `flash` cookie.

Propose to add a `enableFlash` setting defaulting to `true` to allow the developer to completely disable the flash. It won't remove the flash functions from memory, just won't set the cookie, or always return an empty struct etc.

**Comment by andybellenie** [comment]
Isn't it possible to store the flash as a cookie instead of in session already?

**Comment by neokoenig** [comment]
Yep, that's what I'm doing, but it will always issue `Set-Cookie: FLASH=%7B%7D;Path=/` , which is what I want to avoid as I'm never using the flash; I mainly want to do it as lucee doesn't yet support `sameSite` in their cookies amongst other things...

I'm running wheels in a completely stateless way, and not using built in session management at all, nor do I want built in cookies - I'm issuing everything manually.

**Comment by andybellenie** [comment]
Gotcha.

How about adding the option "none" or false to the existing flashStorage setting?

**Comment by neokoenig** [comment]
Yes, that's much more elegant
