### ISSUE TITLE
turn imageTag() exception on/off

### ISSUE THREAD

**Issue by michaeldiederich** [cfwheels/cfwheels#979]
Currently, the function ```imageTag()``` throws an exception if a local image/file doesn't exist or is not an image file.

I would request, that the exception could be turn on/off by a global setting. Or could be turn off in the developer mode. Right now, I want to test something in my development environment and I have one file missing, but I don't care about the missing file, I want to check something else and not update my images folder.

wheels\view\assets.cfm line 195 ff.
cfwheels 2.0.2

**Comment by neokoenig** [comment]
Seems reasonable.

I'd propose we could add a `required` (something like `strict`) attribute on the `imageTag()`, which (to keep current behaviour) could default to` true`, and only if that attribute is `true` would it throw an exception

That way in development you could just set:
```
set(function="imageTag", required = false)
```

Thoughts?

**Comment by chapmandu** [comment]
Closed via f05ed8e99e39067e4d0fe7113504bcdce93f8675
