### ISSUE TITLE
Docs - Clearing search bar doesn't update results

### ISSUE THREAD

**Issue by bshea5** [cfwheels/cfwheels#982]
Wheels 2.1 Beta

If you enter a search term on the docs page and hit 'Enter' key, result in one result; Clearing the value in the search bar doesn't update the results and it will continue only showing the 1 result until you navigate away or click one of the categories on the right.

<img width="1924" alt="Screen Shot 2020-03-05 at 10 41 21 AM" src="https://user-images.githubusercontent.com/3984775/76014927-4eb5cd00-5ecf-11ea-9efb-8563013fc070.png">

**Comment by neokoenig** [comment]
Cool, will sort...

**Comment by michaeldiederich** [comment]
I cannot reproduce this on 2.1, I guess it is fixed.
