### ISSUE TITLE
Docs - Categories vanish when scrolling down

### ISSUE THREAD

**Issue by bshea5** [cfwheels/cfwheels#983]
Wheels 2.1 Beta

If there is a long list of functions, scrolling down to view will cause the categories on the right to vanish and appear towards the bottom of the page instead.

<img width="2077" alt="Screen Shot 2020-03-05 at 10 50 32 AM" src="https://user-images.githubusercontent.com/3984775/76014864-334ac200-5ecf-11ea-9b65-2502677714fd.png">
<img width="2096" alt="Screen Shot 2020-03-05 at 10 50 25 AM" src="https://user-images.githubusercontent.com/3984775/76014873-3645b280-5ecf-11ea-82dc-d1d45c7207a5.png">

**Comment by neokoenig** [comment]
hmm. Might be semantic UI, but shall see if we can fix.

**Comment by neokoenig** [comment]
Also need to fix ACF2018 which is doing something weird
 
![localhost_62018_wheels_docs](https://user-images.githubusercontent.com/381268/79984871-af11c580-84a1-11ea-993f-cfde462a05d2.png)

**Comment by neokoenig** [comment]
> Also need to fix ACF2018 which is doing something weird

This should be fixed in https://github.com/cfwheels/cfwheels/commit/bb1aaccb1f423bf45616d3c69d3de2e64f737cbb 

Still looking at the other oddities.

**Comment by neokoenig** [comment]
Can't replicate at the moment in Edge, Chrome, FF; closing for now
