### ISSUE TITLE
Error on preview SQL button on migrator page

### ISSUE THREAD

**Issue by bshea5** [cfwheels/cfwheels#992]
When clicking the preview SQL button on the migration page, an error occurs. This is due to 'var' being used in a variable definition when outside of a function definition.

It works when I remove the 'var' keyword in src/wheels/public/migrator/sql.cfm on line 16 in the for loop statement.

CFWheels version 2.1

<img width="173" alt="Annotation 2020-04-14 102940" src="https://user-images.githubusercontent.com/3984775/79256561-1645cf00-7e3d-11ea-81dc-bfd31279a670.png">

**Comment by neokoenig** [comment]
Can you confirm the engine used? Was built using lucee where I think var in that context is fine; so might need refactoring if you're using ACF?

**Comment by bshea5** [comment]
ACF 2016

**Comment by neokoenig** [comment]
Thanks  - I'll run some more tests on ACF

**Comment by chapmandu** [comment]
Just noticed looking at the tests that inputClass for buttonTo is not documented..

**Comment by neokoenig** [comment]
It's in the https://api.cfwheels.org/v2.1/controller.buttonTo.html code example - it's a bit of a weird one as you'd have to list all the `input` possiblities.. 

Hmm - I guess now there isn't actually an `<input>`  but a `<button>` that should change ... I wonder if anyone ever used that?

**Comment by chapmandu** [comment]
Oops.. I didn't see 

Yes, do they need to be prefixed with `button`, now.. perhaps we can alias `input` prefixes in the function so it's backwards compatible.
