### ISSUE TITLE
Wheels 2.1 core tests failed

### ISSUE THREAD

**Issue by michaeldiederich** [cfwheels/cfwheels#993]
I pulled the git project and switched to the branch "2.1". I created a datasource and database and run the core tests. I changed the `config\settings.cfm` and added: `set(allowCorsRequests=true);`

I still have 22 errors, 12 for CORS and 10 other errors.

I changed the lucee server admin settings to the default values (e.g. no complete NULL support) and I am not sure what else I have to do...

ubuntu 18
lucee 5.2.8.50
java 1.8.0_102
Tomcat 8.5.5
apache 2.4

**Comment by neokoenig** [comment]
On a side note, the tests on the 2.1 branch itself will fail on CI as the engine check will be in place; 

The current master is the best place to run core tests. At the moment I'm seeing just the one failure on Lucee:

(My Local Machine: Commandbox + MySQL 5.x)

Lucee 4.5.5.006 / 5.2.1.9 / 5.3.5.92 ( 1 Failure)
model.properties.timestamps
Explicit timestamps are respected on create
assert failed: Year(post.createdAt) eq 1969 Year(post.createdAt) = 2020

I don't know why they test suite hasn't picked this up...

**Comment by perdjurner** [comment]
@michaeldiederich I think upgrading to Lucee 5.3.2.77 should get rid of a few of those errors.
Also, what MySQL version are you running?

**Comment by michaeldiederich** [comment]
`Server version: 10.1.44-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04`
That should be mysql 5.6 equal.

I will check to upgrade my lucee, but I am afraid there a some problems when I upgrade from 5.2 to 5.3

**Comment by neokoenig** [comment]
@michaeldiederich I'm running the latest lucee 5.3 in production (and mySQL 5.6) at the moment.
I'm in the process of rewriting our test suite so we can get to the bottom of some of these errors - our Travis CI suite isn't catching them.

But at the moment, Lucee@5 on the current master is now passing (lots of fixes in the last24 hours)

**Comment by michaeldiederich** [comment]
Null Support to default, pulled last master, lucee restart, start core tests with reloading. Attached is my result.
[cfwheels-test-result.pdf](https://github.com/cfwheels/cfwheels/files/4510633/cfwheels-test-result.pdf)

Any ideas?

**Comment by geirman** [comment]
>  I created a datasource and database

How do I do this? I haven't noticed any instructions or data structure.

**Comment by michaeldiederich** [comment]
> > I created a datasource and database
> 
> How do I do this? I haven't noticed any instructions or data structure.

First you go to your database and create a empty database, e.g. `create database cfwheels;`
You open the lucee server/web admin, create a new datasource.
The tests should create everything they need, but it took me some tries as still some of the test still fail on my system.

**Comment by geirman** [comment]
@michaeldiederich ah cool, I wasn't sure if there was a table structure expected. Empty database. got it. Thanks!

**Comment by neokoenig** [comment]
If you guys are feeling adventurous, check out the docker-test branch. (specifically the readme in /src/docker/) - I've done a docker-compose for local testing which is starting to run  Lucee5 / ACF16 / ACF18 against MySQL56/Postgres/SQLServer.  The best part is once docker is up and running, you don't even need to setup any test datasources, and can run then via the VueJS test runner. So we could add later MySQL versions or MariaDB directly to that if needed.

CORS requests are complex. I suspect they'll end up being treated differently as you can't override the headers in ACF anyway, so we only test against lucee to start with etc - plus the new docker test runner uses JS to run the tests, so there's an implicit CORS issue there. Ultimately, CORS is an integration test more than a core test :) In that docker branch I've commented them out for now.

**Comment by geirman** [comment]
That sounds so cool, @neokoenig. But I'm not even sure where I'd start. I've dabbled in docker, but I'm still fairly intimidated TBH. I would love for that not to be true any longer though, so I'll nibble at that readme and see if I have any "aha" moments. Thanks!

**Comment by neokoenig** [comment]
Can this be closed? Or do you still get errors on the current master?

**Comment by michaeldiederich** [comment]
Current Setup: Windows 10, commandbox with Lucee 5.3.6+61, db is 10.1.44-MariaDB (Ubuntu 18)
Branch: origin/master

All tests a green. I close the issue. Thanks!

**Comment by neokoenig** [comment]
Awesome :)
